### ISSUE TITLE
Implement basic commenting

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1003]
See designs and commentary in #977

### This task is done when...
 - [ ] CMS reviewers can add comments to APDs
 - [ ] state users can see and reply to reviewer comments

**Comment by mgwalker** [comment]
I think we need to be very mindful of how we model the data and data relationships around comments, though, since the APD can change over time.  E.g., if you comment on a goal and then the state deletes that goal, how do we handle that relationship?

@jeromeleecms @NAretakis Are there records retention concerns around being able to edit or delete comments after they've been sent?  (I know editing and deleting aren't part of the MVP, but...)  I.e., if a CMS analyst sends comments back to the state, should they be allowed to edit or delete those comments later?  For the sake of auditing and records keeping, it seems like the answer should be _no_.  They could mark it as resolved so it doesn't show up anymore, but it should be retained, right?  So you could edit/delete comments up until you push the big "submit" button, but not after.  Does that make sense?

**Comment by NAretakis** [comment]
Yes, marking as resolved is good as a way to hide them. But we do want to be able to retain the comments & responses. Editing and deleting until the submit/response button is pushed makes sense. Once that is clicked, those comments are stored with the APD.

**Comment by jeromeleecms** [comment]
This will cover the State and Federal Experience, unless otherwise noted by @lauraponce or @mgwalker

**Comment by NAretakis** [comment]
closing as #977 is the Epic for this functionality.
