### ISSUE TITLE
Wireframe "Section II" of the APD to results of previous activities

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1006]
As we move past the pilot, we need to evaluate how to manage updates into the APD.  This issue will focus on how we can capture the information from section II of the HITECH APD template and include that required information into the app.

### This task is done when...
 - [ ] Product has met with design to ensure the required components of Section II is present
 - [ ] Sketches have been made
- [ ] Product approves final sketch
- [ ] Development task has been created

**Comment by lauraponce** [comment]
From the docs, here's what Section II should have:
- Results of previously approved HIE activities, if applicable
- Table that summarizes the state’s last HIE funding request, approval amount, expenditures, and amount of funding remaining from that approval
- CMS recommends showing the full HIE funding history, or the most recent approval and expenditures, at minimum

**Comment by lauraponce** [comment]
As part of this section, would something like this (but updated with our styles) work?

<img width="604" alt="screen shot 2018-09-12 at 6 40 56 pm" src="https://user-images.githubusercontent.com/21222704/45462205-a77e1e00-b6bb-11e8-8e90-d52eace8e2e4.png">


This is from the [Nebraska APD](https://docs.google.com/document/d/1a6p-TVIO6UMaoAu3rhE7XZ27S68FqqTiS6N2-PtkOCE/edit)

**Comment by lauraponce** [comment]
And something along these lines for #2 in the list?: 

<img width="633" alt="screen shot 2018-09-12 at 6 45 43 pm" src="https://user-images.githubusercontent.com/21222704/45462321-296e4700-b6bc-11e8-8ee2-9537435f2844.png">

**Comment by lauraponce** [comment]
The first box is similiar to what we have now. I just updated the instructions to capture any notable milestones: 

![screen shot 2018-09-14 at 1 53 01 pm](https://user-images.githubusercontent.com/21222704/45574653-92bd9980-b825-11e8-98e5-569e09a27455.png)

**Comment by lauraponce** [comment]
This is an update to the second part of this section where states will input how they spend down their approved funds. By default, the reauthorize button will be disabled until it sees there is a remainder. When it's enabled, it has the white fill and blue border, and when it's selected it has the blue fill.

![screen shot 2018-09-14 at 1 53 22 pm](https://user-images.githubusercontent.com/21222704/45574659-96512080-b825-11e8-9de0-142e4c6e5ca0.png)

**Comment by lauraponce** [comment]
@jeromeleecms what do you think about something like this?

**Comment by jeromeleecms** [comment]
@lauraponce 

1) This section may not always refer to the prior year expenditures. It may cover the current year expenditures which is triggering the need for an APD. In that case, we wouldn't need to ask about reauthorizing the balance.
2) Based on this sketch, it looks like there could potentially be 9 different line items (HIT/HIE/MMIS x the three sub categories). Any concerns about getting potentially "lost in the scroll?" It would be sufficient to have one text box at the end that encapsulates the state's reason for the additional funding instead of having a box every time a state requests funds to be reauthorized for the next year.
3) I'm not quite clear what this "What should this money be reauthorized to?" means. It may not be necessary and we can roll that all into a single text box as described in (2).

**Comment by lauraponce** [comment]
With the longer list of sections here (minus MMIS):

![screen shot 2018-09-21 at 1 46 05 pm](https://user-images.githubusercontent.com/21222704/45905302-c0b25900-bda4-11e8-904f-859e0776287a.png)

I don't think it would be too long of a scroll having it like this, but we can definitely bring this to testing and see how it is for people inputting the numbers.

The checkbox for reauthorizing the balance would only be enabled if there is a balance to bring forward:

<img width="490" alt="screen shot 2018-09-21 at 1 34 00 pm" src="https://user-images.githubusercontent.com/21222704/45905149-3b2ea900-bda4-11e8-96a2-26a4afcaf5c0.png">

@jeromeleecms thoughts on this?

**Comment by jeromeleecms** [comment]
@lauraponce 

1) Our current guidance groups the FFY together instead of by line item. Could you mockup a version of what that would look like?
2) When we settle on the final one, can we have the overall sketch including the "Results of Previous Activities" for Dev's to reference? 
3) Proposed Logic for the reauthorization check box: 

- If no balance remaining, not selectable. 
- If the state is reporting current FFY and only requesting current FFY funding, not selectable.
- If the state is reporting previous year expenditures (Current FFY - 1) and requesting funding for the current FFY, then allow reauthorization for the previous year . 
- If the state is reporting current FFY funding and the state is requesting next FFY funding (Current FFY + 1), then the state can reauthorize funding for current FFY.

**Comment by jeromeleecms** [comment]
@lauraponce Something like this:

![image](https://user-images.githubusercontent.com/34279968/46039881-ac7f9c00-c0c3-11e8-93fd-717ef553930a.png)

Does that help?

**Comment by lauraponce** [comment]
@jeromeleecms how does this seem?

![screen shot 2018-09-26 at 4 09 28 pm](https://user-images.githubusercontent.com/21222704/46114232-97c80480-c1a6-11e8-8542-0bf04c1a918a.png)

**Comment by NAretakis** [comment]
Hey folks, coming the the party a bit late. The above is good, but I am afraid it is too granular and is asking the states to try and provide expenditures at a level they don't have. What about if we flipped the concept a little bit, with the flow below:

When an APD is updated, Prior Activities Outline is populated with the previous activities (sourced from Exec Summary) and includes buttons for marking the activity as completed as well as continuing. Marking an item complete moves all of the activity information into a collapsed (completed) section underneath the summary. While, marking an item as Continuing, keeps the activity "alive" within the normal Activity List section of the APD.

![image](https://user-images.githubusercontent.com/34281281/46178097-a7148400-c272-11e8-83b8-d0e1c505aa1e.png)


Within the next section, we keep our existing table (maybe make it easier to use) and ask them to provide the amount expended (amount approved should be pre-populated), at this rolled-up, high level. Using the table format we have now, based on the one below. This is important because this is the level that states will be able to report expenditures, not at the level in the sketches above.

![image](https://user-images.githubusercontent.com/34281281/46177898-d8d91b00-c271-11e8-9c34-e0267486b784.png)

**Comment by jeromeleecms** [comment]
@NAretakis  Worth talking about and upon further reflection, maybe my initial thoughts on this may be too ambitious for MVP! Sorry @lauraponce!

I would propose this:
1) **Flow** -- I like the idea, but let's put that in the activity list instead though.

![image](https://user-images.githubusercontent.com/34279968/46218538-b4288600-c2f9-11e8-9e2b-39d3db3a8aa6.png)

The checkbox (or toggle or whatever) would only appear for activities that were being brought in the from the last APD. 

2) **Budget Table** - What you are proposing is not actually that far off from what Laura already sketched out except, it uses FFP as the category vs. cost category (it's already been modified to try to make data entry simpler). I would prefer having the inhouse vs contractor costs included and including the text box below since that lines up with the CMS-37/64, but open to simplifying this section. For the MVP, after mulling over this, we probably need to remove the reauthorization checkbox. I think it will make it very hard to figure out how to add that back into the budget (again me being a big ambitious).

![image](https://user-images.githubusercontent.com/34279968/46219396-1edac100-c2fc-11e8-81d7-791bebe2cf72.png)

vs...

![image](https://user-images.githubusercontent.com/34279968/46222661-e9d36c00-c305-11e8-9e23-09172f32cb0d.png)


3) **Activity Status Textbox at the activity level** - When updating activities (completed or not), we should include an additional section within the activity which talks about activity progress. We still need a place for states to report on project, so we could remove the results of previous activity text box above, keep the budget section (however that shapes up) there, and add an Activity Status Update at the activity level.

![image](https://user-images.githubusercontent.com/34279968/46222207-6f561c80-c304-11e8-8b4a-0f3cbb80794e.png)

4) **Future Enhancement** I think this makes the case that down the road, we should have also include financial reporting at the activity level. From an oversight perspective, I would want to know the progress of each activity financially + scope + on major milestones. Any PM/PMO should be able to provide that information right out of their project management tracking tool with relative ease.

**Comment by lauraponce** [comment]
Added the relevant info from this thread to #1554 for Austin
