### ISSUE TITLE
Setup automated deployment in AWS

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1013]
Make CMS' AWS function like our current AWS sandbox, or as close as we can get it.

- [x] updated CircleCI deployment
   - preview deploys
      - [x] EC2 instance is built and configured
      - [x] database
         - [x] installed
         - [x] configured to allow local network access
         - [x] password set
         - [x] database created
      - [x] self-signed TLS certificates are generated
      - [x] web server
         - [x] installed
         - [x] root path is configured to frontend location
         - [x] API path is proxied to `localhost:API_PORT`
         - [x] using self-signed certificates
         - [x] supports pushstate routing
      - [x] source code is loaded from the PR branch
      - [x] frontend is built and moved into place
      - [x] backend is built and moved into place
      - [x] database migrations and dev seed are run
      - [x] API
         - [x] production, locked dependencies installed
         - [x] configuration file is written
         - [x] started in process manager
      - [x] preview link is posted to Github
         - [x] new comment is created if none exist
         - [x] existing comment is updated if exists
         - [x] links are cleaned up after PRs are closed/merged
 
   - production deploys
      - [x] frontend is built and pushed to S3
      - [x] EC2 instance is built and configured
      - [x] API is loaded onto EC2 instance
      - [x] production, locked dependencies installed
      - [x] configuration file is written
      - [x] started in process manager
      - [x] database migrations are run
      - [x] EC2 instance is added to the load balancer
      - [x] old instance is removed from the load balancer

**Comment by mgwalker** [comment]
There are a few more permissions I need to get setup on the AWS deployer account, but I've forgotten what they are.  😬  I will go through the deployment process manually to see where we run into problems and document which permissions we need so I can get a help desk ticket in.  I think as far as actually making the deployments happen, it shouldn't be too hard once the permissions are right.

**Comment by mgwalker** [comment]
Done! 🎉
