### ISSUE TITLE
Migrate app into new AWS Dev/Test space

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1014]
Issue for the migration of the existing app into our AWS infrastructure.
 
 ** Don't forget to fill out the LABEL and MILESTONE before submitting. If the issue is for the CURRENT SPRINT, add it to the PROJECT. If the issue is a BUG, FUTURE ENHANCEMENT, or OUTSIDE OF THE CURRENT SPRINT, do not add it to the PROJECT (then delete this line) **

**Comment by mgwalker** [comment]
One thing we'll need at some point is a domain name.  I think as far as just getting moved over, it's not critical, but we'll see.  😄

**Comment by mgwalker** [comment]
- need to understand how VPC and subnets are designed so we can figure out where our pieces go
  - does our EC2 instance(s) need to be connected to a particular subnet?
  - for external access to EC2, can we temporarily assign a public IP, or do we use an Elastic IP instead?
  - does our ELB need to be connected to a particular subnet? needs to be publicly accessible while also having access to our EC2 instance(s)
  - do we need to take VPC into account for S3 buckets? (EC2 does not access S3, so it seems like probably not)

- will we be able to manage Route 53 ourselves, or only via tickets?
  - if we can do it ourselves, need to make sure we can point domains at ELB and CloudFront (sitting in front of our S3 buckets)
  - if we do it via tickets, we need to get our ELB and CloudFront instances nailed down so we can get the tickets in ASAP

**Comment by mgwalker** [comment]
Things we've already done:

### Frontend
- create S3 bucket, add content
- create CloudFront distribution

### Backend
- create EC2 instance
- setup environment
- install/run API
- create ELB with EC2 as a target

**Comment by mgwalker** [comment]
I think this one is done, given the other issues we spun up.
