### ISSUE TITLE
Spell out acronyms on first reference throughout yaml

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#1015]
Previously avoided this due to length. Acronyms are included right now without context. Discussion about whether to link to the glossary, or whether to first-reference include acronyms inside the application, recognizing it could eventually become cumbersome in some sections.

### This task is done when...
 - [ ] Include acronyms or glossary link
 - [ ] Product reviews experience

**Comment by jeromeleecms** [comment]
Closing this in favor of #1025
