### ISSUE TITLE
Help Text is Missing

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1024]
During review of the app / user testing, we discovered that help text for the Activity Overview section was missing:

![image](https://user-images.githubusercontent.com/34279968/45773963-9758c800-bc00-11e8-8924-95a3a0a07c0c.png)

Missing text was addressed in #1022, but now there is no text in the boxes:

![image](https://user-images.githubusercontent.com/34279968/45774096-fa4a5f00-bc00-11e8-9645-267b937cb7d4.png)

### This task is done when...
 - [ ] Appropriate updates made to app to pull in tagged YAML data
 - [ ] Someone else has approved of the update.

**Comment by hbillings** [comment]
This is what I'm seeing in the latest version of `master`; is this correct?

<img width="774" alt="screen shot 2018-10-19 at 10 34 38 am" src="https://user-images.githubusercontent.com/509309/47228321-8c718e80-d38a-11e8-84e6-fb3f249a52d1.png">
