### ISSUE TITLE
UI Refinements on Textboxes and how they inform data entry

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1030]
Based on feedback from the last round (7) of usability testing, the textbox sizes can be misleading. 

- Establish a pattern for the size of the textbox that correlates to the expected input

**Comment by lauraponce** [comment]
We can nudge users into entering more/less information based on the size of the text box, so we can try using 3 sizes (small, medium, and large). All of these would have a scroll bar appear once they get to the end of the box and continue typing. 

The numbers are based on our 12 column grid (812px = 7 columns which is the width of the white content block). The ideal number of characters in one line to optimize readability is between 60-75, so having a width of 652px (6 columns) would allow for 75 character max at a 17 font size.

The medium size is half of the large and the small is half of the medium.

How do these seem, @jeromeleecms? 

![screen shot 2018-10-11 at 3 11 47 pm](https://user-images.githubusercontent.com/21222704/46836888-1d7fae80-cd68-11e8-98be-8febfd0c47c1.png)

![screen shot 2018-10-11 at 3 12 14 pm](https://user-images.githubusercontent.com/21222704/46836885-1bb5eb00-cd68-11e8-8b7e-21d54bacc4ff.png)

![screen shot 2018-10-11 at 3 12 20 pm](https://user-images.githubusercontent.com/21222704/46836879-18bafa80-cd68-11e8-9ce5-1c508afdac51.png)

**Comment by jeromeleecms** [comment]
@lauraponce Some thoughts... 

1) I'm good with adopting this if it helps readability. I do remember one comment during user testing where an individual stated that there was too much white space - though my preference is readability over maximizing screen real estate. All the users will have to read, review, and/or respond within this framework at some point!

2) The actual height of the large, medium and small text boxes I'll defer to your expertise. The only one that might not fit in these categories is the "Tweetable" summary of the activity - that might fit in an  "extra-small" category? If not, we can keep that to "small."

3) Is the app supposed to be a fixed max-width overall? Right now, the entire app expands as the browser expands (fills up the entire screen space if the browser is maximized)?

4) Do we need to walkthrough the app and assign everything text-box size designations?

**Comment by lauraponce** [comment]
@jeromeleecms 

1. 👍 

2. Could that also be solved for by adding the guidance in the instructions to write it in one sentence? Otherwise, adding another extra small box that would allow for ~4 lines of text seems like a solid option.

3. Good question. To me, it makes sense to have a max width because it seems to be harder to read the wider it stretches. @hbillings any thoughts on putting a max width on the content blocks?

4. Yes! Let's do this next

**Comment by hbillings** [comment]
I think, depending on how this is structured (which I can dive into), it'd make sense to have a max-width for content. (for instance, I have a 4k monitor at home that would render this basically unusable without a max-width!) Whether we want to set a max-width on the content container, the text, or the entire app is a thing I don't yet have a recommendation for.

**Comment by lauraponce** [comment]
Created #1050 for the dev work on this
