### ISSUE TITLE
Onboard MeT for Change Management / Training 

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1031]
Expanding the team will require some onboarding to get MeT up to speed with the GitHub process and oriented to the way we work. This should help establish some alignment about how to leverage their expertise to the Change Management / Training as we look to rollout.

Related task may be to reconsider how we refer to this topic vs the very broad term of "Change management."

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
 ** Don't forget to fill out the LABEL and MILESTONE before submitting. If the issue is for the CURRENT SPRINT, add it to the PROJECT. If the issue is a BUG, FUTURE ENHANCEMENT, or OUTSIDE OF THE CURRENT SPRINT, do not add it to the PROJECT (then delete this line) **

**Comment by NAretakis** [comment]
Closing this issue as MeT is now onboarded. We'll create more issues for a specific training plan.
