### ISSUE TITLE
Build out help text style updates

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1034]
Pulling this over from #962 — Update the help text styles to match this style:

![image](https://user-images.githubusercontent.com/21222704/45895802-02cca200-bd87-11e8-9dc0-b06b529c3708.png)

To differentiate between instructions and help text, instructions should be details on how to actually fill out the section, "fill out XYZ" while help text should be additional contextual information that would help the user understand background or specific points to remember.

Implement a folded corner or triangle tab icon to a Light blue #DAE9F7 background instead of the yellow, which seems more like an alert or something wrong.

Be aware of:
- Remove bolding of any instructional text
- Be aware of what should go in what style in terms of instructive text vs useful context/help text.
- Not all sections or subsections will have both instruction text and help text, sometimes it's one or the other, which is ok.

Example

![image](https://user-images.githubusercontent.com/21222704/45895816-0f50fa80-bd87-11e8-805d-b5a9059aee80.png)

**Comment by jeromeleecms** [comment]
@lauraponce @jameshupp Is this also ready to commit to the Wiki under "Design Documentation?" Does it needs its own page or can we incorporate it into an existing one?

**Comment by lauraponce** [comment]
@jeromeleecms I might be confused on this one — what would be committed under design documentation?

**Comment by jeromeleecms** [comment]
Thinking the design/style guide you outlined... if this is the pattern we want use, it would be good for future contributors to use it as a reference.

**Comment by hbillings** [comment]
Blocked by #1055 and #1076
