### ISSUE TITLE
Add visual styling documentation to wiki

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1035]
So that future folks understand how we've made decisions so far, we should include information about what/how we're working.

This task will be complete when the wiki includes: 
-[ ] Tell people we use the CMS Design system, and where to find it
-[ ] Point out ways in which we've differed or customized (list examples of custom components)
-[ ] Point to the sketch file and how to find the latest version

**Comment by jenniferthibault** [comment]
@jeromeleecms since we're now using the CMS design system, I'm thinking we don't need this issue exactly as it was initially intended since there's no separate style guide. What it might make sense to do instead is something like:

- Tell people we use the CMS Design system
- Point out ways in which we've differed or customized (list examples of custom components)
- Point to where Sketch files live on Google Drive

At a later point, the team may want to decide if it's worth creating a more full visual library of patterns or styles for this site, but if feels like our implentation of the CMS Design system is still kinda early to tell.

**Comment by jeromeleecms** [comment]
I'm good with this as long as it has no impact on ATO / satisfies any ATO documentation requirements (@mgwalker or @NAretakis?).

Question/Clarification; If we point to Google Drive, will be the general public be able to access it? If they can't, can we post the latest version on GitHub?

**Comment by mgwalker** [comment]
AFAIK, the ATO process doesn't take style guides or documentation into account.  Generally speaking, ATO is more interested in "what" over "how"; e.g., it will want to see that we satisfy the requirements of section 508 (accessibility), but will largely not care about _how_ we do that.

**Comment by jeromeleecms** [comment]
Excellent! As long as the sketch file is accessible by visitors, let's close this out.

**Comment by jenniferthibault** [comment]
Oh the sketch file — I'd highly recommend prioritizing the team's access to the Sketch file over external visitors. The Sketch file changes daily, so if we upload it to GitHub, that's probably not a reasonable expectation for keeping the most updated version available. The same is true of uploading it to Google Drive, except it's not disappointing anyone from the public. 

If we're just uploading it as a backup for a working resource, and not for the SOURCE OF TRUTH:tm: (which should always be the code) we could do either, as long as we're setting clear expectations in the framing content about who on the team is responsible for the most up-too-date files.

**Comment by jenniferthibault** [comment]
And if that feels good, then there's still work to do do complete this issue! So plz don't close

**Comment by jeromeleecms** [comment]
Sounds good - I'll defer to you @jenniferthibault about when you are ready to close!

**Comment by jenniferthibault** [comment]
Added:
- An image of the latest iteration, which shows our transition to the CMS design system:
https://github.com/18F/cms-hitech-apd/wiki/Design-iterations

- A page on visual styling:
https://github.com/18F/cms-hitech-apd/wiki/Visual-styling

As I onboard Austin tomorrow I'll track questions and update it as needed!

**Comment by jenniferthibault** [comment]
I believe this to be done!
