### ISSUE TITLE
State dashboard styling

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1039]
From #676, there are still some significant styling issues to clean up on the dashboard.  A preliminary list based on eyeballing it:

### This task is done when...
  - [ ] "sort" dropdown on "current statuses" and "recent activity" (maybe real, maybe fake for now)
  - [ ] change "approval letter" to a link instead of a button
  - [ ] add "respond" button for APDs awaiting state response to CMS comments
  - [ ] make headers appear sortable on "my tasks" table (maybe actually sortable right now if that's not a huge lift, otherwise punt to another issue)

Related to #722.

**Comment by NAretakis** [comment]
can we connect with @lauraponce regarding #1029 so that we implement the MVP necessary dashboard items? Then, anything else can go into our future enhancement category for post-MVP work.

**Comment by lauraponce** [comment]
@NAretakis I left some comments in #1029 about this, so once we're on the same page with that, I'll come back to this issue to post the MVP updates.

**Comment by NAretakis** [comment]
OBSOLETE DUE TO #1029
