### ISSUE TITLE
Update frontend tests to be date-agnostic

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1047]
Currently a lot of our frontend tests will break every October 1 due to the changing FFY.  We should consider how to modify the tests so that they're deterministic, possibly with something like [sinon's fake timers](https://sinonjs.org/releases/v6.3.5/fake-timers/) (since we already use sinon anyway).

### This task is done when...
 - [ ] tests can run successfully regardless of what year they're run in

**Comment by NAretakis** [comment]
@mgwalker did we do this? or did we just fix this on the app itself?

**Comment by mgwalker** [comment]
Done in #1022.  Backend was done in #1053.
