### ISSUE TITLE
Federal Fiscal Year 2018 is still present with new IAPD (post FFY 2018)

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1048]
With the new FFY, a newly generated IAPD still includes FFY 2018 in the fields (though not in the "What Federal Fiscal Years Does this Cover"

![image](https://user-images.githubusercontent.com/34279968/46892467-59774a00-ce22-11e8-9b9a-f687aabf50ab.png)

This occurs through out the app (screenshot is just for an example). 

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
 ** Don't forget to fill out the LABEL and MILESTONE before submitting. If the issue is for the CURRENT SPRINT, add it to the PROJECT. If the issue is a BUG, FUTURE ENHANCEMENT, or OUTSIDE OF THE CURRENT SPRINT, do not add it to the PROJECT (then delete this line) **

**Comment by mgwalker** [comment]
This is a backend bug - it has 2018, 2019, and 2020 hardcoded when creating new APDs.  😬
