### ISSUE TITLE
Can't properly type percentages into the Quarterly break outs at the activity level

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1049]
When typing percentages into the quarterly breakdown at the activity level, the placeholder 0 persists, making it impossible to enter % < 10% or % that end with a number other than 0.

### This task is done when...
 - [x] User can enter any number in the quarterly breakout in the field
 - [x] Math checks out.
 
 ** Don't forget to fill out the LABEL and MILESTONE before submitting. If the issue is for the CURRENT SPRINT, add it to the PROJECT. If the issue is a BUG, FUTURE ENHANCEMENT, or OUTSIDE OF THE CURRENT SPRINT, do not add it to the PROJECT (then delete this line) **

**Comment by mgwalker** [comment]
This bug applies to several of our formatted text boxes, like some of the dollar inputs.  Whatever the issue is, it's probably the same in all of them, so hopefully a one-time, across-the-board fix.

**Comment by mgwalker** [comment]
The percentage one is especially weird.  There are a couple of things at play here, and it might be useful to have @lauraponce weigh in on how it should behave to make the user experience pleasant.

1. The input does not allow leading zeroes, so if you try to type anything behind the zero, the input will just reject it.  We can reconfigure this one really easily.  If we change this one, then typing behind the zero will give you the value you want.  E.g., if the box says `0%` and your cursor is after the 0, when you type `3`, the box will change to `3%`.

2. The value you see in the input is disconnected from the value that you type.  When you type a value, it gets sent to the activity reducer.  Then the budget reducer runs.  Then the value in the input is updated with the value from the budget reducer - what you type is not what gets put in the box.  The upshot is that the UX ***does not*** allow the user to clear out these boxes.  You can delete everything in them, but the reducers will convert that empty value into a `0`, and that's what the input box will display.

Fixing 1 is really easy and probably necessary.  Fixing 2 is harder, but I think we can make it happen, if that'd make the UX better.

**Comment by lauraponce** [comment]
Is it possible to have the % and $ symbols in the input field, but not part of the actual input? For example: 

![formatting](https://user-images.githubusercontent.com/21222704/47188125-94c6bc80-d2eb-11e8-99ce-800cab059602.gif)

**Comment by mgwalker** [comment]
I'm prototyping switching to a different library for adding the masks, and this new one seems to behave  a lot better.  It still leaves the $ and % in the input, but it's a lot smarter about how it handles the cursor and everything.

One thing I noticed (maybe for a separate issue): the app is inconsistent about whether it accepts decimal places on dollar values.  Should we switch everything over to whole dollars, or should states be entering values to the cent?  My hunch is that all of their initial numbers are whole dollars anyway, but 🤷‍♂️

**Comment by lauraponce** [comment]
@mgwalker Is it okay to tack on another number formatting issue to this one? Currently, there are no commas for large numbers and it starts to become difficult to read once it gets to be 5+ digits. Can you add in commas to show up automatically?

@jeromeleecms Are there any places where we _do_ want the decimals to show up or should everything be rounded across the board? It came up in testing that some of the numbers need to be more exact.

**Comment by jeromeleecms** [comment]
@lauraponce This may show up whenever an hourly wage appears (maybe in the contractor section or an hourly employee if we ever add that). 

I recall there was also a concern about accuracy because the tester saw $2.4M vs $2,424,123 which is not something they would be able to share with their financial management team... related to this question/comment?

**Comment by NAretakis** [comment]
So, this bug is actually resolved. I'm going to spin up a new issue to track the number formatting that we need to have, and reference this in case we need it.
