### ISSUE TITLE
Map the golden path UI decision and process flow

### ISSUE THREAD

**Issue by nicoleslaw** [18F/cms-hitech-apd#106]
Laura and Meg walked through ways they've mapped decision trees for input-heavy applications in the past. We need to do the same for the funding request app.

### This task is done when...
 - [ ] We've mapped the happy path / decision tree in Mural or similar
 - [ ] We've mapped all of the forks off of the happy path (maybe v2) such as the HIE experience that relates to #90

**Comment by nkkl** [comment]
@nicoleslaw @lauraponce can the two of you update the issue description? I don't feel that I understand this task well enough to do that.

Let's also flag areas where it's especially important for @mgwalker and @brendansudol to be involved.

**Comment by nkkl** [comment]
For example, the dev team should be deeply involved in the conversations about budget sections, because those will have a bunch of logic.

**Comment by nicoleslaw** [comment]
I added some notes but would expect @lauraponce to have more input here!

**Comment by lauraponce** [comment]
This looks good to me!

**Comment by lauraponce** [comment]
I started a [mural](https://app.mural.ly/t/gsa6/m/gsa6/1519753079770/c50660659d4d04fd7248310d40e45ad441598ffb) for the task flow and have been basing it off of Nicole's [content exploration doc](https://docs.google.com/document/d/1PjbmxnxnCxE7RrQwm0pIWy_xAs7pX2olD03zgp8JAN4/edit?usp=sharing). There's still a lot more to add, but this is what I was picturing. 

Does this seem like what everyone was expecting for this, or is there another format that would be more useful?

**Comment by nkkl** [comment]
Works for me, but @mgwalker and @brendansudol outweigh me here. I expect it'll get real complicated once we add on the CMS analyst workflow.

**Comment by mgwalker** [comment]
It matches what I was expecting so far.  I also expect it'll get wild once we add more workflows, but...  that's life?  😄

**Comment by lauraponce** [comment]
@jeromeleecms after talking through this a bit more with @quarterback and @nkkl, it might make the most sense to assign this over to you to take over from here based on the fact that you have the right tools and understand the concept of where this needs to go. Does that sound good?

**Comment by jeromeleecms** [comment]
That works for me. Do you want to keep working in Mural or any objections to me translating this into Visio?

**Comment by lauraponce** [comment]
I think Visio might be best since that's ultimately where it will end up and might be easier for you to just update there. Feel free to scrap the Mural!

**Comment by jeromeleecms** [comment]
@lauraponce @quarterback Could you take a look at the overview process flow in [Google Drive](https://drive.google.com/drive/u/0/folders/1-EXHNr6lMcHdnjjus8W5HBd74hxDWCzN)? This is following Nicole's content exploration flow.

All the double bar boxes will have sub-processes on separate pages (to mirror the app), but before I get too far down that path, does this work for you?

**Comment by lauraponce** [comment]
@jeromeleecms this looks great!

**Comment by NAretakis** [comment]
I see where you are going with the double bar boxes. We should be able to draw from the JeromePrototype and content prototype for those, yes?

**Comment by nkkl** [comment]
Is this something we'd be comfortable putting on the wiki? I think it's a really great piece of documentation about the workflow that will be helpful to future teammates.

**Comment by NAretakis** [comment]
I support this idea, but I think we'd want to get it to a reasonable done state first.

**Comment by nkkl** [comment]
Fine by me!

**Comment by jeromeleecms** [comment]
@NAretakis This should mirror the content exploration workflow in Drive + a little verification against what has been built in the app now. If there are parts that I feel are missing, I'll note it in the content exploration document and fill portions from the previous prototype. Seem OK?

I'll start building the sub-processes for the reminder of the map later this week.

**Comment by jeromeleecms** [comment]
First pass of the ["Golden Path"](https://drive.google.com/drive/u/0/folders/1-EXHNr6lMcHdnjjus8W5HBd74hxDWCzN) completed. Cross referenced this between [use case document](https://docs.google.com/document/d/1Oh8C9YSORO03Mh9kGF-TKgWnmQvamuaTIUjcoK3cc7U/edit#heading=h.9lorq0fiufoq) and [the content exploration document](https://docs.google.com/document/d/1PjbmxnxnCxE7RrQwm0pIWy_xAs7pX2olD03zgp8JAN4/edit). 

There are some placeholders for some of the more complicated use cases and some items that haven't been developed yet.

Ready for @nkkl @lauraponce @quarterback @NAretakis review? 

Also, now that this is done, there are some general work flow issues that I sense that would be great if we could talk through after you have had a chance to review.

**Comment by nkkl** [comment]
Looks good to me! I think this will be really helpful for our TRB documentation (#307).

**Comment by lauraponce** [comment]
This looks great @jeromeleecms! It's easy to follow and makes sense to me.

**Comment by jeromeleecms** [comment]
Version 1 complete. Opened up #327 for subsequent enhancements.
