### ISSUE TITLE
Review Activity Summary Table

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1073]
#1041 removes the start date of the milestone in the activity, but this does not filter down to the activity summary table. Would like for Design to take a look at how a new version of the table would look without the start date. 

#1067 Has some additional discussion.

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
 ** Don't forget to fill out the LABEL and MILESTONE before submitting. If the issue is for the CURRENT SPRINT, add it to the PROJECT. If the issue is a BUG, FUTURE ENHANCEMENT, or OUTSIDE OF THE CURRENT SPRINT, do not add it to the PROJECT (then delete this line) **

**Comment by NAretakis** [comment]
summary activity schedule now functions using start date for the activity, and end date for each milestone.
