### ISSUE TITLE
Normalize Heading styles and markup

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1076]
While working on #1034, I realized the styles and markup in the app are inconsistent with both the Sketch file and each other. In order to successfully implement #1034, the proper typography rules must be in place. Currently, any expansion of the typographic styles will create more of a mess to fix later, and implementing styles will take longer from a dev perspective because the current styles aren't organized in a hierarchical manner.

Adding Design to this task as well as Dev because this will require us to be in sync.

### This task is done when...
 - [ ] Visual hierarchy of headings has been updated in design
 - [ ] Heading styles have been updated in Sketch files
 - [ ] all text items are enclosed in text-appropriate markup
 - [ ] heading levels are used semantically (currently, some headings are used because they have the right styles for the design, even if they're used out-of-order)
 - [ ] the styles inherited by text elements match the line height, weight, font size and font face of their corresponding elements in the style guide.
 - [ ] Design has reviewed the typographic implementation and can work with it.
 - [ ] Styles have been added to Storybook

**Comment by jenniferthibault** [comment]
Added a few criteria in the description above to make it work for #1082

**Comment by hbillings** [comment]
A few notes on specifics from my markup assessment-palooza:
## H1s

There's only one `h1` on the site: the state text in the sidebar. It's sized like an `h3`. 
<img width="449" alt="screen shot 2018-11-27 at 1 47 41 pm" src="https://user-images.githubusercontent.com/509309/49110528-03802980-f24b-11e8-99ad-fdf81aa13f36.png">

## H2s

Our only `h2`s appear to be section headings. These are currently styled with `.h1 .sm-h0` classes, of which the latter takes precedence for a size of 2.5rem. I'd like to get away from using anything `h0`, as it breaks expectations of what the largest size font is. I would argue that this should actually be our `h2` size, since we don't use `h2`s for anything other than these headers.

<img width="763" alt="screen shot 2018-11-27 at 1 44 47 pm" src="https://user-images.githubusercontent.com/509309/49110378-8f458600-f24a-11e8-886f-36dc996ed751.png">

## H3s

Subsection headings are button text with both `.h3` sizes and a Basscss class called `sm-h2` applied. The `sm-h2` class takes precedence and makes these 1.5rem large. Semantically, these should be `h3`s. Our
<img width="564" alt="screen shot 2018-11-26 at 2 49 56 pm" src="https://user-images.githubusercontent.com/509309/49109422-df6f1900-f247-11e8-958b-e259708943f7.png">

The title on the APD container on the homepage should be an `h3` instead of a `span` (currently has `h2` class for sizing):
<img width="567" alt="screen shot 2018-11-26 at 2 02 26 pm" src="https://user-images.githubusercontent.com/509309/49109191-5952d280-f247-11e8-84c0-d3bc33357221.png">

## H4s

Within subsections, subdivisions are headed by either `h3`s or just `div`s with bold font. Semantically, these should both be `h4`s.

h3:
<img width="538" alt="screen shot 2018-11-26 at 5 22 19 pm" src="https://user-images.githubusercontent.com/509309/49109554-41c81980-f248-11e8-94ce-7431b087f575.png">

bold div:
<img width="604" alt="screen shot 2018-11-26 at 5 32 49 pm" src="https://user-images.githubusercontent.com/509309/49110254-383fb100-f24a-11e8-9791-add361718c43.png">

## H5s

Most of the text elements in Cost Allocation tables are contained in plain divs, and, as such, don’t indicate their relationship to each other. I went back and forth about the best way to mark these up, and I think we should probably use `h5`s and `p` tags.
<img width="565" alt="screen shot 2018-11-26 at 5 58 55 pm" src="https://user-images.githubusercontent.com/509309/49110223-1cd4a600-f24a-11e8-8af5-40015523041c.png">

**Comment by mgwalker** [comment]
Hmm.  This is really interesting.

The elements you flag to be H2s and H3s are in a generic components so those should be "easy" to switch over across the board all at once.  The H2s are in [Section.js](/18F/cms-hitech-apd/blob/master/web/src/components/Section.js), the `SectionTitle` component.  The H3s are in [Collapsible.js](https://github.com/18F/cms-hitech-apd/blob/master/web/src/components/Collapsible.js)

I wonder if the H4s you've identified should map to the the `heading` property of the `instruction` element we identified in #1088.  That one is a more involved fix, either way, since it'll require dropping into each section and making the fixes, but it'd be dandy to feed two birds with one scone on that one.

**Comment by NAretakis** [comment]
@hbillings is this still a thing that we need to do since we have the design system?

**Comment by jeromeleecms** [comment]
Will be handled section by section. Obsolete.
