### ISSUE TITLE
Clarify interaction of add/edit/remove item component

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cms-hitech-apd#1077]
The pattern of creating a list of one or many items with a title & description is one that happens in a few places of the app. These interactions are often nested, which adds complexity. At least two new members of the 18F team interacted with the component, and didn't  understand it's features or capabilities.

The interaction must allow the user to:
- enter at least one item
- add another item with details
- remove an item and its detail fields
- expand/collapse the details of an item you've added
- name an item, and see the title associated with the description (and see it adjust when changed)

Seen here: https://hitech-apd.app.cloud.gov/apd
![screen shot 2018-10-29 at 2 27 02 pm](https://user-images.githubusercontent.com/11636908/47671794-bf840100-db86-11e8-9429-36b5355da11b.png)

Identified challenges with the current design:
- there are two adjacent buttons for removing an item
- the title field looks and acts like a paragraph field, so it doesn't give users clues to what an appropriate input is
- it's not clear that you can collapse items
- visual grouping of elements is unclear

### This task is done when...
 - [ ] We have proposed a new design for the interaction
 - [ ] We have tested the interaction with users, 
   - [ ] who successfully use it to complete their tasks

**Comment by jenniferthibault** [comment]
Looked at this with other designers, and leaving some notes here for our future selves:

- The purpose of the blue bar (where info is often recapped from what's entered) isn't clear. We should find out if it really serves a purpose (such as capturing info that's brought into tabular data elsewhere in the form) and clarify that, or possibly eliminate it
- Make the pattern consistent and predictable between instances where it's applied, so that all "Add" and "Remove" interactions feel the same, no matter what they're applied to
- Make it more clear what information is the unit of one add/remove instance


And found a few related examples for future inspiration. None of these are quite exactly like our context, but show a few possible different approaches:

![screen shot 2018-11-27 at 4 05 16 pm](https://user-images.githubusercontent.com/11636908/49118509-836dba00-f272-11e8-8046-669900c605c8.png)
<img width="740" alt="screen shot 2018-11-27 at 2 14 59 pm" src="https://user-images.githubusercontent.com/11636908/49118513-8799d780-f272-11e8-9f68-9b3dc1220f91.png">
<img width="749" alt="screen shot 2018-11-27 at 4 27 02 pm" src="https://user-images.githubusercontent.com/11636908/49118530-a4360f80-f272-11e8-9da5-9b02fd1703af.png">
<img width="871" alt="screen shot 2018-11-27 at 4 51 07 pm" src="https://user-images.githubusercontent.com/11636908/49118536-a8fac380-f272-11e8-825a-c27f3f66a5cb.png">

**Comment by NAretakis** [comment]
OBSOLETE due to Austin!
