### ISSUE TITLE
Create dropdown for analysts to set document state

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1081]
Analysts need to be able to set a document's status after it is submitted.

### This task is done when...
 - [ ] dashboard shows all documents for CMS users [#1092]
 - [ ] CMS users can change a document's status [requires #1091]

Maybe related to #1043?
 
Immediate questions:
- Do analysts need to see *all* documents, or only documents that are not in draft?
- What are the document status options?

**Comment by jenniferthibault** [comment]
For your immediate questions, @mgwalker:
- Seeing all documents vs seeing documents that are not in draft
   - State users should see all documents, including those in draft
   - CMS users should see....I'm not sure! @jeromeleecms or @NAretakis this seems like a good place for your help and expertise!
- We're working on finalizing the document status options in #1029 ( 👀 for this dependency @jameshupp )

**Comment by NAretakis** [comment]
Are created and draft the same thing? If so, CMS users should see all types except "created/draft".

**Comment by jenniferthibault** [comment]
Pulling the final words for the dropdown in here from #1029, and integrating with Nick's comment above.

The document status options should be: 

```
Draft in progress
Submitted
Under review
Reviewed, in clearance
Decision: approved
Decision: denied
Withdrawn
```
- State users should see all documents
- CMS users should see all documents except `Draft in progress`

**Comment by mgwalker** [comment]
Going to break this into two issues.  We need (temporary!) backend functionality to allow analysts to explicitly set the document status.  The frontend functionality will come after that, and is probably pending #1029 wrapping up and being implemented, too - not a lot of sense building new UI on the dashboard just so we can toss it out a couple days later when the new MVP dashboard design lands.  😄

**Comment by mgwalker** [comment]
This seems like it's no longer a Layer 1 item.  Should this be de-prioritized in favor of other stuff?

**Comment by NAretakis** [comment]
Correct, this is layer 2. I’ll adjust the priority.

**Comment by NAretakis** [comment]
Obsolete. We'll spin up an issue to track the design pattern for various eAPD document statuses.
