### ISSUE TITLE
Assess current content patterns and make a to-do list

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1083]
### to-do list (that will turn into subsequent issues):
 - [x] Complete #1025 (it feels like cheating to embed one issue as a to-do of another, but this is a dependency).
 - [x] Develop a content backlog based on existing results of user research and auditing the existing content.

**Comment by jameshupp** [comment]
Here’s my stab at an ordered list of in-app content priorities. This does _not_ include the Dashboard, which has settled on a very simple approach for MVP. There might be more to do on that, but we can address that later. My order here is driven by a couple hypotheses:

- Research findings are a higher priority than things we've noticed on our own unless there's an underlying business value justification to prioritize something else.
- Handling of instructional copy in a consistent way will get us a lot of bang for our buck down the line.

If product agrees with this list, we can close this issue.

#1142: Refine the language around attachments (in response to findings in round 8 research)
Build from 1088/1134 (does not exist, exactly): implement the new helpText/instruction format
#1164: Clarify the language related to the Incentive Payments table (in response to findings in round 8 research)
#1178: Clarify and execute the handling of section descriptions in YAML
#1088: Instruction text consistency (refining what is currently `helpText and `reminder` into types of `instruction` in YAML, prior to the app code itself being updated along these lines)
#1179: Review second/third person usage for consistency with CMS #1179
#1177: Clarify about how direct attributable costs are broken out into the subsequent data of the app.
#1180: Further refine content guide to account for Layer 1 updates

**Comment by NAretakis** [comment]
This looks great. We can help prioritize too. Only one that might be a little less priority is the attachment one, because I don't know if we'll even have that in Layer 1. But that is a sprint planning thing. Thanks for putting this together, I think we can close.
