### ISSUE TITLE
Figure out the ideal frequency and cadence of research

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1084]
Potentially:

Week 1: Plan/schedule testing
Week 2: Conduct testing sessions + synthesize/prioritize changes
Week 3: Implement changes
Week 4: Plan/schedule testing 
...

**Comment by lauraponce** [comment]
@NAretakis @jeromeleecms does this look right for the cadence of testing? If so, that would put us in the first week of December for the following round.

**Comment by lauraponce** [comment]
Visualing it as: 
<img width="618" alt="screen shot 2018-11-09 at 1 55 40 pm" src="https://user-images.githubusercontent.com/21222704/48290296-3478f580-e427-11e8-9613-179da8b377c5.png">

**Comment by NAretakis** [comment]
It looks good, but is it too compressed to try and do design updates and dev updates within one week? Maybe we make the purple section two weeks, instead of just one.

**Comment by jeromeleecms** [comment]
@lauraponce Not sure if this is right place to include this, but after yesterday's testing session did some more thinking about flow of testing. Can we try to have the flow of the protocol more tied together?

For example: if we are testing summary budget tables, can we try test adding personnel, contracts, cost allocation -> summary budget table? 

Another example: Add milestones to an activity and review the summary milestone/timetable? 

It seems like there is a bit of struggle during transitioning to different pieces of the APD and then we have to revisit a piece we aren't testing for the user to make sense of what we are actually asking.

**Comment by jeromeleecms** [comment]
@lauraponce Is this done? If so, it seems like we would want to commit this to the Wiki before we close it out. If not, what else needs to be done?

**Comment by NAretakis** [comment]
I think this is connected to #1130 if so, we can close this one.

**Comment by lauraponce** [comment]
Agreed! This is very much part of #1130 and should be included in that. I just added a little more info to the #1130 issue that covers this part of it specifically.

**Comment by NAretakis** [comment]
Awesome, thanks!
