### ISSUE TITLE
Draft design principles

### ISSUE THREAD

**Issue by nicoleslaw** [18F/cms-hitech-apd#109]
I like putting these in the voice of the user. For example, here's what Amber and I did for the FBI Crime Data Explorer: https://github.com/18F/crime-data-explorer/wiki/Experience-Principles

**Comment by nicoleslaw** [comment]
Leaving notes here as I think of them:

- Guide the user
- Make it flexible
- Use specific examples

**Comment by lauraponce** [comment]
@quarterback I drafted up the design principles here: https://docs.google.com/document/d/1lF7R4fczBf_BYpmi8gTHaa-cPxRtRaRoTfgOUqyFGk8/edit?usp=sharing 

Feel free to make any edits!
