### ISSUE TITLE
Tech debt: deployment documentation is out of date

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1090]
Need to update deployment documentation.  Might be worth holding on to this issue until we're a little further along in our migration.

### This task is done when...
 - [ ] deployment documentation matches reality

**Comment by mgwalker** [comment]
Recommend holding until #1014 and #1013 are done.  Documentation would be speculative right now and would just have to be updated again.

**Comment by mgwalker** [comment]
Updated [dev deployment](https://github.com/18F/cms-hitech-apd/wiki/Dev%3A-Deployment), [infrastructure architecture](https://github.com/18F/cms-hitech-apd/wiki/Infrastructure-Architecture), and [authentication](https://github.com/18F/cms-hitech-apd/wiki/Authentication) pages in the wiki, with a small smattering of updates elsewhere as needed (things like library updates, mostly).

@NAretakis @jeromeleecms Do one of you want to review the updated docs before we close this?

**Comment by NAretakis** [comment]
Awesome. No, don't need to review via this issue. If anything comes up during our ATO/compliance stuff, we'll track it there, if updates are needed. Closing this one out.
