### ISSUE TITLE
Reduce the table content for Results of Previous Activities

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1099]
Prepping for state testing, I realized the results of previous activities table is asking for way too much information. This issue proposes a redesign of the table to just the bare essentials, which also matches CMS' expenditure reporting business processes.

Proposal is to cut down the table results of previous activities tables to just this:
![image](https://user-images.githubusercontent.com/34281281/48099712-af4ed000-e1dd-11e8-89ce-c5f2568a5ed7.png)

### This task is done when...
 - [x] design team gives it a look over or head nod
 - [ ] dev issue created to implement

**Attempt to put the actual CSS below for reference. Hopefully this helps?**

<table class="table-cms table-fixed" style="min-width: 100px;"><thead><tr><th id="prev_act_hit_header_null1" style="width: 90px;"></th><th colspan="3" class="bg-navy center" id="prev_act_hit_combined">HIT + HIE</th></tr><tr><th id="prev_act_hit_header_null2"></th><th colspan="1" class="pre-line" id="prev_act_hit_total">Total Computable</th><th colspan="2" class="pre-line" id="prev_act_hit_federal_0">Federal share 90% FFP</th></tr><tr><th id="prev_act_hit_header_null3"></th><th class="bg-aqua-light" id="prev_activity_header0">Approved</th><th class="bg-aqua-light" id="prev_activity_header2">Approved</th><th id="prev_activity_header3">Actual</th></tr></thead><tbody><tr class="align-middle"><th id="prev_act_hit_row_2016">FFY 2016</th><td headers="prev_act_hit_row_2016 prev_act_hit_combined prev_act_hit_total prev_activity_header0"><div class="m0"><label for="approved-federal-combined-2016" class="sr-only">approved total computable, FFY 2016</label><input class="m0 input input-condensed mono right-align" id="approved-federal-combined-2016" type="text" value="$60000"></div></td><td headers="prev_act_hit_row_2016 prev_act_hit_hit prev_act_hit_federal_0 prev_activity_header1"><div class="m0"><label for="approved-federal-hit-2016" class="sr-only">approved federal share for hit + hie, FFY 2016</label><input class="m0 input input-condensed mono right-align" id="approved-federal-hit-2016" type="text" value="$900000"></div></td><td headers="prev_act_hit_row_2016 prev_act_hit_hit prev_act_hit_federal_0 prev_activity_header2"><div class="m0"><label for="actual-federal-hit-2016" class="sr-only">actual federal share for hit + hie, FFY 2016</label><input class="m0 input input-condensed mono right-align" id="actual-federal-hit-2016" type="text" value="$0"></div></td></tr><tr class="align-middle"><th id="prev_act_hit_row_2017">FFY 2017</th><td headers="prev_act_hit_row_2017 prev_act_hit_combined prev_act_hit_total prev_activity_header0"><div class="m0"><label for="approved-federal-combined-2017" class="sr-only">approved total computable, FFY 2017</label><input class="m0 input input-condensed mono right-align" id="approved-federal-combined-2017" type="text" value="$60000"></div></td><td headers="prev_act_hit_row_2017 prev_act_hit_hit prev_act_hit_federal_0 prev_activity_header1"><div class="m0"><label for="approved-federal-hit-2017" class="sr-only">approved federal share for hit + hie, FFY 2017</label><input class="m0 input input-condensed mono right-align" id="approved-federal-hit-2017" type="text" value="$900000"></div></td><td headers="prev_act_hit_row_2017 prev_act_hit_hit prev_act_hit_federal_0 prev_activity_header2"><div class="m0"><label for="actual-federal-hit-2017" class="sr-only">actual federal share for hit + hie, FFY 2017</label><input class="m0 input input-condensed mono right-align" id="actual-federal-hit-2017" type="text" value="$0"></div></td></tr><tr class="align-middle"><th id="prev_act_hit_row_2018">FFY 2018</th><td headers="prev_act_hit_row_2018 prev_act_hit_combined prev_act_hit_total prev_activity_header0"><div class="m0"><label for="approved-federal-combined-2018" class="sr-only">approved total computable, FFY 2018</label><input class="m0 input input-condensed mono right-align" id="approved-federal-combined-2018" type="text" value="$60000"></div></td><td headers="prev_act_hit_row_2018 prev_act_hit_hit prev_act_hit_federal_0 prev_activity_header1"><div class="m0"><label for="approved-federal-hit-2018" class="sr-only">approved federal share for hit + hie, FFY 2018</label><input class="m0 input input-condensed mono right-align" id="approved-federal-hit-2018" type="text" value="$900000"></div></td><td headers="prev_act_hit_row_2018 prev_act_hit_hit prev_act_hit_federal_0 prev_activity_header2"><div class="m0"><label for="actual-federal-hit-2018" class="sr-only">actual federal share for hit + hie, FFY 2018</label><input class="m0 input input-condensed mono right-align" id="actual-federal-hit-2018" type="text" value="$0"></div></td></tr></tbody></table>

<div class="mb3"><div class="overflow-auto"><table class="table-cms table-fixed" style="min-width: 100px;"><thead><tr><th id="prev_act_mmis_null1" style="width: 90px;"></th><th colspan="8" class="bg-aqua center" id="prev_act_mmis_header">MMIS</th></tr><tr><th id="prev_act_mmis_null2"></th><th colspan="1" class="pre-line" id="prev_act_mmis_total">Total Computable</th><th colspan="2" class="pre-line" id="prev_act_mmis_federal90">Federal share 90% FFP</th><th colspan="2" class="pre-line" id="prev_act_mmis_federal75">Federal share 75% FFP</th><th colspan="2" class="pre-line" id="prev_act_mmis_federal50">Federal share 50% FFP</th><th colspan="1" class="pre-line" id="prev_act_mmis_total">Total Computable</th></tr><tr><th id="prev_act_mmis_null3"></th><th id="prev_act_mmis_totalApproved" class="bg-aqua-light">Approved</th><th id="prev_act_mmis_fed90approved" class="bg-aqua-light">Approved</th><th id="prev_act_mmis_fed90actual" class="border-left border-gray">Actual</th><th id="prev_act_mmis_fed75approved" class="bg-aqua-light">Approved</th><th id="prev_act_mmis_fed75actual" class="border-left border-gray">Actual</th><th id="prev_act_mmis_fed50approved" class="bg-aqua-light">Approved</th><th id="prev_act_mmis_fed50actual" class="border-left border-gray">Actual</th><th id="prev_act_mmis_totalActual">Actual</th></tr></thead><tbody><tr class="align-middle"><th id="prev_act_mmis_row_2016">FFY 2016</th><td headers="prev_act_mmis_row_2016 prev_act_mmis_header prev_act_mmis_total prev_act_mmis_totalapproved"><div class="m0"><label for="approved-total-mmis-2016" class="sr-only">approved total computable mmis, FFY 2016</label><input class="m0 input input-condensed mono right-align" id="approved-total-mmis-2016" type="text" value=""></div></td><td headers="prev_act_mmis_row_2016 prev_act_mmis_header prev_act_mmis_federal90 prev_act_mmis_fed90approved"><div class="m0"><label for="approved-federal90-mmis-2016" class="sr-only">approved federal 90% share for mmis, FFY 2016</label><input class="m0 input input-condensed mono right-align" id="approved-federal90-mmis-2016" type="text" value=""></div></td><td headers="prev_act_mmis_row_2016 prev_act_mmis_header prev_act_mmis_federal90 prev_act_mmis_fed90actual"><div class="m0"><label for="actual-federal90-mmis-2016" class="sr-only">actual federal 90% share for mmis, FFY 2016</label><input class="m0 input input-condensed mono right-align" id="actual-federal90-mmis-2016" type="text" value=""></div></td><td headers="prev_act_mmis_row_2016 prev_act_mmis_header prev_act_mmis_federal75 prev_act_mmis_fed75approved"><div class="m0"><label for="approved-federal75-mmis-2016" class="sr-only">approved federal 75% share for mmis, FFY 2016</label><input class="m0 input input-condensed mono right-align" id="approved-federal75-mmis-2016" type="text" value=""></div></td><td headers="prev_act_mmis_row_2016 prev_act_mmis_header prev_act_mmis_federal75 prev_act_mmis_fed75actual"><div class="m0"><label for="actual-federal75-mmis-2016" class="sr-only">actual federal 75% share for mmis, FFY 2016</label><input class="m0 input input-condensed mono right-align" id="actual-federal75-mmis-2016" type="text" value=""></div></td><td headers="prev_act_mmis_row_2016 prev_act_mmis_header prev_act_mmis_federal50 prev_act_mmis_fed50approved"><div class="m0"><label for="approved-federal50-mmis-2016" class="sr-only">approved federal 50% share for mmis, FFY 2016</label><input class="m0 input input-condensed mono right-align" id="approved-federal50-mmis-2016" type="text" value=""></div></td><td headers="prev_act_mmis_row_2016 prev_act_mmis_header prev_act_mmis_federal50 prev_act_mmis_fed50actual"><div class="m0"><label for="actual-federal50-mmis-2016" class="sr-only">actual federal 50% share for mmis, FFY 2016</label><input class="m0 input input-condensed mono right-align" id="actual-federal50-mmis-2016" type="text" value=""></div></td><td headers="prev_act_mmis_row_2016 prev_act_mmis_header prev_act_mmis_total prev_act_mmis_totalActual">--</td></tr><tr class="align-middle"><th id="prev_act_mmis_row_2017">FFY 2017</th><td headers="prev_act_mmis_row_2017 prev_act_mmis_header prev_act_mmis_total prev_act_mmis_totalapproved"><div class="m0"><label for="approved-total-mmis-2017" class="sr-only">approved total computable mmis, FFY 2017</label><input class="m0 input input-condensed mono right-align" id="approved-total-mmis-2017" type="text" value=""></div></td><td headers="prev_act_mmis_row_2017 prev_act_mmis_header prev_act_mmis_federal90 prev_act_mmis_fed90approved"><div class="m0"><label for="approved-federal90-mmis-2017" class="sr-only">approved federal 90% share for mmis, FFY 2017</label><input class="m0 input input-condensed mono right-align" id="approved-federal90-mmis-2017" type="text" value=""></div></td><td headers="prev_act_mmis_row_2017 prev_act_mmis_header prev_act_mmis_federal90 prev_act_mmis_fed90actual"><div class="m0"><label for="actual-federal90-mmis-2017" class="sr-only">actual federal 90% share for mmis, FFY 2017</label><input class="m0 input input-condensed mono right-align" id="actual-federal90-mmis-2017" type="text" value=""></div></td><td headers="prev_act_mmis_row_2017 prev_act_mmis_header prev_act_mmis_federal75 prev_act_mmis_fed75approved"><div class="m0"><label for="approved-federal75-mmis-2017" class="sr-only">approved federal 75% share for mmis, FFY 2017</label><input class="m0 input input-condensed mono right-align" id="approved-federal75-mmis-2017" type="text" value=""></div></td><td headers="prev_act_mmis_row_2017 prev_act_mmis_header prev_act_mmis_federal75 prev_act_mmis_fed75actual"><div class="m0"><label for="actual-federal75-mmis-2017" class="sr-only">actual federal 75% share for mmis, FFY 2017</label><input class="m0 input input-condensed mono right-align" id="actual-federal75-mmis-2017" type="text" value=""></div></td><td headers="prev_act_mmis_row_2017 prev_act_mmis_header prev_act_mmis_federal50 prev_act_mmis_fed50approved"><div class="m0"><label for="approved-federal50-mmis-2017" class="sr-only">approved federal 50% share for mmis, FFY 2017</label><input class="m0 input input-condensed mono right-align" id="approved-federal50-mmis-2017" type="text" value=""></div></td><td headers="prev_act_mmis_row_2017 prev_act_mmis_header prev_act_mmis_federal50 prev_act_mmis_fed50actual"><div class="m0"><label for="actual-federal50-mmis-2017" class="sr-only">actual federal 50% share for mmis, FFY 2017</label><input class="m0 input input-condensed mono right-align" id="actual-federal50-mmis-2017" type="text" value=""></div></td><td headers="prev_act_mmis_row_2017 prev_act_mmis_header prev_act_mmis_total prev_act_mmis_totalActual">--</td></tr><tr class="align-middle"><th id="prev_act_mmis_row_2018">FFY 2018</th><td headers="prev_act_mmis_row_2018 prev_act_mmis_header prev_act_mmis_total prev_act_mmis_totalapproved"><div class="m0"><label for="approved-total-mmis-2018" class="sr-only">approved total computable mmis, FFY 2018</label><input class="m0 input input-condensed mono right-align" id="approved-total-mmis-2018" type="text" value=""></div></td><td headers="prev_act_mmis_row_2018 prev_act_mmis_header prev_act_mmis_federal90 prev_act_mmis_fed90approved"><div class="m0"><label for="approved-federal90-mmis-2018" class="sr-only">approved federal 90% share for mmis, FFY 2018</label><input class="m0 input input-condensed mono right-align" id="approved-federal90-mmis-2018" type="text" value=""></div></td><td headers="prev_act_mmis_row_2018 prev_act_mmis_header prev_act_mmis_federal90 prev_act_mmis_fed90actual"><div class="m0"><label for="actual-federal90-mmis-2018" class="sr-only">actual federal 90% share for mmis, FFY 2018</label><input class="m0 input input-condensed mono right-align" id="actual-federal90-mmis-2018" type="text" value=""></div></td><td headers="prev_act_mmis_row_2018 prev_act_mmis_header prev_act_mmis_federal75 prev_act_mmis_fed75approved"><div class="m0"><label for="approved-federal75-mmis-2018" class="sr-only">approved federal 75% share for mmis, FFY 2018</label><input class="m0 input input-condensed mono right-align" id="approved-federal75-mmis-2018" type="text" value=""></div></td><td headers="prev_act_mmis_row_2018 prev_act_mmis_header prev_act_mmis_federal75 prev_act_mmis_fed75actual"><div class="m0"><label for="actual-federal75-mmis-2018" class="sr-only">actual federal 75% share for mmis, FFY 2018</label><input class="m0 input input-condensed mono right-align" id="actual-federal75-mmis-2018" type="text" value=""></div></td><td headers="prev_act_mmis_row_2018 prev_act_mmis_header prev_act_mmis_federal50 prev_act_mmis_fed50approved"><div class="m0"><label for="approved-federal50-mmis-2018" class="sr-only">approved federal 50% share for mmis, FFY 2018</label><input class="m0 input input-condensed mono right-align" id="approved-federal50-mmis-2018" type="text" value=""></div></td><td headers="prev_act_mmis_row_2018 prev_act_mmis_header prev_act_mmis_federal50 prev_act_mmis_fed50actual"><div class="m0"><label for="actual-federal50-mmis-2018" class="sr-only">actual federal 50% share for mmis, FFY 2018</label><input class="m0 input input-condensed mono right-align" id="actual-federal50-mmis-2018" type="text" value=""></div></td><td headers="prev_act_mmis_row_2018 prev_act_mmis_header prev_act_mmis_total prev_act_mmis_totalActual">--</td></tr></tbody></table></div></div>

**Comment by NAretakis** [comment]
tagged @jenniferthibault to give this a design scan. We can sync on this briefly if it will help.

**Comment by jenniferthibault** [comment]
@NAretakis are these two images a correct summary of the changes you made above?

![screen shot 2018-11-08 at 3 34 03 pm](https://user-images.githubusercontent.com/11636908/48225786-d76c3980-e36b-11e8-9c4f-8e7470a757ec.png)


![screen shot 2018-11-08 at 3 35 12 pm](https://user-images.githubusercontent.com/11636908/48225787-d804d000-e36b-11e8-85e4-3ecd6cec4772.png)

**Comment by NAretakis** [comment]
yes, that is correct.

**Comment by NAretakis** [comment]
Yes please! This look so beautiful.

**Comment by jenniferthibault** [comment]
Moving forward to implementation in #1111
