### ISSUE TITLE
Investigate using AWS with CMS cloud team

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#11]
AWS may be a feasible hosting option for us, but we need support from CMS IT. @NicolasAretakisCMS will broker the initial conversations.

- [x] dream list of AWS services needed

**Comment by brendansudol** [comment]
Here's the initial list:

AWS Elastic Beanstalk - https://aws.amazon.com/elasticbeanstalk/

(Handles the deployment, from capacity provisioning, load balancing, auto-scaling to application health monitoring)

--

Amazon Relational Database Service (RDS) - https://aws.amazon.com/rds/

(PostgreSQL to start at least)

--

Amazon CloudWatch - https://aws.amazon.com/cloudwatch/

(Monitor metrics such as average CPU utilization, request count, and average latency; built into Beanstalk)

**Comment by brendansudol** [comment]
@nkkl -- when should this issue be closed? nick has the dream list, but i assume that convos will CMS IT will be ongoing for perhaps a longish time

**Comment by nkkl** [comment]
If @NicolasAretakisCMS feels good about the list, and won't lose it, then I'm happy to close the issue.

**Comment by nkkl** [comment]
@NicolasAretakisCMS set up a meeting for us on Monday!
