### ISSUE TITLE
Implement style changes & reduce content for Actual Costs of Prior Activities table

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cms-hitech-apd#1111]
Moving forward from design in #1099 

Update the "[Actual Costs](https://hitech-apd.app.cloud.gov/apd#prev-activities-table)" of Prior Activities tables by:
- Removing the columns shown in both tables
- Adding the column shown in the MMIS table
- Changing the cell labels as shown in both tables
- Restyling the table title from a row to `h3` to match elsewhere

(Click the images to enlarge and make them legible 👇 )
![screen shot 2018-11-08 at 6 07 02 pm](https://user-images.githubusercontent.com/11636908/48233250-80be2a00-e382-11e8-90b6-e51983c27bf0.png)

![screen shot 2018-11-08 at 6 06 55 pm](https://user-images.githubusercontent.com/11636908/48233028-ae56a380-e381-11e8-8ac4-f8f9031e1b25.png)

To match this layout when implemented:
![screen shot 2018-11-08 at 4 24 32 pm](https://user-images.githubusercontent.com/11636908/48233050-caf2db80-e381-11e8-89e2-3adb76085286.png)

### This task is done when...
 - [ ] The HIT + HIE table matches the mockup
 - [ ] The MMIS table matches the mockup

**Comment by jenniferthibault** [comment]
@NAretakis new issue created! Would you mind taking a look to label & prioritize within this sprint's activities?

**Comment by NAretakis** [comment]
Updated and in this sprint. Thanks!

**Comment by mgwalker** [comment]
@jenniferthibault @NAretakis

To be clear, the "total computable cost" in the HIT+HIE table should become an input field?  (It's currently computed from the values in the inputs.)

The MMIS table above shows `--`, but should that also be an input?  Or should that be calculated?

If those should both be calculated, then I can power ahead, but if either of them needs to be an input, then I need to make a data model change.  (And if the HIT+HIE table shows a computed value...  why?  It would just be the same as what they entered, I think.  😄)

**Comment by jenniferthibault** [comment]
Thanks for flagging @mgwalker ! That may have been a mistake on my part, and I don't know the data entry well enough to say what is correct or expected. @NAretakis can you guide us here to how the table should handle these cells?

**Comment by NAretakis** [comment]
So, I think this might be a good case for us to pair. Below is a revised table with explanations for calculating fields. However, because of the calculating fields, it kind of got big again. Which is OK, temporarily.
![image](https://user-images.githubusercontent.com/34281281/48520617-8908e000-e82e-11e8-827f-8a68021476d7.png)

**Comment by jenniferthibault** [comment]
Ahhhok — If that's the table we're working with, it gets a little confusing which "total" column is grouped with which % (you noticed this and solved it yourself by grouping the elements with different colored boxes). One way to solve that would be to ungroup the tables again, which makes a longer part of the form, but more clear which parts go together. We could also remedy this with different table styles, but I'm trying to avoid that for now. 

![screen shot 2018-11-14 at 7 48 57 pm](https://user-images.githubusercontent.com/11636908/48522431-b06ba700-e846-11e8-9a56-77a15bfa88c4.png)

**Comment by NAretakis** [comment]
What you've done here is beautiful! This looks perfect!
This also is very similar to the CMS accounting system, which is what I was trying to link this to. Example below for reference.

![image](https://user-images.githubusercontent.com/34281281/48523398-97a8c480-e839-11e8-858e-8d32c6415b59.png)

**Comment by mgwalker** [comment]
Slick!  Is this one ready to roll with @jenniferthibault's design?  It's all clicking in my head now, I think.

**Comment by NAretakis** [comment]
Yes.
"You may fire when ready."
            --Grand Moff Tarkin
