### ISSUE TITLE
Replace the yes/no button styles with more appropriate interaction

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cms-hitech-apd#1115]
Carried forward from #1082 

Problems with the current style and implementation:
- With only two options, it's hard to distinguish if white or black is the selected state
- In most instances where these are implemented, a two-choice option is better represented as a radio button set, with a conditional text area for people to input additional information when needed. In some instances where this is implemented, a single checkbox would be more appropriate. 

![screen shot 2018-11-09 at 6 47 20 pm](https://user-images.githubusercontent.com/11636908/48294035-efb58480-e44f-11e8-84a1-65cb3e87a7c3.png)

### This task is done when...
 - [x] Each instance has been identified.
 - [x] The more appropriate interaction has been assessed and mocked up by design
 - [ ] An implementation issue has been created for the development team (that includes adding the pattern to storybook as a criteria for "done")

**Comment by jenniferthibault** [comment]
## Step 1: Identify each instance:

### Key Personnel
<img width="750" alt="screen shot 2018-11-20 at 9 46 41 am" src="https://user-images.githubusercontent.com/11636908/48781095-508f5900-eca9-11e8-8fbd-6d413762bf01.png">

### In-House Cost Categories
This one is getting eliminated via #1121 so we don't need to address it (win!)
<img width="750" alt="screen shot 2018-11-20 at 9 37 44 am" src="https://user-images.githubusercontent.com/11636908/48781000-17ef7f80-eca9-11e8-9fe7-d54a1b1215c3.png">

### Private Contractor Costs
<img width="746" alt="screen shot 2018-11-20 at 9 38 21 am" src="https://user-images.githubusercontent.com/11636908/48781001-17ef7f80-eca9-11e8-8333-9483533a34e8.png">

### Federal Citations and Justifications
There are 15 of these instances in a row
<img width="764" alt="screen shot 2018-11-20 at 9 39 26 am" src="https://user-images.githubusercontent.com/11636908/48781002-17ef7f80-eca9-11e8-9147-17b9d411eb3d.png">


## Next steps
I'll design the appropriate interaction pattern for each

**Comment by jenniferthibault** [comment]
Trying a new approach for presenting: InVision Freehand, which lets other people draw / comment / add images into the artspace. It might be too much, but for presenting multiple screens of similar interactions, it seems like it gives the rest of the team a better view of things together, more zoom in/out powers, and flexibility in leaving feedback, so worth a try at least once!

🖼 [Check it out »](https://gsa.invisionapp.com/freehand/document/cjmJku59R)

In each of the cases above, changing the statement to a question, and using radio buttons + fields that show up depending on which answer you choose seems to fit the bill. The most complex change I've designed is the Private Contractor Costs section, which adds to work started in #1040. I left specific comments in the doc for folks to follow and respond to.

## Next steps 
I think it's worth pairing to talk through the proposed changes to question structure — @NAretakis & @lauraponce are you game today?

**Comment by jenniferthibault** [comment]
Chatted with @NAretakis & @lauraponce and we are aligned on where this is going! Here's the designs ready for implementation, and highlights from our discussion:

### Key Personnel & Project Management Planning
- Eliminates one of the yes/no buttons by making the first entry the Primary point of contact
- We know that the position and structure of this section might change in a future enhancement via #1151 but think that this addresses the current need and clarifies the interaction.
- In usability testing, we'll gather data to make sure that "No" is the most common answer, and should be the default. Will adjust later as needed. 
![key personnel](https://user-images.githubusercontent.com/11636908/48799213-91e92e00-ecd4-11e8-9459-d71ded5ccc8c.png)

### Federal Citations and Justification
- We believe that more often than not, people are in compliance, and have set the default state as "Yes" automatically. Therefore, folks only need to justify when they are not meeting the requirement.
- In the future, we might look at how this could be more of an active choice, but liked that setting "yes" by default showed positive intent in the partnership. 
![federal citations](https://user-images.githubusercontent.com/11636908/48799229-9a416900-ecd4-11e8-80ce-6f5bd36fae33.png)

### Private Contractor Costs
- Builds on the work in #1040 
- Combines two questions into one! Both options have conditional followups, but we know that Fixed Cost is largely the most common choice, so a safe default
![private contractor costs](https://user-images.githubusercontent.com/11636908/48799249-a4fbfe00-ecd4-11e8-8f04-693d544d0483.png)

## Next steps
Ready to move to implementation! @hbillings I'm thinking this might work as three separate issues for changing each instance, plus one issue for styling adjustments to the radio button and conditional questions. Thoughts/preferences?

**Comment by mgwalker** [comment]
This looks fantastic.

I'd suggest the first issue would be to build the conditional form elements component.  Then Heather and I could split up implementing the changes in the 3 sections.  (The changes feel small enough that they could realistically all go in one pull request, but for the sake of reviewing, it's probably helpful to keep them split up? 🤷‍♂️)

**Comment by hbillings** [comment]
I think splitting this into multiple pull requests makes sense, with the first one being the conditional element. Do we have a radio button React component? (I notice Jen's using the USWDS-style radio buttons, which are pretty finicky about the way the markup's rendered. We'd probably want to have a component for it to make sure they're all rendered the right way.)

**Comment by jenniferthibault** [comment]
Carried forward into dev issues in #1172, #1173, #1174, & #1175. Closing in favor of those 🎉
