### ISSUE TITLE
Standardize vertical and horizontal spacing increments

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cms-hitech-apd#1117]
Carried forward from #1082 

In order to create more consistency and reduce the number of style decisions our team has to make with each new implementation, we should define a limited set of spacing increments, and apply them to headings or elements by default. This should reduce the number of utility classes in the markup, but will also allow us to override them when needed through the BASCSS styles.

### This task is done when...
 - [ ] Figure out what our spacing increments should be (and what elements they're used in pattern with)
 - [ ] Overwrite BASCSS margin & padding variables with the increments we want
 - [ ] Tweak how & where margin & padding variables are used to make them match design spec
 - [ ] Identify which patterns need to incorporate spacing elements in their default state and build them so!
- [ ] (Probably separate issue) Replace those elements in the code with the patterns that have spacing incorporated

**Comment by NAretakis** [comment]
OBSOLETE DUE TO CMS DESIGN SYSTEM
