### ISSUE TITLE
Refine color variables 

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cms-hitech-apd#1118]
Carried forward from #1082 

There's a lot of color variables defined in the codebase that represent visually very similar colors, and others that are defined but don't seem to be in use. We should remove what's not in use and refine the ones that are in use to the smallest number we really need. (It would also be nice if there was some logic to where the color values come from – whether that means an exact match to HHS/CMS styles, or they come from the US Web Design system, to be determined.)

### This task is done when...
 - [ ] Code contains only color variables that are in use on the site
 - [ ] Color variables are unique (different enough from one another that it makes sense to have them) 
 - [ ] Color styles are updated in the Sketch files
 - [ ] An implementation issue has been created for the development team (that includes adding the styles to storybook as a criteria for "done")

**Comment by NAretakis** [comment]
OBSOLETE DUE TO CMS DESIGN SYSTEM
