### ISSUE TITLE
Simplify button styles

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cms-hitech-apd#1119]
Carried forward from #1082 

In order to create a system out of the button styles, reduce the number of unique instances, assign hierarchy to buttons, and implement them consistently. Benefits: consistency, consolidating styles, and best practices.

### This task is done when...
 - [ ] Define default, alternate, and call-to-action button styles
 - [ ] Styles have been updated in Sketch files & set as symbols
 - [ ] An implementation issue has been created for the development team (that includes adding the styles to storybook as a criteria for "done")

**Comment by NAretakis** [comment]
OBSOLETE DUE TO CMS DESIGN SYSTEM
