### ISSUE TITLE
Initial APD submission prototype

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#112]
Our first prototype will take the [content prototype](https://docs.google.com/document/d/1Ln1nqLk-9IEBJPvfMHf01sbS91d4GvJkg5I4O8DOvKw/edit) and make it an in interactive web form that we can usability test.

### This task is done when...
 - [x] We have identified what section(s) of the content prototype we are going to test
  - We will work top to bottom, focusing on the administrative information and project description
  - Later we can deal with personnel, budget, and other sections
 - [x] We have created (preliminary) UI for all of the section(s) of the content prototype that we want to test
  - We will go straight from the content prototype to code, without sketching/wireframes in between
 - [x] We have deployed an interactive prototype to a URL that state testers can access

**Comment by brendansudol** [comment]
split out the various sections into their own issues so greg and i can more easily divvy up (and leave tailored commentary around)

**Comment by mgwalker** [comment]
Here are the individual issues

#146 - state profile
#147 - program overview
#148 - activity creation
#149 - activity details
#150 - personnel
#151 - expenses
#152 - overall review

**Comment by nicoleslaw** [comment]
cc @quarterback for awareness
