### ISSUE TITLE
Design styles for Alerts

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cms-hitech-apd#1120]
Carried forward from #1082 

We should define these styles and apply them consistently before "Submit" functionality is enabled in the app. Setting up these styles will also prepare us for form field validation, when that's appropriate to implement later on.

### This task is done when...
 - [ ] `Error`, `Warning` and `Success` message styles have been defined
 - [ ] Styles have been updated in Sketch files & set as symbols
 - [ ] Areas of the app where these should be implemented are identified and mocked up
 - [ ] An implementation issue has been created for the development team (that includes adding the styles to storybook as a criteria for "done")

**Comment by NAretakis** [comment]
OBSOLETE DUE TO CMS DESIGN SYSTEM
