### ISSUE TITLE
Add shadow to frozen pane of scrolly tables

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1122]
As [discussed in 1098](https://github.com/18F/cms-hitech-apd/pull/1098#issuecomment-438688363), the frozen left pane of scrolling tables should have a shadow on scroll (only on scroll, when the underlying table is moved from its original position).

Note to self: [this method](http://jsfiddle.net/jDyQt/1198/) is probably the way to go for this, rather than `box-shadow`, which will be [a little weird on just one side](https://stackoverflow.com/questions/5115427/how-can-i-add-a-box-shadow-on-one-side-of-an-element).

### This task is done when...
 - [ ] shadow applies to one side evenly
 - [ ] shadow is only applied on scroll, and is removed when the underlying table returns to its original position after being moved

**Comment by NAretakis** [comment]
OBSOLETE DUE TO TABLE REDESIGN
