### ISSUE TITLE
Specifying FFP match rate for Non Personnel Costs

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1124]
Scaling beyond HITECH will require that we consider how to identify match rates by line item for Non Personnel Costs since MMIS and E&E may qualify for 90/10, 75/25 or 50/50.

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
 ** Don't forget to fill out the LABEL and MILESTONE before submitting. If the issue is for the CURRENT SPRINT, add it to the PROJECT. If the issue is a BUG, FUTURE ENHANCEMENT, or OUTSIDE OF THE CURRENT SPRINT, do not add it to the PROJECT (then delete this line) **

**Comment by NAretakis** [comment]
OBSOLETE
