### ISSUE TITLE
Create eAPD brand association with MACPro

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cms-hitech-apd#1126]
In order to create alignment and consistency with other programs that share infrastructure and funding, position the program as a part of [MACPro](https://www.medicaid.gov/state-resource-center/medicaid-and-chip-program-portal/medicaid-and-chip-program-portal.html#MACPro) through visuals and messaging. 

Initial thoughts:
Since this uses the CMS design system (which is the most modern expression of CMS), it already sets a basic visual marker. The association with MacPro might be best if it doesn't add or interfere with the CMS design system layer. Perhaps a strategically placed logo, or intro page ..

**This task is done when...**
- [ ] The team has a a shared understanding of the need
- [ ] We've identified a solution and touchpoints for addressing the need
- [ ] We've drafted the solution and created issues for implementation

Future plans: [Figure out where eAPD builder sits within the context of CMS](https://app.mural.co/t/gsa6/m/gsa6/1559755076803/9316f8837bf3b307f66c4e42dafb4df9168884c5).

**Comment by jeromeleecms** [comment]
Was doing some bug testing in the app and saw that the app still has "CMS HITECH APD" on the login screen. For the pilot release, can we make a small change for this to read "CMS eAPD" (so people get used to seeing that) or should the overall branding update be part of the pilot release?

Also, not quite sure where else this would need to be changed. Once users login, the references are to HITECH APDs (which is OK since right now everything is a HITECH APD).

**Comment by NAretakis** [comment]
@NAretakis @austinhernandez to pair on this.

**Comment by austinhernandez** [comment]
Two very special footers that have the MACPro logo and added copy. `A federal government website managed and paid for by the U.S. Centers for Medicare and Medicaid Services and part of the MACPro suite.` NeEd HaLP w/ wOrdZ.

V1: grey and blue - incl. contact info
![image](https://user-images.githubusercontent.com/23194720/59041466-ab079580-8846-11e9-9900-c975915621d5.png)

V2 - original colors, no contact info
![image](https://user-images.githubusercontent.com/23194720/59041487-b78bee00-8846-11e9-830d-69b74c2108b2.png)

**Comment by jeromeleecms** [comment]
As long as the contact information is updated to: CMS-EAPD@cms.gov!

**Comment by austinhernandez** [comment]
I just thought it needed a contact spot so if someone is completely lost they know there's hope! I won't put your fake email address.

**Comment by austinhernandez** [comment]
Here's the final design! She's ready 2 become a dev task. Basically, we are changing the footer to add the Medicaid and MACPro logos and moving the current HHS logo and text to the left:

![image](https://user-images.githubusercontent.com/23194720/59117718-7bc35800-891c-11e9-9603-0b7a6779d67a.png)
 
Footer uses these colors:
- $gray-lightestfor footer
- $primary-darkest for footer's footer

Here are the logos:
[logos.zip](https://github.com/18F/cms-hitech-apd/files/3266751/logos.zip)

**Comment by austinhernandez** [comment]
Met 6/10 to discuss. @hbillings is making this a ticket!

Updated text to read "A federal government website managed and paid for by the 
U.S. Centers for Medicare and Medicaid Services and part of the MACPro suite." ![image](https://user-images.githubusercontent.com/23194720/59207199-9728a000-8b74-11e9-9867-90b5e6b45c86.png)

**Comment by jeromeleecms** [comment]
This is done - #1596 is the dev task!
