### ISSUE TITLE
"Direct Attributable to the Project" Button doesn't do anything

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1128]
When entering key personnel, when identifying and individual as attached to the project should add their cost into the total request.  This part of task #884. 

![image](https://user-images.githubusercontent.com/34279968/48580653-a3959480-e8d4-11e8-99de-b72e4a2b6979.png)

For now, should show up as HIT personnel. Project State staff. If the state hires contractors to provide oversight on multiple projects, we should have them include that under the program administration (Activity 1). 

![image](https://user-images.githubusercontent.com/34279968/48580749-dfc8f500-e8d4-11e8-9e02-2d3e45fb9ec3.png)

### This task is done when...
 - [ ] There is a representation of the Key Personnel through out the budget tables within the app
 - [ ] Design has done a pass of how this will be intergrated through out the app
- [ ] A dev issue has been spun up to support
 
 ** Don't forget to fill out the LABEL and MILESTONE before submitting. If the issue is for the CURRENT SPRINT, add it to the PROJECT. If the issue is a BUG, FUTURE ENHANCEMENT, or OUTSIDE OF THE CURRENT SPRINT, do not add it to the PROJECT (then delete this line) **

**Comment by mgwalker** [comment]
@NAretakis To be clear, if a key person has costs directly attributable to the project, we add their cost to the total state personnel costs per fiscal year, for HIT?

Do we also need to multiply the cost from the box circled in Jerome's first picture by the percent time the person is committed to the project?  If so, we might want to put some help text in explaining that the cost they enter is 100% of that person's cost.

**Comment by NAretakis** [comment]
Yes. A key person's FFY costs gett added to the state personnel costs, per FFY, for HIT.

No, to the multiplication question. We're probably going to just reword that to section so that it isn't so math-y. We just need to know how much of the key person's time is attributable to the project, and that is separate from their associated costs.

**Comment by mgwalker** [comment]
Affects:

- summary budget table
  - HIT project state staff cost
- federal share by FFY quarter
  - in-house HIT and HIE cost
- program budget table
  - HIT cost

**Comment by mgwalker** [comment]
Is the key personnel cost 90% federal and 10% state, always, since it's being lumped in as an HIT cost?  We set the federal/state split at the activity level, so I'm not sure what to do with this cost.

**Comment by NAretakis** [comment]
Yes, that looks right.

**Comment by NAretakis** [comment]
key personnel cost is 90/10, always. We should probably test this to make sure states agree, and if not, then perhaps the drop down selector could be used here to denote, 90/10, 75/25, or 50/50. However, for the purposes of this issue, 90/10 is fine.

**Comment by NAretakis** [comment]
Huh, this is a tricky one. My immediate thought is that it should actually dump into the Program Administration (Activity 1) bucket, or at least use the same quarterly breakout selection. Meaning that setting it at 100% Q1 for program administration, sets it at 100% Q1 for key personnel.

Is using the same quarterly breakout that is used for Program Administration possible?

**Comment by mgwalker** [comment]
That is possible, yep.

Pinging @jameshupp - this seems like stuff that'll need some explanation.

**Comment by jameshupp** [comment]
I may need a bit of explanation about the part of this that @mgwalker tagged me in on. Seems like its own issue for me to pick up, but I'm not 100% sure I follow. Here's my understanding:

The key personnel costs are included under Program Administration, which is always an HIT cost and therefore a 90-10 cost. And then any adjustment to the quarterly share of Program Administration would also apply to the way the federal share of the key personnel cost. And so the content work is: make that clear to state staff in a useful way.

Is that correct?

**Comment by NAretakis** [comment]
That is correct.
