### ISSUE TITLE
Usability testing protocol

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#113]
First draft of a usability testing protocol for seeing how states react to our content prototype.

### This task is done when...
 - [x] The scope of the test has been chosen
 - [x] Research questions have been written
 - [x] The protocol and methodology have been written
 - [x] Design has reviewed the protocol and given the ok
 - [x] Dev has reviewed the functionality to be tested and given the ok

**Comment by nicoleslaw** [comment]
For future reference, I set up an Adobe Connect link for us for interviews and gave you both host/admin access: https://gsa-tts.slack.com/files/U0B2CD0EM/F8VCLJKJ9/CMS_APD_Usability_Testing_Dial-in

**Comment by nkkl** [comment]
@NAretakis and I wrote up our first draft of the protocol, and a recruitment letter. Would love 
👍/👎  feedback from @lauraponce and @mgwalker / @brendansudol by EOD so we can send out recruitment mails.

- [Protocol](https://docs.google.com/document/d/1Z55G-pTcsVsuvk-mZnVaDhXJn5GwP10tXaA9ZHoXo-0/edit#heading=h.ni1qojbqg7c2)
- [Recruiting email](https://docs.google.com/document/d/1QlHnm_-TtXbr0HsDhLZIEub-8_CbRe8AjMxWRme48RE/edit#heading=h.ty83bl4ret6w
)
