### ISSUE TITLE
Plan user research for the federal reviewer experience

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1131]
Usability test the federal reviewer experience to make sure it flows well, solves for their main use cases as a reviewer, and is easy to use.

**Comment by lauraponce** [comment]
Started a [doc with some questions to answer](https://docs.google.com/document/d/1x1dvEzZksEHGZnIxNj5MWOBX7pnI57Hk3uBKeZx8S_o/edit#) and will be adding more to this today.

**Comment by NAretakis** [comment]
Closing as we completed the first part of this. We'll spin up another federal reviewer research issue as part of Layer 2.
