### ISSUE TITLE
Make a decision about including the completed date for activities

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1137]
In the 8th round of usability testing, some state users mentioned wanting a way to mark activities as complete in addition to setting the start and end dates. 

Questions to answer:

- Is this out of scope for the intention of this tool as an APD creation/submission tool (not a project management tool)?
- Will adding the completed dates be useful for the federal reviewer to see?

**Comment by NAretakis** [comment]
Confirmed that we do not need an end date for activities, #1006 will address if an activity is completed or not.
