### ISSUE TITLE
Implement consistent number formatting for fields with numbers

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1141]
We have lots of fields (tables) that require an input of numbers. We'd like this to be a consistent experience, which formats using commas, dollar signs, and percentage signs. Dollars need to be rounded to the nearest dollar, and we need to be able to accommodate 14 characters ($1,000,000,000). Referencing #1049 for where this work originated.

![47188125-94c6bc80-d2eb-11e8-99ce-800cab059602](https://user-images.githubusercontent.com/34281281/48717672-1e152b80-ebd7-11e8-92dc-c3ef93e6c73e.gif)

**Comment by NAretakis** [comment]
@lauraponce does this issue look right to you?

**Comment by mgwalker** [comment]
From a dev perspective, adding automatic commas is straightforward, but if we want to let users manually enter commas, that's more difficult.  (We'd probably need to switch out number input libraries again.)

Do percentage fields need to support commas as well?  Not sure why anyone would be listing anything as 1000% but 🤷‍♂️.  What about rounding to whole numbers?  If percents should support decimals, how many?  (The library we use supports decimals, and even lets us specify how many we allow.)

I assume supporting 14 characters is a matter of getting the styling right so the inputs are wide enough.  @hbillings?  Does that sound right?  I don't think there's anything limiting the numeric size of the input values, but some of the inputs might be too small to actually show the numbers?

**Comment by mgwalker** [comment]
I wanted to get rid of the leading zero, but it turns out the library we use intentionally leave leading zeroes until the input is un-focused, and they have a pretty good argument for why:  https://github.com/s-yadav/react-number-format/issues/240

**Comment by NAretakis** [comment]
No worried about the leading zero, but adding automatic commas is really what we need here. We also won't need percentages with commas (it shouldn't come up). 

All dollar amounts should round to whole numbers. But percentages should allow two decimal places: **58.55%**
