### ISSUE TITLE
Attach a unique identifying number to the APD submissions

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1143]
State users are used to having a number associated with their APDs for ease of tracking. 

- [ ] Enable a mechanism for attaching unique identifiers to each APD/contract

**Comment by mgwalker** [comment]
This sounds like a 3-part issue to me:

1. dev to do the backend work to create an identifier for each APD
   - what should the identifier be? a number?
   - could it be words instead (might be easier for humans to manage)?  maybe something like [supercurious-senior-woodlouse](https://www.npmjs.com/package/adjective-adjective-animal)
2. design to figure out where it belongs
   - does it show up on the dashboard?
   - does it show up in the print/PDF as well?
   - etc
3. dev to implement the design for showing the ID

Does that sound right?

**Comment by lauraponce** [comment]
@mgwalker That sounds right to me for the 3 parts. 👍 

I wonder what the naming conventions are now for the files that states submit as their APDs? @NAretakis @jeromeleecms, do you know? 

If there is a standard, maybe it would make sense to follow that structure or to set it as the defaults then allow states to edit the name/ID if they would like.

**Comment by jeromeleecms** [comment]
@lauraponce We have an existing nomenclature that we can share/reuse.

@NAretakis (Friendly reminder!) Were you able to located the SOP for the SEA nomenclature we discussed yesterday?

**Comment by NAretakis** [comment]
I think our naming convention should cover the identifier stuff. @mgwalker does this look usable?

[StateCode]-[YYYY-MM-DD]-HITECH-[Submission Name]
                        (Date Received)		                                      


Submission Name | Description | Example Names
-- | -- | --
APD | Advanced Planning Document | TX-2018-09-13-HITECH-IAPD
CNT | Contracts, Contract Modifications and Contract Amendments* | TX-2018-09-13-HITECH-CNT
RFP | Request for Procurement | TX-2018-09-13-HITECH-RFP

**Comment by mgwalker** [comment]
👍 That works.  One last question: should the `YYYY-MM-DD` be based on when the APD is created, since it isn't submitted in the app?

**Comment by NAretakis** [comment]
Yes, when APD is created. Eventually maybe we think about switching this to submitted if possible.

**Comment by mgwalker** [comment]
Created #1323 for backend work; and #1324 and #1325 for frontend work.

@lauraponce Should we also create an issue for design?

**Comment by lauraponce** [comment]
@mgwalker I just created #1346 for the design side of this. I'm assuming it will be pretty straightforward for the pilot (maybe even as simple as just updating the name dashboard), but we'll think through it more from the design perspective in that issue.

Closing out this issue in favor of #1323, #1324, #1325, and #1346 which capture the work for design + dev.
