### ISSUE TITLE
Carry over the activity numbers from the Program Activities section to the Summary Schedule table

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1147]
### Background

In the 8th round of testing, some state users were having difficulty interpreting the activities in the table and thought it'd be easier to view and sort if the numbers carried over.

### This task is done when...
 - [ ] Carry over the numbers from the Program Activities section.

For example, since Public Health System Modernization was entered in as the 6th activity, in the table below, it would show up as "6. Public Health System Modernization"

![screen shot 2018-11-19 at 1 19 37 pm](https://user-images.githubusercontent.com/21222704/48735638-c8a04500-ebfd-11e8-8b99-9f344fe6f7e6.png)

**Comment by jeromeleecms** [comment]
Done per @mgwalker
