### ISSUE TITLE
Add in data validation for percentages

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1149]
Currently, any number can be entered as a percentage (e.g. 1000%). A future enhancement for this is to add in some data validation to limit the percentages to < or = 100%. 

Related to: https://github.com/18F/cms-hitech-apd/pull/1146

**Comment by jeromeleecms** [comment]
Let's close this so we can do a more robust dissection of validation in a broader context. Percentages are not meant to be called out on it's own for any reason.
