### ISSUE TITLE
Build Layer 1 state dashboard

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cms-hitech-apd#1161]
Carried forward from design in #1110 

Changes to what's currently on production include: 
- Adding introductory text to the page
- Removing the `My tasks`, `Recent activity`, and `Upcoming events` sections of the existing dashboard
- Changing the style and features of `Current statuses` to only show what APD documents exist, and allow functionality to start a new one. (Matching mockups below)
- Re-labeling the title of the former `Current statuses` section to `[State name] APDs` in the main content area and the sidebar
- Moving the "Create new" button from the sidebar and into the main content area
- Created a null state view for when there aren't any documents yet

### This task is done when...
-  [x] Design provides dev with production-ready assets (content & icons) for placement
 - [ ] Production site matches mockups for null state
 - [ ] Production site matches mockups for populated state
 
![dashboard-layer1-null](https://user-images.githubusercontent.com/11636908/48806440-52c4d800-ece8-11e8-90e6-0e60ab4d19f1.png)

![dashboard-layer1](https://user-images.githubusercontent.com/11636908/48806441-52c4d800-ece8-11e8-9e7e-6c3c47953dd6.png)

**Comment by jenniferthibault** [comment]
## Assets:

**Text:**
Populated state:
`Use the eAPD to build and manage your state’s Advanced Planning Documents. Follow the instructions to enter relevant information. Save your work in progress and come back to a draft at any time. Each APD your state creates in the eAPD will be listed here for you to review or edit. To submit an APD, open it and select Save as PDF, then send the document to CMS just like you've done before.`

Null state:
`You have not created any APDs.`

**Icon**
Exported as an SVG at the size it's used in the mockup, but let me know if I can make a different or better format — this is the first icon export I've made for this project, so not sure what our rig is like in this area.

[icon-document.svg.zip](https://github.com/18F/cms-hitech-apd/files/2605300/icon-document.svg.zip)

**Comment by mgwalker** [comment]
@jenniferthibault How would you feel about using the [FontAwesome document icon](https://fontawesome.com/icons/file-alt?style=regular) instead?  We're already using FA so it'd be a (slightly) lower lift.
