### ISSUE TITLE
Fancy dashboard functionality for nesting APDs/contracts and approval timeframes

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1162]
### Background

In usability testing, some questions about the nesting/ordering of APDs and contracts came up. When there is a contract attached to an APD, it can be useful to see those together in the dashboard (someone suggested that associated contracts could branch off the APD). It was also mentioned that it would be easier to find out when the approval dates were for the APDs if it were shown on the dashboard with the approval letters. APDs are approved for different timeframes so it can be complicated for users to keep track of.

### This task is done when...
 - [ ] There is a decision made about how to display APDs with attached contracts in the dashboard and a concept has been designed.
 - [ ] There is a decision made about how/if to show the dates that the APD was approved for, how/if we are going to attach the approval letters, and a concept has been designed.

**Comment by lauraponce** [comment]
While working on #1821, Jerome and I talked through some options for when we'll need to scale to other types of APDs. Adding the notes here:

There are three types of IDs for the APDs:
- ID for database 
- ID for creating APD (how is this used internally)
- ID for when submitting (SEA ID)

There are multiple types/combinations of APDs to account for in the naming:
- 3 program areas — HITECH, MMIS, E&E
- 7 types of APDs — IAPD, PAPD, OAPD (with updates), closeout APD
- Contracts, attached documents or submitted separately

States need to know:
- program area
- type of APD
- sequence 

To test:
- What would users name the APD doc as if it was freeform?

**Comment by beparticular** [comment]
Closing, will reevaluate later in the roadmap .
