### ISSUE TITLE
Build conditional radio button element

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cms-hitech-apd#1172]
Part of #1115 
So that we can replace the yes/no buttons, we must first build and style the component we'll use to replace them. That starts with building and styling a React radio button, and adding the conditional element to it.

This pattern is a radio button that offers secondary fields to complete when the user selects a relevant option. When the option is not chosen, the secondary fields are not displayed.

An example of a radio button, with an option selected that DOESN'T have a conditional element:

<img width="514" alt="screen shot 2018-11-26 at 11 03 32 am" src="https://user-images.githubusercontent.com/11636908/49026107-01df3480-f16b-11e8-928d-70cfb3617745.png">

An example of a radio button, with options selected that DOES have a conditional element 

<img width="501" alt="screen shot 2018-11-26 at 11 03 40 am" src="https://user-images.githubusercontent.com/11636908/49026147-16233180-f16b-11e8-82b2-eb13010c7232.png">

The conditional element should accept any type of form field, including multiple text areas

<img width="754" alt="screen shot 2018-11-26 at 11 05 51 am" src="https://user-images.githubusercontent.com/11636908/49026219-4c60b100-f16b-11e8-9a24-fd8a74415b6b.png">
<img width="755" alt="screen shot 2018-11-26 at 11 06 02 am" src="https://user-images.githubusercontent.com/11636908/49026220-4c60b100-f16b-11e8-97e9-de44c6cf4d3b.png">

### This task is done when...
 - [ ] The radio button component has been built and styled
 - [ ] The conditional component has been added to the radio button component and styled to match mockups
 - [ ] The patterns are ready to use in production
 - [ ] Both patterns have been added to storybook

**Comment by jenniferthibault** [comment]
@hbillings can you take a look at this writeup and adjust? I feel like I wasn't able to capture enough clarity for what "done" looks like for a front end task. Thank you!

**Comment by hbillings** [comment]
@jenniferthibault I made a couple light edits -- I don't think we have a React radio button component at all right now, so we'd need to build that first (@mgwalker can correct me if I'm wrong there!)

**Comment by mgwalker** [comment]
We do not!

I have a prototype of a conditional container in the [mgwalker/conditional-prototype branch](/18f/cms-hitech-apd/tree/mgwalker/conditional-prototype), contained entirely in the [Storybook index](https://github.com/18F/cms-hitech-apd/blob/mgwalker/conditional-prototype/web/src/stories/index.js).  Not that we need to use it, just making a note that it exists.  It isn't styled at all, so it would need a bunch of love anyway.

Depending on how we implement it, this could be a good candidate to split into an independent component.

**Comment by NAretakis** [comment]
@hbillings do you know if this is part of the design system? Do we need to build our own conditional button anymore?

**Comment by jeromeleecms** [comment]
Done - we have this covered through design system and other work that has been completed.
