### ISSUE TITLE
Replace yes/no with conditional radio button in Private Contractor Costs section

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cms-hitech-apd#1175]
Builds from designs in #1115

In order to make the eAPD form more usable and the selected answer state more clear, we should replace the yes/no button in the Private Contractor Costs section with one conditional question.

This work combines what was previously two questions into one, and answers with dependent fields only change content entered _below_ that condition-setting field. (Previously, if you answered "Yes" to an hourly resource question, the fields above it (which you might have already filled out in error) would become disabled. WOO! Both options have conditional followups, but we know that Fixed Cost is largely the most common choice, so a safe default.

### This task is done when...
 - [ ] The "Cost" and "Hourly resource" fields have been re-ordered and replaced by one a conditional radio button (defined in #1172) instead of yes/no to match the mockup below
 - [ ] "Fixed cost" is set as the default selection, and the conditional FFY fields are displayed by default
 
![private contractor costs](https://user-images.githubusercontent.com/11636908/48799249-a4fbfe00-ecd4-11e8-8f04-693d544d0483.png)

**Comment by hbillings** [comment]
Blocked on #1172.

**Comment by jeromeleecms** [comment]
OBSOLETE due to Austin.
