### ISSUE TITLE
Review second/third person usage for consistency with CMS

### ISSUE THREAD

**Issue by jameshupp** [18F/cms-hitech-apd#1179]
Describe the task here, including any supplemental information. Per @jeromeleecms's [comment from a review of #1168](https://github.com/18F/cms-hitech-apd/pull/1168#pullrequestreview-178445669), the second person ("you" or imperatives with you understood) is used for some portions of instructions and not all. Per my response to that comment, there's a reason to use it in certain contexts and I have tried to use it consistently there.

However, we need to be sure that it is actually consistent both within the app and across users' experience of interacting with CMS.

### This task is done when...
 - [ ] CMS instructional content outside the app has been reviewed to be sure the use of second person isn't totally alien.
 - [ ] Content has reviewed the app content and brought it into reasonable alignment with CMS's use of second person.
 - [ ] Content has updated the app's use of second person to be fully consistent with itself. The area of most concern has been section descriptions, but it may appear inconsistently elsewhere (or there, for that matter).

**Comment by jameshupp** [comment]
@jeromeleecms @NAretakis One thing that would be useful when I pick up this issue is a good basic set of instructional copy elsewhere that you think is a good model of how CMS usually communicates. HITECH-specific is better, but anything your state users are used to seeing is fine. Could be a PDF or a web page somewhere else or anything.

**Comment by NAretakis** [comment]
Let me see what I can find. We're notoriously bad at this, so a good example is a bit tricky.

**Comment by jameshupp** [comment]
These will totally be useful, thank you!

**Comment by CSwartzHMA** [comment]
Being reviewed in conjunction with #2162

**Comment by CSwartzHMA** [comment]
Closed as this was completed as part of #2162.
