### ISSUE TITLE
Identify possible CMS user management tools

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#118]

**Comment by NicolasAretakisCMS** [comment]
Will research portal.cms.gov and others to see what level of integration exists.

**Comment by mgwalker** [comment]
To clarify, this task is about finding a system to use for login, right?  Or is it something else altogether?

**Comment by NAretakis** [comment]
After doing some searching, we have basically one option for an integrated login system, the CMS Enterprise Identity Management (EIDM). I have collected the links and info on connecting to the EIDM which could eventually be used for doing user logins and identity management. However, their simple process requires 5-6 months of lead time prior to a go-live date. So, so this will definitely need to be something in a later phase. CMS SharePoint has a few forms that initiate the process, but I'm not going to go down that road with our currently planned milestones. But at least we have this for reference. 

Meaning that, while I am going to close this task, @mgwalker we'll need to figure out how we can handle this within our own app (not integrated to CMS user management system).
