### ISSUE TITLE
Standardize and semantic-ize page structure

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1187]
There are a few small, discrete pieces of page structure that should be addressed or investigated further. Lumping these together as they're all similar.

Let's see if we can un-nest the page containers a hair. We've got `body` -> `.app` -> `.site` -> `.site-body` before we ever even get to the basic sidebar/main body structure. This isn't really affecting anything, but it's kind of a code smell.
<img width="488" alt="screen shot 2018-11-26 at 1 35 49 pm" src="https://user-images.githubusercontent.com/509309/49116746-d25c2500-f25b-11e8-8ec5-16a22a0deb0e.png">

We’re using an `aside` for the sidebar on the homepage but not on the APD page; we should use `aside` for both. We should also be using `main` for the accompanying content body since we're making use of HTML5 elements.

The `header` element [should be used for introductory content](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header), but it is just used for a couple of small buttons. It would make more sense to make the header something that is the actual header of the page (possibly the <state> HITECH APD text?) or drop it altogether. The buttons should just be moved to a regular ol' `div`.

Do we need/want a footer of some kind?

### This task is done when...
 - [ ] The investigations above have been completed
 - [ ] Sidebars are consistent
- [ ] HTML5 element usage is consistent

**Comment by jeromeleecms** [comment]
This is done! Implementation of design system and reworking components has solved this...
