### ISSUE TITLE
Structure sidebar as accordions with "always-on" content

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1189]
The sidebar is built as a list of `li`s. When a user clicks the "expand" option to the right of a top-level sidebar item, the item's children are appended to the DOM as top-level elements that have extra left padding (to create the indentation). So this:

<img width="210" alt="screen shot 2018-11-26 at 2 13 42 pm" src="https://user-images.githubusercontent.com/509309/49117455-f3257a00-f25d-11e8-9302-f69e9a919786.png">

...is this under the hood (the `pl2` class indicates a child element):
<img width="558" alt="screen shot 2018-11-26 at 2 24 31 pm" src="https://user-images.githubusercontent.com/509309/49117446-eef95c80-f25d-11e8-8516-c976903559e2.png">

Expanded, so it's easier to read:
<img width="563" alt="screen shot 2018-11-26 at 2 25 19 pm" src="https://user-images.githubusercontent.com/509309/49117450-f0c32000-f25d-11e8-9b16-16a31b2bbd94.png">

Ideally, we would not be appending and removing elements from the DOM. This breaks with 18F's preference for [progressive enhancement over graceful degradation](https://www.shopify.com/partners/blog/what-is-progressive-enhancement-and-why-should-you-care), because if JS is disabled or errors out for whatever reason, users will be unable to use the side navigation to access child nav objects. In contrast, the [dropdown menus](https://designsystem.digital.gov/components/headers/basic/) and [accordions](https://designsystem.digital.gov/components/accordions/) used in the USWDS function very similarly to our nav, but they use JS to hide the content. If JS fails, the child elements will be rendered visually and will be usable. We should use a similar approach.

Also, the child elements should be a new `ul` nested within their parent `li`.

### This task is done when...
 - [ ] Child elements are nested within parent elements
 - [ ] Child elements are rendered on page load and shown/hidden with JS

**Comment by NAretakis** [comment]
@hbillings can you help me determine if this is still a thing for us to do, or if it is resolve as part of the other sidebar work you are doing?

**Comment by NAretakis** [comment]
OBSOLETE because this will be closed by us adopting the CMS Design System.
