### ISSUE TITLE
research (& implement?) admin view plugin

### ISSUE THREAD

**Issue by brendansudol** [18F/cms-hitech-apd#119]
one that plays nice with express and psql

**Comment by brendansudol** [comment]
Ok, I did some research here on what's out there and how we may want to proceed.

What I was looking for -- a simple plugin / js package that we could add to our project that would give us an admin dashboard / interface view into our database. Something that allows us to quickly inspect our tables and the data entries in those tables, and perhaps allow us to add / edit / remove entries through a webpage. Basically something akin to the built-in Django admin site (https://docs.djangoproject.com/en/2.0/ref/contrib/admin/).

What's out there?

1. "Express Admin" (https://github.com/simov/express-admin): After adding a configuration file, it spins up a dashboard and allows you to see your tables and data, and add / edit / remove entries. The interface is bulky / clunky (i.e., flash of unstyled content on each page load), but it does seem to generally work. I spun it up locally on our backend to test it out, and here's a quick preview: https://cl.ly/p3Hr. Downsides: this project doesn't seem very active or well-maintained :/

2.  "strapi" (https://github.com/strapi/strapi): this is a much newer, more active project with a more ambitious focus -- to be an API creation tool / much larger Node.js framework. It includes a nice looking admin dashboard, but that really seems like just a small piece of this. This feels like overkill / not the right fit for our (more humble) needs now, but it's maybe worth a read-through @mgwalker just for funsies. 

3. "Lumber" (https://www.forestadmin.com/lumber/): looks neat, but admin dashboard is hosted on their site (see https://doc.forestadmin.com/knowledge-base.html) which seems a bit odd to me. "We [people who made Lumber] host the admin UI. No data from your application ever reaches our servers as requests are initiated directly from your browser, to your application."

4.  "crudl" (http://crudl.io/): young (perhaps abandoned?); seems like it would still require us to write a lot of code to wire up, which is kind of against the point.

Recommendation: All in all, I'm not thrilled with the node.js admin data dashboard landscape. This is not a need-to-have feature for us right now, just a nice-to-have for quick data inspection / visibility without needing to use SQL. I vote on not adding any right now, and if we need to down the road, we can re-evaluate. 

cc: @mgwalker @nkkl

**Comment by nkkl** [comment]
I'm fine with tabling this until we're farther along and have a better sense of what kind of UX an admin might need.
