### ISSUE TITLE
Create analyst interview protocol

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1190]
Describe the task here, including any supplemental information.

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
 ** Don't forget to fill out the LABEL and MILESTONE before submitting. If the issue is for the CURRENT SPRINT, add it to the PROJECT. If the issue is a BUG, FUTURE ENHANCEMENT, or OUTSIDE OF THE CURRENT SPRINT, do not add it to the PROJECT (then delete this line) **

**Comment by CSwartzHMA** [comment]
Draft prepared for team review.

**Comment by MCorradoHMA** [comment]
Completed
