### ISSUE TITLE
Update framing document

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1197]
Describe the task here, including any supplemental information.

### This task is done when...
 - [x] Nick has reviewed
 - [ ] Jerome has signed off

**Comment by NAretakis** [comment]
Started reviewing.

**Comment by NAretakis** [comment]
Made a new version that better reflects our 2019 work. I’ll link in here shortly.

**Comment by NAretakis** [comment]
New version here:
https://docs.google.com/document/d/11cyPx5MvAL05545BGs0SjyH-sImU6k0QInjx0ydSMY0/edit?usp=sharing

**Comment by NAretakis** [comment]
Ok, made a bunch up dates to the new framing doc. But I need @jeromeleecms 's input, especially for a review of the project goals starting on Page 9. Should I grab us some time to work through it?

**Comment by jeromeleecms** [comment]
OK, went through and made updates to the doc (tried the new suggestion editing feature this time). Happy to talk through the changes @NAretakis

**Comment by NAretakis** [comment]
Framing doc updated. Only remaining part to review are the long-term goals, which we can do at a later point. Ideally, when we are triaging issues and need to prioritize any of the long-term goals.
