### ISSUE TITLE
Organize ATO Folder in Google Drive

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1199]
Organize and add all supporting documents in the ATO folder in Google Drive

### This task is done when...
 - [x] All current documents supporting the ATO are in the ATO folder
 - [x] All current documents are cataloged

**Comment by NAretakis** [comment]
ATO folder organized. Now I'm adding XLC stuff.

**Comment by NAretakis** [comment]
Added XLC stuff. I'll figure out if converting out of DOCX is preferred.
