### ISSUE TITLE
Investigate using cloud.gov as a prototyping space

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#12]
What are the rules around using cloud.gov as a prototyping space while we try to get a stable home for this? If we're good to go, let's also get this set up.

**Comment by brendansudol** [comment]
sounds like we got a 👍 here, right @mgwalker? if so, let's close this and open an issue around deploying a skeleton app to sandbox

**Comment by mgwalker** [comment]
We need sign-off from CMS, too.

**Comment by nkkl** [comment]
We also have a thumbs up from CMS.
