### ISSUE TITLE
Clean up structure of Google Drive so only active/critical documents are present

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1203]
Clean up Google Drive and the folder structure
-Active
-Background/Onboarding Material
-Archived

### This task is done when...
 - [x] Active Documents are present in the top folder layer
 - [x] Inactive documents are archived, but still available
 
 ** Don't forget to fill out the LABEL and MILESTONE before submitting. If the issue is for the CURRENT SPRINT, add it to the PROJECT. If the issue is a BUG, FUTURE ENHANCEMENT, or OUTSIDE OF THE CURRENT SPRINT, do not add it to the PROJECT (then delete this line) **

**Comment by NAretakis** [comment]
Good to go.
