### ISSUE TITLE
Migrate Project to the CMS GitHub

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1207]
For long term sustainability, we would like to move/migrate the existing project to the CMS GitHub.

Can this be done?

### This task is done when...
- [ ] Migration to CMS GitHub Complete
- [ ] CI/CD testing working 
- [ ] Deploys are working

**Comment by jeromeleecms** [comment]
CMS has created a GitHub repo for us, but there are some additional steps we need to do in order to migrate the repo. Other work is taking priority over this, but just adding some notes for tracking purposes.

**Comment by mgwalker** [comment]
Obsolete by #1907
