### ISSUE TITLE
Review Federal Review Interview Synthesis to Identify Needs

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1208]
Review Federal Review Interview Synthesis to identify pieces that will bring value to Layer 2.

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
 ** Don't forget to fill out the LABEL and MILESTONE before submitting. If the issue is for the CURRENT SPRINT, add it to the PROJECT. If the issue is a BUG, FUTURE ENHANCEMENT, or OUTSIDE OF THE CURRENT SPRINT, do not add it to the PROJECT (then delete this line) **

**Comment by NAretakis** [comment]
Synthesis was reviewed, and I've uploaded all the notes and synthesis doc to drive:
https://drive.google.com/drive/u/1/folders/1Bo7XozSZSteklhXyaiNLzQMPkAsAX2fB
