### ISSUE TITLE
Totals in Summary Budget Table should total for the row (they are using pre-cost allocation totals)

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1217]
In the Summary Budget Table, the totals should reflect _Federal_ + _State_ amounts. Instead, what is happening is that the totals are showing the pre-cost allocation total amounts for each project activity type. 

There might be a clever way to show the pre-cost allocation total, the cost allocated amount, and then the Federal and State shares, but if there is not, then just totaling _Federal_ and _State_ will do.

![image](https://user-images.githubusercontent.com/34281281/50642838-a94d4500-0f29-11e9-9b39-943e27d04371.png)

**Comment by mgwalker** [comment]
Is it accurate to call this the "Medicaid total"?  If so, should we rename the column as well to be extra clear?

**Comment by NAretakis** [comment]
Yes, _Medicaid Total_ is what it is, so we should rename the column.
