### ISSUE TITLE
Program Budget Table needs to total Federal + State, instead of total pre-cost allocation dollars.

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1218]
Related to #1217 the program budget table total amount should be a sum of Federal + State. And the same for MMIS (Federal + State).
![image](https://user-images.githubusercontent.com/34281281/50643356-131a1e80-0f2b-11e9-85cb-9cd936e29177.png)

**Comment by mgwalker** [comment]
Same question: is this "Medicaid total" and should we rename the column as well?

**Comment by NAretakis** [comment]
Yes, this is the _Medicaid Total_
