### ISSUE TITLE
Get IAA Signed By Everyone That Needs to Sign It

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1219]
Get a thing signed.

**Comment by jeromeleecms** [comment]
Are you ready to close this? @NAretakis

**Comment by NAretakis** [comment]
Closed!



Nick Aretakis
•:303.844.7117 | •:Nicolas.Aretakis@cms.hhs.gov<mailto:Nicolas.Aretakis@cms.hhs.gov>

Need to schedule a meeting – see my online calendar<https://outlook.office365.com/owa/calendar/00097e1134f74c91a078b5a5d82adf31@cms.hhs.gov/4fe8b55caa634909950fb83afe7e043816837037865193385017/calendar.html>
