### ISSUE TITLE
Develop Project Team Directory

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1222]
As the team is growing, we should have a directory of contacts for folks who are directly supporting our project. The major fields to include:

- Name
- Phone
- Email
- Agency/Vendor
- High Level Role(s)
- Additional Notes

The [directory](https://docs.google.com/spreadsheets/d/1osef6aH87cqwGSlngPe28V8o5DNr6hvg0vEGpJGBDOo/edit#gid=634347005) will be housed in Google Drive and open to folks editing.

### This task is done when...
 - [x] Directory has been built
 - [x] Product has approved

**Comment by jeromeleecms** [comment]
@NAretakis Please take a look at the general form of the directory and update it with other contacts that are missing.

**Comment by NAretakis** [comment]
This is good to go. We just need to populate it with everyone's info.
