### ISSUE TITLE
Migrate Framing Document to Wiki

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1223]
With the refinements to the Framing document, we should migrate some of the key components over into the Wiki.

### This task is done when...
 - [x] Framing document on G-Drive is completed
 - [x] Framing document is migrated to Wiki

**Comment by NAretakis** [comment]
I think we need to keep these separate, however we can definitely update the Wiki with info from our 2019 framing doc.

**Comment by NAretakis** [comment]
Wiki and roadmap updated!
