### ISSUE TITLE
Number abbreviations beyond $1 billion dollars is not clear

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1225]
Starting at a billion dollars, the system has a odd lettering numbering system to report large numbers:
1) Million = M (makes sense)
2) Billion = G (edge case)
3) Trillion = T (not a real use case)
4) Quadrillion = P (not a real use case)

It's not clear how the letters correlate to numbers. Hovering over the number, doesn't provide any more specifics on the actual cost.

![image](https://user-images.githubusercontent.com/34279968/50999935-70404200-14e0-11e9-8f4f-82971ebe55d1.png)

![image](https://user-images.githubusercontent.com/34279968/50999875-4129d080-14e0-11e9-83c0-be6d5175b6d0.png)

### This task is done when...
 - [ ] Numbers -> Letter shortening is explained
 - [ ] Decision is made on how to adjust
- [ ] Adjustment (if any is made) to the numbers

**Comment by mgwalker** [comment]
It looks like the library we're using ([d3-format](/d3/d3-format)) is using SI prefixes, so mega (M), giga (G), tera (T), peta (P).  We should look into whether we can modify what it uses instead of the standard SI set.

**Comment by mgwalker** [comment]
There's no way to change the prefixes that d3-format uses.  We can look into changing to another library, or writing our own.
