### ISSUE TITLE
File attachments for contracts is not scoped in the MVP and should be disabled for the upcoming release.

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1228]
Attaching files within the app is a future enhancement. Decide how to address this in the app before releasing it (hide, disable, etc).

### This task is done when...
 - [ ] Decision on how to best address the attachment of documents to the APD has been made.
 - [ ] Decision has been implemented into the app
- [ ] Someone else has verified that the attachment function can not be accessed by other means.

**Comment by mgwalker** [comment]
Both hiding and disabling will be pretty simple implementation tasks, so if y'all choose either of those, we can knock this out pretty quickly.  On the API side, we'll just have it bail out with an HTTP 501 status code (`Not Implemented`) instead of actually processing anything.

**Comment by mgwalker** [comment]
Whenever we do this, we should also remove the `react-dropzone` dependency.

**Comment by NAretakis** [comment]
Reminder that this just needs to be "Hiding" the functionality to attach, because we're going to want to unhide it for layer 2.

**Comment by jeromeleecms** [comment]
What does hiding mean in this case? 
1) Hide Button in App (I don't like the idea of display:hidden within a production app)
2) Disable API functionality

?

**Comment by mgwalker** [comment]
With React, we can just remove the component from the page, so the code and functionality are still there, but it isn't used anywhere.  On the API side, we can not load the file upload endpoints, so the API won't respond to them.
