### ISSUE TITLE
Document use cases

### ISSUE THREAD

**Issue by nicoleslaw** [18F/cms-hitech-apd#123]
List the potential use cases of the APD app and their relative importance levels

**Comment by NAretakis** [comment]
[OK, document created with 5 use cases identified.](https://docs.google.com/document/d/1Oh8C9YSORO03Mh9kGF-TKgWnmQvamuaTIUjcoK3cc7U/edit#) Now to start putting some content into the basic flow.

**Comment by nkkl** [comment]
These look great! They're going to be super helpful for doing manual testing of the product. 🎉

**Comment by nkkl** [comment]
This is another candidate for something to put on the wiki, if you're comfortable with that.

**Comment by NAretakis** [comment]
Closing this task, as the use cases are listed. There is a separate issue #123 that actual insures the use-cases are completed.
