### ISSUE TITLE
Research Design System

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1232]
Capture results here!

**Comment by NAretakis** [comment]
also @hbillings

**Comment by hbillings** [comment]
Note to myself in case I don't get it locked down today: We need to set the app up to compile SCSS if we're going to move over to the design system.

**Comment by jenniferthibault** [comment]
A few early notes and questions from the design side:
- There's a sketch file! WOO that makes this much faster.
- Tables:
    - The examples in the design system site are fairly simple. Ours app has multiple layers more complexity — would like to find table examples in use within apps built on the system
    - Sketch file not quite accurate w/ site examples, I'm treating the site as the source of truth
- Accordions:
    - In the Sketch file but not on the design system site? Is it in the code?

Heather and I are meeting shortly to compare notes.

I'd like to find other designers working with the system and see if we can share design files, which may have a more broad range of applications.

**Comment by jeromeleecms** [comment]
@jenniferthibault @hbillings After you meet, let us know if you think if it would be helpful to schedule a meeting with the folks that maintain the design system or you want us to pass along any specific questions (+ virtual introduction).

**Comment by jenniferthibault** [comment]
Thanks @jeromeleecms ! That will be super helpful, I'm 100% sure we'll want this. Heather and I will talk about what we need earliest to target intros to the right types of folks.

**Comment by hbillings** [comment]
Some notes from @jenniferthibault and my chat:
- Starting by implementing the grid is likely a good first step. (The grid is a separate NPM package from the design system, so we can install it without messing with anything else.) The grid in the Sketch file is a bit off from what's in the code.
- Are there other CMS brand guidelines out there?
- Who's using this design system other than Healthcare.gov?

**Comment by jenniferthibault** [comment]
@hbillings would you say we could close this?

**Comment by NAretakis** [comment]
Done!
