### ISSUE TITLE
Research Analyst Research

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1236]
Catch up on what research took place while we were away so that we know what to follow up on next.

### This task is done when...
 - [x] MET has shared the research
 - [x] Next steps have been identified

**Comment by lauraponce** [comment]
Synthesis doc: https://docs.google.com/document/d/1W51GUjRT-DSBFxIZHCPC4wwqfd5wUfeSdwI1_qIaRmc/edit# 

Fed research folder: https://drive.google.com/drive/folders/1SSkkVPYO9gswbMrxIv-D1qHI5ASzp0TY?usp=sharing

**Comment by lauraponce** [comment]
Created #1272 for the next steps related to this reviewer research
