### ISSUE TITLE
Figure out best way to implement CMS design system styles

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cms-hitech-apd#1250]
Building off of @hbillings #1247 —

I'm not sure what goes into changing over all the styles to the CMS design system. This issues is to help us figure that out.

### This task is done when...
 - [x] We understand what's involved in changing over to the CMS styles & components for our app
 - [x] We have a strategy for how we'll try to attack it
 - [x] We've created new issues for breaking that strategy down into actionable items

**Comment by jenniferthibault** [comment]
Had a great session with @hbillings and @mgwalker this morning and found an approach we think will work for getting started:

**Understand how far apart our systems are:**
- Start with bringing in the most vanilla default CMS design system
- Flag if their components are different than ours (if we are both using things like alerts/messages in the same way)


**So that we can get a feel for the system in practice, carve out pieces that can be restyled independently:** 
- Start with the underlying grid, since it's a separate npm package ( #1246 )
- Try restyling and building a component that is modular enough to separate from the rest — the side nav / vertical nav
- Try restyling a complete page — like the dashboard page
- Try restyling a more complex set of basic components together — the State Profile Contact Info portion of the form

Once I've made separate issues for each of these, I'll come back to close this issue.

**Comment by jenniferthibault** [comment]
@hbillings up for taking a peek at the new issues to see if I missed any, or underrepresented dav details that we need at this stage?

**Comment by hbillings** [comment]
@jenniferthibault This looks good to me! Thanks for doing this :)
