### ISSUE TITLE
Write export instructions/descriptions for state users

### ISSUE THREAD

**Issue by jameshupp** [18F/cms-hitech-apd#1256]
The print preview PDF experience is a little wonky and users are not always clear on what is going to happen, including noting anything unusual.

### This task is done when...
 - [x] Content loosely documents the print preview PDF workflow as a basis for instructions
 - [x] Pattern for displaying this instruction is approved by visual design and usable by content
 - [x] Content writes and deploys to production

**Comment by jeromeleecms** [comment]
@jameshupp This seems dependent on #1160 (i.e. can't write instructions until we figure out what the process for exporting will look like).

Does that seem right to you?

**Comment by jameshupp** [comment]
This is labeled blocked by #1160, but I think we've figured the process out, right? #1160 is now more focused on building what the exported document will look like, not the process itself? If so I'm ready to pick this up.

**Comment by jeromeleecms** [comment]
@jameshupp I agree with your assessment + removed the #1160 blocker. 

As you scope out the instructions, I'm seeing some potential overlap with #1316. If this is only associated with Exporting the PDF than I think this is fine, but if you start to venture into what you can do with the PDF after it's exported, maybe worth checking in with @MCorradoHMA.

**Comment by jameshupp** [comment]
Here's a really quick draft. This works as long as we follow through on #1321, which creates a separate section for exporting rather than leaving it as a button at the bottom of the menu. That feels like a less confusing experience than seeing multiple buttons, and as I mentioned on that issue it aligns with something we heard in testing. These instructions are part of completing that issue.

Note that I did mention one thing you could do after exporting, which is to make additional changes. I am not suggesting anything about what to do after submitting. So I don't _think_ this trips issues on #1316, but if it does let's not go too far down this road.

### Export and Submit

To submit your APD for analyst review, export the document as a PDF, then send it to CMS just like you’ve done before.

1. Select **Export** to open up your browser’s print options.
1. In the print window, select **Save as PDF**. In Chrome, this option is listed under _Destination_. In other browsers, this option is part of a dropdown menu labeled _PDF_. 
1. Select **Save.** This will download a PDF to your computer.
1. If you decide to make changes before you submit, follow those three steps again to download a new PDF.
1. Email the completed APD to **(CMS APD email address)**.

[Export]

**Comment by jameshupp** [comment]
I think the second item in the checklist is addressed by #1321. @lauraponce does that seem right, or is that a separate need? It seems a little odd that both have checklists for each other if that's it.

**Comment by lauraponce** [comment]
Yep — agreed! It feels like #1160 is closeable at this point with creating the implementation issue as the only remaining to-do (which will be done as part of the creation of all the issues for applying the design system to each section).

**Comment by jeromeleecms** [comment]
Per sprint planning, @jameshupp when you are ready to tackle this one, let's pair so you can see how this applies to Internet Explorer.

**Comment by jeromeleecms** [comment]
Per Standup on 04/22, we'll demo this during our working session time on 04/22. Putting this as "in progress" since we'll do a little work on this.

**Comment by jameshupp** [comment]
New copy on this in the previous comment with draft info. Feedback encouraged!

**Comment by lauraponce** [comment]
Looks good to me! It seems straightforward with the necessary detail. I also like that these instructions make it clear that they repeat this export process at any time.

**Comment by jeromeleecms** [comment]
I was playing this a bit more in different browsers and selecting the PDF printer is a more generic experience. Maybe revising it to:

2) Select your PDF printer. If you do not have a PDF printer, select **Save to PDF**.
3) If prompted, provide a file name. Select OK to open or save the file to your computer.

I know you were thinking not to select the PDF printer, but this process could apply to any/all browsers. The exception being a IE user with no PDF printer...

**Comment by jameshupp** [comment]
Changed the text per Jerome's suggestions. I wanted to get away from a conditional on step 2 that seems to favor one term over another. If you think it's so much more likely than the other version, it's fine to include it, but "a PDF printer" struck me as a slightly odd term of art. Since both commands will _work_ if someone sees them, let's just let them do whatever comes up first.

**Comment by jeromeleecms** [comment]
Reclosing this.. because. ah.
