### ISSUE TITLE
Coordinate the pilot

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1258]
Before the pilot launches, we need to figure out the logistics about how it will work.

### This task is done when...
 - [x] We know which states are participating in the pilot
 - [x] We know which CMS reviewers are participating in the pilot
 - [x] We have a point of contact for issues/bugs that state users encounter
 - [x] The review/update process for the pilot is understood by CMS and states

**Comment by jeromeleecms** [comment]
@MCorradoHMA To rewrite issue!

**Comment by jeromeleecms** [comment]
@MCorradoHMA Could you take a look at this and see if this still needs to stay open? It looks like this is done/very close to done?
