### ISSUE TITLE
Assessment of eAPD sections for layer 1

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1263]
Review and assess each section of the eAPD, and then report here on if a section is acceptable or unacceptable for layer 1.

Criteria will be based on :
1) Regulatory (Does it explain what it needs to do in this section?)
2) Functional (Does the editor or math work?)
3) Layout and interactions (Do the design patterns and sections function?)
4) Content (Is helptext/reminder info complete and clear?)

**Comment by jeromeleecms** [comment]
I'm going to throw this back in the prioritized backlog -- there are several things changing in the app, so I can't pick this up until we are closer to release/finalizing content in the app.
