### ISSUE TITLE
Restyle side nav in eAPD prototype to use design system vertical nav component

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cms-hitech-apd#1267]
_Part of #1250_ 

In order to start understanding how to use the CMS design system, we should start with a component that occurs infrequently and is modular enough to edit alone. The side nav in the app prototype fits that bill!

### This task is done when...
 - [x] The side nav has been replaced with the vertical nav component in the sketch files
 - [x] We know what we expect it to look like in place (through mockups)
 - [ ] The side nav has been replaced and customized in the code
 - [ ] The side nav's sticky functionality has been restored on long pages

 **Current side nav:**
![screen shot 2019-02-06 at 10 55 31 pm](https://user-images.githubusercontent.com/11636908/52389627-5acc2280-2a62-11e9-99a3-4af01c4b6fed.png)

**[Vertical navigation component](https://design.cms.gov/components/vertical-nav/) from CMS Design System**
![screen shot 2019-02-06 at 10 56 58 pm](https://user-images.githubusercontent.com/11636908/52389664-8d761b00-2a62-11e9-9719-4bf1ae8b57ca.png)

**Comment by jenniferthibault** [comment]
Here's what the vertical nav could look like in our context:
![screen shot 2019-02-12 at 11 04 21 am](https://user-images.githubusercontent.com/11636908/52649281-0ab3ec80-2eb6-11e9-87bc-b6aceaac2afc.png)

**Additional notes:**
- I dropped the "HITECH" text in this mockup to reflect [Jerome's comment](https://github.com/18F/cms-hitech-apd/issues/1126#issuecomment-460375167)
- I started looking at the button styles in addition to the vertical nav component, since they're layout was grouped, but we could totally reserve that for #1280 

A question for @lauraponce: 
- Do you remember if there was a decision to truncate the menu text with ellipses `...` on purpose? In the mockup above, I wrapped text to a new line instead of hiding it, but glad to revisit if you remember that being tested & intentional

A question for @hbillings:
- This mockup aligns the navigation to the grid, but the right-hand side of the nav container expands into the grid's gutter (probably thru padding?). There aren't any layout files for me to compare this with, so I'm not sure what the most logical treatment is, but from a layout perspective, it will always look best when we line up text on the grid columns within containers. Is this a feasible way to go? Or is there a better approach?

![screen shot 2019-02-12 at 11 10 17 am](https://user-images.githubusercontent.com/11636908/52650011-659a1380-2eb7-11e9-93fe-81bb901eb11c.png)

**Comment by lauraponce** [comment]
@jenniferthibault the ellipses can go! I agree — much better spelling out the whole thing. 

The only reason why they are there now (if I recall correctly) is because we hadn't gotten to handling smaller screen sizes and so the bandaid put in place on the front end forever ago was to truncate it.

**Comment by hbillings** [comment]
@jenniferthibault Okay, I think I get the question (I was confused because I struggle with telling left from right, and I was looking at the left side... oy.) Yes, the gutter is created through padding, which is not my favorite. The most straightforward way to hack this is to create divs that only serve as column containers. In this case, that structure would look a bit like this:
```
<div class="ds-l-col--3">
  <aside class="sidebar">
    [...]
  </aside>
</div>
```

That _should_ put the padding between the sidebar and the main content, not within the sidebar. 

Does that answer the question, or did I totally whiff on what you were asking?

**Comment by jenniferthibault** [comment]
Heather and I had a great pairing session today on the grid questions above — this issue is doing it's job in that it broke out a component that would help make sure we understood how the new grid worked.

We expected to see a grid that is built like this, where the gutter is made of margins:
<img width="712" alt="screen shot 2019-02-14 at 11 12 40 am" src="https://user-images.githubusercontent.com/11636908/52811252-7da19c80-3049-11e9-9fcf-a2cb1aca3750.png">

And discovered a grid that is built like this, with the gutter is built of padding:
<img width="712" alt="screen shot 2019-02-14 at 11 13 39 am" src="https://user-images.githubusercontent.com/11636908/52811312-a1fd7900-3049-11e9-81bd-43524df71605.png">

So we do expect the layout to look like the screenshot above, where the content in the container starts & ends on the grid columns, but the padding on the container means the container will end halfway through the gutter. We discovered that gutters are 32 px wide, but made of two abutting 16px-wide units of padding on the outside of each container.

Next steps, we'll take this into the code! Onward to grid glory and implementing the styles here!

**Comment by jenniferthibault** [comment]
WIP PR for this in #1310
