### ISSUE TITLE
Restyle the State Profile Contact Info using the CMS Design System

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cms-hitech-apd#1269]
_Part of #1250_

In order to transition a few more complex components and layouts to the [CMS Design System](https://design.cms.gov/), restyle the State Profile Contact Info portion of the form. 

### This task is done when...
 - [x] We feel good about the component and layout restyling
 - [x] Design files have been updated with new library components
 - [x] A new issue has been created for development changes for the concept
 
**Current styles:**
![screen shot 2019-02-06 at 11 41 25 pm](https://user-images.githubusercontent.com/11636908/52390910-ce712e00-2a68-11e9-8ba1-25ecb3cd6d66.png)
![screen shot 2019-02-06 at 11 41 33 pm](https://user-images.githubusercontent.com/11636908/52390911-ce712e00-2a68-11e9-8278-883d4f43a909.png)

**Comment by jenniferthibault** [comment]
Holy moly I think I've cracked it!

## What I've learned about the design system & it's components through rebuilding this section
### The CMS design system **does not** have an accordion component. 
This was an initial snag because we use accordions heavily in the prototype. We could choose to use ours, or build one, but the accordions were previously causing some headache in the layout, so I wanted to see where they came from before making that choice. After checking in with @lauraponce on previous research, here's that summary:
 > no research points to the fact that we should definitely use the accordions. But the accordions allow for states to quickly see what’s next. And potentially for the fed experience, the accordions could be expanded by default to make it easier for them to go through the review process (more research needs to be done for the fed users though to validate that hypothesis)

Based on this, I recommend we try releasing the content from the accordions, and instead rely on:
- The new navigation styling (which does not truncate the heading text)
- Numbering the sections to help people orient them in their progress
I think this will both make our codebase simpler since it removes a custom component, AND make the app space appear visually cleaner since we're removing some containers (we were backing ourselves into a corner through so many nested boxes)

### The CMS design system has components and patterns that solve a few of our pesky old problems
- Their [React Checkbox/ `<Choice>`](https://design.cms.gov/components/choice/) component has a prop called `checkedChildren` that would allow us to do what we planned in https://github.com/18F/cms-hitech-apd/issues/1173 to replace the yes/no buttons.
- Their [React `<Review>` Pattern](https://design.cms.gov/patterns/review/) is a great solution to the Add/Edit/Remove pattern clunkiness (at least for this section) that we documented in https://github.com/18F/cms-hitech-apd/issues/1077 but hadn't solved for yet.

### The CMS design system does not have an equivalent `Help text` component
The nearest equivalent is the [Alert](https://design.cms.gov/components/alert/) (the one without the icon) but without looking at our alert system as a whole yet, I don't think we should touch. Which means that _in this section_, this is the only custom component we need. I'm sure we'll find more later, but glad to find that everything else is covered.

Will follow up with mockups in the next comment (they're ready, just want to get these thoughts out first)

**Comment by jenniferthibault** [comment]
👀 👆 🖥 [Clickable prototype](https://gsa.invisionapp.com/share/BJQNX2KXQVW#/348460956_State_Profile_Contact)

## Styled mockup
- Drops accordions and makes more full use of grid space
- Uses all CMS design system components patterns, including the React Choice and React Review Pattern noted above
- Only unique eAPD component is `Help text`
- Changes `State` field in address form to a Select component instead of a Text field component, following design system practices
![state profile contact](https://user-images.githubusercontent.com/11636908/53256678-6e000480-3696-11e9-8714-85f4bd6bc7d4.png)


## A few critical interactions to try out in the InVision Prototype

### Adding Primary APD Contact with Associated costs
![costs associated - add contact](https://user-images.githubusercontent.com/11636908/53256838-d6e77c80-3696-11e9-885d-76c1f382c43f.gif)

### Adding an additional contact
- I didn't record the the interactions for removing the additional contact, but they are available through the clickable prototype on Laura's contact info
![add-second-contact](https://user-images.githubusercontent.com/11636908/53256944-0d24fc00-3697-11e9-82fc-8db40873e4f7.gif)


______
**Next steps and specifics to review:**
- @jameshupp from a content and IA navigation perspective, what do you think about numbering the first-level navigation numbers (as shown in the mockup) ?
- @hbillings @mgwalker: Even in this short section there are a lot of individual components. I was hoping that by using all the CMS Design System components as "vanilla" as possible, that would help reduct implementation complexity. Please flag anything that has complexity I may not be understanding well enough
- @lauraponce: 👀 on all the interaction choices and how they line up with research to date  
- @jeromeleecms & @NAretakis: General reactions to seeing the CMS Design System in place in the app for the first time?

**Comment by mgwalker** [comment]
My initial hunch is that since the underlying data isn't changing, it's not a huge lift, but that's said with total ignorance about the CMS Design System.

There are a couple of options that jump to mind re: accordions, though.  One is we can just replace them on the state profile section with this new design.  The other is we can modify the `<Subsection>` component that we use (it's what provides the accordion) to this new style, and all the other parts of the app will inherit the new design all at once.  The latter seems more sensible to me just from a consistency perspective, but wanted to point out that we can do it either way.

**Comment by jeromeleecms** [comment]
@jenniferthibault Overall, I like the clean look of the implementation and the interaction is smooth (I like how clicking "Yes" transitions smoothly into the new set of questions).

Just something for my understanding -- how does this design pattern scale to the other portions of the app? (I know this issue is only focused on the State Profile contact info)...

1) Do you envision "the navigation number" + spacing with the actual content is going to be consistent throughout the app (beyond what is listed in #1267, #1268, and #1269)? It seems like that might eat into some potential real estate issue if this pattern is pushed down into the activities or summary sections (esp. with the sections that rely heavily on tables). 

![image](https://user-images.githubusercontent.com/34279968/53353141-fbcb3200-38d8-11e9-9431-a03349555a36.png)

2) The content area does appear to be fixed width (not sure if this will change), but this white space may reduce the available space for large blocks of content (esp. in the activity areas). Is it too early to just to some high level discussion on this?

**Comment by jenniferthibault** [comment]
Had a great synchronous chat with Heather & Jerome. Here's the recap of that discussion

**`How does this design pattern scale to the other portions of the app?`** 
I think by "this design pattern you mean the [React Checkbox/ `<Choice>`](https://design.cms.gov/components/choice/) component using `checkedChildren` from above? If so, I anticipate that this component can also be used for other instances we've identified within the app, like #1174 and #1175 , yes!

**`Do you envision "the navigation number" + spacing with the actual content is going to be consistent throughout the app`**
I anticipate it will be consistent throughout this page (and the form is all on this one page of the app) And that we'll need that column of white space abutting the nav/menu on the left, through this whole page. That sets the left boundary at a predictable place and leaves our eyeballs a little breathing room.

**`Available space for large blocks of content`**
We'll make the smartest choices about max-width settings for the rest of the app as we get more info about those places, (and maybe even revisit previous decisions) but I don't expect any of this to make the size smaller than what we have now. I think we may even be using more of the available space to the right if we are dropping some of the right-hand padding inflicted by accordions and containers. All to say: not too soon to discuss at a high level, but hard to make other choices given limited info we have now.


At this point I think the only outstanding questions are the content ones for @jameshupp — those don't feel like hard blockers, so I'll move ahead into breaking these down for implementation. Please do chime in though @jameshupp so I can make accurate next issues :)

**Comment by jenniferthibault** [comment]
Drafted new issues to break this work down in #1329 , #1330, #1331, #1332 . @mgwalker @hbillings please take a peek and add/edit, they need help from the folks who will be working on them :)
