### ISSUE TITLE
Create a basic admin landing page

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1273]
There needs to be a place admins can go to link to the various pages of admin functionality (see #1253, #1254).

### This task is done when...
 - [ ] there is a page for admins to do adminy things
 - [ ] admins can easily get to it (e.g., maybe they are sent directly to the admin page when they log in - they are not state users, so maybe they shouldn't see the state dashboard anyway)

**Comment by jenniferthibault** [comment]
Pulling designs ready for implementation forward from #1351:

![Layer 1: Admin Landing_2](https://user-images.githubusercontent.com/11636908/54464821-a3a48480-474e-11e9-9e53-af7a0dcbe4d4.png)


And with grid:
![Screen Shot 2019-03-15 at 6 08 00 PM](https://user-images.githubusercontent.com/11636908/54464839-b7e88180-474e-11e9-8e73-b75b69a65f5d.png)

**Implementation styling notes:**

- `[Administrator actions]` uses H1 visual styling - @jameshupp this is the time to flag if you want different microcopy here!
- `Create user accounts` and `Manage user accounts` use H2 visual styling
-  Blurb copy in a copy+paste-able format: `Make new accounts for federal  analysts and state filers` and `Edit account details and authorization levels for existing user accounts` - @jameshupp 👀 
- The two icons are [user-cog](https://fontawesome.com/icons/user-cog?style=solid) and [user-plus](https://fontawesome.com/icons/user-plus?style=solid) from Font Awesome. I'll send a PR to add their licensing info to the repo.
  - Icon fill: `$color-primary-alt-darkest` from the [CMS Design System palette](https://design.cms.gov/style/color/)
  - Background: `$color-primary-alt-darkest` from the CMS Design System palette
- Just like the [state dashboard page](https://github.com/18F/cms-hitech-apd/issues/1378), this uses 8 columns overall, centered on the grid (or two 4-column containers inside 8 an column container, off-set by 2 on each side)
- Vertical spacing is still eyeballed — as we've discussed previously, use the defaults and let's see what it looks like before adjusting

I thiiiiink that's everything? Ping me with questions!

**Comment by jameshupp** [comment]
Can I clarify something: does the admin create more than one user account at a time? What does the next page look like? (I don't know where that is right off if it's mocked up, sorry.) The copy as it currently exists in this mockup suggests the person will create several accounts in a single stroke. If that's true, it's pretty close. If not, I'd like to edit it a bit.

**Comment by jenniferthibault** [comment]
Good flag! I believe an admin creates only one user account at a time. 

That page can be seen here: https://hitech-apd.app.cloud.gov/admin/create-account/
(It's currently using the old styles)

**Comment by jameshupp** [comment]
Cool. I think the only real change is the title should be `Create new user account` (if there is space for that). I like the `new` just to differentiate as clearly as possible.

**Comment by jeromeleecms** [comment]
If my memory serves, @mgwalker said that admins need to have separate accounts (correction if needed please!). If a user logs in with their admin credentials, I agree that it should take them directly to the admin page.

**Comment by mgwalker** [comment]
Having separate admin accounts is the easiest way to satisfy one of the NIST controls for ATO, yes.

A better approach, maybe for the future, would be to re-enter your password when you navigate to the admin dashboard.  That way you only have one account to manage, but you still satisfy the NIST control (I *think*).
