### ISSUE TITLE
Review APD to eAPD crosswalk MeT drafted

### ISSUE THREAD

**Issue by CSwartzHMA** [18F/cms-hitech-apd#1275]
MeT would like to provide a quick overview of the eAPD crosswalk drafted in December and talk about next steps for fine tuning the document.

### This task is done when...
 - [ ] A meeting is scheduled to review the draft.
 - [ ] The review is completed and next steps have been discussed.

**Comment by CSwartzHMA** [comment]
@jeromeleecms is scheduling something you'd like Melissa and I to work on? Later next week looks good.

**Comment by jeromeleecms** [comment]
That would be great - feel free to DM me on Slack and I can work with you to look through the team's calendars and try to line it up with yours and Melissa's.

**Comment by NAretakis** [comment]
Done! Next steps are for MeT folks to be included in pilot planning.
