### ISSUE TITLE
Figure out and gather domain info

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1278]
In order to get a domain name, we need a set of information about our AWS environment to point the domain at.  Figure out what the information is, and then go get it.

### This task is done when...
 - [x] we know how to get a domain name with external nameservers pointed at AWS resources
 - [x] we have identified and collected the relevant information

**Comment by mgwalker** [comment]
It looks like we can drop a couple of extra AWS services into our configuration and then getting domains setup should be super easy.

I've drawn it a little bit in [a mural](https://app.mural.co/t/gsa6/m/gsa6/1550082334208/ca2582ed93b796ebb625b1cc0b4e68ab91b25c34), but I'll describe it here too.

### Frontend

Our frontend is stored in a AWS S3 bucket.  We can add the AWS CloudFront service to serve up the S3 contents.  This does several good things for us:
- serving directly from S3 is discouraged as a bad practice, so using CloudFront mitigates that
- CloudFront can provide SSL termination, either through its own certificates or certificates generated elsewhere
- CloudFront generates a custom domain for you, like asdf1234.cloudfront.net, which will never change, even though your S3 bucket may move around
- the CMS domain management folks just need to add a `CNAME` record for our frontend domain that points at the domain CloudFront generated for us

We can get CloudFront setup now!  That way when it's time to issue our frontend domain, they can do it all in one go instead of having to go back and change things later.

### Backend

Our backend will run on an EC2 instance.  We can add an Elastic Load Balancer instance to serve access to it, which does a few nice things for us:
- using ELB lets us switch out EC2 instances seamlessly, which means we'll be able to update the OS image and all that fancy stuff without downtime!
- ELB can also terminate SSL connections, which is nice
- ELB generates a custom domain which will never change, even as we plow through EC2 instances
- the CMS domain management folks just need to add a `CNAME` record for our backend domain that points at the domain ELB generated for us

We can also setup ELB now!

---

Note that I've been assuming we'll have at least two domains - one for frontend and one for backend (e.g., eapd.cms.gov and api.eapd.cms.gov).  If that's not the plan, that's fine - I think the layout here will mostly work, but we'd move everything to CloudFront instead of using ELB/ALB for the backend.

**Comment by NAretakis** [comment]
At this time, MACPro’s domain is not utilizing Route 53 for DNS. We are in the process of switching over. The timing couldn’t be better for you to bring this up to GDIT (who manages AWS support) is just rolling this Route 53 offering out. For new domains, it should be available right away. 

This means that when we are ready, we put a ticket into JIRA and connect with GDIT to request it. I figure we might even be ready to do this next sprint.

**Comment by mgwalker** [comment]
It will be interesting to see if they also let us manage the Route 53 service.  Like if they create the record and then let us point it where it needs to go, we're going to be on easy street (as far as the domain goes).
