### ISSUE TITLE
Refine the UX for saving and exporting as a PDF

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1280]
### Background

There are three options for saving and exporting: 
1. `Save APD` button (in the left nav): saves the current state of the APD
2. `Save as PDF` button (left nav): functionality is not hooked up, but it would allow users to export as a PDF
3. Print preview button (bottom right): switches the page to a printable version of the APD

**Questions**
- Is having two buttons with the word `save` confusing? Should we call it export instead of save?
- Do we need all three? Can we consolidate the Save as PDF and print preview button?
- Should the print preview button be more prominent?
- Can the print preview open in a new tab?
- Do we need instructions for how to export from the print preview page?

![screen shot 2019-02-11 at 3 09 39 pm](https://user-images.githubusercontent.com/21222704/52600323-16e56e80-2e10-11e9-81d8-1fb604467a5c.png)

### This task is done when...
 - [ ] We have figured out the right number of save/export buttons
 - [ ] We know what the button labels should be
 - [ ] We have a recommendation and decision for updating/not updating the export experience

**Comment by lauraponce** [comment]
Tagging in @jameshupp and @jenniferthibault  — what are your thoughts on the save/export experience? I think we could consolidate the print button and the Save as PDF button into one but definitely want your input on this!

**Comment by jenniferthibault** [comment]
Totally agree! 

Feels smart to remove the print button and rely on the browser's Print commands instead of adding our own. Then paring the action buttons down to `Save` | `Export` (and making 'em _werk_)

**Comment by mgwalker** [comment]
From a code perspective, we can programmatically trigger the browser's print dialog, so if we want an `Export` button that opens the print dialog, we can do that.

One thing to note is that we need to run some code before the app is ready to print.  I think most of the changes are handled with a print media stylesheet (for which we don't have to do anything 🎉), but some will need to be done with Javascript (e.g., changing `$1.2M` to `$1,203,582`).  We can reliably run our code if the user triggers a print using our button, but it might be a little trickier if they use the browser's native `File -> Print` method.

There are browser events for [before the print dialog is displayed](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeprint) and [after the job has been sent to the printer](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onafterprint), so we should be able to hook into those to run our code before it gets to the print dialog.  My understanding is that support isn't completely consistent across browsers, so we might need to check it in a few to be sure it works as expected.  We could prototype that separately, though.

**Comment by lauraponce** [comment]
@jenniferthibault ooohh I just saw your mockup on #1267 which updates the buttons to `Save` | `Export` so it sounds like you've already thought about this 🙌 ! 

It seems like _this_ issue can be closed and the things to do are:

1. Implement the new save/export buttons styles (this is already being handled in #1267) 
2. Remove the print preview button in the bottom right
3. Hook up the Export button to trigger the browser's print dialog

I'll create an issue for 2 & 3 to track the work then will close this one out. Do that seem 👍 to you, @mgwalker?

**Comment by mgwalker** [comment]
Perfecto!

**Comment by lauraponce** [comment]
Created #1281 to track the dev work — closing this out.
