### ISSUE TITLE
Remove print preview icon and hook up export button

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1281]
_Builds off of #1280_

The Save / Export buttons will be updated in #1267, so this issue is for hooking up the **functionality** of the Export button (currently, the button label is Save as PDF) and removing the printer button.

Greg's note about the dev work on #1280:

> From a code perspective, we can programmatically trigger the browser's print dialog, so if we want an `Export` button that opens the print dialog, we can do that.
> 
> One thing to note is that we need to run some code before the app is ready to print. I think most of the changes are handled with a print media stylesheet (for which we don't have to do anything 🎉), but some will need to be done with Javascript (e.g., changing `$1.2M` to `$1,203,582`). We can reliably run our code if the user triggers a print using our button, but it might be a little trickier if they use the browser's native `File -> Print` method.
> 
> There are browser events for [before the print dialog is displayed](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeprint) and [after the job has been sent to the printer](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onafterprint), so we should be able to hook into those to run our code before it gets to the print dialog. My understanding is that support isn't completely consistent across browsers, so we might need to check it in a few to be sure it works as expected. We could prototype that separately, though.

### This task is done when...
 - [ ] Print preview button on the bottom right of the page has been removed
 - [ ] The export button works and triggers the print dialog

**Comment by jeromeleecms** [comment]
@mgwalker If the print preview icon is removed, that will remove it from the entire app, correct? There is a print preview icon on the login page that isn't really useful + not accessible (the screen reader currently reads this as "button").
