### ISSUE TITLE
Update the dashboard instructions for exporting the APD

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1282]
The export button is changing from `Save as PDF` to >> `Export`  as part of #1267 so the dashboard instructions for submitting and APD should be updated to reflect that.

![screen shot 2019-02-11 at 11 55 42 am](https://user-images.githubusercontent.com/21222704/52661716-7ea2c480-2eb7-11e9-9db4-923fab25fa61.png)

### This task is done when...
 - [ ] Dashboard text has been updated to reflect the button label change

**Comment by NAretakis** [comment]
Closing in favor of #1268
