### ISSUE TITLE
As the product team, I want to be able to define the scope of the pilot so the entire team knows what is important to work on.

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1291]
As a follow up to #1255, Nick, Nikki and Jerome will review the pilot workflow so the team has clearly defined edges on what the initial release of the product will look like.

### This task is done when...
 - [ ] Meeting scheduled for review of the workflow
 - [ ] Open questions in the cards have been addressed
 - [ ] Follow up meeting has been scheduled to share results with the rest of the team

**Comment by NAretakis** [comment]
@jeromeleecms to close

**Comment by jeromeleecms** [comment]
This has been addressed with updating the priorities with Zenhub + other discussions. Will reopen if needd.
