### ISSUE TITLE
Simplify sidebar components

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1294]
Right now we have two sidebar React components, `Sidebar.js` and `StateDashboardSidebar.js`. They use the same basic markup (which means any change to one has to be made to the other also, and introduces the possibility of them getting out of sync), so we should consolidate them into a single component and render the right nav with props or something.

### This task is done when...
 - [ ] There is a single sidebar component 
 - [ ] We've come up with a logical way of passing in nav items

**Comment by jeromeleecms** [comment]
This is done by accident.
