### ISSUE TITLE
Replace password meter with a real one

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1297]
There is a ham-fisted password meter in the account creation UX.  It should be replaced with a good one.

### This task is done when...
 - [ ] there is a better password meter

**Comment by jeromeleecms** [comment]
@mgwalker Is this something we need for ATO? Or a nice to have and we can eventually layer this into the next release cycle after the Pilot?

**Comment by mgwalker** [comment]
Definitely not required for ATO.  The UX we have now is functional, but it might not be a great experience for users and it's kind of ugly.

**Comment by jeromeleecms** [comment]
Closed because it works as is.
