### ISSUE TITLE
Create a mobile menu

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1298]
The current sidebar disappears on small screens. While we don't anticipate people filling these out on mobile, we know that folks tend to look at things on mobile even if they aren't going to fill them out. We can keep this simple and just do a nav with top-level items (i.e., none of the accordion magic) behind a hamburger.

### This task is done when...
 - [ ] we decide on mobile nav items
 - [ ] we decide on/design mobile nav interaction
 - [ ] the structure for a simple mobile nav is in place
 
*Don't forget to add the LABEL and MILESTONE before submitting.

*If the issue is for the CURRENT SPRINT, add it to the PROJECT.

*If the issue is a BUG, or FUTURE ENHANCEMENT, do not add it to the PROJECT

**Comment by jeromeleecms** [comment]
We are not planning on implementing a mobile functionality in the near-far future. May revisit this down road.
