### ISSUE TITLE
See what project management tools CMS has available

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#130]
For each of these, does CMS have access? Are there any blockers?
 - [ ] [Jira](https://www.atlassian.com/software/jira)
 - [x] [Microsoft VSTS](https://www.visualstudio.com/team-services/)
 - [ ] [GitLab](https://about.gitlab.com/)
 - [ ] other?

**Comment by NAretakis** [comment]
We have access to MVST, not sure if team services is included. I've asked about the others are are waiting to hear back. I am also inquiring about Waffle.io. I know you said you couldn't use, but I'm curious from the CMS side, maybe we can get a blessing on it, which seems like the easiest.

**Comment by NAretakis** [comment]
Confirmed that we have access too, Visual Studio Windows Pro w/MSDN
Software Assurance Non-Specific
License Only NO MEDIA
INCLUDED(Open),Full New License
& Software Assurance Pack(All
Languages), (Open Business) 

Which does include Team Services. Yay! However, I'll need to put in a purchase request. But at least it is approved software.

**Comment by nkkl** [comment]
Awesome! Just access to the VSTS web tool is sufficient for me, although we can have a conversation about whether or not we want to take advantage of any of the other parts of the suite.

**Comment by NAretakis** [comment]
Asked about VSTS install/access. As well as Waffle.io as that might be quicker. Waiting to hear back from the CMS service desk staff.

**Comment by nkkl** [comment]
Great, thanks Nick!

**Comment by NAretakis** [comment]
Ugh. We have Jira, but only CMS staff are allowed. GSA is not allowed access. Very strange, but they were pretty adamant. I am confirming VSTS for GSA access now, and still waiting on waffle.io. Probably one of those two is our best option.

**Comment by NAretakis** [comment]
Slow and steady. Still waiting on waffle confirmation. Just missed Galentines day, which is a shame, really.

**Comment by NAretakis** [comment]
HOT DOG! @nkkl we are good to go on the use of Waffle. I know it is not your favorite, but is the easiest at this point. I'm going to close this out, and then if we really need to up our game I can put in the request for $$ to buy MSVST+Team services. But that is a whole other process.

**Comment by nkkl** [comment]
Cool beans! I'm reaching out to our internal IT governance folks to get it wired up.

**Comment by NAretakis** [comment]
Adding CMS approval change text for posterity. In this context, schedule = approved:
-----Original Message-----
From: CMS IT Service Desk [mailto:CMS_IT_Service_Desk@cms.hhs.gov] 
Sent: Thursday, February 15, 2018 11:13 AM
To: Aretakis, Nicolas J. (CMS/CMCHO) <Nicolas.Aretakis1@cms.hhs.gov>
Subject: Infrastructure Change CRQ000000879314 has been scheduled. RE: Use of Waffle.io

Infrastructure Change CRQ000000879314 submitted on your behalf by Shaneka Strahan has now been scheduled for implementation.
Status: Scheduled
Impact: 3-Moderate/Limited
Summary: RE: Use of Waffle.io

**Comment by NAretakis** [comment]
-----Original Message-----
From: CMS IT Service Desk [mailto:CMS_IT_Service_Desk@cms.hhs.gov] 
Sent: Thursday, February 15, 2018 11:30 AM
To: Aretakis, Nicolas J. (CMS/CMCHO) <Nicolas.Aretakis1@cms.hhs.gov>
Subject: Infrastructure Change CRQ000000879314 has been completed. RE: Use of Waffle.io


Infrastructure Change CRQ000000879314 submitted on your behalf by Shaneka Strahan has been completed.
Status: Completed
Impact: 3-Moderate/Limited
Urgency: 3-Medium
Summary: RE: Use of Waffle.io
