### ISSUE TITLE
Draft recruiting email for state pilot participants

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1312]
The email that will be sent out as part of #1311 needs to include enough information so that state participants are informed about the pilot and have clear expectations. 

Some of the pieces of info to consider including are:
- Timeline for the pilot
- Explain the hand-holding process for states with CMS throughout the pilot
- Set expectations with states that it will be a bit more work for them to use the app (exporting their APD, going back and forth with questions, merging changes back into the app, etc)  

### This task is done when...
 - [x] The email is drafted
 - [ ] Nick and Jerome review/approve the content

**Comment by jeromeleecms** [comment]
From our discussion at the working session on 02/26/2019, @CSwartzHMA will work with @jameshupp about preparing this communication.

**Comment by MCorradoHMA** [comment]
James to send draft language to @CSwartzHMA Monday around 2pm

**Comment by MCorradoHMA** [comment]
Hi there! Here's a draft email we came up with...

Hello – As you may know, CMS is working with its federal partner 18F to modernize the HITECH IAPD submission process. The new eAPD will be an online application (app) that helps states submit IAPDs and associated contracts easily and helps CMS analysts review them more efficiently. It is also the goal of the app to support and improve communication between CMS and states by tracking and demonstrating where the IAPD is in the review process.

As part of the development of the eAPD, CMS has conducted numerous usability sessions to get input from states on the design and features of the eAPD. Thanks to those states, the eAPD has been designed to address many of the common issues with the current IAPD submission process—including the creation of budget tables that automatically calculate, elimination/reduction of repetitive information, and ensuring that various sections of the IAPD connect and tie together.

Building on the great work and feedback received to date, CMS is ready to take the next step in the testing process. **CMS is seeking a limited number of states to volunteer to pilot the eAPD by using it to prepare your upcoming IAPD submission to CMS.  We are particularly seeking states whose IAPDs are due for submission on or before INSERT DATE.**

As with states that have previously volunteered to provide feedback, pilot states in this round will have the opportunity to have a direct impact on the changes made to the app before nationwide release.

If you are interested, please contact INSERT at INSERT by INSERT.

Thank you for your time and support as always.

**Comment by lauraponce** [comment]
Tagging in @jameshupp for 👀

**Comment by lauraponce** [comment]
This issue _was_ dependent on #1170 but that is now closed since this issue was able to move forward without it.

**Comment by CSwartzHMA** [comment]
We might want to consider adding language about the pilot focusing on limited capabilities so that we can level set on the type of feedback we want to get during the pilot. We don't want to focus on the final set of capabilities. 

Rather than alluding to a due date, should we ask for states intending to submit an APD in the next month?

Should we also include a list of requested requirements? This would be Chrome users? Preferably those with the ability to convert PDF to Word? 

Would there be a need to outline time commitments and describe feedback expectations?

**Comment by CSwartzHMA** [comment]
Since we want to be able to set clear expectations, we want to finalize the process for merging changes back into the app and incorporate any relevant information into the emails - this might be suggested system requirements, expected time requirements, etc.

**Comment by MCorradoHMA** [comment]
Updated email based on comments/feedback:

Hello – As you may know, CMS is working with its federal partner 18F to modernize the HITECH IAPD submission process. The new eAPD will be an online application (app) that helps states submit IAPDs and associated contracts easily and helps CMS analysts review them more efficiently. It is also the goal of the app to support and improve communication between CMS and states by tracking and demonstrating where the IAPD is in the review process.

As part of the development of the eAPD, CMS has conducted numerous usability sessions to get input from states on the design and features of the eAPD. Thanks to those states, the eAPD has been designed to address many of the common issues with the current IAPD submission process—including the creation of budget tables that automatically calculate, elimination/reduction of repetitive information, and ensuring that various sections of the IAPD connect and tie together.

Building on the great work and feedback received to date, CMS is ready to take the next step in the testing process. CMS is seeking a limited number of states to volunteer to pilot the eAPD by using it to prepare your upcoming IAPD submission to CMS. We are particularly seeking states whose IAPDs are due for submission on or before INSERT DATE. The testing in this phase will be on limited functionality in the eAPD (not the full go-live system).

As with states that have previously volunteered to provide feedback, pilot states in this round will have the opportunity to have a direct impact on the changes made to the app before nationwide release.

If you are interested, please contact INSERT at INSERT by INSERT. We will also hold an interest meeting for states to learn more about eligibility, commitment, and time frames on INSERT. 

Thank you for your time and support as always.

**Comment by MCorradoHMA** [comment]
@jeromeleecms @NAretakis and others...this email I think is pretty much ready to go for your review. Items that need to be decided include:

- picking a date for to host the interest session
- picking a contact person for those that have questions or are interested in signing up
- regarding eligible states, picking a timeframe in which their APD is due (e.g., looking for sites that are submitting APDs in July - Aug (?))

**Comment by jeromeleecms** [comment]
Could we move the "call to action" a little earlier in the email message? I.e. CMS is looking for states to participate in a limited pilot (not prescriptive here, but the actual request is a little buried). The message will likely to be distributed through the existing tester's mailing list, but some folks on that list may not have tested/participated before so the additional background is helpful.

**Comment by MCorradoHMA** [comment]
Sure! Will do. Thanks for the feedback.

**Comment by lauraponce** [comment]
This content looks great! Following @jeromeleecms's feedback, I took what you have and just swapped around the order of the paragraphs to bring that call to action up higher. I also wordsmithed some of the text and marked those up in bold so you can see what's changed. Let me know what feedback y'all have on this!

> Hello – As you may know, CMS is working with its federal partner 18F to modernize the HITECH IAPD **creation and** submission process. The new eAPD will be an online application (app) that helps states submit IAPDs and associated contracts easily and **will** help CMS analysts review them more efficiently. It is also the goal of the app to support and improve communication between CMS and states by tracking and demonstrating where the IAPD is in the review process.
> 
> Building on the great work and feedback received to date, CMS is ready to take the next step in the testing process. **We are seeking four** states to volunteer to pilot the eAPD by using it to prepare your upcoming IAPD submission to CMS. We are particularly seeking states whose IAPDs are due for submission on or before INSERT DATE. The testing in this phase will be on limited functionality in the eAPD (not the full go-live system) **because the design and development is still underway**.
> 
> If you are interested, please contact INSERT at INSERT by INSERT. 
> 
> As part of the development of the eAPD, CMS has conducted numerous usability sessions to get input from states on the design and features of the **app**. Thanks to those states, the eAPD has been designed to address many of the common issues with the current IAPD submission process —including the creation of budget tables that automatically calculate, elimination/reduction of repetitive information, and ensuring that various sections of the IAPD connect and tie together.
> 
> As with states that have previously volunteered to provide feedback, pilot states in this round will have the opportunity to have a direct impact on the changes made to the app before nationwide release.
> 
> We will also hold an interest meeting for states to learn more about eligibility, commitment, and time frames on INSERT. Thank you for your time and support as always.

**Comment by lauraponce** [comment]
@jeromeleecms @NAretakis it doesn't look like we have an answer yet to some of the questions @MCorradoHMA called out (I also added one to the list too 🙂 ), do you have an idea about these? Let me know if it's easier to talk through this on a call since there are a few things here.

1. What date will the interest session take place?
2. Who should be the contact person for those that have questions or are interested in signing up?
3. Regarding eligible states, what is the timeframe for which their APD should be due (e.g., looking for sites that are submitting APDs in July - Aug (?))
4. Who will be sending the email out?

**Comment by NAretakis** [comment]
Possible answers to the above questions, we can hammer these out during a working session.

1. What date will the interest session take place?
 _Next sprint?_
2. Who should be the contact person for those that have questions or are interested in signing up?
 _Perhaps we start using the eAPD mailbox for this? AKA Nick and Jerome?_
3. Regarding eligible states, what is the timeframe for which their APD should be due (e.g., looking for sites that are submitting APDs in July - Aug (?))
_Nick's proposal: Can be submitted as soon as they are ready, but no later than June 1st._
4. Who will be sending the email out? 
_eAPD Mailbox?_

**Comment by lauraponce** [comment]
**Decisions from Monday sync:**
1. Laura to create an issue about interest session and sync with Melissa and Caryn
2. eAPD mailbox
3. States will start using the app June 1, submit by July 1
4. eAPD mailbox

**Other to-dos:**
- Ask about accessibility when recruiting

**Comment by lauraponce** [comment]
Updated version of the recruiting email — the changes include adding the CMS email address, adding some dates, changing some of the phrasing from "CMS" to "we" since it's going to be sent from the CMS email.

> Hello!
> 
> As you may know, we are working with our federal partner, 18F (GSA), to modernize the HITECH IAPD creation and submission process. The new eAPD will be an online application (app) that helps states submit IAPDs and associated contracts easily and will help CMS analysts review them more efficiently. It is also the goal of the app to support and improve communication between CMS and states by tracking and demonstrating where the IAPD is in the review process.
> 
> Building on the great work and feedback received to date, we are ready to take the next step in the testing process. We are seeking four states to volunteer to pilot the eAPD by using it to prepare your upcoming IAPD submission to CMS. We are particularly seeking states whose IAPDs are due for submission on or before July 1. The testing in this phase will be on limited functionality in the eAPD (not the full go-live system) because the design and development is still underway.
> 
> If you are interested, please email CMS-EAPD@cms.hhs.gov by 5/24.
> 
> As part of the development of the eAPD, we have conducted numerous usability sessions to get input from states on the design and features of the app. Thanks to those states, the eAPD has been designed to address many of the common issues with the current IAPD submission process —including the creation of budget tables that automatically calculate, elimination/reduction of repetitive information, and ensuring that various sections of the IAPD connect and tie together.
> 
> As with states that have previously volunteered to provide feedback, pilot states in this round will have the opportunity to have a direct impact on the changes made to the app before nationwide release.
> 
> We will also hold an interest meeting for states to learn more about eligibility, commitment, and timeframes the week of 5/20. Thank you for your time and support as always.
>

**Comment by MCorradoHMA** [comment]
Looks great to me!

**Comment by lauraponce** [comment]
@NAretakis @jeromeleecms is this good to go for closing out?

**Comment by NAretakis** [comment]
Good to go, with the only exception of if we need to shift any of the dates in the body itself. But we can proof that before we send out. Closing unless anyone thinks we need to reopen to address.
