### ISSUE TITLE
Draft confirmation email with instructions for states who have selected for the pilot

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1313]
Once the 4 states have been chosen, they will need to be notified that have been selected and will need additional instructions plus next steps.

This email should include:
- Timeline for when they will be able to log in and when they should submit their APD by
- How they will submit their APD
- Naming convention for the eAPD PDF file with the date (or versioning)
- Establish how they should document bugs, questions, comments
- Let them know there will be some TBD research sessions to collect their feedback 
 
### This task is done when...
 - [ ] The email is drafted
 - [ ] Nick and Jerome review/approve the content

**Comment by jeromeleecms** [comment]
From our discussion at the working session on 02/26/2019, @CSwartzHMA will work with @jameshupp about preparing this communication.

**Comment by lauraponce** [comment]
Draft of the confirmation email:

> Hi NAME,
> 
> We’re excited to have you join us in the eAPD pilot as one of the four state participants!
> 
> **What’s next**
> 
> We will create an account for you and will send over those details along with the URL where you can log into the eAPD application. The estimated timeline for when you’ll be able to log in and start filling in your APD is between 1-3 months, so we expect that you’ll be able to start using the app around July. We’ll be sure to keep you posted with any updates during this timeframe.
> 
> **How the eAPD process will work**
> 
> You’ll use the app to fill in your APD just like you normally would. At any point in time, you can export a PDF copy of the information you’ve entered, but any changes that you need to make should be done through the app. Once you’re ready to submit to CMS for approval, you’ll export the final version of your APD and will email it to your CMS reviewer (you’ll find more detailed instructions about how to do this within the app).
> 
> Please submit your APD by DATE to ensure there is enough time for CMS to respond to you with any questions.
> 
> **Sharing feedback**
> 
> We’ll be scheduling three sessions with you to see how your eAPD experience is going and to collect your feedback. 
> 
> The first session will be for shadowing you while you fill in your APD — once you’re able to log in and get started, we’ll find the time that works best for you to do this with us. The second session will be an interview format where we’ll ask some questions about your experience after you submit your APD to CMS. The third session will be a lightweight follow-up interview after your APD has been approved.
> 
> If you have feedback that you’d like to share asynchronously while it’s still fresh in your mind, please add your thoughts here: https://forms.gle/1QYMduhWNWyUem5F6 — use this form at any time to provide feedback as often as you’d like.
> 
> If you run into any issues, contact NAME at EMAIL. 
> 
> We’ll reach out to you with any updates to the pilot and will be in touch. Thanks again for your participation! 
>

**Comment by lauraponce** [comment]
I'll be editing it in the Google Doc here: https://docs.google.com/document/d/1ktgEMakVf73pMNp3bSHjBlP-lwhFNe3ruAcz4BRGkyo/edit# — feel free to make any comments or suggestions here or in the doc directly

**Comment by MCorradoHMA** [comment]
Is it expected that they already have their IAPD developed and they're just copying the information into the app during the timeframe? Or are they actually developing the IAPD using the app? My concern is that one month may not be enough time for them to develop the IAPD and enter it into the app, given it's a new process. Should/are we planning on selecting for states that have their IAPDs pretty much done by the time the app goes live? #1311

**Comment by lauraponce** [comment]
Draft of the email to send out to states who volunteered but weren't selected:

> Hello!
> 
> Thank you for your interest in the pilot! The participant slots have all been filled and the four states that will be participating have been notified. We selected the states based on the complexity of their APD and their timeline.
>  
> After the pilot is over in the next few months, we’ll be making updates to the application based on the feedback. If you would like to share your thoughts or have any questions, reach out to us at CMS-EAPD@cms.hhs.gov. 
> 
> We will share updates and timelines for the production-ready eAPD application in the near future. Thanks again!

**Comment by lauraponce** [comment]
@MCorradoHMA thanks for raising a flag on this. My understanding is that the states won't necessarily have their APDs developed by then and that they would be doing the bulk of the work once they have their logins to the app. Though, if it's part of their process to have their docs sort of filled out throughout the year or over a longer time period, there might be some copying and pasting (which will be interesting to learn about from the feedback sessions). With that in mind, does one month still feel tight? 

@NAretakis @jeromeleecms any input on this?

**Comment by NAretakis** [comment]
This looks great, ready to close this issue from my perspective, but I'll leave it to @lauraponce to click the button.
