### ISSUE TITLE
Create accounts for each of the states participating in the pilot

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1314]
Once the 4 state pilot participants have been decided (depends on #1311), accounts should be created for each of them.

### This task is done when...
 - [x] An account has been created for each of the states participating in the pilot

**Comment by mgwalker** [comment]
Anyone with admin privileges will be able to create the accounts. Once users are identified and there's a policy for how to get their account information to them.  I'm going to remove the dev label from this one, but feel free to add it back if that's not right!

**Comment by NAretakis** [comment]
Accounts created!
