### ISSUE TITLE
Send account credentials to state participants

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1315]
When we're ready for the pilot to begin, the login credentials for each of the states should be provided to them.

### This task is done when...
 - [x] The login credentials have been sent over to the states (depends on #1314)
 - [x] The states are given the go-ahead to begin using the app

**Comment by MCorradoHMA** [comment]
Contact info for pilot states:

ALASKA
Heidi Lengdorfer | State HIT Coordinator
Office of the Commissioner | Department of Health and Social Services
350 Main Street, Suite 427  | Juneau, AK 99801
Office: 907.465.5808 | Cell: 907.500.2083
Heidi.Lengdorfer@alaska.gov | http://dhss.alaska.gov

DELAWARE
Mary E. Marinari, MPA
Senior Administrator -  Information Systems Unit
Division of Medicaid and Medical Assistance
Biggs Building, Door #2
Herman M. Holloway Sr. Health and Social Services Campus
1901 N. DuPont Highway, New Castle, DE 19720
Office: (302) 255-9548
mary.marinari@delaware.gov


IDAHO
Emily Bennett - Medicaid <Emily.Bennett@dhw.idaho.gov>

FLORIDA
Jamie Bustos <Jaime.Bustos@ahca.myflorida.com>

**Comment by MCorradoHMA** [comment]
Draft email to send with log-in credentials (please review/edit!):

Hello! Thank you so much for participating in the eAPD Builder Pilot. We are providing you with your log-in credentials to the application:

[INSERT CREDENTIAL INFORMATION]

Please note that this log in is unique to you. While you can provide it to others in your state to work in the application, if two people are logged into the app with the same log in work may not be saved properly. If there are others in your state that you anticipate may be working in the app at the same time, please let us know at [INSERT EMAIL] and we'll set up additional accounts.

If you run into any issues, you can reach out to us at CMS-EAPD@cms.hhs.gov.

If you have feedback that you’d like to share asynchronously while it’s still fresh in your mind, please add your thoughts here: https://forms.gle/1QYMduhWNWyUem5F6 — use this form at any time to provide feedback as often as you’d like.

**Comment by MCorradoHMA** [comment]
@NAretakis @lauraponce @CSwartzHMA @jeromeleecms 

Take a look at the draft email...esp the second full paragraph.

**Comment by NAretakis** [comment]
revised, this should work. I'll send this out to the state pilot users.

**Comment by MCorradoHMA** [comment]
OK! Mary Marinari confirmed, she's good to go. @NAretakis

**Comment by NAretakis** [comment]
Account credentials sent!
