### ISSUE TITLE
Test the workflow for merging changes back into the app

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1316]
When states need to make updates to their previously exported APD, they'll need to log back in and merge in the new changes. The process might include converting a PDF to a Word doc, tracking changes, then going back in and making the updates in the app. We should understand what this workflow feels like and how it actually works before having the states go through it.

### This task is done when...
 - [x] The workflow for making changes from app > PDF > Word > app has been tested
 - [x] Any relevant and important steps/findings have been identified (anything worth mentioning to state participants?)

**Comment by jeromeleecms** [comment]
@MCorradoHMA In our user testing while we were at the HIT connect conference, a couple of the states noted that they don't have access to Acrobat Pro, which may limit their ability to convert items from PDF -> Word (other workarounds?). #1374 still needs a synthesis doc, but I can share the raw notes with you if you want to review.

**Comment by CSwartzHMA** [comment]
Research developments: 
After receiving edits or comments from internal review process or CMS Analyst, states may not have two screens, they may be using a small monitor or a paper version of the printed PDF to review comments and edits. Updating in this way can be time consuming and leaves room for edits and comments to be missed.
Could not convert PDF to word when exporting from Chrome. It timed out.
Some tables in PDF display scroll bars and no lines to delineate cells.
Seems like a lot to print. Most I have seen are under 100 pages (sometimes I only get Appendix D).
Button currently says “Save as PDF” – related to an open issue.

**Comment by NAretakis** [comment]
@jeromeleecms does this list look good?

**Comment by NAretakis** [comment]
@MCorradoHMA @CSwartzHMA is this ready to be closed?

**Comment by NAretakis** [comment]
@MCorradoHMA @CSwartzHMA haven't heard anything on this issue lately, is there anything left here to do?

**Comment by NAretakis** [comment]
Per @CSwartzHMA  closing this issue.
