### ISSUE TITLE
In order to feel confident that APD creators have reached the end of the form experience, provide a closing cue

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cms-hitech-apd#1321]
_Carried forward from a comment in https://github.com/18F/cms-hitech-apd/pull/1320 and issue #1318_

Without the final "submit" action, removed for the pilot from issue #1318, we lose a bit of clarity that someone is "done" with the form after the Executive summary, and obvious next steps.

Through design and content, we should create the feeling of done-ness and clear steps for finishing. There are likely multiple ways to do this. 

### This task is done when...
 - [x] The UX for finishing the form is designed
 - [x] The user has clear instructions to follow to submit their APD (addressing in #1256)
 - [x] The team agrees
 - [x] Issues to implement the change have been created if needed

**Comment by NAretakis** [comment]
Move buttons from #1348 to the bottom and this issue can be resolved.

**Comment by jenniferthibault** [comment]
Hold on there speedy! 

Moving buttons from the side to the bottom works if users complete the form starting at the top and ending at the bottom, but I'm not confident that's the ONLY case. I thiiiiink we know that folks jump around a bit, and want to save at multiple points, not just when they're "done".

Here's another idea!
We could Replace the section formerly known as `Certify & Submit` with a more simple section called `Export` (check it out @lauraponce I think I found a scenario for the BIG BUTTON 😄 ) Since the side nav is going to be sticky, folks will be able to get to the export functionality from any other point in the page by going through the side nav. 

![App - 9: Export](https://user-images.githubusercontent.com/11636908/54065506-d8b15400-41ef-11e9-8965-072eeb938b35.png)

It needs some content design here to make sure the instructions are right for this closing stage (ping! @jameshupp )

This would provide the "end cue" as we've defined, and I'd plan on resolving the rest of the "Save" button location problem in #1337 

Thoughts?

**Comment by NAretakis** [comment]
I like this a lot. Clean and consistent approach, that also works with the sticky side nav.

**Comment by jameshupp** [comment]
We just heard in testing that in interstitial step or two between deciding to export and getting a PDF would be nice. We probably can't provide that right away, but this separate Export section gives us enough room to describe the situation effectively. Assigning myself so I can knock out copy for this. This looks fantastic!

**Comment by jameshupp** [comment]
This pattern emerged in yesterday's conversation about implementing the design system across the sections of the app. Everyone seemed onboard with creating this and we have Nick's comment above, so I'm going to check off "team agrees" so I'm going to check this off.

**Comment by jameshupp** [comment]
I've created #1449 to implement the design, so this issue is complete!
