### ISSUE TITLE
Tabletop Exercise for Pilot

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1327]
Once the pilot plan is more clear, we will conduct a tabletop exercise with the team to make sure we have a understanding of how things will flow through the pilot.

### This task is done when...
 - [ ] Walkthrough of the complete workflow from State Selection -> Decision is completed

**Comment by jeromeleecms** [comment]
Monday working session was cancelled due to holiday, so this is scheduled for Thursday, 05/30.

**Comment by jeromeleecms** [comment]
Pilot Related Material: 
- Pilot Research Folder: https://drive.google.com/drive/u/0/folders/1LXBatCRum-PRy8IjvaDVitdP7dhLySmI
- Mural: https://app.mural.co/t/gsa6/m/gsa6/1540576639730/98e9cb36a85619864c28a397648ed67e18defdee
- Feedback Collection Methods: https://docs.google.com/document/d/19ka_nDYbUkpXuaz5FWUYhqpfQ1bV6FDO6w5pX1TcqOM/edit
- Research Planning: https://docs.google.com/document/d/1f3E7EYy1YHzk4dJrXkKUndOqj_R1_raGigE9sGvgjVM/edit#heading=h.2r3braxl72kr
- Pilot Framing Document: https://docs.google.com/document/d/1J4El9GyJ2ceS8V0UR1VPaUaufrWcwlfquu3jzSKBgFA/edit

**Comment by MCorradoHMA** [comment]
@jeromeleecms can you email @CSwartzHMA and I the docs on the google drive? Thanks!!

**Comment by jeromeleecms** [comment]
Tabletop exercise completed! Shared Pilot Framing document + timelines with MeT and MITRE teammates!
