### ISSUE TITLE
Work through the research plan and focus questions

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1328]
Let's build off the draft of the research plan (#1296) for the pilot and add more to it/make updates.

Here's the current version: [Research strategy.pdf](https://github.com/18F/cms-hitech-apd/files/2907518/Research.strategy.pdf)

### This task is done when...
 - [x] Laura + MeT have walked through the research plan
 - [x] MeT shares feedback about the plan
 - [x] Updates/edits are incorporated and details are added

**Comment by lauraponce** [comment]
👋@CSwartzHMA @MCorradoHMA looking at a time for us to chat more about this — would either 12:30-1:30 ET on Thursday or Friday this week work for you?

**Comment by CSwartzHMA** [comment]
Friday works for me.

**Comment by CSwartzHMA** [comment]
Laura, let's go ahead and schedule the meeting for Friday, if that works for you. I can attend and Melissa will join if she is available.

**Comment by lauraponce** [comment]
@CSwartzHMA @MCorradoHMA for this week, would sometime between 1:00-3:00 ET Tuesday or between 3:00-4:30 on Wednesday work for you?

**Comment by CSwartzHMA** [comment]
I can be available between 2 and 3 ET on Tuesday. Unfortunately these other times are already booked for me.

**Comment by lauraponce** [comment]
I just sent the invite for 2-2:50 pm ET tomorrow ✔️

**Comment by lauraponce** [comment]
Latest version based on updates from conversation with @CSwartzHMA: [Research strategy.docx](https://github.com/18F/cms-hitech-apd/files/2932469/Research.strategy.docx)

Next steps: Laura to create 2 issues (one for fed, one for state) to draft interview guides.
