### ISSUE TITLE
Replace buttons with CMS design system components in State Profile Contact & Side nav

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cms-hitech-apd#1329]
_Broken up for implementation from #1269_
____

In order to build out the transition to the CMS design system, add the pieces needed to implement the system’s new components and styling for the first section: https://hitech-apd.app.cloud.gov/apd#apd-state-profile 

### This task is done when:
- [ ] We (AHEM, Heather....) investigate how our system is using buttons 
  - [ ] We use this to decide a strategy:  import the CMS Design System button component or use the Design system CSS
- [ ] The Button component has been added to the codebase
   - [ ]  and the correctly styled variation is used for each instance in the State profile contact section
   - [ ]  and the correctly styled variation is used for each instance in the side navigation

**Comment by hbillings** [comment]
I _think_ we're using a React component to render buttons, which means we could very likely restyle all of the buttons at once. Should we rename this issue accordingly?

**Comment by jenniferthibault** [comment]
We updated this issue description to accurately reflect that question as part of the work :high-five:

**Comment by mgwalker** [comment]
We have a `<Btn>` component, but sometimes we also use `<button>` directly, because who even wants consistency?

**Comment by mgwalker** [comment]
PR #1473 removed one of the buttons from the sidebar, #1467 will remove the other.  The state profile buttons were switched over to the CMS design system in PRs #1397 and #1451
