### ISSUE TITLE
Modify <Section> component to use CMS design system styles with new layout

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cms-hitech-apd#1332]
_Continuation of #1269_
____
To start implementing the style and layout of the new design system, update our `<Section>` component

### This task is done when...
 - [ ] Each section is numbered in the app and in the sidenav. 
  - [ ] The styling matches the mockups below:
	- Section headline is semantically and stylistically h2: `ds-h2`
	- Number has h2 style properties, + `font-weight: normal` `color: base-inverse`
	- Copy is: `ds-text--lead`
 - [ ] Overall layout and interaction matches the [InVision prototype](https://gsa.invisionapp.com/share/BJQNX2KXQVW#/348460956_State_Profile_Contact)

**New:**

![screen shot 2019-02-26 at 11 35 53 pm](https://user-images.githubusercontent.com/11636908/53468024-879ea480-3a26-11e9-9ca0-e5993f575e99.png)

**Current:**

![screen shot 2019-02-26 at 11 51 10 pm](https://user-images.githubusercontent.com/11636908/53468036-938a6680-3a26-11e9-8150-3a0836a90a74.png)

**Comment by hbillings** [comment]
@jenniferthibault I'm noticing the number in the circle doesn't have serifs, but the headline font does use serifs on the numbers. What font should this be?
<img width="441" alt="Screen Shot 2019-03-19 at 4 38 38 PM" src="https://user-images.githubusercontent.com/509309/54640172-83820780-4a65-11e9-8baf-a20ea80341fd.png">

**Comment by jenniferthibault** [comment]
Great flag! That looks like it's because it's a typography class from the old system.

The CMS eAPD prototype used Source Sans Pro (which has the recognizable serifs on `1`, and is what the US Web Design System uses.)

The CMS Design System uses Open Sans for everything (It's not totally clear to me why they'd make this small change to the USWDS styles, and I can't find it in their docs, but they did).

**Comment by jenniferthibault** [comment]
Long story short — everything should be moved over to Open Sans (as the style of the CMS design system)
