### ISSUE TITLE
Align displayed order of instruction content with how it's ordered in an instruction block

### ISSUE THREAD

**Issue by jameshupp** [18F/cms-hitech-apd#1333]
**Expected behavior:** when I create an instruction block in the YAML, the order in which I insert the elements (heading, short, detail, helpText) should reflect the order in which they will display.

**Observed behavior:** the order of the YAML block is unrelated to the displayed order.

**Possible fix:** Code the app to treat `instruction` blocks as a semantically ordered element and display the content from those blocks in the order in which they appear in the YAML.

**Explanation:** This follows in a comment; it's too long to put here.

### This task is done when...
 - [ ] Content and engineering are aligned on the best way to manage these content blocks
 - [ ] Any code changes required to enable someone with the appropriate skills to manage this content are made.

Note that i'm wording the to-do list this way because it's possible others will disagree with me about the outcome here.

**Comment by jameshupp** [comment]
Explanation: I believe this is because the code is interpreting the YAML without assigning any semantic value to the YAML. There is a lot of content where that makes sense, but we now have a specific elemental block, the `instruction`, and I think it's probably better to treat it semantically.

The instruction block is flexible; one can put the elements in any order in there. There is a good reason for this: some instructions have a short directive, followed by a bit of explanation of that directive. It makes sense to order that `short -> detail`. Some of them, on the other hand, have long explanations of generalized requirements, rather than content that further illuminates the instruction. It makes sense to order that `detail -> short`.

When a content manager makes that choice, it makes sense that the content would render in the same order. By divorcing the displayed order from the YAML order, an action that is solely governing content becomes an action that require engineering time.

If all the sections of the app were identical, this would make sense; degrees of freedom lead to entropy. But the sections are all different, so we are already dealing with incongruous display orders. It seems better to empower the content manager instead of making that an engineering job. 

For example, the Standards and Conditions section has YAML that is structured like so:
```
instruction:
    heading: A heading
    detail: A whole lot of content, maybe even multiple paragraphs
    short: Please complete this text box.
```
The logical way to think about this when you look at it is that the text box that follows will come immediately after the `short` instruction. *That would suggest it would render like so:*

### Heading

Here is why this compliance issue matters
Background on requirements and such
What Medicaid is going to do with the information
More detail detail detail detail detail

**Please complete this text box.**
[textbox]


*But the way it actually renders is:*

### Heading

**Please complete this text box.**

Here is why this compliance issue matters
Background on requirements and such
What Medicaid is going to do with the information
More detail detail detail detail detail

[textbox]

**Comment by jeromeleecms** [comment]
Unclear whether or not this is technically feasible. Will revisit.

**Comment by beparticular** [comment]
can close per Laura
