### ISSUE TITLE
Large APDs take time to load

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1339]
The sample APD currently takes ~5 seconds to load while in the office, while a blank APD takes < 1 second. It is not clear why the delay, but it does affect the user experience of the app. 

May be related to the rich text box editor or the network connection or ... ?

### This task is done when...
 - [x] Analysis of the issue has been completed.
 - [x] Decision about any remediation is made.
- [x] Remediation (if needed) is completed.

**Comment by NAretakis** [comment]
After @jeromeleecms confirmed the delay is only 3 seconds. We decided to close this bug, as it is currently at an acceptable level. If additional delays appear, we'll capture a new bug, and fix as necessary.
