### ISSUE TITLE
Add "Certify and Submit" section

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1341]
The "certify and submit" section was removed for layer 1, in #1320.  It eventually needs to be put back.

### This task is done when...
 - [ ] the "certify and submit" section is back and functional

**Comment by mgwalker** [comment]
You can see the original code in the linked PR (#1320).

**Comment by jeromeleecms** [comment]
Let's close this. We will revisit the idea of certify and submit when we get to this part of the electronic submission process.
