### ISSUE TITLE
Identify places where the unique IDs will be used

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1346]
Dependency for #1325

This need for having unique identifiers for the APDs came up in #1143, and the dev issues have already been created. This issue is for figuring out where this unique ID will be used in the eAPD experience and how it will be displayed. 

As per Nick in #1143, the format for the IDs should be:

`[StateCode]-[YYYY-MM-DD]-HITECH-[Submission Name]` with the date as when the document was created in the app.

For example, **TX-2018-09-13-HITECH-APD** (for APDs), **TX-2018-09-13-HITECH-CNT** (for contracts), and **TX-2018-09-13-HITECH-RFP** (for request for procurement)

### This task is done when...
 - [ ] Design has figured out where the ID is used and how it will be displayed
 - [ ] #1325 has been updated with design details

**Comment by lauraponce** [comment]
My initial thought here to limit the effort and scope for the pilot is to _just_ update the titles in the dashboard to follow the new naming convention such as:

![screen shot 2019-03-04 at 1 28 42 pm](https://user-images.githubusercontent.com/21222704/53767083-85ef3980-3e89-11e9-8746-c8ccffae2f07.png)

@jameshupp & @jenniferthibault - can you think of other places where we'd want to use the new nomenclature/IDs for each of the documents?

**Comment by jenniferthibault** [comment]
Spoke with @lauraponce today and we identified one other place we may want to use the ID.

In the Document title field at the top of the form builder, which lets us simplify the area with the state icon next to it:

![Screen Shot 2019-03-08 at 10 41 41 PM](https://user-images.githubusercontent.com/11636908/54065840-0ef0d280-41f4-11e9-96ea-9fdf1a2e269f.png)



We also used the new designs from #1268 to add the ID as info under the APD title instead of replacing it:

![Screen Shot 2019-03-08 at 10 44 10 PM](https://user-images.githubusercontent.com/11636908/54065870-6e4ee280-41f4-11e9-9a99-0f624508c8ee.png)

**Comment by lauraponce** [comment]
@jenniferthibault is it fair to assume the ID design for the dashboard will be covered/included in #1268 as part of that big dashboard design update? If so, it seems like I can just update issue #1325 that @mgwalker is working on to pull in the ID on the top of the form builder, but I wanted to confirm before doing that and closing this one out.

**Comment by jenniferthibault** [comment]
Pulling discussion about this that happened in #1268 into this issue!

[Comment](https://github.com/18F/cms-hitech-apd/issues/1268#issuecomment-472243274) from @lauraponce 
> @mgwalker if the docs are named automatically with `(state abbreviation)-(creation date)-HITECH-APD` is it easy enough to parse that and pull out the state name, date, and doc type so that it looks like `State date APD` in the list (which is easier to read at a glance as regular text than the hyphenated file name/ID)? And then the automated ID would go right below like this as @jenniferthibault mocked up in #1346:

> ![image](https://user-images.githubusercontent.com/21222704/54246799-9b9cd880-44f3-11e9-9774-67f66fe1bf52.png)

[Comment](https://github.com/18F/cms-hitech-apd/issues/1268#issuecomment-472419850) from @mgwalker 
> @lauraponce Good news!  😄  We already have the state ID and years covered as data separate from the name.  For the pilot, since everything is an APD, we can just hard code that one in.  Done!

> @jeromeleecms For the APD year, we have a list of the federal fiscal years that the APD covers.  In the mockup @lauraponce posted above, should we display the year the APD was created (calendar or fiscal?) only the first covered year, all of the covered years (`2018, 2019, 2020` - this is how we have it now and it feels kinda clunky), or a start/end combo (`2018-2020`)?

[Comment](https://github.com/18F/cms-hitech-apd/issues/1268#issuecomment-472440557) from @jeromeleecms 
> @mgwalker The creation date is fine (no need to be describe the FFYs covered).

> Just a note for the pilot @lauraponce - the final name we use now, is based on the the date submitted to CMS. When the state submits the APD to CMS in the pilot, they will receive a different name based on the submission date in our current workflow. Eventually in a future layer, we may have to rename the identifier when it gets submitted through the app to CMS. Not exactly sure about the impact now, but just something to consider...

**Comment by jenniferthibault** [comment]
A follow up question to that discussion: 

I think I understand what the ID is and how it's formatted, but I couldn't quite figure out where we netted out on the name. 

**Name:** 
The human-readable plain language thing that people call the document. This is how people would refer to it in conversation.
- What is the format of this thing?

**ID:** The unique identifier of the document
- [SS]-[YYYY]-[MM]-[DD]-HITECH-APD

I might just be the only one confused, so please correct me! Feels like this is close to done :)

**Comment by lauraponce** [comment]
Thanks for calling that question out specifically because it was definitely buried in the comments. I was going off of what you have in the mockup and assumed it was going to be "State date doc type" which ends up being something like "New York 2018 APD" or "California 2019 Request for Procurement."  This feels like a @jameshupp question!

**Comment by jameshupp** [comment]
I'm not 100% sure I understand what we're parsing here, but I'm going to take a guess and tell me if what I'm saying is irrelevant.

* For the list of APDs on the dashboard, just use the ID. The list will be short enough there's no reason we have to show more than that for readability reasons, and the ID is the best individual way to avoid confusion.
* For the header area within an open APD, you want the ID small and a name big? And that's the question you're asking me: how to format that?

If that's all about right, I agree with Laura. There may be several documents with similar names, but the point where it's confusing is at the dashboard level, not the open doc. So once it's open, those three pieces of information feel like they provide someone reassurance that they're in the right place.

**Comment by lauraponce** [comment]
@jameshupp that makes sense to me! To summarize what I _think_ we're landing on, here's what I am picturing: 

### ID usage on the dashboard:

![Screen Shot 2019-03-19 at 5 03 41 PM](https://user-images.githubusercontent.com/21222704/54649869-25572380-4a69-11e9-8078-03d0860ae79c.png)

### ID usage in the APD builder:

![image](https://user-images.githubusercontent.com/21222704/54649886-343dd600-4a69-11e9-8fb5-150fbcc6896e.png)

Does that feel right to everyone? To me, this seems good enough for layer 1 at this point. And we'll definitely be collecting feedback on the dashboard during the pilot to see if this works for users.

**Comment by jameshupp** [comment]
Looks great to me!

**Comment by lauraponce** [comment]
Moving to implementation with #1388 and #1389!
