### ISSUE TITLE
Draft research questions for the state interviews in the pilot

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1347]
Created from #1328

Build off the [Research Plan](https://docs.google.com/document/d/1f3E7EYy1YHzk4dJrXkKUndOqj_R1_raGigE9sGvgjVM/edit#) focus questions to create research questions for the interviews:

- What were the high points and best parts about the eAPD experience?
- What were the low points? What was unclear or confusing? What’s missing?
- What would they want to change about this experience? What else do they wish was possible or included?
- How did they work through inputting the information (e.g. all at once, with multiple people, etc)? How would they prefer to do this next time?
- How did the internal approval process work with the app? How well/not well did exporting work?
- How does the eAPD experience compare to the existing (previous) APD submission process?
- Accessing the app (e.g. firewalls, did everything appear properly, browser-specific issues, etc)
- How did the back and forth with the CMS reviewer go? How was it receiving comments? What did you do with the feedback / how did you incorporate it if they needed to make updates?

### This task is done when...
 - [x] State interview questions have been drafted
 - [x] Questions have been shared with the team
 - [x] Feedback has been incorporated and protocol is complete

**Comment by lauraponce** [comment]
@CSwartzHMA @MCorradoHMA this is a draft of the research questions for the the user interviews with state participants in the pilot which will take place after they submit their APD — can you take a look and let me know what you think? Did I miss anything? What else should we be asking about? Any and all feedback welcome!

### State user interview protocol:

- Did you run into any issues with accessing the app? 
-- Follow-ups: Were there any firewalls? Were there any browser-specific issues? Did the app load properly?
- Tell me about your eAPD experience. What stood out about it?
- What were the high points and best parts of the experience for you?
- What were the low points?
-- Follow-up: What was unclear or confusing? 
- How does the eAPD experience compare to the previous APD creation and submission process?
-- Follow-ups: Did anything catch you by surprise? Were you able to enter as much information as you can in the paper process? What was difficult to translate?
- Walk me through how you filled out the APD. Did you have a process?
-- Follow-ups: Did you enter all of the information at once? Did you copy and paste? How many times did you log in? Were other people involved? How would you prefer to do this in the future?
- How did your state’s internal approval process work for this APD? 
- Tell me about how exporting the APD to a PDF went for you. How well or not well did that go?
- How did the back and forth with the CMS reviewer go? 
-- Follow-ups: How did you receive comments and/or feedback from your CMS analyst? What did you do with the feedback? How did you incorporate changes back into the app?
- What do you feel is still missing from the app?
-- Follow-ups: What else do you wish was possible or included? What would you change about this experience?

**Comment by lauraponce** [comment]
Google Doc version of the state user interview protocol: https://docs.google.com/document/d/1k7oQJv0tQ7-BnMar1iQFziyd25fkdkoNwBf7dd06pmM/edit?usp=sharing (Melissa and Caryn I know you don't have access, so I'll make sure to post any changes in this issue!)

**Comment by lauraponce** [comment]
@NAretakis @jeromeleecms :eyes: https://docs.google.com/document/d/1k7oQJv0tQ7-BnMar1iQFziyd25fkdkoNwBf7dd06pmM/edit?usp=sharing — let me know if you have feedback!

**Comment by MCorradoHMA** [comment]
I think the questions look great!

Perhaps add something about time...feel free to edit. 
How long did it take you to complete the APD from the time you first entered into the app to the time you were ready to submit? --Follow ups: Was this faster or slower than the prior (paper/email) process? What step took the longest? What steps were faster compared to previous? 

What areas of the eAPD were significantly different to you than the paper APD? --Follow ups: what areas were the most aligned (for example, were easiest/most intuitive to translate from paper to eAPD)? What areas required more review/interpretation? 

Now that you've finished, if you had to give advice to someone just starting out, what would you tell them? What did you wish you knew about the process at the beginning?

**Comment by lauraponce** [comment]
Thanks for the feedback! I incorporated all of these suggestions into the updated protocol here:

### Logistics

- One hour interview
- 15 minute debrief right after the interview is over
- The interviews will take place soon after the state submits their APD (need to be in close communication with them so we can get the interview on the calendar)
- Give state participant heads up that we’ll probably want them to screen share

### Introduction
Thank you for being part of the eAPD pilot! Having you participate and give us feedback about your experience is so important because we are using that to add to and improve the app for the next version that we open up to more states. 

There are a lot of features and functionality we still plan to add and learning about your experience and what you need will help us know what types of things to prioritize. 

Before we start and go into some of our questions, do you have any questions for us? 

### Interview guide

- Tell me about your eAPD experience. What stood out about it? What was your understanding of what the app was going to be able to do?
- What were the high points and best parts of the experience for you?
- What were the low points?
-- Follow-up: What was unclear or confusing? 
- Did you run into any issues with accessing the app? 
-- Follow-ups: Were there any firewalls? Were there any browser-specific issues? Did the app load properly? Any problems logging in or changing your password? Did you have any other technical issues with the app in general?
- How does the eAPD experience compare to the previous APD creation and submission process?
-- Follow-ups: Did anything catch you by surprise? Were you able to enter as much information as you can in the paper process? What was difficult to translate? What areas of the eAPD were significantly different to you than the paper APD? What areas were the most aligned (for example, were the easiest/most intuitive to translate from paper to eAPD)? What areas required more review/interpretation?
- Walk me through how you filled out the APD. Did you have a process?
-- Follow-ups: Did you enter all of the information at once? Did you copy and paste? How many times did you log in? Were other people involved? How would you prefer to do this in the future? How long did it take you to complete the APD from the time you first entered into the app to the time you were ready to submit?
- How did your state’s internal approval process work for this APD? 
- Tell me about how exporting the APD to a PDF went for you. How well or not well did that go?
- How did the back and forth with the CMS reviewer go? 
-- Follow-ups: How did you receive comments and/or feedback from your CMS analyst? What did you do with the feedback? How did you incorporate changes back into the app?
- What do you feel is still missing from the app?
-- Follow-ups: What else do you wish was possible or included? What would you change about this experience? 
- Now that you've finished if you had to give advice to someone just starting out, what would you tell them? What did you wish you knew about the process at the beginning?

### Additional feedback

- [Follow up on anything from the interview]
- As we continue working on this APD submission experience, we will make many changes to the design. What is one thing that we should not change?
- What is one thing we definitely should change?

### Wrap up

- Thank you so much for your help!
- Are you interested in continuing to provide feedback and participate in testing?
- If we know, tell them what to expect next.
