### ISSUE TITLE
Remove helptext and reminders from print view

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1349]
Remove helptext and reminders from print view because they add a lot of unnecessary text that aren't useful when reviewing an APD.

From #1160

### This task is done when...
 - [ ] helptext and reminders are hidden in print view

**Comment by mgwalker** [comment]
Reminders became `helpText` in the new `Instruction` content structure (model?).  Did the old `helpText` become `detail`?  Should `detail` be hidden in print view @jameshupp?  What about `short`?  The short version of this question is, which pieces of an instruction should be shown in print view?

**Comment by jameshupp** [comment]
I think you've just shown us some versions of this (outside GH) so apologies if it's late to this, but I _think_ we're good to remove all three `detail` `short` and `helpText`. As a note for future testing to @lauraponce this is something to ask federal users, not state ones. I suspect it'll matter more for reviewing than for creation.

**Comment by mgwalker** [comment]
#1370 hides the help text in print.  There is no "reminder" text anymore, so I'm not sure what else this issue title is referring to.  But there's still the question of `detail` and `short`, which James says above we can probably remove?

Tagging @CSwartzHMA as well to make this issue easier to find now that the other is merged. 😄
