### ISSUE TITLE
Define common expense categories and subcategories

### ISSUE THREAD

**Issue by nicoleslaw** [18F/cms-hitech-apd#135]
Formalize the top categories of expenses, such as:

- Computers, Software, or Hardware
- Software Licenses
- Office Supplies
- Business Travel
- Training
- Outreach
- Other Miscellaneous Expenses
- Procurements or Acquisitions

Relates to #96 

Note: We have the assumption we'll make it possible for states to add their own.

**Comment by NAretakis** [comment]
Added my comments, to the document. It seems like it has everything that we see.

**Comment by nicoleslaw** [comment]
@brendansudol @mgwalker Adding these expense categories to the content exploration, but the doc is here for future reference: https://docs.google.com/document/d/16PmhnjWtS_bU4lcJ-4QUcB-1_X07tNKjEmOtlcCKEUI/edit#heading=h.li8jq4pcr4wi
