### ISSUE TITLE
Draft research questions for federal users in the pilot

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1350]
Created from #1328

Build off the [Research Plan](https://docs.google.com/document/d/1f3E7EYy1YHzk4dJrXkKUndOqj_R1_raGigE9sGvgjVM/edit#heading=h.vft2r9ew7tyc) focus questions to create research questions for the interviews:

- What works well with the layout of the APD sections from a reviewer perspective?
- What doesn’t work well with the current layout for the APD PDF as a reviewer?
- What is there to consider from the reviewers’ workflow for the following iterations of the app? What else should be included as part of this eAPD experience?
- How does the reviewing the eAPD generated PDF compare to the existing (previous) APD review process?
- How was the back and forth questions with states about their eAPD submission? What process did they follow for responding with questions?

### This task is done when...
 - [x] State interview questions have been drafted
 - [x] Questions have been shared with the team
 - [x] Feedback has been incorporated and protocol is complete

**Comment by lauraponce** [comment]
@CSwartzHMA @MCorradoHMA this is a draft of the research questions for the user interviews with **federal** participants in the pilot which will take place after they review the APD (in PDF format). Let me know what feedback you have!

- Tell me about your review experience. What stood out about it?
- As a reviewer, what works well with the layout of the APD sections?
- What doesn’t work well for you with the current layout for the APD PDF?
-- Follow-up: What was unclear or confusing? 
- How does reviewing the eAPD-generated PDF compare to the previous APD review process?
-- Follow-up: Did anything catch you by surprise?
- Walk me through how you reviewed the APD. Did you have a process?
-- Follow-ups: Did you review the entire document in one sitting? Did you use any other documents or materials? Were other people involved? How would you prefer to do this in the future?
- How did the back and forth with the state go? 
-- Follow-ups: How did you send comments and/or feedback back to the state? What did you expect to happen next after you reached out to the state?
- What is there to consider from your workflow for the following iterations of the app? 
-- Follow-ups: What else should be included as part of this eAPD experience? What would you change about this experience?

**Comment by lauraponce** [comment]
Google Doc version of the federal user interview protocol: https://docs.google.com/document/d/1GlB4DEegOflA3h9E9FkeXb0nWzlkYVWlaWpNqXLfoio/edit?usp=sharing

**Comment by lauraponce** [comment]
@NAretakis @jeromeleecms :eyes: https://docs.google.com/document/d/1GlB4DEegOflA3h9E9FkeXb0nWzlkYVWlaWpNqXLfoio/edit?usp=sharing — let me know if you have feedback!

**Comment by MCorradoHMA** [comment]
I like it! I think I'd add the same question regarding time...[nick/jerome weigh in on if this is the right timeframe]

How long did the process take from submission to approval? Was it faster or slower than your typical (paper/email) review process? In the future, once you're familiar with the app, do you anticipate it will be faster or slower than the paper/email review process?

Do you think your experience with this process with this particular state is representative of most states you work with? How do you think this process would translate to a more challenging state? What areas do you think will be the most challenging?

**Comment by MCorradoHMA** [comment]
by right timeframe I mean "submission to approval" :)

**Comment by lauraponce** [comment]
Great additions, Melissa. I integrated those into the protocol here:

### Logistics
- One hour interview
- 15 minute debrief right after the interview is over
- The interviews will take place soon after the CMS analyst reviews the state’s APD via PDF

### Introduction
Thank you for being part of the eAPD pilot! Having you participate and give us feedback about your experience is so important because we are using that to add to and improve the app for the next version that we open up to more states and CMS analysts. 

There are a lot of features and functionality we still plan to add, especially around the federal user experience, and learning about what you need will help us know what types of things we should prioritize. 

Before we start and go into some of our questions, do you have any questions for us? 

### Questions

- Tell me about your review experience. What stood out about it?
- As a reviewer, what works well with the layout of the APD sections?
- What doesn’t work well for you with the current layout for the APD PDF?
-- Follow-up: What was unclear or confusing? 
- How does reviewing the eAPD-generated PDF compare to the previous APD review process?
-- Follow-ups: Did anything catch you by surprise? Did it alleviate any of your existing pain points during the APD review? Was it faster or slower than your typical (paper/email) review process? In the future, once you're familiar with the app, do you anticipate it will be faster or slower than the paper/email review process?
- Tell me about how you reviewed and assessed the tables. 
-- Follow-ups: Do you trust the calculations? Did you compare them against anything?
- Walk me through how you reviewed the APD. Did you have a process?
-- Follow-ups: Did you print it out or use a screen? Do you have a preference for printing vs screen? Did you review the entire document in one sitting? Did you use any other documents or materials? Were other people involved? How would you prefer to do this in the future? How long did the process take from submission to approval? 
- Do you think your experience with this process with this particular state is representative of most states you work with? 
-- Follow-ups: How do you think this process would translate to a more challenging state? What areas do you think will be the most challenging?
- How did the back and forth with the state go? 
-- Follow-ups: How did you send comments and/or feedback back to the state? What did you expect to happen next after you reached out to the state?
- What is there to consider from your workflow for the following iterations of the app? 
-- Follow-ups: What else should be included as part of this eAPD experience? What would you change about this experience?

### Additional feedback

- [Follow up on anything from the interview]
- As we continue working on this APD submission experience, we will make many changes to the design. What is one thing that we should not change?
- What is one thing we definitely should change?

### Wrap up

- Thank you so much for your help!
- Are you interested in continuing to provide feedback and participate in testing?
- Is there anyone else who was involved in your review process that you think would be helpful for us to talk to next?
