### ISSUE TITLE
Design print view of budget summary table

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1363]
We've approached print-friendliness by breaking fiscal years out into their own tables for most budgetary tables. The final print summary, however, is not quite so cut-and-dried. 

### This task is done when...
 - [ ] We understand what users need from the final summary print view
 - [ ] We have a design ready to implement

**Comment by lauraponce** [comment]
Closing out in favor of #1160 since this work is captured as part of 1160.
