### ISSUE TITLE
Total Cost by Activity at the Activity Level

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1364]
After talking with @hbillings about how to break up the budget tables in #1358, I realized that there is no consolidated activity total at the activity level (though each activity is summarized in the Executive Summary section). From a reviewer perspective, it would be nice to see the total cost at the activity level without jumping down to the executive summary back and forth, so the review of an activity can be a self contained. 

### This task is done when...
 - [ ] A decision about adding this into the existing app has been made
 - [ ] Appropriate issues have been spun up (if needed) with Design/Dev/Product input.

**Comment by NAretakis** [comment]
We do include a total FFP at the activity level, within the cost allocation section. Might be an easy lift to put this somewhere more obvious?

![image.png](https://images.zenhubusercontent.com/5c536083d11206601037eb29/a02dc554-557e-4345-b321-d6577ed231d1)

**Comment by jeromeleecms** [comment]
Yup --  this issue is about total cost of activity (not just the FFP). The cost allocation piece is fine where it is, but having a consolidated look at total cost of the activity in a more obvious place is what I'm looking for here.

Really obvious place (similar to the pattern in the personnel section), but defer to the design team about how/where to ACTUALLY put it if this is deemed useful/feasible...

![image](https://user-images.githubusercontent.com/34279968/54835303-12b63780-4c7f-11e9-960e-e30189b69c11.png)

Part of me likes it here, because as a reviewer, I would be able to see right away that the cost of this activity is X, some cost allocation is going on, and with the cost, it could be a potentially high risk project.

Just seeing the FFP could deflate the understanding of the total cost...

**Comment by mgwalker** [comment]
Covered in one way by #2074
