### ISSUE TITLE
Design top navigation info architecture and style it

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cms-hitech-apd#1366]
_Split out from #1268_

So that users have a complete navigation experience in the APD builder at the pilot stage, we should intentionally define the architecture of the nav, and style it to match the CMS design system.

Currently, the top nav has been growing ad-hoc, one piece at a time. It feels like it would be helpful to look at the whole experience as defined in the pilot, and design an info architecture that reflects that.

It's possible that everything we currently have is exactly right, but in case it's not, I split this issue out to keep from blocking #1268 

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/d882cf9b-df89-4a34-894d-a8dd60f93f75)

![Screen Shot 2019-03-08 at 8 03 38 PM](https://user-images.githubusercontent.com/11636908/54063838-4a33d700-41dd-11e9-8d66-a4acd9899e8c.png)

Drafting plans for how this scales would be nice to have, but probably not required for pilot. It would be pretty normal for a nav to change form later as new functionality is added that changes the site's capabilities.

### This task is done when...
 - [x] Define site nav items, and how many layers there are (is it one-level, or more? Should we group or bundle related navigation items in some way?) (Info architecture = content + UX?)
 - [x] Select appropriate labels (content design)
 - [x] Select fitting interaction component to fit the info model (look to CMS Design System and USWDS)
- [x] Style it to match CMS Design system styles, 
  - [x] Define default, active, focus, hover states
- [x] Make implementation issues

**Comment by jeromeleecms** [comment]
Two different outputs, @austinhernandez @jameshupp to decide how to split when they tackle this.

**Comment by austinhernandez** [comment]
After a dev + design meeting we decided on exploring the following header:

![Header](https://user-images.githubusercontent.com/23194720/55653706-5780b900-57bd-11e9-9c8e-32029498ca4f.png)

![Header Hover](https://user-images.githubusercontent.com/23194720/55653705-5780b900-57bd-11e9-9df1-56a03037e8ee.png)

Notes: 

- The rationale for the header is the name or email will indicate system status: "You are logged in as `xxxx xxxx` and doing things on that account. Should you need to make changes to the profile or log out it is on this account."
  - Not sure if the `xxxx xxxx` will be the email address or user name, the goal is just to let a user know that's the account changes are being made under in the case of a shared computer or multiple log ins. 
  - Information will pull from information input on the `manage account` page
- The "state dashboard" button is now in the location of a "home" link or logo. It takes you back to the "start page" whether thats the APD builder / APD list screen or the manage users screen for the admin. 
  - @jameshupp still working on content. 
  - There is an arrow back button to indicate you are a one level down from the homepage.
- There are no horizontal header interactions on the current design system, [only vertical](https://design.cms.gov/components/vertical-nav/) so I am using [the interaction styles from USWDS V2 for horizontal (top) nav](
 https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/release-2.0/components/preview/header--basic.html) also [here](https://components.designsystem.digital.gov/components/detail/header--default.html)
- Icons on [Font Awesome](https://fontawesome.com/icons/sign-out-alt?style=solid)
- Background color for the header is `primary darkest`

**Comment by jameshupp** [comment]
The reason for the language in the upper left to stay away from `dashboard` is right now it's just a list of APDs plus a `Create new` button. So `ST APD Home` says three things:

State abbreviation: This makes clear that it's not every APD that exists, nor only APDs this particular user is involved in. It's all of them for the state
APD: It's singular/plural agnostic when used like an adjective. And it's clear that it's not everything related to Medicaid in that state; it's the APDs only.
Home: it is something of a homepage and there will eventually be more information there, but most importantly it's a small indicator that it's something other than this page, which `NY APD` or `NY APDs` on its own might not convey.

On the right, I think the email address is better than the name. Names can have overlaps or change or have fields that don't quite work right for a given individual, and there's not that much need to get extra personal here. Email address is unique, unless there are offices that would try to do this with a single shared account.

**Comment by jameshupp** [comment]
I think everything on this issue except creating an implementation issue is done, but since @austinhernandez ported all the cool information over to (Seth, [APD's hottest issue](https://i.imgur.com/fhAIbLB.gif) is) #1308 I'm going to close this one out.

**Comment by jameshupp** [comment]
Sorry, I just realized this is _not_ reflected in #1308. Sorry for my confusion.
