### ISSUE TITLE
Cognitive walkthrough with HITECH team

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#137]
Let's walk through the first pass of the design with the HITECH team and get feedback from them.

### This task is done when...
 - [x] We've decided what to share with the team
 - [x] We've presented to the HITECH team
 - [x] We've captured the feedback from the HITECH team and documented it
-  [x] #231

**Comment by NAretakis** [comment]
Jerome and I shared the walk of the app and github information. We'll create a new issue when we need specific feedback on the federal review portion of the app.
