### ISSUE TITLE
HIT Connect: Create multiple exported versions of the APD in PDF form for Federal reviewers 

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1373]
Dev (@mgwalker?) will prepare different versions of the APD in PDF form so we can test with our Federal reviewers. The exported PDF will have various amount of help text to see what is enough, too much, etc. 

### This task is done when...
 - [ ] Different versions of the PDF have been prepared and are ready for review

**Comment by mgwalker** [comment]
We should define what's included in each version of the PDF!  I know #1349 refers to "helptext and reminders," which I think translate to "long detail and help text" in the new content system (is that the right term?), but are there other variations?

- with full set of instructions (heading, short text, detailed text, and help text)
- with just instructions (heading, short text, detailed text)
- with minimal instructions (heading, short text)

**Comment by jeromeleecms** [comment]
@mgwalker any objections to closing this? We have the  different PDF's and based on a Slack conversation with Laura/James, it seems like we will just cut what we think (hypothesis) we need to and test it in the pilot.

**Comment by mgwalker** [comment]
Works for me

**Comment by jeromeleecms** [comment]
Excellent - Closed per notes above.
