### ISSUE TITLE
Plan in-person research for HIT conference

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1374]
Before heading into HIT Connect next week, let's identify the research questions we hope to answer and write up a plan.

### This task is done when...
 - [x] Research focus has been identified
 - [x] Main research questions are written
 - [x] State research plan is drafted / shared out 
 - [x] Federal research plan is drafted / shared out
 - [x] Next steps are called out and issues have been created

➡️[Main research folder](https://drive.google.com/drive/u/0/folders/1aK8fVxYap7u1pWWHRsd0BxEOpJ59tTge)

**Comment by lauraponce** [comment]
Research protocols and materials are all in this folder: https://drive.google.com/drive/u/0/folders/1aK8fVxYap7u1pWWHRsd0BxEOpJ59tTge

**Comment by lauraponce** [comment]
@NAretakis @jeromeleecms here's the protocol for the state testing: https://docs.google.com/document/d/1z4BzXu9kjHqncndZX-1goIGC3EvhamHL_NRtAtJGTy8/edit?usp=sharing — let me know if you have feedback and/or feel free to make any edits!

**Comment by lauraponce** [comment]
@NAretakis @jeromeleecms if you run into any other CMS analysts while you're there, here is the [short] protocol for them about the reviewer experience of the PDF version of the state's APD: https://docs.google.com/document/d/1e4-svouy2rg5wfmmZMQEX47L2aNSFJQupDWAw3vux-g/edit# 

The one thing I haven't linked to is the PDF of the state submission because that example APD has disappeared from my account. (I'll check in with Greg in the morning about that!)

**Comment by NAretakis** [comment]
I'm going to try to spin up a synthesis doc for us today, and that should give us next steps.

**Comment by NAretakis** [comment]
Synthesis doc created, @lauraponce . Should we use today's time to spin up any resulting issues?

https://docs.google.com/document/d/1qZ0SeFRGEAubFOj4KACMOKjgktk-LBwy8V3RB1qPSxc/edit#

**Comment by NAretakis** [comment]
Issues have been created and prioritized. Closing this out!
