### ISSUE TITLE
Run usability tests on first draft submission experience

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#138]
In parallel with the in depth user research and content modeling work, we'll also do some quick usability testing on the initial prototype.

### This task is done when...
 - [x] Appropriate participants are identified
 - [x] Participants are scheduled
 - [x] Usability sessions are run
 - [x] Findings are synthesized and shared with the team

**Comment by nkkl** [comment]
@nicoleslaw @lauraponce would love some input from y'all about which states it would be most helpful to test with.

**Comment by nicoleslaw** [comment]
A few suggestions: NY, OH, MI, and AK. We are talking to AK today, so we can confirm if they're interested in future studies.

**Comment by nkkl** [comment]
@NAretakis @jeromeleecms let's try to get emails out to NY, MI, AK, FL, DC, and IA today.

[You can use the email template in Drive](https://docs.google.com/document/d/1QlHnm_-TtXbr0HsDhLZIEub-8_CbRe8AjMxWRme48RE/edit#heading=h.ty83bl4ret6w). If you CC me on the emails, I can take over scheduling once they reply back to us. We may need you to help us set up WebEx rooms if they can't use Hangouts or Zoom, though.

**Comment by NAretakis** [comment]
Emailed participants, and @nkkl and I are scheduling.

**Comment by nkkl** [comment]
We have four participants scheduled! 🎉

**Comment by nkkl** [comment]
[Lightweight research synthesis is done](https://docs.google.com/document/d/1QMobLtJ3iRC6PjXUHJKf7xS0guJHzcSxCWgvLr6Pyrk/edit#heading=h.was5739jjjo7)!
