### ISSUE TITLE
Build out template that other pages inherit from

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1384]
When there are new components to be added (for example, the footer as part of the dashboard in #1378) the components are only built into that one page and aren't shared across _all_ of the pages. 

In order to make the dev process easier and more efficient, we need to have a template that pages such as the Admin page and Login page, can inherit from. 

### This task is done when...
 - [ ] Template has been developed and pages can inherit from it

**Comment by jeromeleecms** [comment]
Closing this as we are piece mealing the solution. The "wrapper" can host this.
