### ISSUE TITLE
Implement replacement of typography system - use CMS Design System styles

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cms-hitech-apd#1385]
The prototype site used Source Sans Pro, but the CMS Design System uses Open Sans universally.

We should replace the font family universally, and start tackling how to remove the old prototype's atomic styling in favor of CMS Design System classes.

Describe the task here...

### This task is done when...
 - [x] Source Sans Pro has been smited from the code base

cc @hbillings who can probably get more specific :)

**Comment by hbillings** [comment]
SMITE IT, SMITE IT ALL

We'll need to remove classes that set the font face to the font we're no longer using. We'll also need to make sure that changing the font face doesn't inadvertently change some sort of spacing, etc.

**Comment by mgwalker** [comment]
Is this one finished by #1612, or are there a few more places that still need attention?
