### ISSUE TITLE
Implement password policy and write documentation

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1387]
Per issue #1307, this issue is to implement the password policy decided upon from #1307. Additionally, we'll need to write up documentation on our policy.

### This task is done when...
 - [ ] password policy implemented
 - [x] password documentation created in the wiki

**Comment by mgwalker** [comment]
Wiki: https://github.com/18F/cms-hitech-apd/wiki/Password-policy

Not sure what the implementation checkbox refers to.  Is it about implementing it in code?
