### ISSUE TITLE
Define statuses for activity milestones

### ISSUE THREAD

**Issue by nicoleslaw** [18F/cms-hitech-apd#139]
We need to define an initial set of statuses states can choose for milestones. This is currently part of section 2 under the project schedule. Ex:

- Not started
- Planning
- Ongoing
- In progress -- do we need both of these? states seem to say both...
- Complete

Somewhat related to #96

**Comment by jeromeleecms** [comment]
Maybe:
- Not started
- In Progress
- Deferred or Suspended (just in case the milestone was stalled?)
- Complete

Maybe semantics/personal interpretation, "In Progress" means something that has a start, middle and end. "Ongoing" means that it is perpetual with no end. HITECH ends in 2021, so "In Progress" seems appropriate!

**Comment by nicoleslaw** [comment]
Sounds great! I will update this section of the prototype and close this out.
