### ISSUE TITLE
Get GDIT to do AWS things

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1390]
This issue is for us to actually track the items that are blocked by GDIT, while we wait for things to happen. @mgwalker if we just need to spin up Jira tickets, let me know and I can help with that. If we're just waiting on their response, and haven't heard anything, also let me know, and I can escalate. 

This issue is done when:

- [x] sub-domains are created and pointed to our app
- [x] credentials are requested and received
- [x] certificates are requested and received
- [x] CI permissions are setup

**Comment by NAretakis** [comment]
JIRA ticket created and nudged.

https://jira.cms.gov/browse/CMSAWSOPS-28326

**Comment by mgwalker** [comment]
Ticket for getting AWS access key info, necessary for #1013

https://jira.cms.gov/browse/CMSAWSOPS-29125

**Comment by mgwalker** [comment]
As soon as the subdomains are setup, we'll also need SSL certificates.  Since we don't control the domains' DNS, we can't get the certificates ourselves.  (There is a way we could get Let's Encrypt certificates without having technical control of the domain DNS, but it's a manual hack and we'd have to do it again every 60 days.)

**Comment by NAretakis** [comment]
I'm sensing a subsequent Jira request to get SSL certs.

**Comment by NAretakis** [comment]
Access key ticket: https://jira.cms.gov/browse/CMSAWSOPS-29125

**Comment by NAretakis** [comment]
subdomains created!
AWS access keys received!

But a few remaining permissions/credential things to figure out. Working on this with Greg.

**Comment by jeromeleecms** [comment]
Will continue to track certificate acquisition here... JIRA ticket incoming.

**Comment by mgwalker** [comment]
Ticket for certificates: https://jira.cms.gov/browse/CMSAWSOPS-29755

**Comment by mgwalker** [comment]
Ticket for CI/CD permissions for deploying backend: https://jira.cms.gov/browse/CMSAWSOPS-29959

**Comment by NAretakis** [comment]
CI/CD permissions appear to be done. And certs are now ready as well. @mgwalker the Jira issue has been assigned back to you to complete the certs.

**Comment by NAretakis** [comment]
@mgwalker did we do all of the things?

**Comment by mgwalker** [comment]
The things are done!  🙌

**Comment by NAretakis** [comment]
woot woot!
