### ISSUE TITLE
Update "change password" behavior

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1396]
As originally discussed in [Jen's comments on #1274](https://github.com/18F/cms-hitech-apd/issues/1274#issuecomment-475223198), we need to change the way the "change password" piece of the "Modify Account" form works.

##### Default
Using [fa-lock-solid](https://fontawesome.com/icons/lock?style=solid)
![screenshot of password section in default mode](https://user-images.githubusercontent.com/11636908/54754303-8ee64780-4bb9-11e9-8c80-024e8d3afbcf.png)

##### Edit mode
Using [fa-unlock-solid]()
![screenshot of password section in edit mode](https://user-images.githubusercontent.com/11636908/54754309-93126500-4bb9-11e9-9021-ed5ff79acd5b.png)

### This task is done when...
 - [ ] the Modify Account form is updated to behave as described

**Comment by NAretakis** [comment]
Pretty sure this is done, as I saw the PR go in. Keep me honest @mgwalker

**Comment by mgwalker** [comment]
Yes!  I guess Zenhub doesn't automatically close issues when associated PRs get merged.  😬
