### ISSUE TITLE
Practical GitHub "training"

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#14]
- Branches
- Issues
- Commenting
- Pull requests
- Merges
- Project boards
- Our workflow

**Comment by brendansudol** [comment]
I think this can take the form of a meeting over the next week or so where we walk through an actual PR across its lifecycle -- once there's a good archetypal example, i can schedule

**Comment by nkkl** [comment]
Is this done? Can we close it? :)

**Comment by mgwalker** [comment]
Rescheduled for today

**Comment by jeromeleecms** [comment]
I'm good with closing this, unless @NicolasAretakisCMS wants a follow-up(?).
