### ISSUE TITLE
Add "recover password" link to login page

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1401]
In #1376, there's a small footer below the password field that allows users to email CMS to reset their password. We don't have that email address yet, so we're waiting to add the footer until we do.

Also, we should remove the cancel button on the login page. It does not appear in the original mock-ups and does not route the user anywhere.

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/468581aa-1046-44d0-b3a6-e04916baad68)

Blocked by #1400.

### This task is done when...
 - [ ] the card footer element is implemented
 - [ ] users can email CMS from the email in the footer
- [ ] Cancel button is removed from the login page

**Comment by jeromeleecms** [comment]
@heather / @mgwalker  Please use this email address: CMS-EAPD@cms.hhs.gov for the password recovery link. The email was created, but we may not be able to test it fully until 04/12.
