### ISSUE TITLE
"What problem are you trying to solve?" - Where does it fit in the app help text

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1407]
This came up from leadership feedback and from user testing, we should be able to answer the question "What problem are you trying to solve?" within the activities or elsewhere.

We should also include "How much does this cost?" Not just limited to the fiscal year request.

### This task is done when...
 - [ ] Content has identified a location to include this (help text or otherwise)
 - [ ] Product concurs
- [ ] Content has been loaded into the app

**Comment by quarterback** [comment]
Closing this issue in favor of #1819. Similar questions. Outcomes should overlap.
