### ISSUE TITLE
Activity Name has disappeared from the Activity Section accordion

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1410]
In previous versions of the app, the name of the activity appeared next to the activity number in the APD builder. This is no longer the case and per @mgwalker may have been introduced when the name-building logic was moved for performance reasons. 

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/f57ec7f9-6185-45f1-8a00-0cb047d04ad4)

The sticky side bar will help some navigation around this, but we should decide if this needs to go back in and then implement/not implement.

### This task is done when...
 - [ ] Conscious decision is reached about whether or not we should re-enable this functionality. Will need some design/content input here.
 - [ ] Issue is resolved either through dev implementation or no action is needed.

**Comment by mgwalker** [comment]
I think in this case, we don't necessarily need design to weigh in.  Since we already know it’s a bug from the Slack convo, the fix is to bring things back in line with the intended design.  I can confirm that this change happened solely in dev, by accident.

**Comment by nkkl** [comment]
Yup, makes sense to me! @jeromeleecms that first checkbox is a PM task, with input from design, so that's an action item for you. 😉

**Comment by jeromeleecms** [comment]
Yup - PM task! I just wanted to double check with design to make sure the new non-accordion world didn't affect this request (i.e. no need to waste time on re-storing a functionality if the removal of accordions obsoletes this need).

Thanks, all! 👍
