### ISSUE TITLE
Button fonts are appearing blurry

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1414]
The fonts inside the buttons are appearing as blurry. The default font weight for this from the [design system](https://design.cms.gov/components/button/) is 700 which renders like this:

![Screen Shot 2019-04-02 at 2 39 10 PM](https://user-images.githubusercontent.com/21222704/55438780-72ea8a80-5557-11e9-9f8e-fcbdc43ce921.png)

Is there something else happening here or would it be clearer/easier to read if we override this 700 and change it to 500 which renders like this?:

![Screen Shot 2019-04-02 at 2 40 48 PM](https://user-images.githubusercontent.com/21222704/55438774-6fef9a00-5557-11e9-917b-b49ed3d0ced1.png)

### This task is done when...
 - [x] Fonts in the buttons are no longer blurry

**Comment by NAretakis** [comment]
Fixed!
