### ISSUE TITLE
Review Exported PDF for Readability / Clarity

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1418]
#1160 streamlines the export of the PDF, but in the review of #1394, it may pull out too much (i.e. no information was provided in the APD about what the content of the next text box was).  Once #1160 is completed, we should review a final exported PDF to verify that a reviewer (state or federal) would know what each field is meant to describe.

This is not a review of inputted data, but to review that each field has an associated header/explanation for what should be in that field.

### This task is done when...
 - [ ] Multiple folks have reviewed the exported PDF for potential clarity errors
 - [ ] Product approves the PDF

**Comment by NAretakis** [comment]
We've merged this issue into #1418. Closing this issue.
