### ISSUE TITLE
Admin Users should be routed to the admin dashboard when logging in

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1420]
As part of the ATO requirements, Admin users must have separate accounts. After admin users have logged in, they should be routed to the admin dashboard that was described in #1273. Non-admin users should not be allowed to access the dashboard.

### This task is done when...
 - [ ] Upon logging in, Admin users will be routed to the Admin Dashboard where they can do admin-y related actions
- [ ] Non-Admin users who attempt to access the admin screens will be re-routed or given a permission denied notification
 - [ ] Someone else has looked at the code

**Comment by mgwalker** [comment]
The admin forms `CreateAccount` and `EditAccount` will need to be updated so that their cancel buttons go to the proper admin dashboard route as well, whatever that ends up being.

Slack convo: https://gsa-tts.slack.com/archives/C8E5EJK9V/p1554476353152200
