### ISSUE TITLE
All Team members have established non admin accounts

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1421]
Currently, all team members with person specific accounts are admins within the eAPD. Once #1420 is completed, admin accounts will be routed to the admin dashboard instead of the main page. 

To help test the admin experience, all team members will need to setup their own non-admin accounts (the `state coordinator` role is a good choice).

Choose your own state if you don't want to lose your in progress APDs. Make sure you select a user authentication role when you are steeling this up.

### This task is done when...
 - [x] Jerome has set up a non-admin account (California)
 - [x] Nick has set up a non-admin account (Colorado)
 - [x] Nikki has set up a non-admin account (Nevada)
 - [x] James has set up a non-admin account (New Jersey)
 - [x] Laura  has set up a non-admin account (Washington)
 - [x] Austin has set up a non-admin account (New York)
- [x] Heather has set up a non-admin account (Utah)
- [x] Greg has set up a non-admin account (Missouri)
- [x] MeT has set up a non-admin accounts(s) (Caryn - Virginia)

**Comment by jeromeleecms** [comment]
Updated the checklist due to site reset.

**Comment by CSwartzHMA** [comment]
Caryn has created a MeT account for VA.

**Comment by jeromeleecms** [comment]
This is done!
