### ISSUE TITLE
Not all territories have images of their location.

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1423]
See the screenshot below. 

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/2449d7ad-0f5d-4a12-9da1-c6fed3b0f388)

Not necessary to fix now unless one of those states/territories is part of the pilot.

### This task is done when...
 - [ ] All States and Territories have their associated map icon
- [ ] Verified by someone else

**Comment by mgwalker** [comment]
In #1730, we made it so that territories without images wouldn't try to display anything, so the broken image behavior is fixed. Do we want to keep this issue/open a new one to track getting images for the 4 remaining territories?

**Comment by jeromeleecms** [comment]
Let's close this out since the documented bug is complete. I don't think it's a deal breaker if we can't locate images for each territories (nice to have).
