### ISSUE TITLE
Review layout of exported PDF

### ISSUE THREAD

**Issue by CSwartzHMA** [18F/cms-hitech-apd#1425]
Some of the issues identified may already be known, but we want to be sure we are relaying all in case they are not already known.

#1160 streamlines the export of the PDF, but in the review of #1394, it may pull out too much (i.e. no information was provided in the APD about what the content of the next text box was). Once #1160 is completed, we should review a final exported PDF to verify that a reviewer (state or federal) would know what each field is meant to describe.

This is not a review of inputted data, but to review that each field has an associated header/explanation for what should be in that field.

### This task is done when...
 - [ ] Design team has reviewed sections that have had the design system implemented
 - [ ] Issues have been created for anything identified

**Comment by CSwartzHMA** [comment]
Data in tables appear misaligned in PDF version.

![image](https://user-images.githubusercontent.com/45497254/55647263-4169fd00-57ab-11e9-8eea-22f463fe02a5.png)

**Comment by jeromeleecms** [comment]
Per Sprint Planning 05/02/2019 - We are going to hold off on tackling this until we the rest of the design system has been implemented in relation to the pilot. Moving this to below "Consistent UI Design"

**Comment by austinhernandez** [comment]
Page 1: Is this page intentionally left blank as a coversheet? 
Page 2: Bold labels
- can we do `[name], [role]`?
- should we remove edit button?
Page 3: Bold labels
Page 4: The checkboxes don’t render as checked
Page 5: Can the `<textarea>`s collapse?
Page 6: Can the `<textarea>`s collapse?
- Can we move the sections up or does it need to start on a new page?
Page 9: Table label alignment is off
