### ISSUE TITLE
Clarify that the fiscal year in question is federal

### ISSUE THREAD

**Issue by jameshupp** [18F/cms-hitech-apd#1427]
States sometimes default to breaking down activity according to their own fiscal years (SFY). The app should clarify that the fiscal years are federal (FFY). This should happen early in the app so future references are clear.

### This task is done when...
 - [ ] A simple reference to federal fiscal years is part of an instruction prior to any budgeting breakdowns
 - [ ] Product has approved the language

**Comment by CSwartzHMA** [comment]
This is addressed in #2162 so we can close this issue.
