### ISSUE TITLE
On initial access, form details in Manage Account screen are not loaded onto the page.

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1428]
First click to "Manage Account" from non-admin account does not populate form:

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/662c1fd8-d8c5-4d9c-8dc5-ab3f32f2a886)

Form data is only populated after selecting "Save Changes," navigating away from, and then back to the "Manage Account" screen: 

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/dc0cdb83-02f2-46db-b8f7-a9d260dc6d26)

Note, blank data is not saved. 

### This task is done when...
 - [ ] Form data on manage account screen is loaded without need to save page
 - [ ] Someone else has reviewed the code and confirmed bug is resolved

**Comment by mgwalker** [comment]
The `/me` APD endpoint doesn't return the user's information.  Not sure if the app state reducer would save it, either.
