### ISSUE TITLE
Onboarding feedback

### ISSUE THREAD

**Issue by austinhernandez** [18F/cms-hitech-apd#1433]
Provide notes to the onboarding

### This task is done when...
 - [x] I've complete onboarding
 - [x] I've provided feedback to the team about onboarding experience
 
[Here is a Google Doc that summarizes my onboarding experience. ](https://docs.google.com/document/d/1eH2wVPXc18I8PWl_oXAWbHk1rfXQLw4N2R-7_y6YUGg/edit?usp=sharing). The document includes:
- Things I found helpful
- Things I found less helpful
- People I talked to
- Links I had and used / didn't use 
- My personal learning styles

**Comment by NAretakis** [comment]
This feedback is awesome. Thanks @austinhernandez . Anything else on this issue or are we good to close it out?

**Comment by NAretakis** [comment]
:tada:
