### ISSUE TITLE
Inconsistent Stickiness Sidebar Behavior with Internet Explorer

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1434]
#1430 appears to work fine in Chrome, but has some interesting behavior on Internet Explorer.

1) Sidebar resizes on scroll

APD Load: 

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/e7da6dd1-52f7-4d1f-bd00-a4086efcdcb0)

APD on scroll:

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/0f4e2a5f-70dd-4eb2-b186-2c2cba1dc940)

2) ~~Page content is not centered in IE~~ Not sure when this was fixed, but IE content is centered.

### This task is done when...
 - [ ] Left side navigation remains consistent in size during scrolling in IE
 - [ ] The sidebar has appropriate bottom whitespace when the page is scrolled to the bottom (if possible - see [the first image](https://github.com/18F/cms-hitech-apd/pull/1721#issuecomment-524382855) to see the problem
 - [ ] ~~Page content is centered in IE~~

**Comment by mgwalker** [comment]
The sidebar vertical spacing issue may be unsolvable, unless we want to write some javascript to track where the sidebar is on the page. I think we could "solve" the sidebar by making it fixed at `top: 0` once its relative top goes below 0, but we'd have to have scroll handling Javascript to enforce that, and we definitely don't want that in browsers that support sticky.
