### ISSUE TITLE
Timed out exporting from Chrome

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1436]
Could not convert PDF to word when exporting from Chrome. It timed out, during #1316 testing.

### This task is done when...
 - [x] does not time out
 - [x] can export a PDF from Chrome

**Comment by mgwalker** [comment]
We need more info before we can do anything with this one.  Can someone explain the process that was being tested and where it failed?  "Convert from PDF to Word in Chrome" isn't clicking for me.

**Comment by NAretakis** [comment]
@CSwartzHMA can you help us with more context? This issue came out of #1316 testing, and I only put in very basic info about the bug, and clearly not enough to get it fixed.

**Comment by CSwartzHMA** [comment]
Yes. Here is Matt's full description (probably more than you need, but describes the process he followed).
Using FL APD -  115 (Chrome) or 125 (IE) pages long – State should know it might take a little bit to download depending on bandwidth.  
Chrome was larger file at 5,828. IE was 684.
Received message several times that page became unresponsive in preview mode within Chrome.
Unable to convert the Chrome PDF version to word (Adobe became non-responsive).
Pages 70 to 125 in IE PDF and Word were blank. Chrome PDF did not contain the blank pages. Both IE versions (PDF and Word) appeared to contain the completed eAPD.

**Comment by mgwalker** [comment]
Thanks @CSwartzHMA, that's very helpful context!  So this isn't a bug in the eAPD app, but it's a bug in the proposed APD export/import workflow?

**Comment by CSwartzHMA** [comment]
So, I think its more of a compatibility issue perhaps? You are correct in that it does not occur within the app. But the exported version of the APD seems to function differently depending on the OS.

**Comment by NAretakis** [comment]
No longer times out!
