### ISSUE TITLE
Implement design system in section 2 (Program Summary)

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1442]
The Program Summary section contains two different types of new components: checkboxes (#1444) and the rich text editor (#1443). 
 
![2_Program Summary](https://user-images.githubusercontent.com/21222704/56003712-ae363900-5c7c-11e9-91f0-b27aab93350b.png)

- `Program Overview` is an H3
- `Program Introduction`, `HIT Overview`, `HIE Overview`, and `MMIS Overview` are H4s
- The help text box uses #E1F3F8 $color-primary-alt-lightest for the light blue and #205493
$color-primary-darker for the left triangle

### This task is done when...
 - [ ] The Program Summary section is using the new design system and matches the mock-ups

**Comment by mgwalker** [comment]
For `Program Introduction`, `HIT Overview`, `HIE Overview`, and `MMIS Overview`, those are currently presented as `Instruction` heading content elements, which is rendered as an `h3`.  It's totally fine if they should be `h4` instead, but I want to make sure before I do it.  😄

**Comment by lauraponce** [comment]
In the Sketch file, Jen set the pattern by making those headings h4s, but it seems like following the defaults of the Instruction heading content element rendering might be cleaner (and simpler). @jameshupp do you have an opinion on this?

**Comment by jameshupp** [comment]
I just went through the app and I can't see why instruction headings should be h3s anywhere in the app. Not sure I'd really got a handle on headers when we were first working on instructions.

**Comment by hbillings** [comment]
Sticking my nose in here...

Here's an example of when the instruction heading should be an H3:
<img width="759" alt="Screen Shot 2019-05-02 at 2 26 45 PM" src="https://user-images.githubusercontent.com/509309/57105005-f75f3300-6ce6-11e9-992d-7a61cc57eb4a.png">

**Comment by mgwalker** [comment]
I've taken out the `subsection` stuff and it's just a plain `<h3>` now in the PR.

So it seems like maybe the `<Instruction>` component should have a flexible heading size and default to 3?  Then in this case, we'd set it to 4?
