### ISSUE TITLE
Apply the design system to the rich text editor component

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1443]
The rich text editor component should be updated to match the CMS design system.

### New design ⬇️  

<img width="733" alt="Screen Shot 2019-04-11 at 5 28 12 PM" src="https://user-images.githubusercontent.com/21222704/56004359-acba4000-5c7f-11e9-944b-23637f42ae38.png">

### Old (current) version for reference

<img width="699" alt="Screen Shot 2019-04-11 at 5 31 16 PM" src="https://user-images.githubusercontent.com/21222704/56004347-a1ffab00-5c7f-11e9-84a1-cf3ee844b725.png">

### This task is done when...
 - [ ] The rich text editor component is using the new design system

**Comment by mgwalker** [comment]
I believe this was done somewhere else.  The rich text editor currently looks like this:

![screenshot of rich text editor showing darker border](https://user-images.githubusercontent.com/1775733/60021017-c5b77800-9656-11e9-9872-611803060757.png)

**Comment by hbillings** [comment]
yep! this is done.
