### ISSUE TITLE
Restructuring Activity Schedule Summary Table

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1446]
The activity list in section 5 uses the same table pattern as the Results of Previous Activities section:

![5_Activity Schedule Summary - Relaxed](https://user-images.githubusercontent.com/21222704/56010826-0f203a00-5c9a-11e9-962e-ff798c26a0e0.png)

### This task is done when...
 - [ ] The Activity Schedule Summary is using the CMS design system

**Comment by mgwalker** [comment]
Goals are to defunkify the data so that it's easier to work with in the future, and switch to the table layout here which is probably also easier to work with in the future.
