### ISSUE TITLE
Bring design elements in line with design system for Activity Overview (Program Activities subsection)

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1452]
Within the Program Activities section, the first subsection is `Activity Overview`. Don't worry about the exact pixels or size discrepancies in the mockup, please use default Design System and we can fine tune global styles later.

Note that the content of the overview is shown as nested, but we're not going to implement that right now. Keep the margins aligned with the higher-level header.

![image](https://user-images.githubusercontent.com/23194720/58210607-e5562c00-7cb7-11e9-8a98-da4fee4a2709.png)

### This task is done when...
- [ ] `Activity Overview` is `h4.ds-h4`.
- [ ] `Textarea` has been swapped for the design system component
- [ ] Each section is wrapped in a `div.data-entry-box` (controls the spacing/margin between each section -- there's probably a better way to do this but I haven't figured it out yet)
- [ ] There is an `hr` at the end of the Overview section

**Comment by austinhernandez** [comment]
Here is the final design of the `Activity Overview page` 
![image](https://user-images.githubusercontent.com/23194720/58210607-e5562c00-7cb7-11e9-8a98-da4fee4a2709.png)

**Comment by austinhernandez** [comment]
@hbillings and @mgwalker - These are the subsections that were development tasks, but didn't have the updated screenshots. 

The goal is to make it look like the rest of the design system, as close to default as possible, so it will be inheriting the already implemented styles. Please let me know if this ticket does not have the right information you need.
