### ISSUE TITLE
Add review pattern to Performance Goals and Benchmarks (Program Activities subsection) and update to use design system tokens

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1453]
Within the Program Activities section, the 2nd subsection is Performance Goals and Benchmarks. 

![image](https://user-images.githubusercontent.com/23194720/58210735-39611080-7cb8-11e9-9d8f-c3245311658f.png)

### This task is done when...
 - [x] The `Collapsible` component has been replaced with the design system review pattern.
 - [x] "Performance Goals and Benchmarks" is `h4.ds-h4`
 - [x] Each section is wrapped in a `div.data-entry-box`
 - [x] Available entry boxes are "Goal Name" (short text entry field) and "Benchmarks" (textarea).
 - [x] The collapsed view shows "Goal [number]: [goal name]" in `h5.ds-h4` and the "benchmark" text.
 - [x] Goals may be edited once collapsed or removed if there is more than one goal in the list. (Note that the current mockup does not allow for removing the first goal, but probably all we care about is making sure that there is at least one goal.)
 - [x] New goals may be added with the "Add another goal" button (would work similar to the contacts in the Key Personnel section using the review component.)
 - [x] Section has an `hr` at the bottom

**Comment by austinhernandez** [comment]
Here is the final design! It should be inheriting the styles from the other sections 👍 
![image](https://user-images.githubusercontent.com/23194720/58210735-39611080-7cb8-11e9-9d8f-c3245311658f.png)
