### ISSUE TITLE
Inconsistent Appearance of "Select" component in IE vs other browsers

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1454]
"Select component" has double drop down buttons in IE:

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/a2a354f0-b78f-489a-a609-9d3946c097fc)

This issue appears in the design system as well, https://design.cms.gov/components/select/

### This task is done when...
 - [ ] Assessment is made whether double dropdown button can be pared down to a single button
 - [ ] Double arrow is removed OR Decision to take no action is made

**Comment by mgwalker** [comment]
Can we close this since IE11 is a "yellow" support browser?

**Comment by jeromeleecms** [comment]
Closing this because of what Greg said.
