### ISSUE TITLE
Implement review patterns for Personnel and Non-Personnel, normalize headings, and replace date fields in In-House Cost Categories subsection (Program Activities subsection)

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1456]
Within the Program Activities section, the 4th subsection is In-House Cost Categories. This subsection uses masked fields for dollar amounts, select field for the category, and single and multiline text fields.

(Note that what says "Activity Schedule" in the mock below should actually say, "In House Cost Categories.")
![image](https://user-images.githubusercontent.com/23194720/58205345-51cb2e00-7cac-11e9-9351-fdd82f07f2ba.png)

### This task is done when...
 - [ ] In-House Cost Categories is a `h4.ds-h4`.
 - [ ] Personnel and Non-Personnel are `h5.ds-h4`.
 - [ ] Personnel and Non-Personnel can be added, edited, and removed with the review pattern.
 - [ ] When collapsed, each personnel cost displays `1: [personnel title]` in `h6.ds-h4`, the description of the personnel in question, and the contract term.
 - [ ] When expanded, the personnel cost uses the multi-box date entry field instead of a datepicker.
 - [ ] When collapsed, each non-personnel costs displays [what, @austinhernandez?]

**Comment by austinhernandez** [comment]
Question for @jameshupp @NAretakis and @jeromeleecms in the `non-personnel` section of the `Activity Schedule`

Should the label for non-personnel be the same as the CTA? It is different in the app so it's different in my mockup!
![image](https://user-images.githubusercontent.com/23194720/58188041-f5551800-7c85-11e9-80d5-9e9d61b5a5a1.png)



@mgwalker I know we talked about the date section looking like this from another ticket (top labels, helper text on start) also, no cancel buttons in this section. That's great, this section should follow the patterns of the other implemented sections and we can look at these as a group in-situ all together, at any stage of development. @hbillings I thought it might be important to tag you in on these decisions if you are implementing any other part of this section.

![image](https://user-images.githubusercontent.com/23194720/58205310-3e1fc780-7cac-11e9-9055-d8dc0158ff8b.png)


Heres the whole thing. This section should not be an edge case and reflect all the design elements from previously implemented sections. Please let me know if you find any discrepancies so we can work it out!
![image](https://user-images.githubusercontent.com/23194720/58205345-51cb2e00-7cac-11e9-9351-fdd82f07f2ba.png)

**Comment by jeromeleecms** [comment]
@austinhernandez The header structure seems inconsistent -- the title "Non-Personnel" falls under the broader header of "In-House Cost Categories," but when I look at the markup, it shows 

1) "In House Cost Categories" is an `<h4>` tag
2) "Personnel" and "Non Personnel" is an `<h2>` tag

![image](https://user-images.githubusercontent.com/34279968/58572297-4322d080-81f0-11e9-8e7b-262ecf4dfb74.png)


Which doesn't seem right - if we are going to rely on the design system, should the "Personnel" and "Non Personnel" tags be <h5> and let it be consistent based on the markup?

Please let me know if I'm misunderstanding your question.

**Comment by jameshupp** [comment]
@austinhernandez To clarify, your question is whether the header and the CTA need to be consistent in both places? So `Personnel` goes with `Add another personnel` but `Non-personnel` goes with `Add another expense` and this seems wrong?

If so I tend to agree the mismatch is weird, but for me it's mostly weird because `another personnel` feels weird, not because `non-personnel` is inconsistent. I think we use `another personnel` instead of `another person` because it might technically be multiple people, in the case of contractors? @jeromeleecms is that right? But for non-personnel, it _is_ an expense, and `Add another non-personnel` just seems really unwieldy to me.

If we want to make it `Add another non-personnel cost` that would probably be the best language choice, but I don't know how long is too long for a button.

**Comment by hbillings** [comment]
@jeromeleecms Good catch! We're updating all of the heading structures as we go, so once the mockup looks 👍, we'll implement consistent headers in the code as well. 

@austinhernandez, do you have an example of how the non-personnel section should look when it's collapsed?

**Comment by jeromeleecms** [comment]
@jameshupp - I hope this addresses your question:
- For personnel cost in the in house category - it won't always be a single individual, but could possibly be a category of staff (i.e. auditors). 
- For contracted staff, we would expect that the state would provide the sum total of the entire contract (the description would then explain what the contract was supporting: staffing or a service).

**Comment by mgwalker** [comment]
I don't know why I didn't notice this earlier, but "contract term" isn't the right concept for state personnel.  Here's the form that we're updating:

![image](https://user-images.githubusercontent.com/1775733/59056740-84edef80-885e-11e9-82c3-34fae66187f9.png)

I'll continue on with updating the rest of the form but will need some 👀 from @austinhernandez on the personnel costs + FTEs part.

**Comment by austinhernandez** [comment]
@hbillings for non-personnel, it would follow the same format as pictured here:

![image](https://user-images.githubusercontent.com/23194720/59058033-bd46fb00-8869-11e9-87b3-981a8a2a3baa.png) I'm trying James's new language on "Add another non-personnel cost" but I'm meh about it. Maybe it should stay the same as `add another expense`

**Comment by mgwalker** [comment]
Right, the non-personnel mockup is fine.  It's the personnel part that has the contract term, and it needs to have cost+FTE instead.

**Comment by austinhernandez** [comment]
@mgwalker, that response was for @hbillings's above. 

In response to your question, I have this mockup: 
![image](https://user-images.githubusercontent.com/23194720/59058597-ffbd0780-886a-11e9-9557-c416ef10577a.png)
Does it make sense to have `Costs` or should it be spelled out `Costs with Benefits` @jeromeleecms ?

**Comment by jeromeleecms** [comment]
Our current template (https://www.cms.gov/regulations-and-guidance/legislation/ehrincentiveprograms/downloads/medicaid_hit_iapd_template.pdf) refers to this section as _Cost With Benefits_:

![image](https://user-images.githubusercontent.com/34279968/59058982-a0eb9400-8852-11e9-8d08-842872cf9744.png)

I also prefer this so it's clear that it's not just annual salary.
