### ISSUE TITLE
Research Implementing Splunk with the App

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1461]
It turns out we need to integrate Splunk with our application in AWS. This issue is for us to connect with GDIT and research what we need to do, and how we need to do it. 

### This task is done when...
 - [x] Splunk meeting scheduled with GDIT
 - [x] Implementation requirements identified and a dev issue created

**Comment by mgwalker** [comment]
We're using [winston](https://www.npmjs.com/package/winston) for logging, which conveniently has a [splunk plugin](https://www.npmjs.com/package/winston-splunk-httplogger).  We'll just need the right set of info to hook it up.

**Comment by NAretakis** [comment]
Winston, this is Splunk. Splunk, this is Winston. Y’all have fun.

**Comment by NAretakis** [comment]
Updates:

We need to get a new job code created (AWS_HiC_Splunk) that will be used for linking the HiC AWS application to the Splunk dashboard. Creating the job code is the first step, and once created, we’ll create a ticket in Jira to make sure the appropriate users are onboarded to the dashboard. 

Yes splunk agents are there already part of our Gold Image. We don't know what they are collecting so once we get the interface set up and then we can configure what to collect after.

**Comment by NAretakis** [comment]
Ticket for job code creation has been submitted to the CMS Service Desk.

**Comment by cthulhuplus** [comment]
https://jiraent.cms.gov/browse/CLDSUPSD-7359

First is CloudWatch Agent config and EUA jobcode for Splunk. @NAretakis what is the status on the EUA Jobcode?

1. Start EUA jobcode process
2. get ADO Business Owner to create EUA jobcode
3. how are yall going to manage LogGroups (manually or Terraform/CloudFormations)
4. Check if each instance (Windows/Linux/LB/etc) is logging to their specific LogGroup.
5. Instance level logs will create their own under each LogGroup.
6. Base OS Logs
7. If using GI then already done
8. If not using GI ADO needs to manually install CloudWatch agent
9. Custom Application Logs (below is a sample configuration)
10. Work with ADO to update CloudWatch agent configuration file
11. If LogGroups are populating properly then can move on to Splunk Onboarding

**Comment by cthulhuplus** [comment]
how are yall going to manage LogGroups (manually or Terraform/CloudFormations)

In the past I have typically used Terraform to manage AWS infrastructure, however the current path seems to be using awscli commands in a BASH script. The lift for writing out new scripts/code is probably not light.

**Comment by cthulhuplus** [comment]
Document on setting up an AWS account/environment for onboarding to Splunk:
https://drive.google.com/drive/folders/1J-o00B5CBMF0H2SS68ZCiuA3B4gp59Pm

I've run into issues with LogGroups. There are supposed to be LogGroups set up for base Linux logs, which are not setup. In order to get them created, I will need to edit our Instances CloudWatch Agent configuration.

**Comment by cthulhuplus** [comment]
Since the acceptance criteria of this Issue have been met, I am going to close it and continue work as a part of the Implement Splunk Issue:

https://app.zenhub.com/workspaces/untitled---206274---2017-12-18-5a3823ad3659e94d8ee569be/issues/18f/cms-hitech-apd/1503
