### ISSUE TITLE
Design the Private Contractor Costs subsection using CMS design system

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1463]
### Background

The work for applying the design system to the Private Contractor Costs subsection (in Program Activities) was started by Jen already and just needs to be finished. 

In this subsection, states will input the name of the contractor, describe their services, input the contract term date, costs, and determine if it's an hourly resource. 

If it _is_ an hourly resource, there are some additional fields to fill out:

<img width="448" alt="Screen Shot 2019-04-15 at 4 58 43 PM" src="https://user-images.githubusercontent.com/21222704/56172760-c8835600-5f9f-11e9-8fc7-5cef99301d5b.png">

For the contract term date range, we can leverage this same date range design from the Activity Schedule subsection (#1455) in place of the calendar:

<img width="403" alt="Screen Shot 2019-04-15 at 4 59 36 PM" src="https://user-images.githubusercontent.com/21222704/56172800-fec0d580-5f9f-11e9-9645-07c4403d5067.png">

### Jen's version that was started using the design system

![4_Program Activities private contractor costs](https://user-images.githubusercontent.com/21222704/56172640-38dda780-5f9f-11e9-8443-c10a8575de10.png)

### Current version in the app

<img width="670" alt="Screen Shot 2019-04-15 at 4 51 20 PM" src="https://user-images.githubusercontent.com/21222704/56172657-4c890e00-5f9f-11e9-91d3-d887e1e9e798.png">

<img width="675" alt="Screen Shot 2019-04-15 at 4 51 35 PM" src="https://user-images.githubusercontent.com/21222704/56172658-4c890e00-5f9f-11e9-9bd1-b9052d56be77.png">

### This task is done when...
 - [ ] There is a mock up of the Private Contractor Costs section that uses the CMS design system
 - [ ] Design has been approved
 - [ ] Implementation issue has been created

**Comment by austinhernandez** [comment]
Here is the Contractor Cost: 
I wanna get these out ASAP so they can become development tasks ASAP. 

- Can I get a review from @NAretakis and @jeromeleecms - Is the FFY information the right thing to summarize when a contractor is added?
- @jameshupp do you wanna be tagged on all the microcopy for these sections or wait until they are "live" to make changes.
- @hbillings or @mgwalker I used the new design system and the[ review pattern](https://design.cms.gov/patterns/review/) like the key personnel section that is already implemented. Anything look suspicious thus far?

![image](https://user-images.githubusercontent.com/23194720/57101897-41004b80-6cf0-11e9-9a46-e36b8008345f.png)

**Comment by jeromeleecms** [comment]
Can we do something like this (maybe following a similar pattern to the executive summary <- not prescriptive!)?

1) Name
2) Summary
3) Contract length
4) Total cost
5) Cost by FFY 

That way the Scope, Term, and Cost of the contract is clear when the fields are collapsed and it will be easy to read when it gets exported to PDF.

**Comment by mgwalker** [comment]
What should the UX be for entering contractor hourly rates?  I'm guessing the "This is an hourly resource" checkbox is probably a conditional (like the "Does this person have costs directly attributable to this program?" question in the key personnel section), but I'm not sure what the fields should look like.  For comparison, here's the current UI:

### No
![screenshot showing UI when contractor resources are not hourly](https://user-images.githubusercontent.com/1775733/57155096-27b6d800-6da0-11e9-9c45-380b18d73e7e.png)

### Yes
![screenshot showing UI when contractor resources are not hourly](https://user-images.githubusercontent.com/1775733/57155156-58970d00-6da0-11e9-809d-0a70f8963bbf.png)
The first field, that gets cut off, should be "number of hours"

**Comment by austinhernandez** [comment]
Oh yeah! I missed the conditional button on this one. How does this look? @mgwalker ?

To @jeromeleecms 's point I showed what the review sections would look like with: Name, Summary, Contract length, Total cost, and Cost by FFY. Maybe after the summary reaches a certain length, we can truncate. I wanted to show what a summary would look like with a lot of text.

Conditional radio button - yes
![image](https://user-images.githubusercontent.com/23194720/57169418-872edb00-6dd4-11e9-97c9-34279f6a3561.png)

Conditional radio button - no
![image](https://user-images.githubusercontent.com/23194720/57169422-8f871600-6dd4-11e9-932e-c52602de9a6f.png)

Truncated summary example:
![image](https://user-images.githubusercontent.com/23194720/57169443-c65d2c00-6dd4-11e9-9386-1254c107ff8c.png)

**Comment by mgwalker** [comment]
Nice!

For @jeromeleecms, bear in mind that we can show more details in the print view if we want to, too, so it's not strictly necessary to put everything in the on-screen review view.

**Comment by jeromeleecms** [comment]
Thanks @austinhernandez and @mgwalker! Few thoughts...

The only reason I was thinking that we would should have the whole content now is at some point we (a reviewer) will be using the app to review on screen. If we have this view, we won’t have to expand it when we review it once it’s collapsed/truncated (and we don’t have to put special conditions on this view). With that in mind, would that make a difference in the way you both might consider the experience? I could be OK with truncating it for the state only view with the option to expand it on screen and always expanded with printing it we want to make it more concise.

The FFY cost may not always be the same, so we would need to keep it separate.

Last thing, could we give some line breaks between the summary and the dates and funding to give our eyeballs a little breathing room? But I defer to you @austinhernandez about how that spacing might look. Right now, its seems pretty compact.

**Comment by hbillings** [comment]
This look so good, @austinhernandez! It seems ready to break out into dev tasks if we want?

@jeromeleecms The visual display of this is actually going to be pretty straightforward to change in the future once we start implementing reviewer features! (Reviewers might have a totally different page built with commenting functionality in mind, potentially maybe who knows.)

That said, do we know what information state users might find useful to see in the collapsed view? That might be a helpful starting point.

**Comment by austinhernandez** [comment]
Now implementation task #1522

**Comment by jameshupp** [comment]
Oof, closed _as I was typing this_. A couple copy thoughts:

* Can it say `Contract term` both expanded and collapsed? It'll be easier to find your way for editing if that language is consistent. `Total Contract Cost` vs `Total cost` is less of a concern for me, but it also feels a bit weird to see them inconsistent.
* This takes us into the title/sentence case problem again. Here's a situation where title case looks really awkward to me (This Is an Hourly Resource and/or Hourly Rate). What header level are those? I don't want to go back on myself, but if that's the general use case for h5s on down, maybe that's a case for sentence case at those lower header levels?

This is maybe getting to a point where I want to spin up a whole separate issue just on defining header levels, uses, and text guidance for them.
