### ISSUE TITLE
Design the Cost Allocation subsection using the CMS design system

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1464]
### Background

The Cost Allocation subsection in Program Activities includes two rich text editors, tables that accept inputs, text fields, and select fields all of which need the design system applied.

### Current version without the design system

<img width="650" alt="Screen Shot 2019-04-15 at 5 10 44 PM" src="https://user-images.githubusercontent.com/21222704/56173236-b3a7c200-5fa1-11e9-8664-15c3575ab9af.png">
<img width="652" alt="Screen Shot 2019-04-15 at 5 11 01 PM" src="https://user-images.githubusercontent.com/21222704/56173237-b3a7c200-5fa1-11e9-89fa-d7c9bf94d6ce.png">
<img width="658" alt="Screen Shot 2019-04-15 at 5 11 10 PM" src="https://user-images.githubusercontent.com/21222704/56173238-b3a7c200-5fa1-11e9-9cc2-3cd3007f65a9.png">
<img width="655" alt="Screen Shot 2019-04-15 at 5 11 17 PM" src="https://user-images.githubusercontent.com/21222704/56173239-b4405880-5fa1-11e9-926b-eab03b772c40.png">
<img width="660" alt="Screen Shot 2019-04-15 at 5 11 26 PM" src="https://user-images.githubusercontent.com/21222704/56173240-b4405880-5fa1-11e9-9240-3c2fb933d921.png">
<img width="654" alt="Screen Shot 2019-04-15 at 5 11 34 PM" src="https://user-images.githubusercontent.com/21222704/56173241-b4405880-5fa1-11e9-9617-0b1415f06a96.png">

### This task is done when...
 - [ ] The Cost Allocation subsection has been designed using the CMS design system
 - [ ] The designs have been reviewed and approved
 - [ ] The implementation issue has been created

**Comment by austinhernandez** [comment]
What I did: 
- Moved all the FY information into one section
- Applied new design system styles to the tables
- Added a conditional text field that appears only when you have `Other Funding Amount` information 

![image](https://user-images.githubusercontent.com/23194720/57106023-50849200-6cfa-11e9-97f1-516109c3d50d.png)

- Can I get a review from @NAretakis and @jeromeleecms 
- @hbillings or @mgwalker I used the new design system and the[ review pattern](https://design.cms.gov/patterns/review/) like the key personnel section that is already implemented. Anything look suspicious thus far?

**Comment by mgwalker** [comment]
Whoa, that makes so much sense to me.  I love the conditional "explain the other funding" box.  The only minor concern I have is I'm not sure if that should be a one-line textbox or if it needs to be a bigger text area.  I ***think*** the states may need to get pretty detailed about that, but definitely a question for @NAretakis or @jeromeleecms.

**Comment by jeromeleecms** [comment]
@mgwalker is so APDsmrt(TM)! :tada:

This field is a little small for the level of detail that a user might have to enter and would need to be expanded. If it helps with your thinking, here's the intent/use of the field:

A state may have received funding from a grant that spans:
1) the project (so may span all years)
2) multi, but not all years of the project

If we isolate the grant funding topic to a single year, that might confuse a reviewer or have them miss how the grant funding is applied to the request.

Another possible flow (not prescriptive):
1) After the cost allocation section - ask the State if they have any other funding to report (using existing language)
2) If the answer is no, then the field isn't necessary and the "Other Funding Amount" box never appears.
3) If the answer is yes, the `textarea` could display and the "Other Funding Amount" box also appears in the cost allocation section. 

Let me know if that doesn't make sense...

**Comment by austinhernandez** [comment]
That sounds good to me and that's the conditional workflow I was thinking. Are you saying the only change is to replace `input` with `text area` because a user will have to put a lot of info? If so, it's ready to implement and I can move this over with that change.

**Comment by jeromeleecms** [comment]
Just to verify - we would shift the grant `textarea` right after the cost allocation section instead of incorporating it into the FFP by year?

**Comment by NAretakis** [comment]
Quick and dirty mock-up from parking lot. This moves the "Other Funding Description" section from where it is in the app to in between the Cost Allocation Section, and the FFY cost allocation math section. Per the screenshot below:

![image.png](https://images.zenhubusercontent.com/5c536083d11206601037eb29/01791427-1add-4a35-8631-de2706f4cdf8)

**Comment by austinhernandez** [comment]
Integrated @NAretakis 's cool mockup into my mockup and then moved to implementation task #1526
