### ISSUE TITLE
Design the Standards and Conditions subsection using the CMS design system

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1465]
The Standards and Conditions subsection consists of lots of legal/instructional text accompanied with multiline text fields. These should all be updated to use the design system.

The current version of Standards and Conditions without the design system:

<img width="641" alt="Screen Shot 2019-04-15 at 5 23 32 PM" src="https://user-images.githubusercontent.com/21222704/56173652-6e848f80-5fa3-11e9-9a0f-222c14702027.png">

<img width="654" alt="Screen Shot 2019-04-15 at 5 23 45 PM" src="https://user-images.githubusercontent.com/21222704/56173653-6e848f80-5fa3-11e9-9774-ab3c54fbc438.png">

<img width="658" alt="Screen Shot 2019-04-15 at 5 23 55 PM" src="https://user-images.githubusercontent.com/21222704/56173654-6e848f80-5fa3-11e9-82ff-a04003edf9ad.png">

<img width="651" alt="Screen Shot 2019-04-15 at 5 24 04 PM" src="https://user-images.githubusercontent.com/21222704/56173655-6e848f80-5fa3-11e9-85d2-bea46042bf11.png">

<img width="646" alt="Screen Shot 2019-04-15 at 5 24 13 PM" src="https://user-images.githubusercontent.com/21222704/56173656-6f1d2600-5fa3-11e9-9b55-d8cae70cd15a.png">

<img width="655" alt="Screen Shot 2019-04-15 at 5 24 22 PM" src="https://user-images.githubusercontent.com/21222704/56173657-6f1d2600-5fa3-11e9-913a-e1605cfd1d0a.png">

<img width="654" alt="Screen Shot 2019-04-15 at 5 24 33 PM" src="https://user-images.githubusercontent.com/21222704/56173658-6f1d2600-5fa3-11e9-80d1-1188302d05ce.png">

<img width="651" alt="Screen Shot 2019-04-15 at 5 24 42 PM" src="https://user-images.githubusercontent.com/21222704/56173659-6f1d2600-5fa3-11e9-9507-cf2d754f932d.png">

<img width="655" alt="Screen Shot 2019-04-15 at 5 24 51 PM" src="https://user-images.githubusercontent.com/21222704/56173660-6f1d2600-5fa3-11e9-8cb6-c9c86165422b.png">

<img width="655" alt="Screen Shot 2019-04-15 at 5 24 58 PM" src="https://user-images.githubusercontent.com/21222704/56173661-6f1d2600-5fa3-11e9-9095-d51f25430440.png">

### This task is done when...
 - [ ] The Standards and Conditions subsection has been designed using the CMS design system
 - [ ] The designs have been reviewed and approved
 - [ ] The implementation issue has been created

**Comment by lauraponce** [comment]
Standards and Conditions using the design system:

![Standards](https://user-images.githubusercontent.com/21222704/56512969-cd875e80-64e5-11e9-9d87-92e7fdd010e3.png)

@austinhernandez @NAretakis @jeromeleecms how do you feel about this layout?

**Comment by jeromeleecms** [comment]
@lauraponce How would a user interact with this section? 

Specifically: 
1) What collapses this section? Will there be a "Complete" section like we talked about that will close the section? 
2) Does "Edit" reopen the section for editing? I was reading the reference on design.cms.gov and I don't quite understand the pattern for editing (it only seems to describe review).

Also:
1) Small thing(?), but is it redundant to repeat the directions of "Describe how this activity will support the {Condition}" vs. just including directions at the top as "Describe how this activity will support the following Standards and Conditions." That sounds more like a content question, but if we drop the repeating language, it may change the way the help text appear against each section.

**Comment by austinhernandez** [comment]
I agree with @jeromeleecms regarding what we were talking about yesterday. 

The things that feel missing to me:
- The opportunity to complete
- Knowing what's required or not
- The hierarchy of these belonging to one activity still seems to be a little confusing. 
- The fact that the sections are collapsable (accordion) seems confusing as to what's behind them.
- I also feel like my work on #1463 relates a lot to this as well. Let's cowork!

**Comment by austinhernandez** [comment]
I was thinking about something like this for another section. Let's discuss and come to a consensus:

![image](https://user-images.githubusercontent.com/23194720/56608810-a27e3700-65d9-11e9-87c5-0db4fac7fa91.png)

**Comment by austinhernandez** [comment]
@mgwalker and @hbillings Is there an *easy* way to use the [help drawer pattern from the CMS design system](https://design.cms.gov/components/help-drawer/) here:

![image](https://user-images.githubusercontent.com/23194720/57103669-76a73380-6cf4-11e9-9654-3ae7c51f0fb6.png)

If not, we can just put the long helper text in the blue boxes.

**Comment by austinhernandez** [comment]
If not, we can do it like this: 

![image](https://user-images.githubusercontent.com/23194720/57105953-2206b700-6cfa-11e9-81dd-27ffb9ec64e1.png)

**Comment by mgwalker** [comment]
At a glance on the design system site, it *looks like* adding the help drawer shouldn't be too much of a lift, though it could be more complicated in practice.

**Comment by hbillings** [comment]
I agree with @mgwalker. That said, I'm trying to think of the editing experience in context of our YAML files and I don't know how that would play with the help drawer? I'm also little leery of introducing yet another place for help text to live. What if we did something like truncated the text in the blue box, with a "More" twisty-downy thing that expanded the box with additional content? (note that I don't feel _super_ strongly about this and am willing to be convinced otherwise!)

**Comment by austinhernandez** [comment]
Now an implementation issue in #1523
