### ISSUE TITLE
Implement save button, interactions, and error messages

### ISSUE THREAD

**Issue by austinhernandez** [18F/cms-hitech-apd#1467]
We are going to start implementing #1308 !

The Save state interaction styles are as follows:

Unsaved changes 
![Screen Shot 2019-04-11 at 1 41 47 PM](https://user-images.githubusercontent.com/21222704/55991710-bb90fa80-5c5f-11e9-8eec-07100ce821f9.png)

Save failed - the error message persists and doesn't disappear until they try saving again
![Screen Shot 2019-04-11 at 1 39 02 PM](https://user-images.githubusercontent.com/21222704/55991736-cba8da00-5c5f-11e9-85ad-db38f98ad321.png)

Save success (what they see immediately)
![Screen Shot 2019-04-11 at 1 41 22 PM](https://user-images.githubusercontent.com/21222704/55991765-debbaa00-5c5f-11e9-9ba8-94a905983ae9.png)

All changes saved (no new changes made) 5 seconds later after the toast popup disappears. (tentatively we say after 5 seconds, but we are going to investigate further interactions once everything is implemented and final error messaging is in)

![Screen Shot 2019-04-11 at 1 42 57 PM](https://user-images.githubusercontent.com/21222704/55991907-25a99f80-5c60-11e9-98bc-6ef52ae5c40c.png)

Once a change is made, the button turns into the Save changes button again

![Screen Shot 2019-04-11 at 1 41 47 PM](https://user-images.githubusercontent.com/21222704/55991929-35c17f00-5c60-11e9-9a21-c28b200285d5.png)

While content is being saved (Save loading state)
([loading spinner](https://design.cms.gov/components/spinner/)):
![Save interactions - new placement - save loading](https://user-images.githubusercontent.com/23194720/55494404-b4873e00-5608-11e9-88db-a8a65326e7b4.png)

### This task is done when...
 - [ ] Button states are implemented as referenced above
 - [ ] We are able to see the button state interactions in situ, and the design is ready to be reviewed by a designer (so we can choose the best interactions for the error / toast messages)

**Comment by austinhernandez** [comment]
Documenting feedback from team from our discussion 4/22:
- the save button will live in its own grid column so she doesn't overlap content. 
- @jameshupp to determine final text on save button: 
  - "save" or "save changes" for the button label? 
  - "saving" or "working" for loading state?

**Comment by jameshupp** [comment]
Save and saving. Don't get fancy until someone says we gotta. 🚀

**Comment by mgwalker** [comment]
@austinhernandez To clarify, there's just one save button, and it's fixed at the bottom of the screen?

**Comment by austinhernandez** [comment]
Yes for now, it's one save button and its fixed. What's unclear is where on the bottom of the screen. @hbillings says it might have it's own devoted column in the grid system.
