### ISSUE TITLE
Implement top navigation (horizontal header)

### ISSUE THREAD

**Issue by austinhernandez** [18F/cms-hitech-apd#1468]
We ready to start implementing #1366  !

After a dev + design meeting we decided on exploring the following header:

![Header](https://user-images.githubusercontent.com/23194720/55653706-5780b900-57bd-11e9-9c8e-32029498ca4f.png)

![Header Hover](https://user-images.githubusercontent.com/23194720/55653705-5780b900-57bd-11e9-9df1-56a03037e8ee.png)

Notes: 

- The rationale for the header is the name or email will indicate system status: "You are logged in as `xxxx xxxx` and doing things on that account. Should you need to make changes to the profile or log out it is on this account."
  - Not sure if the `xxxx xxxx` will be the email address or user name, the goal is just to let a user know that's the account changes are being made under in the case of a shared computer or multiple log ins. 
  - Information will pull from information input on the `manage account` page
- The "state dashboard" button is now in the location of a "home" link or logo. It takes you back to the "start page" whether thats the APD builder / APD list screen or the manage users screen for the admin. 
  - @jameshupp still working on content. 
  - There is an arrow back button to indicate you are a one level down from the homepage.
- There are no horizontal header interactions on the current design system, [only vertical](https://design.cms.gov/components/vertical-nav/) so I am using [the interaction styles from USWDS V2 for horizontal (top) nav](
 https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/release-2.0/components/preview/header--basic.html) also [here](https://components.designsystem.digital.gov/components/detail/header--default.html)
- Icons on [Font Awesome](https://fontawesome.com/icons/sign-out-alt?style=solid)
- Background color for the header is `primary darkest`

### This task is done when...
 - [x] Header is implemented with dropdown states as referenced above
 - [x] New design system horizontal header pattern is added to the library (in USWDS, but not CMS design system.)
 - [x] We are able to see the header in situ, and the design is ready to be reviewed by a designer (so we finalize content and give feedback on interactions)

**Comment by mgwalker** [comment]
What should the `< NY APD Home` text be when the user is on a page they can't go "back" from?  Eg, the consent banner, the login page, or the dashboard.

**Comment by jameshupp** [comment]
Does it make sense for it to be blank in those contexts? I don't know what that does to the patterns of people's usage — will they find it again on internal pages? — but if it's one-way traffic (or they're already on that page) we may not need anything at all.

**Comment by jameshupp** [comment]
Currently the banner on those one-way pages says `CMS HITECH APD`. On #1028 I've been thinking about a new title for the top of the Dashboard that's not state specific but would say something like `HITECH APD Builder`. I wonder if some combination of the two—`CMS HITECH APD Builder` makes sense on those pages? Then I wouldn't need to use the `title` on the Dashboard for that content on 1028.

**Comment by jameshupp** [comment]
Okay, per conversation earlier today, on pages that are too high in the experience for a "back" experience, replace `< NY APD Home` with `CMS HITECH APD`. That can be consistent across: on the login and consent pages everything is consistent and we don't (and don't need to) know which state they're in. On the dashboard, each state already has distinguishing content all over the place (the upper left image and name, the list of APDs, etc.).

**Comment by hbillings** [comment]
Were there any special administrator actions that should appear in an admin's dropdown, or should the options in the dropdown be consistent across user types?

**Comment by jameshupp** [comment]
The administrators don't see anything but managing accounts and creating accounts, right? Only they're already in one of those two?

I don't think we want to give them `Manage account` in the same way, since that would just be their own account and the entire point of the admin account is to manage the range of users.

Two versions of this for admin accounts come to mind:

1. They see `Manage user accounts` and `Create new user account` — or whatever we call them on the admin dashboard — in the dropdown, along with `Log out`. Those three things. This might necessitate a validation about unsaved information if they are mid-edit on someone when they try to navigate away.
1. The only thing in the dropdown is `Log out`. This is equivalent to what we have now without introducing the confusion between `Manage account` (i.e. your own) and `Manage user accounts` (i.e. everyone's you have access to).

**Comment by mgwalker** [comment]
I'd kind of thought keeping it consistent between user types would make it easier for admin users to figure out how to change their own password.  From the dashboard, it might not be immediately obvious that "Edit account details and authorization levels for existing user accounts" also means editing your own account, for example.  Like if you click your name and then see "manage account," that feels very clearly tied to *your* account in a way that clicking on "Manager user accounts" outside of any other context does not.

**Comment by jameshupp** [comment]
Well you've at least convinced me that the simplest solution (which I assume this is) might be worth trying. And if it is worth trying, it is probably the correct thing to do until proven otherwise.
