### ISSUE TITLE
Creating a new user account does not automatically update the Admin Manage User Accounts

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1472]
After creating a new user account in Internet Explorer, I accessed the "Manage User Accounts" and my new user account does not appear in the drop down (even after logging out and logging back in).

### This task is done when...
 - [ ] After new users are created, they appear in the drop down menu in the "Manage User Accounts" screen
 - [ ] Someone else has verified that the change works

**Comment by NAretakis** [comment]
I don't think I had this issue in Chrome, is it just in IE?

**Comment by jeromeleecms** [comment]
Yes, just tested this in Chrome. 

Curiously, #1428 also points to an issue where the page is not pulling/displaying data correctly on initial page load. Not sure if these issues are related.

**Comment by mgwalker** [comment]
@jeromeleecms Would you mind checking this in the #1520 preview deploy?  I'm curious if the IE cacheing bug was the same problem.

**Comment by jeromeleecms** [comment]
For record keeping.. the PR is #1620, I tested this in both IE and Chrome. I realize I didn't mention it when I approved it :)
