### ISSUE TITLE
Create Google Form for async feedback during pilot

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1474]
Resulting from #1257, part of the feedback collection will take place asynchronously. 

If/when state and federal users have feedback to share outside of scheduled sessions, they will have the option of providing feedback via a Google Form. Collecting the feedback in this format will make it easy to collect and will keep it categorized/organized.   

### This task is done when...
 - [x] Form is created for states/territories
 - [x] Form is created for federal users

**Comment by lauraponce** [comment]
Draft of the form for states: https://docs.google.com/forms/d/e/1FAIpQLSckQYl7guecyW1mZTlxDL-ovgf95wM_Y0d5XqUDWROt-oo4uw/viewform?usp=sf_link

@NAretakis @jeromeleecms what are your thoughts on this form format for collecting the async feedback? 

I tried to keep it simple by just categorizing by sections/subsections with a spot to give general feedback (which makes it efficient for us to parse). Also with this format, it's super easy for folks to provide the feedback without seeing a daunting questionnaire to fill out; everything is optional and up to them for sharing their comments.

I didn't want to make it too prescriptive by asking questions about their experience because that's the type of qualitative feedback we should be able to get from our interviews and follow-up conversations with users. 

Open to feedback; let me know what you think!

**Comment by lauraponce** [comment]
Draft of the federal asynchronous feedback form: https://docs.google.com/forms/d/e/1FAIpQLScVsMYmKFK70gPI7yZqpI16j7XWqrf6oawaG7PoCyZL9b2Rug/viewform?usp=sf_link

I structured this form less granularly than the state feedback form because reviewers will be looking at everything together and might not think about content by subsections. They can add in any feedback/comments that come to mind as well as jot down any questions for us.

**Comment by jeromeleecms** [comment]
With the open ended feedback - at what point do we ask,

1) For the State:  "What didn't the app allow you to do when making your APD?" 
2) For the Federal Reviewer: "Was there any information missing that prevented you from completing your review?" With an emphasis less on the data entered into the fields, but was the app missing a prompt for a piece of information that was critical to the review experience?

**Comment by lauraponce** [comment]
@jeromeleecms we captured that question for states as part of the user interviews where we'll be able to dive into it: https://github.com/18F/cms-hitech-apd/issues/1347 

It looks like we didn't have this exact type of question for federal users, so I added it as a follow up to the last question of the protocol: https://docs.google.com/document/d/1GlB4DEegOflA3h9E9FkeXb0nWzlkYVWlaWpNqXLfoio/edit

Let me know if this covers what you are talking about.

**Comment by jeromeleecms** [comment]
Thanks @lauraponce! That makes sense to me -- so this form is only intended the few states that actively participate in the pilot (my mind started wandering about the possibility of using this for other states who just want to play with the app - but your latest comment brought me back in focus). 

This looks good -- I also like the instructions that they can enter the form as many times as they want during the process. My only comment would be to make that line stand out more, but totally not needed for us to move forward on using this.

**Comment by lauraponce** [comment]
Good call! I moved it up to the top, but it doesn't look I can do any type of bold formatting:

> Thank you for helping us improve the APD experience by sharing your feedback!
> 
> You can submit this form as many times and as often as you'd like throughout the pilot. 
> 
> Everything here is optional, so feel free to jump around and fill out only the sections for which you have feedback (you can leave the rest blank). Add your comments under the associated sections. Use details and try to be as specific as possible so that we can understand what you are referring to. 
> 
> Let us know what was on your mind when you were using the APD app — what's working well, what's not working well, what you were confused about, what's missing, etc. Any and all feedback is fair game and much appreciated.
> 
> We'll check regularly for responses and will follow up with any questions we might have.
