### ISSUE TITLE
Implement the CMS footer across all of the pages

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1477]
The footer that exists only on the Admin page currently and should be present on all of the pages of the app for consistency.

The Admin page with the footer:

![Screen Shot 2019-04-18 at 8.56.08 AM.png](https://images.zenhubusercontent.com/57f4106595e42b6c5ba9e43c/7bfccb29-e1e7-469c-a739-98132c535128)

### This task is done when...
 - [ ] The footer is on the log in page (including when the government system warning pops up), create account page, manage user accounts page, the main app, and dashboard

**Comment by jeromeleecms** [comment]
Closed by #1519 - :tada:
