### ISSUE TITLE
Internet Explorer: Content within App is not centered on screen

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1479]
IE appearance: 

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/df6171f3-2e57-47b1-86fe-c1ffd6f5ab69)

Chrome:

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/cd042711-ca74-4df9-8205-c862a23ed998)

### This task is done when...
 - [ ] IE content is centered and experience is similar to other browsers

**Comment by hbillings** [comment]
Which version of IE is this happening in?

**Comment by jeromeleecms** [comment]
IE 11.

**Comment by jeromeleecms** [comment]
![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/a2a0b913-549e-44b6-9979-c86aa80a9182)

Updating based on the new header

**Comment by jeromeleecms** [comment]
This seems to have been fixed ... somehow...
