### ISSUE TITLE
Come up with a coherent design for tables

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1480]
Austin mentioned on #1439 that there are some [usability best practices](https://medium.com/mission-log/design-better-data-tables-430a30a00d8c) we should incorporate. In addition, we're currently using table headers in a way that isn't particularly accessible; namely, we've got headers in the far left cell when there are both horizontal and vertical headers. Example:

<img width="684" alt="Screen Shot 2019-04-18 at 5 14 06 PM" src="https://user-images.githubusercontent.com/509309/56396704-64f66400-61fd-11e9-88a8-e9d93a3ee31f.png">

The `FFY` headers in the above example should _probably_ be headings, such as:
<img width="691" alt="Screen Shot 2019-04-17 at 6 09 19 PM" src="https://user-images.githubusercontent.com/509309/56396731-7d667e80-61fd-11e9-931e-00f503c0563f.png">

(Note that this :point_up: pattern already exists in some tables, such as the Incentive Payments table in Program Summary.)

Some things to start with:
- [ ] font: courier
- [ ] font-weight: normal
- [ ] font-size: normal (same as body text)
- [ ] could we keep the K and M all capitalized? (Unless there was a specific reason to do it, it doesn't seem like it.)
- [ ] don’t use center alignment - numerical data is right-aligned, textual data is left-aligned, and headers are aligned with their data if possible.
- [ ] colors?

**Comment by austinhernandez** [comment]
@hbillings here are some table designs:

![image](https://user-images.githubusercontent.com/23194720/57480616-3c96de00-726e-11e9-9dc1-ece841e3cac7.png)

**Rationale:** 
Using [the tables from the design system](https://design.cms.gov/components/table/), but there are some [usability best practices for the table](https://medium.com/mission-log/design-better-data-tables-430a30a00d8c), that I wanted to incorporate. 

- font: courier, weight: normal font-size: normal (same as body text)
- don’t use center alignment - numerical data is right-aligned, textual data is left-aligned, and headers are aligned with their data if possible.
- let's talk about this when we have hours!
