### ISSUE TITLE
Plan Interest Meeting for Pilot

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1481]
As part of #1312, we do want to have the opportunity for states to hear more about what to expect when they sign up for the pilot. 

Planning/prepping for the interest meeting + updating the language in #1312.

### This task is done when...
 - [x] #1312 has been updated with information about the interest meeting
 - [x] content of the interest meeting has been planned out
 - [x] time frames (in relation to #1312 and logistics have been defined (how to schedule, how to conduct the meeting, materials needed and how to capture feedback/insights shared during the meeting)
 
@CSwartzHMA Feel free to modify the success criteria

**Comment by MCorradoHMA** [comment]
@MCorradoHMA

**Comment by lauraponce** [comment]
Hi @MCorradoHMA and @CSwartzHMA! During our working session today, we talked through the open questions in #1312, and the interest meeting came up. We are thinking that next sprint (starting week of 5/20) would be a good time to hold the interest meeting with states. What are your thoughts on that?

**Comment by MCorradoHMA** [comment]
Sounds good to me! I can work on drafting the outline of the interest meeting, including information needed and decision points.

**Comment by NAretakis** [comment]
@MCorradoHMA are we on track to close this out by Friday? Any blockers in your way?

**Comment by MCorradoHMA** [comment]
On track to share a draft with the team Thursday

**Comment by MCorradoHMA** [comment]
I started a draft of the presentation for the interest meeting. I don't have google docs so I tried to copy it here...let me know if this worked @jeromeleecms @CSwartzHMA @NAretakis @lauraponce 

Here are some questions to answer/resolve:
Slide 11: Outline the commitment for the states. I have that there will be: 
- 3 formal check-in points between the pilot state, CMS, and 18F 
- that there will be an "online system" to log bugs or issues encountered, and 
- that CMS will be available by phone any time to support states and answer questions. 
Correct? 

Need sign up deadline.

Is the export only into PDF or is it into PDF and/or Word?



[https://app.zenhub.com/files/113234315/bfec86ee-b96a-46b2-bf5b-c786a226231f/download](https://app.zenhub.com/files/113234315/bfec86ee-b96a-46b2-bf5b-c786a226231f/download)

**Comment by jeromeleecms** [comment]
@MCorradoHMA Thanks! Can we schedule some time to walk through this? 

Generally, I would say we should reference the Pilot Framing Document as the basis of this slide deck (purpose and hypothesis).

I'll follow up with an email too.

**Comment by jeromeleecms** [comment]
@MCorradoHMA Any updates on the slide deck?

**Comment by MCorradoHMA** [comment]
Here it is! LMK if it doesn't work.

[https://app.zenhub.com/files/113234315/704495a1-1583-4adc-ba93-5b86afaaa841/download](https://app.zenhub.com/files/113234315/704495a1-1583-4adc-ba93-5b86afaaa841/download)

**Comment by MCorradoHMA** [comment]
Hey there, just checking in on the review @NAretakis @jeromeleecms ...I know you're in SF. LMK if you want any changes (or @CSwartzHMA).

**Comment by CSwartzHMA** [comment]
Looks like we can close this one out now that the meeting has been conducted. Anything still outstanding?

**Comment by jeromeleecms** [comment]
@CSwartzHMA This is done! We planned, executed, and completed this -- way beyond the success criteria defined above. We can answer the one off questions and collect name now.
