### ISSUE TITLE
Understand what's involved with the update experience for state users

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1483]
When it comes time to submit an APD **update** that builds off of a previously approved APD, there should be an easy, efficient way to do so through the eAPD app. 

The goal of this issue is to design the update experience of the app since it will diverge from the first-use experience. After we have the mock-ups, we can put it in front of state users to get their feedback.

Some considerations:
- Which sections will need to be updated completely? 
- What information will just need to be reviewed/verified?
- Will they need to see and compare to previous years?
- Will they need a flow to verify previous info is still accurate?
- What are the editing interactions like?

### This task is done when...
 - [x] Considerations have been identified
 - [x] Design patterns have been research/discussed

**Comment by jeromeleecms** [comment]
Yes - this seems in line with what I was thinking/heard. Also tagging #1006, #297, and #298 since they seem related. @lauraponce Let me know if you think we should close any of them in favor of this issue.

**Comment by lauraponce** [comment]
Working doc to think through the update experience considerations: https://docs.google.com/document/d/1BxRKzYnVkgDINUWyWkJIQxMilIZTqW2URSYNluFsAYI/edit#

**Comment by lauraponce** [comment]
To do when I pick this back up: 
- Continue researching review/update/verify patterns
- Sketch out some options for the app and share/pair

**Comment by lauraponce** [comment]
This is on hold until we have the milestone planning discussion because it's dependent on the layer 2 priorities
