### ISSUE TITLE
Implement the Executive Summary section

### ISSUE THREAD

**Issue by austinhernandez** [18F/cms-hitech-apd#1491]
From the design ticket #1457 we are ready to implement!

Final mockup with text updates from @jameshupp and product approval!

![image](https://user-images.githubusercontent.com/23194720/56919327-4cecd300-6a8e-11e9-90d0-a40c57a0c9ad.png)

### This task is done when...
 - [ ] The Executive Summary section looks like the mockup
 - [ ] Use the [review pattern](https://design.cms.gov/patterns/review/) from the CMS design system 
 - [ ] Designers approve! 
 
Details:
- This design was created 4/22 as part of our coworking session.
- This mockup has updated copy - just one line "Total Funding Request" might be subject to change pending @jameshupp approval.
- Don't worry about the exact pixels heights from this mockup, I am using the [review pattern](https://design.cms.gov/patterns/review/) from the CMS design system.
  - The action on edit is to jump you up to the activity section.

Text to copy in is here:

Activity 1: `activity name`
Continued Operations of the Medicaid EHR Incentive Payment Program, includes modifications to the SLR, HIT staff, auditing, outreach, and non-personnel expenses for administering the program.

Date: `start date xx/xx/xxxx` - `enddate xx/xx/xxxx`
Total cost of activity: `$XXX,XXX,XXX`
Medicaid share: `$XXX,XXX` (`$XXX,XXX` Federal Share)

Total cost:
Federal Fiscal Years requested: `FFY xxxx, xxxx, xxx`
Medicaid Share: `$XXX,XXX` (`$XXX,XXX` Federal Share)
Total Funding Request: `$XXX,XXX`

**Comment by mgwalker** [comment]
This issue is only for the activity summary part of the executive summary, right?  Not also the budget table?
