### ISSUE TITLE
Design review of the Activity Schedule Summary Table

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1502]
This issue is to do a design review of the Activity Schedule Summary Table, per how it will look via the dev implementation issue #1446 . The goal of this issue is to make sure the start and end dates of activities are correctly being applied, as well as the dates for milestones (within activities). A few points to consider:

* Activities have start and end dates, specified within each activity's schedule
* Activities have milestone dates, specified within each activity's schedule

### This task is done when...
 - [x] Design review has been completed of the Activity Schedule Summary Table
 - [x] Mockups have been designed that give users information about activity start and end dates & milestone dates
 - [x] A mockup is selected to implement
 - [x] a development issue is created with the selected mockup

**Comment by lauraponce** [comment]
![Screen Shot 2019-05-16 at 10 33 27 AM](https://user-images.githubusercontent.com/21222704/57875711-6ac57200-77c8-11e9-97c5-8ef4f7318e1e.png)

- Activity date is start date – end date
- Singular date for a milestone
- Formatting should be MM/DD/YYYY

**Comment by lauraponce** [comment]
Created implementation issue #1537 for this!
