### ISSUE TITLE
Optimize Save Button Location

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1516]
After the implementation of #1490, there were some potential technical issues / performance concerns with locating the Save Button outside of the content area. Since the functionality of the Save Button was OK, the team decided to move forward on the PR (since the functionality worked) and open a new issue to address how to place the Save Button (which may eventually become obsolete if the automatic save functionality is implemented).

What was proposed was to have a white bar (maybe opacity: 50%, padding: 10) that will provide a home for the save button so it doesn't just float. 

### This task is done when...
 - [ ] Design has provided a mock-up 
 - [ ] Product has approved the concept
- [ ] Dev has confirmed that technical feasibility of the implementation

**Comment by mgwalker** [comment]
Optimizing location by removing it. #2091
