### ISSUE TITLE
Implement the Standards and Conditions subsection using the CMS design system

### ISSUE THREAD

**Issue by austinhernandez** [18F/cms-hitech-apd#1523]
From the design ticket #1465 we are ready to implement!

 One outstanding question I just noticed for @jeromeleecms, @NAretakis , @hbillings, and @mgwalker  - in the mockup they have a WYSIWYG text format editor. I am not sure if this is needed or it can just be a format-less text area.

Final mockups:
![image](https://user-images.githubusercontent.com/23194720/57105953-2206b700-6cfa-11e9-81dd-27ffb9ec64e1.png)

![image](https://user-images.githubusercontent.com/23194720/57336700-d89cda00-70f4-11e9-8d7c-430709f72da1.png)

### This task is done when...
 - [ ] All the subsections under Standards and Conditions follow the pattern of theses mockups
 - [ ] Use the [helper text pattern](https://hitech-apd.app.cloud.gov/apd#apd-state-profile-key-personnel) like the one in the Key Personnel section
 - [ ] Designers approve! 
 
Details:
- This design was decided upon on 5/7 as part of our post-standup parking lot session.
- The styles are header, [hint text (like the ones in the form)](https://design.cms.gov/components/text-field/), and then helper text (the one with the light blue background, then text area.
- Don't worry about the exact pixels heights from this mockup, I am using the helper text pattern and that should apply to all of the sections under Standards & Conditions.
  - I also didn't mock up every section because they are looooooong and will all look the same :)
- We may come back to something like a help drawer in v2 and beyond.

**Comment by NAretakis** [comment]
@austinhernandez yes, this section should have a rich text editor. Maybe our users will report that it isn't needed and we can change later, but it should be rich text for now.
