### ISSUE TITLE
Implement the Cost Allocation subsection using the CMS design system 

### ISSUE THREAD

**Issue by austinhernandez** [18F/cms-hitech-apd#1526]
From the design ticket #1464 we are ready to implement!

Final mockup:
![image](https://user-images.githubusercontent.com/23194720/57337528-bbb5d600-70f7-11e9-868a-a72a305dfb1d.png)

### This task is done when...
 - [ ] The Cost Allocation subsection looks like the mockup
 - [ ] Designers approve! 
 
Details:
- This design was decided upon on 5/7 as part of our post-standup parking lot session.
- Don't worry about the exact pixels heights from this mockup, I am using the styles from the CMS design system.
- I moved some elements around more than they are on other sections. 
  - All the FY information goes together
  - The gray section doesn't have a background anymore and follows a form structure
  - The final $ amounts follow the [review pattern](https://design.cms.gov/patterns/review/)
  - Other funding description goes above Federal Financial Partipation (FFP) and Cost Allocation now
    - Is Partipation a CMS word or is that a typo, @jameshupp?
- Still working on global table styles but this table is getting closer to the final table design (#1480)

**Comment by jameshupp** [comment]
>Is Partipation a CMS word or is that a typo, @jameshupp?

Typo! Please fix while implementing, if it's not too much trouble!
