### ISSUE TITLE
Pilot Framing Document

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1527]
Per @nkkl's request, the PM team should prepare a framing document to explain the goal of the pilot. Specifically:

- What we’re trying to learn
- Minimum criteria for starting it
- What we’re going to measure/track
- How we’ll know when it’s time to move forward to the next phase
- Who the target audience is

Draft is available: https://docs.google.com/document/d/1J4El9GyJ2ceS8V0UR1VPaUaufrWcwlfquu3jzSKBgFA/edit#

### This task is done when...
 - [x] Draft Framing document is written by PM team
 - [x] Framing document has been reviewed by someone who is not the author
- [x] The rest of the team has been briefed on the pilot scope

**Comment by jeromeleecms** [comment]
Made updates to the doc based on feedback from @nkkl and @lauraponce. Also reorganized the document to have it follow more of a "science paper-y" type structure.

**Comment by NAretakis** [comment]
done?

**Comment by jeromeleecms** [comment]
Done!
