### ISSUE TITLE
Email for eAPD business owner for Pilot + 508

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1528]
Per our discussion with the CMS 508 team, we can request that the pilot go live without 508 testing provided the scope of uses is 1) small and 2) time limited. 

We will still need to complete the VPAT + the CMS Section 508 test plan

### This task is done when...
 - [x] Email requesting 508 testing not be required for the pilot is drafted
 - [x] Email has been reviewed by someone who is not the author
- [x] Email has been provided to the business owner
- [x] Email has been submitted to CMS 508 team
 
*Add a LABEL (design, dev, compliance, BUG, etc) before submitting.

*If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for PRODUCT to prioritize.

**Comment by jeromeleecms** [comment]
@NAretakis I drafted a short email requesting the waiver for 508 testing for the pilot.

https://docs.google.com/document/d/1fD283u30J95wvAM_z2Apu139iKu4xx27D4MW2bElP2k/edit

Were you able to track down who would need to send the request to the 508 team?

**Comment by NAretakis** [comment]
Changes added. If you concur, I can take this to Ed for us to request. If so, just assign the ticket to me and I’ll roll with it.

**Comment by jeromeleecms** [comment]
Accepted most of your changes with some minor changes - :high-five:

On to you...

**Comment by NAretakis** [comment]
We're good to go for the pilot!

![image.png](https://images.zenhubusercontent.com/5c536083d11206601037eb29/3115d09e-c655-492f-8778-d8aa3bf68e17)
