### ISSUE TITLE
Agree and Consent Screen has an inconsistent look between IE, Chrome, and Firefox

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1540]
There is odd spacing that appears when viewing the consent screen across browsers. Screenshots below:

IE:
![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/7b880f34-d836-483f-a09f-4ada8811d261)

Chrome:
![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/cafbb9c4-04fd-40eb-bac1-d0091d91ccaa)

Firefox:
![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/9b5d5731-b191-463d-9715-adfca853d2e7)

Also, this appears similar to the issue we encountered with the login screen (band below the login card in Chrome), but now only appears in Firefox:

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/5c7f6b6e-9d4a-491f-862a-cb0fec30575b)

Is this related to the page template and/or some one off issue with the way the card layout is structured for the consent screen? 

### This task is done when...
 - [ ] Consent screen appears consistent on browsers
 - [ ] Underlying issue is reviewed/addressed (i.e. adding new pages similar to this style won't result in one off styling corrections)

**Comment by hbillings** [comment]
#1541 should address this.

**Comment by jeromeleecms** [comment]
:thumbsup: Assigning @hbillings on this so we can track the consent and the login screen per the note above.
