### ISSUE TITLE
Mock up the APD update experience

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1554]
For the update experience, we've talked about using the step pattern: https://design.cms.gov/patterns/step-list/ which could help users see what they've done so far and what they have yet to do.

The research in #1555 should inform what the users need for updating their APDs. For example, how important is versioning, seeing their previous APD, etc.

An approach to consider is mocking up a few options to show one with the minimum amount of changes needed to implement the update experience, one with the ideal experience, and maybe one in between.

### This task is done when...
 - [x] Mock up has been created and shared out
 - [ ] #1556 has a design prototype ready to be used in testing

**Comment by lauraponce** [comment]
@austinhernandez when you're ready to start on this — I took a look at #1006 to see what's applicable to this ticket so you don't need to read that mega thread, and based on that, here is what states need in order to update their APDs in the app so that CMS has the info they need:

1. States need to indicate if their activities are continuing or if the activities are completed. One way to do this could be to add a `continuing` and `completed` checkbox/button in the **Activity List** section by each activity.

2. States need to give an update about the activity status if it is not completed. One way to do this could be to add a text box near where we ask if it's continuing or completed for them to provide the update in the **Activity List** section.

3. States need to say how much money they've spent on HIT in-house, HIT contractors, HIE in-house, HIE contractors, MMIS in-house, and MMIS contractors. One way to do this could be to update the table in the **Previous Activities** section with that and show the remaining balance.

**Comment by austinhernandez** [comment]
Here are the design problems I was trying to solve with these mockups

- States need to indicate if their activities are continuing or if the activities are completed. One way to do this could be to add a continuing and completed checkbox/button in the Activity List section by each activity.
- States need to give an update about the activity status if it is not completed. One way to do this could be to add a text box near where we ask if it's continuing or completed for them to provide the update in the Activity List section.
- States need to say how much money they've spent on HIT in-house, HIT contractors, HIE in-house, HIE contractors, MMIS in-house, and MMIS contractors. One way to do this could be to update the table in the Previous Activities section with that and show the remaining balance.

From [the user needs synthesis doc](https://docs.google.com/document/d/1ECxXQ4zO4RjL6LXKwC1wIsPBM1lREAAAOGANN67Z_AM/edit#) 

- 1 Some sort of version control
- 2 Keeping track of what’s been edited/reviewed and any to-dos
- 3 Some way to validate tables and share out with stakeholders
- 4 Guidance and guardrails for what to update

Maybe/worth exploring
- 1 Multi-user editing. Roles based permissions
- 2 Ability to restrict what people can do
- 3 A way to interface with Excel

 ### Mockups
Update experience:
![Reviewer Copy](https://user-images.githubusercontent.com/23194720/60908570-3317fb00-a24a-11e9-866f-e22fc25c89ef.png)
Track changes/History:
![History tab](https://user-images.githubusercontent.com/23194720/60908569-3317fb00-a24a-11e9-861c-5a6483b583c1.png)

Export to XLS last priority dependent on pilot feedback.
![Export to XLS](https://user-images.githubusercontent.com/23194720/60908568-3317fb00-a24a-11e9-951f-19b63fe4e4c7.png)

Tasks/to-dos (out of scope):
![Tasks tab](https://user-images.githubusercontent.com/23194720/60908571-3317fb00-a24a-11e9-8dfa-74da0163e094.png)


We discussed the mockups 7/8/19 and determined the highest priority with @NAretakis.  They are as follows:

1.  Turn text fields into labels with plain text following the [steps list pattern](https://design.cms.gov/patterns/step-list/)
  - Will need edit/update button
  - Will need checkboxes to select activity completeness
2. Ability to move sections into the results of previous activities 
  - Once an activity is marked as complete, user has the ability to see the executive summary of the activity and check the current spend with the previous spend.
3. Ability to track changes/ show history (Also helps Fed Reviewers easily see changes)
  - Before we do "tasks" or "to-dos" and assignments, we need to figure out how to do an auto-save, track changes, and display history.
4. Excel, download only (maybe after we determine if Excel plays a pivotal role in the pilot with our test users)


Next steps:

 - [ ] Have a follow up dev+design meeting to see what is technically feasible
 - [ ] Determine the best way to prototype (static mockups vs clickable interactive HTML sandbox)
 - [ ] Create a prototype to show to state users

**Comment by austinhernandez** [comment]
Closing out this ticket. Designs from this thread are moved to #1748
