### ISSUE TITLE
Plan and conduct research for what state users need for update experience

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1555]
In order to prioritize and solve for state user needs for the update experience, we should talk to state folks and learn about their needs.

### This task is done when...
 - [x] There is a research plan (what do we want to learn and how)
 - [x] Protocol is written
 - [x] Participants are recruited
 - [x] Research sessions are scheduled
 - [x] Research is conducted
 - [x] Synthesis is complete
 - [x] Findings are shared out
 - [x] We have clear direction for #1554

**Comment by lauraponce** [comment]
[Research plan](https://docs.google.com/document/d/17Rk7DfaddZ_rnPhIaHv-0ubI9w6U0GTokF7D2YhtZ4Q/edit#)

[Interview protocol](https://docs.google.com/document/d/16Jkf39Q7G3qwaajme4_RiwWkzhDImI_ApvbNnpCAmeQ/edit#)

**Comment by lauraponce** [comment]
@NAretakis @jeromeleecms – does this plan and protocol seem right to you? Anything else you think we should be asking about?

**Comment by jeromeleecms** [comment]
Thanks, @lauraponce for talking this through with me!

**Comment by lauraponce** [comment]
@NAretakis @jeromeleecms I'm looking at some potential times for these interviews, and here are a few of the time windows:

Monday 6/10 11-12 PT
Wednesday 6/12 9-10 PT
Thursday 6/13 10-1:30 PT

Do any of those work for you? Alternatively, we could use an hour of the working time on Monday afternoon if we need another option.

**Comment by lauraponce** [comment]
Here's a draft of the recruiting message that I could send out on Monday of next week if these dates work:

Hello!

Thank you for volunteering to participate in the HITECH APD research for the new eAPD application.

We are about to begin another round of user interviews related to APD updates. If you'd like to participate, please fill out this Google Form with your availability on 6/10, 6/12, and 6/13. At the end of this week, we'll send out the confirmations for each of the sessions.

We really appreciate your time and input on this project. Feel free to reach out if you have any additional questions!

Thanks in advance,
Laura

**Comment by jeromeleecms** [comment]
@lauraponce I can do:
 
- 06/10, 11-12 PT
- 06/13, 10-11 AM PT (skipping stand-up); 12-1:30 PM

**Comment by lauraponce** [comment]
I'll send the recruiting email on Monday:

> Hello!
> 
> Thank you for volunteering to participate in the HITECH APD research for the new eAPD application.
> 
> We (18F and CMS) are continuing our work to improve the APD experience and are about to begin another round of user interviews related to APD updates. If you'd like to participate, please fill out this Google Form with your availability on 6/10 and 6/13. At the end of this week, we'll send out the confirmations for each of the sessions.
> 
> We really appreciate your time and input on this project. Feel free to reach out if you have any additional questions!
> 
> Thanks in advance,
> Laura, Nick, Jerome

**Comment by lauraponce** [comment]
Linking to all the docs for easy access: 

Here is the [update experience research folder](https://drive.google.com/drive/u/0/folders/1Xl66amTDFIphWLNYfZFsVzvdP0bHUOG7) with all of the docs for this round of research including [Google Form for recruiting](https://docs.google.com/forms/d/1s6JI0APEOUFJMjJVlOoQz18ZG1uT6vUNnm0JuQMB0Mg/edit?usp=sharing),  [research plan](https://docs.google.com/document/d/17Rk7DfaddZ_rnPhIaHv-0ubI9w6U0GTokF7D2YhtZ4Q/edit?usp=sharing), [interview guide](https://docs.google.com/document/d/16Jkf39Q7G3qwaajme4_RiwWkzhDImI_ApvbNnpCAmeQ/edit?usp=sharing), [interview notes doc](https://docs.google.com/document/d/1vHRMzNiAHIRIEAXx5UQB1mi7MaUPusKLpUc12O33hr4/edit?usp=sharing), and [research participants list](https://docs.google.com/document/d/1thohanXgUcLWwLkhS0QGpuMSXUsBIgk6K2eHoHE8XnA/edit).

**Comment by lauraponce** [comment]
The recruiter email has been sent out! We should start receiving some responses soon.

**Comment by lauraponce** [comment]
I sent calendar invites with the WebEx to each of the participants and also sent them emails to make sure they received the invite.

I also let the two folks know who volunteered but aren't participating in this round that we will have more opportunities to provide feedback in the future, thanking them for volunteering, and telling them they can reach out with questions for us.

**Next steps**: 
- [ ] Send a follow-up email to the participants the day before their interview to ask them to start thinking about an APD update example and that we will be asking them to share their so they can be prepared for the interview.
- [ ] Assign an interviewer to each of the 4 interviews

**Comment by lauraponce** [comment]
Synthesis:  https://docs.google.com/document/d/1ECxXQ4zO4RjL6LXKwC1wIsPBM1lREAAAOGANN67Z_AM/edit#

I added it to our agenda for coworking time on Monday to talk through and figure out next steps.
