### ISSUE TITLE
Usability testing with update experience prototype at MESC

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1556]
In order to test out the designs to see what works for users and where to iterate, we should conduct some usability testing with the mockups from #1554. This can be lightweight testing and doesn't need to be built out as a fully functional app — we can opt for a static prototype.

 - [x] Protocol is written
 - [x] Participants are recruited
 - [x] Research sessions are scheduled
 - [x] Research is conducted
 - [x] Synthesis is complete
 - [x] Findings are shared out
 - [x] We have clear direction for what to iterate on and new issues have been created

**Comment by lauraponce** [comment]
Starting the research plan in this folder: https://drive.google.com/drive/u/0/folders/1dRMOMfifUFcjgeYypHISWqrhSzCKt1Ss

**Comment by lauraponce** [comment]
Linking to https://github.com/18F/cms-hitech-apd/issues/1748

**Comment by lauraponce** [comment]
> Hello! We are going to be at MESC next week and will be conducting some in-person usability testing sessions for new functionality of the eAPD application. If you're going to be around at MESC and would like to participate in the research or if want to just stop by to say hi and see what we're working on, reply to this email to let us know so we can coordinate. Thank you!

**Comment by lauraponce** [comment]
@jeromeleecms what do you think about something light and casual like that for reaching out to the state distro list about MESC? Do we need to add anything else?

**Comment by jeromeleecms** [comment]
This looks good. I don't know if we have enough information about the space yet, but do we want to find a place where people can find us? If not, lets drop the language that says "stop by"...

Hello! We are going to be at MESC next week and will be conducting some in-person usability testing sessions for new functionality of the eAPD application. If you're going to be around at MESC and would like to participate in the research or if you want to say hi to see what we're working on, reply to this email to let us know so we can coordinate. Thank you!

**Comment by lauraponce** [comment]
Good call! That seems right to me too. I'll send this out now.

**Comment by lauraponce** [comment]
Protocol draft: https://docs.google.com/document/d/1B0JLgMPvrFEvgAD61RlrtdsePqsH3P6l7qTghRUlsj0/edit#

I'm going to make a couple of tweaks to the prototype flow in InVision because some of the buttons aren't hooked up for the way I've written the guide, so I'm waiting on getting edit access from Austin.

@jeromeleecms does the flow in the protocol seem right to you? Anything missing?

**Comment by lauraponce** [comment]
Start of the synthesis:

https://docs.google.com/document/d/1hOABKqZ18qC7iRriB7sVZ5mv9O9Ucxu0b_go-0S5m7Y/edit

Still need to add the feedback from Jerome's session

**Comment by lauraponce** [comment]
Issues have all been created!
