### ISSUE TITLE
Fix label styling on key personnel section

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1558]
As @austinhernandez pointed out in reviewing #1539, the label styles for the review panel in the key personnel section may be wrong.

Current:

![current](https://images.zenhubusercontent.com/5707ce4abf93871ccd9917fb/328bafdc-945f-4a70-b16c-d040bb4b3d7e)

The header line is the person's name, the next line is their role within the state.  Next is how much that person costs the state in total, if anything.  The ***first*** person in the list will have an additional fourth line that just states that they are the primary point of contact - none of the other people will have that last line.

Some questions for Austin:

- should there be vertical spacing between the person's role and their cost to the state?
- should `Total cost:` be bolded? (It's the only text serving as a label in the review section)
- should `Primary APD Point of Contact` be bolded?
- should these lines be rearranged?  Maybe `Primary APD Point of Contact` should get bumped up

### This task is done when...
 - [ ] design determines whether the key personnel section needs to be revised
 - [ ] design can tell dev what needs to be changed
 - [ ] dev has created an implementation issue (if needed)

**Comment by beparticular** [comment]
This is outdated with the current design, closing.
