### ISSUE TITLE
Houston, we've lost the sticky sidebar

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1560]
Sticky sidebar is no longer sticky when scrolling through an APD. This occurs in Chrome and IE. 

![image.png](https://images.zenhubusercontent.com/5c536083d11206601037eb29/bbb92ed5-c04c-4870-9204-0f79dbe0c671)

### This task is done when...
 - [ ] stickyness returns

**Comment by hbillings** [comment]
![wat](https://i.kym-cdn.com/photos/images/newsfeed/000/173/576/Wat8.jpg?1315930535)

This is so weird; the `position: sticky` attribute appears to still be in place?! Yay.
