### ISSUE TITLE
Activities and Goals Section Review

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1567]
From our conversation in the #1565, the goals and activities section is asking for three things:

1) Name of the Goal
2) Explanation of the Goal
3) Associated Benchmarks on how the state will measure progress.

However, we only have two input fields: name of the goal + benchmarks. 

Per @jameshupp - "a single input should generally have a single ask. Otherwise we get a lot of different structures: benchmark-by-benchmark descriptions, a description and then a list of benchmarks, a description with benchmarks mixed in at various points, etc.

We could do something with the instructions themselves to make that clearer, though? Maybe just Description as a title, and then an instruction like:

Briefly describe how this goal relates to the vision identified in the program summary. Then provide any benchmarks the state will use to measure progress toward the identified goal.

(That would involve moving the first sentence from the section instructions to the ones for this specific input field.)

If this feels like too big a set of things to discuss, go ahead and approve the merge and we can figure this out as a separate need."

(copied from comment in #1565)

### This task is done when...
 - [ ] Instructions of Goals and Activities Align with our ask / input fields
 - [ ] Appropriate tasks/issues are created to support any implementation needs

**Comment by lauraponce** [comment]
@jeromeleecms is this one outdated/obsolete since we have https://github.com/18F/cms-hitech-apd/issues/1819 now?

**Comment by jeromeleecms** [comment]
Closed out because of #1819
