### ISSUE TITLE
Prepare Site for Pilot Testing

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1571]
Prior to Pilot go-live, we need to set up the site to receive users.

Current thinking is to reset the database and setup a separate site for continued Dev work.

### This task is done when...
 - [x] Database Reset
 - [ ] new Dev environment has been established

**Comment by mgwalker** [comment]
- removed all APDs from the production database
- assigned everyone's state accounts to Texas
- added the sample APD to Texas

Should be ready to onboard state users now!  Once we get the staging environment settled down, we can move our accounts over there, remove them from production entirely, and then hopefully not manually edit the production database again! 🤞

**Comment by NAretakis** [comment]
This perhaps includes a staging branch for new features.

**Comment by mgwalker** [comment]
We have a staging environment. It's not _finalized_ but it's useable. Should we open a new issue to track eventually getting domains/SSL certificates for staging, and close this one?

**Comment by NAretakis** [comment]
Yes, mind spinning up a new issue with what we need? Or an estimation of what we need?

**Comment by mgwalker** [comment]
Done! #1690
