### ISSUE TITLE
Investigate using context to set gray background on card pages

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1572]
There's a recurring issue where sizing the gray background of cards is A Thing. [@mgwalker suggested it might be a use case for React context. ](https://github.com/18F/cms-hitech-apd/pull/1541#issuecomment-494906680) We should look into that because it would be a more robust solution than what we've currently got going.

### This task is done when...
 - [ ] We know whether we can use [context](https://reactjs.org/docs/context.html) for this or not.

**Comment by jeromeleecms** [comment]
Context has had some bad things said about it. Decision made.
