### ISSUE TITLE
Notify Federal MES officer that their states has been selected for the pilot

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1577]
Once the states have been recruited (#1311), the participating states' federal MES officers need to be aware of their pilot participation and what it means for them.

### This task is done when...
 - [x] Federal MES officers of participating states have been notified and informed about the pilot and what they need to do

**Comment by jeromeleecms** [comment]
@NAretakis Ready to close this out after our meeting with the Federal reviewers yesterday?

**Comment by NAretakis** [comment]
Done
