### ISSUE TITLE
Plan and schedule shadowing sessions with states during the pilot

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1578]
After state users have spent about a week familiarizing themselves with the app, we should [shadow them](https://docs.google.com/document/d/19ka_nDYbUkpXuaz5FWUYhqpfQ1bV6FDO6w5pX1TcqOM/edit?usp=sharing) while they are entering their APD information. 

### This task is done when...
 - [x] Shadowing has been scheduled for the 4 states
 - [x] Shadowing guide has been created and shared
 - [x] Shadowers have been assigned

**Comment by lauraponce** [comment]
Shadowing guide is here: https://docs.google.com/document/d/1bHrwkFAOWDVKKBFXvE72oFB2Jvo86ipAGSqe7BQbtZ8/edit#

Caryn and I have been communicating via email about this and she's able to help with outreach and observation. 🎉 

Next steps are to email the 4 states, schedule the sessions, and send out the calendar invites.

**Comment by jeromeleecms** [comment]
Emails for sent out for scheduling shadowing session. Pending response.
