### ISSUE TITLE
Schedule and conduct shadowing sessions with federal users during the pilot

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1579]
Soon after the federal reviewers begin their review process of the eAPD exported PDF, we should [shadow them](https://docs.google.com/document/d/1J4El9GyJ2ceS8V0UR1VPaUaufrWcwlfquu3jzSKBgFA/edit#) while they are conducting their review.

### This task is done when...
- [ ]  Shadowing has been scheduled for the reviewers of the 4 states
- [ ]  Shadowing guide has been created and shared
- [ ]  Shadowers have been assigned

**Comment by CSwartzHMA** [comment]
Outreach to DE (Peggy) has been initiated.

**Comment by lauraponce** [comment]
I added Florida's shadowing feedback to the [Mural](https://app.mural.co/t/gsa6/m/gsa6/1565221073087/af7440229ec464a7b6ad3973d2f84ea94aafee3b) with the states' feedback from shadowing and interviews.

**Comment by jeromeleecms** [comment]
@CSwartzHMA @lauraponce Can we schedule ID? I spoke with the reviewer and they are open to being interviewed (they had already reviewed the document, but still open to being interviewed).

**Comment by jeromeleecms** [comment]
AK's federal reviewer will not participate due to miscommunication around what is expected for the eAPD vs. the normal submission.

**Comment by lauraponce** [comment]
Closing this out because all three of the interviews are completed and incorporated into the ongoing synthesis.
