### ISSUE TITLE
Schedule and conduct pilot user interviews with states after they submit their APD

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1580]
Once the state participants complete and submit their APD, we should meet with them to conduct a user interview. [Interview protocol is here](https://docs.google.com/document/d/1k7oQJv0tQ7-BnMar1iQFziyd25fkdkoNwBf7dd06pmM/edit?usp=sharing)

### This task is done when...
 - [ ] Interviews have been scheduled
 - [ ] Interviewers have been assigned
 - [ ] Interviews have been conducted
 - [ ] Interview data has been synthesized

**Comment by CSwartzHMA** [comment]
The interview with DE has been scheduled and I will reach out to the remaining states to get a status on their submission.

**Comment by lauraponce** [comment]
The synthesis in the [Mural](https://app.mural.co/t/gsa6/m/gsa6/1565221073087/af7440229ec464a7b6ad3973d2f84ea94aafee3b) now includes:

Shadowing (DE, ID, FL, AK)
Post-submission interviews (DE, ID, FL)

The only remaining state is AK at this point!

**Comment by jeromeleecms** [comment]
AK - we will just do a close out interview, will require some modifications.

**Comment by jeromeleecms** [comment]
Completed interview with AK today. This is ready to close per our sprint planning discussion.

@lauraponce Feel free to add notes/re-open if needed.
