### ISSUE TITLE
Synthesize research from shadowing and initial interviews

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1582]
Synthesis will be ongoing throughout the pilot because the research is ongoing, and once the shadowing and initial interviews are complete, we'll want to bring everything together.

### This task is done when...
 - [ ] Research from shadowing and initial interviews has been synthesized
 - [ ] Findings are shared out with the team
 - [ ] Next steps have been identified

**Comment by jeromeleecms** [comment]
Closed in favor of #1584. Synthesis has been ongoing.
