### ISSUE TITLE
Synthesize all of the research from the pilot and put in findings doc

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1584]
After the follow-up interviews have been conducted, a final synthesis should take place to bring everything together and put the finishing touches on the findings.

### This task is done when...
 - [x] Final synthesis has been conducted
 - [x] Findings and recommendations have been shared out and talked through with the team
 - [x] Next steps have been identified and issues have been created
 - [ ] Research report with findings has been written and shared out (add to wiki)

**Comment by lauraponce** [comment]
The synthesis affinity diagram is in Mural: https://app.mural.co/t/gsa6/m/gsa6/1565221073087/af7440229ec464a7b6ad3973d2f84ea94aafee3b

Starting to write the research report here: https://docs.google.com/document/d/1ghx6yHbAJ1gWzMeouOq-MM_ZIrF9dQFsx8FTtOkoB2Y/edit#

**Comment by lauraponce** [comment]
@jeromeleecms the pilot findings doc is ready for your 👀 — can you scan through this and let me know if you have any feedback before we share this out more widely? https://docs.google.com/document/d/1ghx6yHbAJ1gWzMeouOq-MM_ZIrF9dQFsx8FTtOkoB2Y/edit#

@CSwartzHMA here is a Word version, let me know if you have any feedback on this as well: 
[Pilot research findings.docx](https://github.com/18F/cms-hitech-apd/files/3890360/Pilot.research.findings.docx)

**Comment by jeromeleecms** [comment]
Just for tracking purposes, completed my review and provided edits on 12/06. Will wait for comments/feedback!

**Comment by jeromeleecms** [comment]
Closing this since the work is done and have Nick review the document separately.
