### ISSUE TITLE
Update pilot framing document with discussion and conclusions

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1585]
After the final synthesis has been conducted and shared out, the [pilot framing doc](https://docs.google.com/document/d/1J4El9GyJ2ceS8V0UR1VPaUaufrWcwlfquu3jzSKBgFA/edit#) should be updated based on the findings.

### This task is done when...
 - [ ] The pilot framing doc is up to date based on the findings from the pilot

**Comment by jeromeleecms** [comment]
Turns out that #1584 and updating the Pilot Framing Document have lots of overlap, so we are going to close this out in favor of the synthesis document.
