### ISSUE TITLE
Gather business needs of federal reviewers

### ISSUE THREAD

**Issue by austinhernandez** [18F/cms-hitech-apd#1593]
Describe the task here and link or add dependencies to any applicable issues...

### This task is done when...
 - [x] We know [what federal reviewers are looking for in an APD](https://docs.google.com/document/d/1jfTE15Z2n3nQrSv-kOIForHsyUzDKzPV6wtYP000w5U/edit#)
  - First task: @NAretakis and @jeromeleecms can y'all fill out this document ⬆️ when you get a chance? It should take ~30mins and will help with roadmap, design, and feature planning.
 - [ ] We have a list of tasks to completion [Story mapping exercise](https://app.mural.co/t/gsa6/m/gsa6/1559853434918/c0dfd5e03547f574bf0a0faa5df89255d073d5dc)

### Other important docs
- [Similar mural of storyboarding we are using to determine layer cake functionality](https://app.mural.co/t/gsa6/m/gsa6/1558540089689/7da3aaba47e218c4939fae339c8710fc2191013a)
- [Research by MeT for federal reviewers](https://drive.google.com/drive/u/0/folders/1Bo7XozSZSteklhXyaiNLzQMPkAsAX2fB)
- [The synthesis doc from that research MeT conducted](https://docs.google.com/document/d/1W51GUjRT-DSBFxIZHCPC4wwqfd5wUfeSdwI1_qIaRmc/edit#heading=h.gjdgxs)

**Comment by NAretakis** [comment]
30 minutes of content in. Jerome put his in too. :)

**Comment by lauraponce** [comment]
I put some time on our (Laura, Austin, and Jerome) calendars for tomorrow after standup to talk through the synthesis, triangulate the findings with the [state research](https://docs.google.com/document/d/1ECxXQ4zO4RjL6LXKwC1wIsPBM1lREAAAOGANN67Z_AM/edit#), and figure out next steps for #1554.

**Comment by jeromeleecms** [comment]
Done! Per standup report. Will defer to #1554.
