### ISSUE TITLE
Update footer with new logos and colors

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1596]
The new footer with MACPro and Medicaid branding got some design love in #1126. It should look like this now: 
![image](https://user-images.githubusercontent.com/23194720/59208197-9bee5380-8b76-11e9-82eb-3d86a8bf6425.png)

### This task is done when...
 - [x] The background of the footer is `$gray-lightest`.
 - [ ] The existing logo is right-aligned
 - [ ] Text associate with existing logo reads, "A federal government website managed and paid for by the U.S. Centers for Medicare and Medicaid Services and part of the MACPro suite."
 - [ ] Two new logos have been added on the left-hand side ([link](https://github.com/18F/cms-hitech-apd/files/3266751/logos.zip))
 - [ ] A new small blue strip below the footer contains contact information: "Email CMS-EAPD@cms.gov for help or feedback." on the left, with the email address linked; and "7500 Security Boulevard, Baltimore, MD 21244" on the right.

**Comment by mgwalker** [comment]
Closed by merging #1621
