### ISSUE TITLE
Full walkthrough of Jerome's prototype

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#16]
We saw part of the prototype, but we should get a full walkthrough of all of it.

**Comment by jeromeleecms** [comment]
How much detail do you want to go through with the prototype? I walked Nikki through it at lightspeed in two hours, so either do it in a few sessions or one long working session. Open to either.

**Comment by brendansudol** [comment]
i vote for another lightspeed 1-2 hour full walkthrough, followed by access to the static files so we can look more afterwards

**Comment by jeromeleecms** [comment]
Works for me. I'll see if I can find a way to do a massive search and replace for the hyperlink references so you can just take the files and view the pages. @nkkl is this something you can schedule or do you want me to take that on?

**Comment by nkkl** [comment]
@jeromeleecms we should coordinate 👍
