### ISSUE TITLE
Executive summary program budget summary table has a rounding error

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1613]
The state and federal shares on the first row should sum to the FFY19 total in the second table, but the total is $1 higher.  Are the federal/state shares and total being computed independently?

![image.png](https://images.zenhubusercontent.com/5707ce4abf93871ccd9917fb/0f7c48d0-5d18-40ff-9ba3-223cbf866a5c)

### This task is done when...
 - [ ] the state/federal share sums to the total

**Comment by jeromeleecms** [comment]
Let's close for now - we can come back to this if it rears it's head again.
