### ISSUE TITLE
Bold the labels in the review sections

### ISSUE THREAD

**Issue by austinhernandez** [18F/cms-hitech-apd#1614]
### This task is done when...
 - [ ] bold style and `:` are added to the labels

Before
![Screen Shot 2019-06-18 at 4 58 13 PM](https://user-images.githubusercontent.com/23194720/59722291-4ad30500-91f1-11e9-8f0a-1fadfea3fad0.png)

After
![Screen Shot 2019-06-18 at 5 52 09 PM](https://user-images.githubusercontent.com/23194720/59722502-d482d280-91f1-11e9-81c8-6d9d9a1f787b.png)

**Comment by jeromeleecms** [comment]
This is done!
