### ISSUE TITLE
Table headers with multiple colspans don't get read for subsequent headers

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1615]
On double decker table headers, VoiceOver has a tough time identifying second or third cells associated with the top level header when that header has a `colspan` of more than `1`.

(The pattern shown in the VoiceOver box is what's read aloud. `[top level heading], [second level heading], [content], [content type]`.)

This first one works fine:
<img width="709" alt="Screen Shot 2019-06-19 at 4 55 41 PM" src="https://user-images.githubusercontent.com/509309/59806895-3d7e4f00-92b3-11e9-998d-4fca67562455.png">

The second one doesn't:
<img width="696" alt="Screen Shot 2019-06-19 at 4 55 52 PM" src="https://user-images.githubusercontent.com/509309/59806911-496a1100-92b3-11e9-964e-f62855ec3acc.png">

### This task is done when...
 - [ ] We come up with a way to read table headers aloud in a sensical way.

**Comment by jeromeleecms** [comment]
This appears to be a Safari Bug. We can reopen if needed.
