### ISSUE TITLE
Fix all the headings!

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1632]
We need to go through the app, identify all the headings, figure out what semantic level they should be (e.g., `h1`, `h2`, etc.), and also figure out style level they should be.

### This task is done when...
- [ ] all the headings are identified
- [ ] semantic levels are identified for all the headings
- [ ] style levels are identified for all the headings
- [ ] semantic and style levels are implemented for all the headings

**Comment by quarterback** [comment]
I could fix these, but I need to know where to find them are they Sass level or somewhere else? I've only messed with the YAML in the app up to now.

**Comment by quarterback** [comment]
I added a tab of this to the IA spreadsheet where I'll itemize the existing headers and in theory, propose new ones: https://docs.google.com/spreadsheets/d/19lKi_qorIYzRXRM-OLNYkZOAYaWH6jBeMYhD0Ar9jb0/edit#gid=43082245

**Comment by quarterback** [comment]
Done, issue moved to dev #1763
