### ISSUE TITLE
Content Review of eAPD Sections (for pilot)

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#1635]
Review and assess each section of the eAPD, and then report here on if a section is acceptable or unacceptable for layer 1.

Criteria will be based on :
4) Content (Is helptext/reminder info complete and clear?)

**Comment by NAretakis** [comment]
Per Ron, nothing egregious standing out for pilot. However during pilot will be a good time to make sure content sections are actually helpful/needed.
