### ISSUE TITLE
Save failed message doesn't disappear

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1641]
When the save fails, the error pops up and is persistent. In the case where the save continues to fail, the error doesn't go away and there are no follow up steps for the user.

![Screen Shot 2019-06-28 at 9 35 56 AM](https://user-images.githubusercontent.com/21222704/60357373-55776200-9988-11e9-8299-0d9230570072.png)

Is there a way to add some more information about this error? For example, if it fails 3 times, then a different error appears letting them know to wait a few minutes before trying again, or what to do if it keeps happening, or when the last save was in case they have to bite the bullet and not save their most recent work. 

### This task is done when...
 - [ ] Repeated save fails don't block the user and there are actions for the user to take when save continues to fail

**Comment by quarterback** [comment]
Yeah, at minimum it feels like it should tell you why it fails or else, you'd probably keep failing.

**Comment by quarterback** [comment]
I can edit this text, but I don't know where it is @mgwalker @hbillings or if it's something you all ought to edit. Save failed. Check [%section%] to ensure you completed all items. Try saving again. We don't need the boolean check section thing.

**Comment by mgwalker** [comment]
It's the default, written in the code in [`web/src/reducers/errors.js, line 69`](https://github.com/18F/cms-hitech-apd/blob/master/web/src/reducers/errors.js#L69). You have my blessing to change it if you want, or just let us know the precise text to put there.

FWIW, I should point out that there's no context available when this error pops up, so we don't know what section they should look at, which is why it isn't helpful 😬

**Comment by lauraponce** [comment]
Should we close this issue in favor of the more specified issues that came out of coworking time? #1659 (back end), #1660 (content), and #1661 (front end)

**Comment by quarterback** [comment]
@mgwalker I'll change it. I won't put any context besides "check again and try again" because that'll be better than "keep saving until forever."  Will close this issue @lauraponce

**Comment by mgwalker** [comment]
>keep saving until forever

😂
