### ISSUE TITLE
Add some line breaks to instructional text and help text

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1643]
Add line breaks in between the new lines to space out the content:

![Screen Shot 2019-06-28 at 9 50 00 AM](https://user-images.githubusercontent.com/21222704/60358425-e0595c00-998a-11e9-84c1-dc7be51a24c6.png)

![Screen Shot 2019-06-28 at 9 54 07 AM](https://user-images.githubusercontent.com/21222704/60358430-e2bbb600-998a-11e9-9833-6960a9d4f2ba.png)

### This task is done when...
 - [ ] There are line breaks in the text of cost allocation instructions and key personnel help text

**Comment by austinhernandez** [comment]
I believe these should be in an ordered list instead of having line breaks.

**Comment by lauraponce** [comment]
Good catch, thanks, @austinhernandez! @quarterback is that still a Ron task or should I flag this for dev?

**Comment by quarterback** [comment]
@lauraponce I think I should still be able to do that.

**Comment by quarterback** [comment]
This is done, PR #1645
