### ISSUE TITLE
Fix vertical spacing in activity details, activity overview

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1648]
There is too much spacing after **Activity Overview** and the beginning of the form. This screenshot is from before the activities were switched to the form/review pattern, but it accurately depicts the problem:

![screenshot showing excess vertical spacing](https://user-images.githubusercontent.com/23194720/60369051-7360b900-99c0-11e9-9992-cea225e53a38.png)

### This task is done when...
 - [ ] spacing is reduced
 - [ ] design approves

(from #1638)

**Comment by mgwalker** [comment]
@austinhernandez Can we double-check if this one is still relevant? When we changed the activities over to the form/review pattern, some of the spacing got changed as we wrapped things in a `data-entry-box` class.  Right now, just looking at it, the spacing looks consistent to me. So I guess the question is, if it's not right, what should it be, and should that change be applied site-wide?

**Comment by mgwalker** [comment]
@lauraponce This is what it looks like now:

![screenshot](https://user-images.githubusercontent.com/1775733/62729247-30442d80-b9e3-11e9-9dc6-09f6d04c5314.png)

It kind of looks like there should be spacing above **Activity Overview** and less spacing after it?

**Comment by lauraponce** [comment]
@mgwalker would it be possible to match the spacing of `Activity Overview` and the `Provide a short overview of the activity` to how it looks for the Activity Schedule below?

<img width="370" alt="Screen Shot 2019-08-09 at 4 37 49 PM" src="https://user-images.githubusercontent.com/21222704/62814218-60afc880-bac4-11e9-9f06-fb680748ea00.png">

vs.

<img width="362" alt="Screen Shot 2019-08-09 at 4 37 37 PM" src="https://user-images.githubusercontent.com/21222704/62814224-65747c80-bac4-11e9-887f-7f47b19ef385.png">
