### ISSUE TITLE
Extend form labels to the width of form elements?

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1650]
When design system form labels are used for rich text fields, the form labels do not have the same width as the text fields.  Can we change that?

![screenshot showing different length between the form label and the form element](https://user-images.githubusercontent.com/1775733/60444928-c797b300-9be3-11e9-9a61-7d335d74d1c3.png)

### This task is done when...
 - [ ] form label width is adjusted to match rich text field width

(from #1638)

**Comment by NAretakis** [comment]
closing due to #1640 which covers this bug.
