### ISSUE TITLE
Reduce size of MACPro and Medicaid logos

### ISSUE THREAD

**Issue by austinhernandez** [18F/cms-hitech-apd#1656]
### This task is done when...
 - [ ] The MACPro and Medicaid logos are reduced to about 40% of their current size on small display and 80% on large display

Currently - big logos on small screen/display:
<img width="498" alt="Screen Shot 2019-07-01 at 4 10 15 PM" src="https://user-images.githubusercontent.com/23194720/60463924-39d7ba00-9c1b-11e9-8ecc-c08c712043fc.png">

Better solution for logos on small screen/display
<img width="698" alt="Screen Shot 2019-07-01 at 4 15 41 PM" src="https://user-images.githubusercontent.com/23194720/60464139-b4083e80-9c1b-11e9-8cac-3e22e545cf0c.png">

Better solutions for logos on large screen/display
<img width="1010" alt="Screen Shot 2019-07-01 at 4 15 18 PM" src="https://user-images.githubusercontent.com/23194720/60464160-c1252d80-9c1b-11e9-893f-f0fbdd076403.png">

**Comment by mgwalker** [comment]
Should we scale the image files themselves? I'm not sure how to scale an image with CSS relative to itself rather than relative to its container. Maybe with a `transform: scale();`?
