### ISSUE TITLE
Determine the best way to handle blank inputs

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1658]
There are several places in the app that have different ways of handling blank inputs. For example:

`Date not specified` and `$0`
<img width="295" alt="Screen Shot 2019-07-01 at 1 38 43 PM" src="https://user-images.githubusercontent.com/21222704/60465323-af389000-9c05-11e9-8d96-4735d6e717b9.png">

`Undefined`
<img width="347" alt="Screen Shot 2019-07-01 at 1 38 51 PM" src="https://user-images.githubusercontent.com/21222704/60465324-af389000-9c05-11e9-8c0b-72ad50d14846.png">

`Blank`
<img width="222" alt="Screen Shot 2019-07-01 at 1 38 57 PM" src="https://user-images.githubusercontent.com/21222704/60465325-af389000-9c05-11e9-875b-8b4b46582a0b.png">

`N/A`
<img width="678" alt="Screen Shot 2019-07-01 at 1 39 15 PM" src="https://user-images.githubusercontent.com/21222704/60465326-af389000-9c05-11e9-869c-17bfdc725f92.png">

Some fields leave it blank, some use 0, some use NA, some use undefined, and maybe more. Since we aren't doing validation, we should figure out the best way to handle blank values and apply that to all fields.

### This task is done when...
 - [ ] There is an established way of handling blank inputs

**Comment by quarterback** [comment]
Hmm..

**Comment by quarterback** [comment]
For all dates, "date not specified" seems suitable to me. For areas with calculations, zero until the section is complete, makes sense. 

Alternatively, we could have a "section not complete" for anything that hasn't been finished yet as a boilerplate non-math placeholder. For simplicity sake (and for all other sections where this might be TBD spaces) and it's more helpful than "undefined."

**Comment by NAretakis** [comment]
For all dates, "date not specified" seems suitable to me. For areas with calculations, zero until the section is complete, makes sense.
☝️  I am in favor of this one. "Date not specified" for dates that aren't specified, and zeros for areas with calculations.

**Comment by quarterback** [comment]
This has to be a dev issue now that we have content for these blank inputs.

**Comment by quarterback** [comment]
PR #1682 closes this.
