### ISSUE TITLE
Update the content on the save failed messaging

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1660]
Pulling over from #1641.

When the save fails, it's likely because there is an invalid date. We should update the save failed messaging so that it lets the user know they should doublecheck the dates they inputted. And if it continues to fail, they should refresh the page. They might lose some data when refreshing since the last save so they should save often.

**Current messaging:**
![image](https://user-images.githubusercontent.com/21222704/60466040-6da8e480-9c07-11e9-96ed-994a94c03fc9.png)

### This task is done when...
 - [ ] There is new content for the save failed message
 - [ ] The new content has been plugged in (or a dev task has been created to do so)

**Comment by quarterback** [comment]
Updated and pushed PR #1674
