### ISSUE TITLE
Total cost doesn't tab across

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#1664]
On total cost section, expected to tab across to "edit" but it goes to “edit activities above” instead. Edit button doesn't appear to do anything. 

Might need to be reworded (@quarterback)

**Comment by mgwalker** [comment]
@quarterback Can you say more about which section this is happening in?

**Comment by mgwalker** [comment]
https://docs.google.com/presentation/d/1mlHiSkV10hZGIp2oGDD2Baxweyoy7nn1ZtTFK5ttP8w/edit#slide=id.g5c3b9a2e73_0_143

Fixed when we re-did the executive summary - there's no "edit" link for the total costs piece anymore.

![Screen Shot 2019-08-06 at 12 21 43 PM](https://user-images.githubusercontent.com/1775733/62561422-cf7eee80-b844-11e9-9ce0-4b6960cb8d97.png)
