### ISSUE TITLE
IA review

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#1691]
The IA goes many layers deep which impacts things like headings throughout the app. This information architecture review issue would take a look at the IA, the challenges of a deep IA and whether it can be rectified in the current pilot state. 

### This task is done when...
 - [x] Audit the information architecture of the app
 - [ ] Pair with dev to assess whether it can be improved after audit
 - [x] Collaborate with design to consider design iterations

**Comment by jeromeleecms** [comment]
@quarterback Could you provide some additional details in the issue, please?

**Comment by quarterback** [comment]
@jeromeleecms Working on that. This was meant to be a placeholder until I had clearer ideas on what this ought to entail.

**Comment by quarterback** [comment]
The tasks in this issue are done. The successor issue is actually _doing_ a potential revision of the IA but I'm still working on that [via this spreadsheet](https://docs.google.com/spreadsheets/d/19lKi_qorIYzRXRM-OLNYkZOAYaWH6jBeMYhD0Ar9jb0/edit#gid=0) and will log in another issue.
