### ISSUE TITLE
User journey or task flow of the update experience

### ISSUE THREAD

**Issue by austinhernandez** [18F/cms-hitech-apd#1692]
During the dev design sync, we realized we didn't understand the user flow of how people would actually _get_ to the update experience. 

Confusion and questions around the following:
- what it meant to "update" vs edit
- technical concerns about editing a submitted document
- confusion around what "Create new" button" does

![image](https://user-images.githubusercontent.com/23194720/61068935-3ab9da00-a3d9-11e9-9c75-460994795497.png)

### This task is done when...
 - [ ] Team understands the difference between update, edit, and new eAPD
 - [ ] Consensus around next steps. 
 
I started on a user journey here:
https://gsa.invisionapp.com/freehand/document/66RFYgCgl

**Comment by lauraponce** [comment]
Incorporating this into #1748
