### ISSUE TITLE
"Milestones" and its children are both h6s

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1694]
`Milestones` is an `h6`. Its `Review` component children also are `h6`.

<img width="1085" alt="Screen Shot 2019-07-15 at 5 00 27 PM" src="https://user-images.githubusercontent.com/509309/61255140-99a68880-a724-11e9-8898-bd5dd9033e0c.png">

**Comment by quarterback** [comment]
Not sure _I_ can fix this one in yaml, right? Do we just want to rec a different structure for those sub-headings? I can fix the spacing of course, and I did some prototyping in the browser but realized that wasn't necessarily helpful either. Do we want a proposal of what else to do with these? (I don't think it needs to be H7, perhaps the other headers should move up a size and then the h6 can stay as-is? @hbillings

**Comment by hbillings** [comment]
@quarterback Yeah, I think this is more a "how the heck do we structure this so that it makes sense?" question. Maybe there's a way to get rid of a heading level in this section? Maybe `Milestones` is the heading and `Milestone 1/2/3` are items in a list? 🤷‍♀ 

The headings can't move up a size because they're already starting at `h1` and flowing down in semantic order, and `h7`s don't exist, so it's time to get creative, heh. (This is one problem that using a modal for edit patterns would solve really, really well.)

**Comment by CSwartzHMA** [comment]
May be resolved when #2242 is completed.
