### ISSUE TITLE
Hierarchic heading level gets crazy in Cost Allocation

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1696]
The semantic structure of this section is tolerable, but it's confusing visually. Semantically, the order is:
- Cost Allocation
  - FFP
    - 2019
    - 2020
    - Total
- Standards and Conditions

But the subsections in Cost Allocation are given larger fonts (`h3` sizes) than the section headings (which are `h4` sized). See screenshot:

<img width="554" alt="Screen Shot 2019-07-16 at 11 17 53 AM" src="https://user-images.githubusercontent.com/509309/61315334-ca85cc80-a7bb-11e9-9d2d-563283ef2f3b.png">

This is the part of the app that is just so deeply nested that I don't know what to do with it.

**Comment by quarterback** [comment]
Proposed fixes: https://docs.google.com/spreadsheets/u/1/d/19lKi_qorIYzRXRM-OLNYkZOAYaWH6jBeMYhD0Ar9jb0/edit#gid=0

**Comment by quarterback** [comment]
Successor issue #1763
