### ISSUE TITLE
Mad Libs exercise

### ISSUE THREAD

**Issue by nicoleslaw** [18F/cms-hitech-apd#17]
Copy and paste the following Mad Libs template into the comment field below. Update the `{{terms in brackets}}` with your answers and click **Comment**. (You can edit your comment after posting!)

```
The HITECH APD app helps states submit APDs in the best way possible by helping them {{user goal}}, {{user goal}}, and {{user goal}}.

To do this well, we must deliver an experience that is {{adjective}}, {{adjective}}, and {{adjective}}. 

The app experience will make users feel {{adjective}} and {{adjective}} encouraging them to {{desired action}} or {{desired action}}, which will help us {{agency goal}} and {{agency goal}}.
```

**Comment by mgwalker** [comment]
The HITECH APD app helps states submit APDs in the best way possible by helping them specify their needs, do math right, and get funded.

To do this well, we must deliver an experience that is easy, minimal, and painless. 

The app experience will make users feel focused and optimistic encouraging them to submit only what's really needed or think carefully about what they're doing, which will help us make good decisions about approving projects and understand how to help states share their work.

**Comment by nicoleslaw** [comment]
The HITECH APD app helps states submit APDs in the best way possible by helping them understand what's required of them, provide complete information, and receive timely responses from CMS.

To do this well, we must deliver an experience that is reflective of the regs/requirements, easy to use,  and easy to understand.

The app experience will make users feel confident and supported encouraging them to partner with CMS on submissions and take advantage of the HITECH program, which will help us support people who need Medicaid and reach our goal of having more offices use digital records.

**Comment by NicolasAretakisCMS** [comment]
The HITECH APD app helps states submit APDs in the best way possible by helping them {{create a simplified submission}}, {{consistently created document}}, and {{a submission that reflects the goals of state}}.

To do this well, we must deliver an experience that is {{intuitive}}, {{not overwhelming}}, and {{easy to update/edit}}. 

The app experience will make users feel {{relieved}} and {{informed}} encouraging them to {{respond to questions}} or {{engage in new projects}}, which will help us {{gain insight into state efforts}} and {{fund successful Medicaid IT projects}}.

**Comment by jeromeleecms** [comment]
The HITECH APD app helps states submit APDs in the best way possible by helping them {{user goal}}, {{user goal}}, and {{user goal}}.

To do this well, we must deliver an experience that is {{simple to use}}, {{simple to implement}}, and {{solves peoples problems}}. 

The app experience will make users feel {{confident}} and {{not confused}} encouraging them to {{not fear the APD process}} or {{be fearful of their Federal Partners}}, which will help us {{improve State flexibility in their programs}} and {{get them working on their projects sooner/faster}}.
