### ISSUE TITLE
Understand what information needs to be collected, answered, and updated in the instances of create new APD

### ISSUE THREAD

**Issue by austinhernandez** [18F/cms-hitech-apd#1707]
We came across potholes in the design workshopping on 7/15. Our team meeting ran into the question of how we handle `Create new APD` and the choices a user has in that workflow. 

We came up with this as a potential first step, but need to know what needs to be displayed so we can show some options to users! 
![image](https://user-images.githubusercontent.com/23194720/61412954-3fd6c780-a8b8-11e9-8509-8236f2ee187a.png)

We decided to go back to the drawing board with doing some drafting in a doc before we explore visual design options. 

### This task is done when...
 - [ ] There is a[ text based version](https://docs.google.com/document/d/1nX0d_a5PI886wl3epJu4SP6_ALLqFFnIo_IBsLDKMiQ/edit?usp=sharing) of the data we need to collect in the 3 potential journeys you can take after `create new apd`. 
- [ ] Flowchart explains the constraints, parameters, and must-haves when creating a new APD https://app.mural.co/t/gsa6/m/gsa6/1563383330690/2e1e8324d51c7631686f6a4c27ccec28752d5ebb

**Comment by austinhernandez** [comment]
Questions updated on the mural after my sync with @lauraponce!

**Comment by jeromeleecms** [comment]
I put some responses next to your questions @austinhernandez. Hopes that helps frame our conversation tomorrow.

**Comment by austinhernandez** [comment]
Closing out this ticket. Designs from this thread are moved to #1748
