### ISSUE TITLE
Add line breaks to key personnel & cost allocation sections

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#1709]
### This task is done when...
 - [ ] successor issue to #1643
 - [ ] add ordered list for both key personnel and cost allocation sections in separate yaml files

**Comment by quarterback** [comment]
Unless I'm missing something, the line breaks look added to #1708 to me. I went to add them and can't figure out where they're missing from.

**Comment by jeromeleecms** [comment]
@quarterback This is what I see in #1708... are you seeing the same thing?

![image](https://user-images.githubusercontent.com/34279968/61567483-92d58980-aa34-11e9-8ef4-31a940380acc.png)

**Comment by quarterback** [comment]
that helps! Will fix!

**Comment by quarterback** [comment]
Fixed in the latest update #1708 PR

**Comment by jeromeleecms** [comment]
Done!
