### ISSUE TITLE
Map out IAPD Update Regulatory Triggers + IAPD Update Content

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1711]
After our working session on 07/15, there seemed to be some general lack of clarity around what needed to be updated in the IAPD during the update experience. Create a mural and shared that with the team to help bring a little order around it and hopefully help inform the work that @austinhernandez is doing for the actual experience.

https://app.mural.co/t/gsa6/m/gsa6/1563383330690/2e1e8324d51c7631686f6a4c27ccec28752d5ebb

### This task is done when...
 - [x] Jerome has completed workflow
 - [ ] Someone from design reviews and determines if/how this might be useful to mapping out the update experience.

**Comment by jeromeleecms** [comment]
Design has reviewed; conversation about how to utilize this information started 07/19/2019; followup discussion scheduled for 07/22

**Comment by jeromeleecms** [comment]
We will hold off on closing this until we have some additional progress on prototypes, etc. + the historical information will also be helpful to those reviewing how we go through solutioning process for APD updates.

**Comment by lauraponce** [comment]
@jeromeleecms are okay to close this one since we have the prototypes in https://github.com/18F/cms-hitech-apd/issues/1748?

**Comment by jeromeleecms** [comment]
Let's close this out, linked to #1748!
