### ISSUE TITLE
Upload images as separate files instead of embedded in text fields

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1735]
Currently in our rich text editor, if the user adds an image, we encode that image in base64 and add it to the text. The result is that the text field can be enormous, and if the user adds multiple images, it can exceed our upload limit, meaning the APD couldn't be saved.

The rich text editor we use provides a mechanism for handling images. Right now we use it to base64 encode the image data, but instead, we could upload the images and then just add a link to the text. That would dramatically reduce the data size of the text field. Depending on how we implement the links, it could even allow browsers to cache the images separate from the APD data (which is not cached), speeding up data loads (maybe!). It will *definitely* make it easier to compute differences in text fields over time.

### This task is done when...
- [ ] backend provides an API path for uploading images associated with an APD
  - [ ] we know where to store files (S3 in production/staging/preview; what about dev?)
- [ ] backend provides an API path for fetching an image
  - [ ] enforces that only users with access to the APD can access the image
- [ ] frontend uses the API to upload images, and embeds URLs into the rich text instead of encoded images

**Comment by jeromeleecms** [comment]
@mgwalker Is this an issue that has come up during the course of the pilot or is this some preventative actions + future planning?

**Comment by mgwalker** [comment]
Preventative + future, definitely not anything I've heard from users. It should be transparent to them, aside from any save size issues.

**Comment by mgwalker** [comment]
duplicate of #1742

**Comment by mgwalker** [comment]
It looks like we're going to need a special AWS authorization role to do this. We need a way to allow our API EC2 instance to read and write to an S3 bucket. We can either give it credentials and then configure those as part of the build step (so our API server would log into AWS using those credentials), or we can give the EC2 instance a role that allows it to read/write the S3 bucket (in which case, our API server doesn't have to log into AWS at all). Either way, we will need the CMS IT team to setup the new AWS role for us.

I'm not sure which way is better offhand.

- Giving the API its own credentials _might_ be more maintainable because then the app is more self-contained. It reads its credentials from the environment and it can do what it needs to do, and the infrastructure configuration is irrelevant. There's less "magic." However, now you've got an additional user account to keep track of.
- Assigning a role directly to the EC2 instance eliminates the extra user, but it makes the connection to S3 "magic." That is, our API does not know how it's connecting. If the EC2 configuration ever got changed (by accident, etc.), it could be really hard to figure out why the image save suddenly stopped working. You might quickly realize there was a credential problem, but you'd dig in and realize the API doesn't have credentials at all. How the heck did it ever work?!

🤔

**Comment by mgwalker** [comment]
Going with the route of having credentials because that seems a heck of a lot more maintainable. I've opened [a Jira ticket](https://jira.cms.gov/browse/CMSAWSOPS-50395) to get those created!
