### ISSUE TITLE
Decimals in dollar fields cause the save to fail

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1739]
All of our dollar fields are expected to be whole dollars, no cents. If a user inputs a decimal, they will not be able to save their APD.

### This task is done when...
 - [ ] decimals don't break everything

**Comment by mgwalker** [comment]
There are a few possible fixes here.  One is to make it so the dollar field doesn't allow decimals at all. When a user types a decimal, nothing will happen. This has the benefit that the field is never in an invalid state, but it might be confusing or frustrating for a user to type something and not have it show up. That said, I think this is my preference.

Another approach is to have the field rounded to the nearest whole dollar when the field loses focus. Upside is that it responds to the user as expected, downside is that the rounding after-the-fact may itself be confusing.

A third approach is not to change the frontend at all and round the numbers on the backend. Upside is the user gets to see exactly what they typed, downside is that what's in the backend won't precisely match what's in the frontend, and that strikes me as a huge downside.

**Comment by jeromeleecms** [comment]
I like the idea of not having decimals since that falls in line with what we've asked states to avoid with HITECH APDs. 

Need some design input here too (@lauraponce?) - to minimize user frustration, can/should we have the system inform the user that decimals are invalid in dollar fields (like a client side validation / pop-up notification)?

**Comment by mgwalker** [comment]
@lauraponce Do you have thoughts about what might be the best user experience for this one? I think simply not accepting decimals is a pretty standard UX pattern, and I'm a little uneasy about changing the values they entered by rounding them after the fact.

**Comment by mgwalker** [comment]
Holding for #1755. Then we can make a change in the `NumberField` component and get the whole APD at once, instead of having to fix multiple places.

**Comment by lauraponce** [comment]
My concern with not accepting decimals is that if they are typing a number with a decimal and are not watching their screen closely, they can type in $100.70 and it would show up as $10070.

After looking into it, I feel like your second option would be a better way to go from a UX perspective. 

For the states that do like using decimals, they can input the exact amount and we'd do rounding for them so it would take the burden off of them to do it (less room for human error). Also, people are not very surprised if an input field gets rid of leading zeros or changes 10 to 10.00 in finance apps, so it seems reasonable to think it'd be a similar expectation for rounding.

We could even add in some help text and/or mention it as part of the training materials that MeT is creating to use rounded numbers or expect the system to round for you.

One con is that some state users use exact amounts in their spreadsheets so the numbers in the eAPD tables might be slightly off, but this really applies to all rounding.
