### ISSUE TITLE
Line items in Summary Budget Table are blank while the subtotal is showing the correct dollar amount

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1740]
When dollar amounts are entered in the activity section for project state staff, contracted resources, or non-personnel, those lines show up as $0 in the Proposed Budget Table while the subtotal line adds up to the expected numbers. 

![Screen Shot 2019-07-31 at 12 13 20 PM](https://user-images.githubusercontent.com/21222704/62240837-b2ea3e80-b38c-11e9-9a5c-547f0a9ff15c.png)

### This task is done when...
 - [ ] The individual table rows for state staff, contracted resources, or non-personnel are showing the correct dollar amounts as expected

**Comment by lauraponce** [comment]
After some troubleshooting with the team, it appears that the table populates correctly if there are dollar amounts in activity 1 but the tables shouldn't be dependent on that.

**Comment by lauraponce** [comment]
Steps to reproduce:

1. Create a new APD
2. Add a second activity 
3. Go to In-House Cost Categories
4. Add $1000 for Costs with benefits for 2019 and 2020 and add 2 FTEs for 2019 and 2020
5. Go to the Summary Budget Table and see that the line items don't show up correctly, but the subtotals work. (Also applies to the Quarterly Federal Share table)

**Comment by mgwalker** [comment]
The budget calculation is getting a `NaN` value somewhere and throwing everything else off. My initial guess is that if one of those values is _blank_, it's not being treated as zero. I'll dig in some more, but if that's the case, it should be a fairly simple fix.
