### ISSUE TITLE
Collapsed APD key personnel only shows TOTAL cost, not cost by year

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1747]
When users enter APD key personnel, they can add costs for that personnel, for each fiscal year covered by the APD. However, when they're done and collapse the personnel, the review view only shows the total cost across all years.

![screenshot showing a key personnel in review mode](https://images.zenhubusercontent.com/5707ce4abf93871ccd9917fb/e3d4512a-82f3-4199-8711-2d516db197e3)

In print view, this means it's impossible to track those costs on a year-by-year basis and make sure they land in the tables correctly.

I think the review view should also show the costs per fiscal years.

### This task is done when...
 - [ ] the key personnel review component shows costs per fiscal year as well as the total

**Comment by jeromeleecms** [comment]
Reference contract and state personnel for existing design.
