### ISSUE TITLE
Gather up-to-date descriptions of Medicaid conditions

### ISSUE THREAD

**Issue by nicoleslaw** [18F/cms-hitech-apd#175]
Describe the task here, including any supplemental information.

### This task is done when...

 - [x] Nick collects the content for the 11 conditions
 - [x] Content is in the doc: https://docs.google.com/document/d/1PjbmxnxnCxE7RrQwm0pIWy_xAs7pX2olD03zgp8JAN4/edit#heading=h.1w89ewpdilim
 
cc @quarterback for reference

**Comment by NAretakis** [comment]
[Created a separate doc here](https://docs.google.com/document/d/1fhzlAzDJDb-9WWM31EPlRaS1nxcxfV6PIWdKc-WTag4/edit#), that has the content. I've also copied it into [the content exploration doc here](https://docs.google.com/document/d/1PjbmxnxnCxE7RrQwm0pIWy_xAs7pX2olD03zgp8JAN4/edit#). Closing!
