### ISSUE TITLE
APD key personnel asks for percentage of time, but entry field is a plain text input

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1753]
We should mimic the percent input field from the quarterly FFP share table, where we include a percent sign at the end. It'll require either duplicating some CSS or refactoring the classes a bit (the latter makes more sense to me). We could also consider adding a `<PercentField>` component, but I think there are only these two instances of it so maybe better to just leave it for now.

### This task is done when...
 - [ ] the APD key personnel "percent commitment to program" input field has a percent sign mask

**Comment by mgwalker** [comment]
See here for a fancy CSS class that we already have for styling this thing:
https://github.com/18F/cms-hitech-apd/blob/master/web/src/styles/scss/forms.scss#L103

**Comment by jeromeleecms** [comment]
This is usability issue.
