### ISSUE TITLE
Short Activity Overview section exporting with scroll bar

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1767]
ID discovered that the short activity overview section is not exporting to PDF correctly. If they include lots of narrative, the box changes to a scrolling box. However, when exporting, the box does not auto-expand like other long boxes, but instead shows a scroll bar that is unable to scroll (because its a PDF).

![image.png](https://images.zenhubusercontent.com/5c536083d11206601037eb29/e11c2588-932b-48dc-bcd1-235156a0f0b0)

### This task is done when...
 - [ ] export to PDF auto-expands the short activity section removing the need for a scroll bar

**Comment by jeromeleecms** [comment]
@hbillings @mgwalker Thoughts on this one? This is keeping the Federal reviewer from completing their review - so we entered this in as Sev 1 bug.

**Comment by jeromeleecms** [comment]
Tried with Chrome and Internet Explorer - both had some results.
