### ISSUE TITLE
Broken Aria References within APD Builder

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1781]
Per Wave: An aria-labelledby or aria-describedby reference exists, but the target for the reference does not exist.

Rationale:

*Why It Matters*
ARIA labels and descriptions will not be presented if the element referenced does not exist in the page.

*How to Fix It*
Ensure the element referenced in the aria-labelledby or aria-describedby attribute value is present within the page and presents a proper label or description.

*The Algorithm... in English*
An element has an aria-labelledby or aria-describedby value that does not match the id attribute value of another element in the page.

### This task is done when...
 - [ ] WAVE (or comparable testing tool) does not report this error
 - [ ] Someone else has looked at/approved the code

**Comment by mgwalker** [comment]
There are 95 of these, and they are ***ALL*** on the rich text editor. 😬

**Comment by hbillings** [comment]
![lulz](https://media1.tenor.com/images/5bab3fd00a4461d07e44c5aa82e3f049/tenor.gif?itemid=4993318)

**Comment by hbillings** [comment]
![lulz](https://media2.giphy.com/media/1YYNnvecqkm4M/giphy.gif)
