### ISSUE TITLE
Add update button/link to state dashboard

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1782]
From the update experience usability testing that we conducted in MESC, it was clear that users expected to see an update call to action rather than the `create new` button to take them to the update experience. 

### This task is done when...
 - [ ] Mock up of updated dashboard with `update` call to action has been created
 - [ ] Designs have been shared and approved by product

**Comment by beparticular** [comment]
Added this to the UER mural and closing
