### ISSUE TITLE
Refine the design of the activities section of the app

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1790]
### Background 
In multiple rounds of usability testing and interviews, state users have been confused by the current implementation of the activities section. The most recent research is [synthesized in this Mural](https://app.mural.co/t/gsa6/m/gsa6/1565221073087/af7440229ec464a7b6ad3973d2f84ea94aafee3b).

**Some of the biggest opportunities for improving the way the activities section works are**:
- Make it easy and obvious how to edit and delete an activity
- Communicate that the first activity is not removable (or solve for this another way)
- Make it possible to escape/cancel out of adding a new activity if you change your mind
- Allow users to rearrange the order of activities
- Let users easily see the full view of all the activities
- Differentiate the short activity summary from the detailed summary in a clear way

**Considerations**:
- Move the activity start and end date up to the top of the activity section so that it's not confused with the milestones/goals
- Add help text for what date to put in (and what to do if there is no end date)
- Keep in mind that there are more improvements to the activity section happening in #1567 for the Goals and Benchmarks subsection

### Screenshots
The current mechanism for editing and deleting takes place in the top section for adding the activities initially:

![Screen Shot 2019-09-04 at 4 30 56 PM](https://user-images.githubusercontent.com/21222704/64300391-6799f180-cf31-11e9-8896-7bf1805610f6.png)

The activity start and end dates are entered in between benchmarks and milestones:

![Screen Shot 2019-09-04 at 4 32 22 PM](https://user-images.githubusercontent.com/21222704/64300518-ebec7480-cf31-11e9-96ed-d261aead4421.png)

The only ways to close out of an activity are by clicking the Close button at the top or the Done button at the bottom of the section:

![Screen Shot 2019-09-04 at 4 35 18 PM](https://user-images.githubusercontent.com/21222704/64300562-1e966d00-cf32-11e9-886e-099429a35442.png)

![Screen Shot 2019-09-04 at 4 35 33 PM](https://user-images.githubusercontent.com/21222704/64300560-1b02e600-cf32-11e9-919f-ffba83065d90.png)

### This task is done when...
 - [ ] There is a mock-up of the reimagined activities section that can be tested with users
 - [ ] The design is shared out with the team and approved by product

**Comment by lauraponce** [comment]
@quarterback and I are tackling this issue together in [this Mural](https://app.mural.co/t/gsa6/m/gsa6/1567546533952/9092ee01dd2246c1f8ab287b81fc247aa5570ad3).

I'll be working through the design iterations at the top of the Mural, and Ron is going to map out the current content for the Activities section and work through the ordering/organizing the questions and wording.

**Comment by lauraponce** [comment]
I'm working through some iterations of the secondary navigation within the activities modal. Here's a version that matches the same styling and interactions as the main nav:

![Screen Shot 2019-09-09 at 4 41 15 PM](https://user-images.githubusercontent.com/21222704/64573591-b4f6d400-d320-11e9-81c2-533704973c75.png)

![Screen Shot 2019-09-09 at 4 41 28 PM](https://user-images.githubusercontent.com/21222704/64573597-b922f180-d320-11e9-8d83-7b67693748b8.png)

@jeromeleecms I'm going to try and steal some parking lot time on Tuesday to get some quick feedback on this direction from the team.

**Comment by lauraponce** [comment]
Adding a new activity: 

![Screen Shot 2019-09-09 at 5 29 41 PM](https://user-images.githubusercontent.com/21222704/64575323-17070780-d328-11e9-96dc-a037008666ac.png)

![Screen Shot 2019-09-09 at 5 30 33 PM](https://user-images.githubusercontent.com/21222704/64575326-19696180-d328-11e9-965d-2f4676198aa2.png)

**Comment by quarterback** [comment]
Looking at the copy sections of these areas, I'm wondering whether the issue is to change the styling of helping text, subsections to be easier to decipher. Or if the issue is with clarity. Or perhaps both. Standards & Conditions help text, I'm wonder if we can test with it removed and see how it changes things. It'll certainly clean that section up. 

We can follow through with that across the app, removing template language in sections since they're using the template to complete the sections and eliminate the redundancies. The density of the language makes it wonder if plain language-ifying it (which I've resisted from the outset) would render them less effective. 

<img width="728" alt="Screen Shot 2019-09-09 at 11 27 51 PM" src="https://user-images.githubusercontent.com/4461062/64589244-821d0200-d359-11e9-9b46-cf8f4d8009c5.png">

**Comment by quarterback** [comment]
**Some style prototyping **
- Removing blue help text entirely. If it's pulled from the template and reviewers are using the template when filling out eAPD, how helpful is it? We initially envisioned it in a world where they weren't using it, but that doesn't seem to be the case from testing. We can clean up those sections and determine if/what is really necessary for text.  

- Making text beneath sections italicized
<img width="354" alt="Screen Shot 2019-09-10 at 4 41 59 PM" src="https://user-images.githubusercontent.com/4461062/64657821-f0a9a080-d3e9-11e9-83f1-1b789cdb93b6.png">

**Comment by lauraponce** [comment]
I've been kicking around some ideas about how to optimize the order of the Activity subsections so that it flows better and to solve for some of the issues users were having. 

The key changes include:
- Moving activity start and end dates to the overview
- Switching the order of detailed summary and short summary
- Removed the Activity Schedule section since the start/end dates are in the overview, and moved milestones into the Performance goals and benchmarks section
- Moved Alternative considerations to the bottom before S&C

I didn't make any changes to the other sections yet because I wanted to get feedback on this so far 💭 

![Screen Shot 2019-09-17 at 5 04 30 PM](https://user-images.githubusercontent.com/21222704/65088193-442d6880-d96d-11e9-8f77-1fe058be8c98.png)

@jeromeleecms @quarterback 👀

**Comment by lauraponce** [comment]
Closing in favor of new epic: https://github.com/18F/cms-hitech-apd/issues/1852
