### ISSUE TITLE
Show the math that is happening in the background

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1792]
Through user research, we've learned that users love automatic math (yay!), but they want to understand what calculations are happening behind the scenes.

These are the three main tables that could use some additional clarification for what math is happening.

1.  Summary Budget table:

![Screen Shot 2020-01-24 at 3 36 45 PM](https://user-images.githubusercontent.com/21222704/73111497-5c833600-3ebf-11ea-8625-088dc409cbc1.png)

![Screen Shot 2020-01-24 at 3 38 14 PM](https://user-images.githubusercontent.com/21222704/73111563-95bba600-3ebf-11ea-89b9-06612bc6b20e.png)

2. Program Budget table (in Executive Summary):

![Screen Shot 2020-01-24 at 3 39 29 PM](https://user-images.githubusercontent.com/21222704/73111607-bedc3680-3ebf-11ea-9994-36c1f754692e.png)

3. FFP Cost Allocation

![Screen Shot 2020-01-24 at 3 41 56 PM](https://user-images.githubusercontent.com/21222704/73111669-137fb180-3ec0-11ea-9c62-1f3bd14a845c.png)

### This task is done when...
 - [ ] There is a mock up of showing the math
 - [ ] The design has been shared with the team and approved by product

**Comment by lauraponce** [comment]
Note from #1935

Add a short narrative to explain cost calculation in paragraph format, for example:
>The total cost of the Auditing activity is $1,000. Because of other funding of $100, the total cost to Medicaid is $900. This activity is using a 90/10 funding split, resulting in a federal share of $810 and a Delaware share of $90.

**Comment by lauraponce** [comment]
I'm approaching this issue table by table since there's some variance in the types of calculations happening between the different tables. 

@jeromeleecms what are your thoughts on something like this?:

![Screen Shot 2020-01-22 at 5 12 08 PM](https://user-images.githubusercontent.com/21222704/72948557-5adc3580-3d3a-11ea-9b49-3ac5ae4fb9cc.png)

I moved the total amounts to the left since we already know those numbers, and the kept the final calculated amounts in the bottom so it was clearer what the new numbers are. This also includes the `x` and `=` signs to show what math is happening.

**Comment by lauraponce** [comment]
@mgwalker is going to take a crack at some of these

**Comment by mgwalker** [comment]
Some hypotheses:
- If we show a review component of the APD key personnel in the first activity's state personnel section, that will help users understand that's where those costs show up
- The summary budget table we have now is useful to CMS and possibly for internal use at the state, but may not be useful to the state analyst who is creating the APD. The table shows Medicaid, federal, and state shares of each expense type, but that might be a level of detail that isn't useful to the person entering the data. Instead, it might be better to show absolute totals of those costs and only show the Medicaid, state, and federal shares of totals.
  - The readonly/print view would still show the current table, since that one is meant for CMS and may be used by states for their internal purposes.
- The summary table totals should probably show full dollar amounts always and never show the shortened "$56k" style. I'm not so sure about the other rows.

Thinking something like this to go on the cost allocation/FFP page. The idea is to show where all the numbers come from at once:

![screenshot of activity cost summary table](https://user-images.githubusercontent.com/1775733/73285065-14179100-41bb-11ea-993d-19d611d0b706.png)

**Comment by mgwalker** [comment]
Here's my initial proposal for the new FFP section.

![ffp tables](https://user-images.githubusercontent.com/1775733/74359069-30edc000-4d88-11ea-9a21-564b15f398e4.png)

 It begins with a big costs summary table that borrows from @lauraponce's original idea of putting math symbols directly into the table. I played around with making parts of the table collapsible to save space, but I thought it might be nice to leave it open so users will always see see this final activity review in full (even if they choose not to actually pay attention to it).

I pulled the "other funding" and "federal-state split" inputs out of the table. When I put them in the table, they were kind of small and it was easy to miss them. I was worried users wouldn't see them at all and would be left wondering where to set them. Pulling them out adds a break to the big table to hopefully make it more clear that the user can do something there.
- I wonder if making the help text block narrow would also help to draw focus. Right now it's the same width as a table row so it still kinda blends into the table.

The table and inputs flow in a progressive way. That is, they get more specific as you go along, and only ask for information from the user at the last moment before it's needed. It feels like a logical way of thinking about the information.

I added some placeholder text to describe the quarterly FFP table (see #2057).

I made the all-years summary into a text narrative, hoping that the relationship between the numbers might be clearer with more words to describe them. I'm not convinced this is actually better than a table.

**Comment by mgwalker** [comment]
I think this is ready for @jeromeleecms and @lauraponce to weigh in on. We could probably spin up a few dev tasks from this.

**Comment by lauraponce** [comment]
@mgwalker The math is finally making sense to me 😄 I haven't seen it spelled out so clearly from start to finish until now so TIL how the math works! 

I like the reasoning behind separating out the other funding table and making this whole section flow logically — that does seem to work really well.

The only feedback I have is for tightening up the layout since the other funding table and the fed/state split tables are spread out — I'd recommend either moving the operators closer to the number that is used in the calculation instead of centering or even just narrowing the whole table.

I think the column headers are helpful in the first table, but since the FTE column isn't _just_ FTEs and you have the units for each row, what do you think about leaving the overall column header off for that? And possibly adding a `Total cost` title to the third column?

**Comment by mgwalker** [comment]
Created dev issue #2074 for implementation. I think we're ready to close this one!
