### ISSUE TITLE
Quotes from the Future exercise

### ISSUE THREAD

**Issue by nicoleslaw** [18F/cms-hitech-apd#18]
Imagine that we’ve shipped the MVP of the HITECH APD app. What are people saying about it?
Copy and paste the following template into the comment field below, and add your answers inline. (You can edit your comment after posting!)

```
## State users are saying...

## CMS analysts are saying...

## CMS leadership is saying...
```

**Comment by jeromeleecms** [comment]
## State users are saying APD's, what's that? We just use this system and we get funding approval in less than two weeks.

## CMS analysts are saying the tools we have help us focus on helping states do their work and not on their administrative correctness. Why did it take so long for someone to create this?

## CMS leadership is saying, can we roll this out to every part of CMS? APDs complaints and turn around times are a thing of the past. The change happened overnight.

**Comment by mgwalker** [comment]
## State users are saying...
* Gosh, this sure takes a lot less time to write!
* It's really great how I don't have to submit the same thing over and over.
* It's nice knowing exactly CMS wants.
  * (☝️  that seems less like an issue in HITECH than MMIS)

## CMS analysts are saying...
* Gosh, this sure takes a lot less time to review, and all the numbers add up!
* We can quickly see how much money we've already approved for a state.
* Having a consistent thread over time is really helpful.
* The states don't view us as a hurdle to clear anymore.

## CMS leadership is saying...
* Gosh, we can answer data calls really fast!
* It was a smart move to let Jerome and Nick lead this work, and we should totally extend it to E&E and MMIS.  (🤞)

**Comment by nkkl** [comment]
## State users are saying...
- APDs get turned around so quickly now!
- We don't need full-time staff or vendors to write APDs anymore

## CMS analysts are saying...
- We have so much confidence in our state partners
- We get to spend more time helping states and less time enforcing regs and tracking numbers

## CMS leadership is saying...
- We're doing really well at customer service
- We know where every dollar is
- This should extend beyond HITECH

## State governors are saying...
- We get our Medicaid money so quickly now

**Comment by mkhandekar** [comment]
## State users are saying...
* I have so much more time on my hands, I now get to spend it with my loved ones
* I don't have to keep doing the same things over and over
* In the end, we get to our money faster
* We get to see faster results for our state's residents!

## CMS analysts are saying...
* We have so much more time on my hands, I now get to spend it with my loved ones
* We am more in attuned to what states need and how to support them

## CMS leadership is saying...
* We're going to fund an extension of this work
* Jerome and Nick have been excellent stewards of this work

**Comment by NicolasAretakisCMS** [comment]
CMS analysts are saying "I can take a vacation and I don't feel bad anymore sticking Jerome et al with work!"

**Comment by jeromeleecms** [comment]
These APDs seem like they write themselves... because they do!
