### ISSUE TITLE
Schedule and draft agenda for stakeholder demo

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#181]
Scheduling demo time with, Carrie, Marty, Eg, Sam, and Dzung.

### This task is done when...
 - [x] Meeting is scheduled
 - [x] Agenda is drafted
 
 ** don't forget to fill out the LABEL, MILESTONE, and PROJECT sections before submitting (then delete this line) **

**Comment by nkkl** [comment]
@NAretakis would you rather do the week of the 19th or the week of the 26th?

**Comment by NAretakis** [comment]
@nkkl week of 26th, so that we will have completed the previous sprint. I think that works.

**Comment by nkkl** [comment]
Sounds good!

**Comment by NAretakis** [comment]
I'll draft agenda today.

**Comment by NAretakis** [comment]
Agenda:
1.	Overview of goal and scope
2.	Meet the team (virtually)
3.	Progress to date:
a.	2 out of 4 milestones completed
b.	prototype on cloud
c.	state testing and input
d.	Authority to Operate underway
