### ISSUE TITLE
Procurement (Test)

### ISSUE THREAD

**Issue by randyhart** [18F/cms-hitech-apd#1812]
Describe the task here and link or add dependencies to any applicable issues...

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
*Add a LABEL (design, dev, compliance, BUG, etc) before submitting.

*If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for PRODUCT to prioritize.

**Comment by jeromeleecms** [comment]
We are moving procurement content to a separate area.
