### ISSUE TITLE
Implement additional help text less obstrusively

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#1817]
We removed help text in PR #1816 to test how users might interact with _less_ content, given the user cases are different. In this issue, we're writing to revert those changes in some way or to design a better way of displaying that information so that it's available for users without showing every time.

This is probably a tandem issue. 

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2

**Comment by beparticular** [comment]
We have some other issues in place to work on this type of thing, as well as noting it would be nice to do some research around help text. Closing per Jerome.
