### ISSUE TITLE
Convert Goals and Objectives Section to align with Objectives and Key Results

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1819]
Per leadership request (and it just makes sense!), content should do a review of the language in the Goals and Objective Section and revise it to align with CMS' move towards utilizing Objectives and Key Results. 

Primer on OKR: https://felipecastro.com/en/okr/what-is-okr/
 
### This task is done when...
 - [ ] @NAretakis has provided some feedback to team about what is expected from OKRs
 - [ ] Content has had a chance to review current state and see what needs to be done
- [ ] Design (user interaction) and Dev are consulted as needed if changes outside of content are required
- [ ] Appropriate issues/pull requests are added to appropriate sections

**Comment by quarterback** [comment]
Pull this to start working on this afternoon. Will pull down the content and push something to review.

**Comment by jeromeleecms** [comment]
@quarterback Does this have any overlap with #1407? Is seems like this is solving for a similar idea -- what are we try to do? How will me measure?

**Comment by quarterback** [comment]
I'd surely be up for merging those issues or closing #1407 in favor of this one.

**Comment by quarterback** [comment]
@NAretakis @jeromeleecms I'm going to rewrite this section contentwise, but if we feel like it needs to do _more_ than just that to be line with the OKR framework, then we'd need to implement some kind of design change. Right now, my changes will focus on try to use OKR language to better help people understand what's being asked of them.

**Comment by quarterback** [comment]
<img width="661" alt="Screen Shot 2019-09-24 at 9 52 12 AM" src="https://user-images.githubusercontent.com/4461062/65533654-ea6bf780-deb2-11e9-92ca-7a9b7d87c871.png">
<img width="575" alt="Screen Shot 2019-09-24 at 9 52 19 AM" src="https://user-images.githubusercontent.com/4461062/65533655-ea6bf780-deb2-11e9-85ec-5a423f39f82e.png">

These aren't accurate anymore because I just pushed a new change that removes that goal content to the goals section (previously, there was no content there at all before...) which should make it easier to navigate. But it's more direct (consistent with our style guide)

**Comment by jeromeleecms** [comment]
@NAretakis Will provide some language around OKRs

**Comment by jeromeleecms** [comment]
@NAretakis Any thoughts/updates?

**Comment by NAretakis** [comment]
Yes! Thoughts:

The most important part of OKRs is that the objectives are clear and that the key results are measurable. To that end, I think the free text boxes are okay (maybe eventually we make them percentage completion type things). What I have in my mind for this is something like:

Replace "Goal Name" with:
Objective: [free text field - should not be too many characters]

Replace "Benchmarks" with:
Key Results: [free text with some measurable component - often we see this as percentages]

Example of this is below:

**Objective:** Improve emergency alerting adoption
**Key Result:** Deploy HIE emergency alerting application [0% - 100%]
**Key Result:** Enable EMS alerts for X percentage ambulatory services [0% - 100%]
**Key Result:** Enable EMS alerts for X percentage of emergency departments [0% - 100%]

What do y'all think on the above?

**Comment by lauraponce** [comment]
Here is a mockup with the updated fields:

![Screen Shot 2019-11-01 at 8 53 58 AM](https://user-images.githubusercontent.com/21222704/68037547-387bd400-fc85-11e9-98ae-5f08bdf6f581.png)

Open questions:

1. Do we need to separate out each key result or group them in a single textbox?
2. I'm not sure what the percentages refer to, but is it something that we need to ask for explicitly or is it something they will include?
3. What help text do we need? In this version, I just repurposed the existing content.

Feedback on this? @NAretakis @jeromeleecms

**Comment by jeromeleecms** [comment]
1. My personal preference would be to have each key result as a separate item. During the update experience, this should force the user to be able to report at each one in turn (and it's traceable!). Not sure how much of a dev lift this would be though (@mgwalker @hbillings?). If it's a huge change, I would be OK with Nick's suggestion of just keeping it as one text box, though that will make the reviewers life a little harder having to make sure the start is reporting on the Key Results.
2. The Key Results in the "Measure What Matters" book references that Key Results should be able to be measured someone (sort of like the SMART Goals concept). SMART = Specific, Measurable, Achievable, Relevant, and Time Bound. That way users/reviewers can assess if the state is making progress toward the objective. 
3. The additional piece I would add to the help text is to show how the Key Result supports the objective (i.e. Relevant). I would support using the SMART framework as help text.

@NAretakis other thoughts?

**Comment by lauraponce** [comment]
Adding in the feedback from our latest round of research where we tested this new section:

**Usability testing findings**
- The list of objectives that were already entered wasn’t obvious
- Expected “add another” interaction to be same as adding new activity
- Users think it might be hard to come up with percentages
- States want to make the measure as generic and non-meaningful as they can. CMS should want it to be as specific as possible.
- One person didn’t think the name of the milestone is descriptive enough without adding additional detail

**Recommendations**
- Add “Objective” label for the list of already-entered objectives
- Add help text around key results to make it easier to enter percentages (#1933 has been created for this)

**Comment by lauraponce** [comment]
Scheduled a sync for Thursday this week with Nick and Jerome to hash out the needs for the Objectives and Key Results section.

**Comment by lauraponce** [comment]
@jeromeleecms here is v2 of the OKR section. I updated the instructions, help text, and reorganized the layout for entering the content.

<img width="380" alt="Screen Shot 2019-12-09 at 11 42 41 AM" src="https://user-images.githubusercontent.com/21222704/70547605-07b17900-1b26-11ea-8afe-a8b5d1543633.png">

When users click "add another key result" it opens up below to add an additional one:

<img width="391" alt="Screen Shot 2019-12-09 at 11 44 58 AM" src="https://user-images.githubusercontent.com/21222704/70547612-0a13d300-1b26-11ea-9092-1738ff590d6e.png">

How does this seem?

**Comment by jeromeleecms** [comment]
1. Can we include help text under "Objective" (similar to what you have under Key Result and Measure)? Or if that makes it too cluttered, what do you think about moving all the help text to the top of this section? 
2. How would we capture this in the current layout: "Onboard 60% of EMS providers by the end of FFY 2021, Currently at 0%." Four fields? Objective, Key Result, Measurement, and Baseline?

Just some additional reference material, from the Measure What Matters website which references the Google OKR Playbook (https://assets.ctfassets.net/cn6v7tcah9c0/4snZXJ821G6KYUoc08masK/58ffcbc7c607d7c6056c7da507727135/Google_OKR_Playbook_V1JS.pdf) 

Objectives are the “Whats.” They:
— express goals and intents;
— are aggressive yet realistic;
— must be tangible, objective, and unambiguous; should be obvious to a rational observer whether an objective has been achieved.
— The successful achievement of an objective must provide clear value for Google.

Key Results are the “Hows.” They:
— express measurable milestones which, if achieved, will advance objective(s) in a useful manner to their constituents;
— must describe outcomes, not activities. If your KRs include words like “consult,” “help,” “analyze,” or “participate,” they describe activities. Instead, describe the end-user impact of these activities: “publish average and tail latency measurements from six Colossus cells by March 7,” rather than “assess Colossus latency”;
— must include evidence of completion. This evidence must be available, credible, and easily discoverable. Examples of evidence include change lists, links to docs, notes, and published metrics reports.

**Comment by lauraponce** [comment]
@jeromeleecms here are a couple options for reworking this section and adding in the additional field to separate target from the baseline:

### A. With hint text below objective 

<img width="363" alt="Screen Shot 2019-12-12 at 7 19 09 PM" src="https://user-images.githubusercontent.com/21222704/70766949-50c72000-1d14-11ea-8316-6e03f8b1d2cc.png">

### B. Hint text removed and longer instructions at the top

<img width="365" alt="Screen Shot 2019-12-12 at 7 17 57 PM" src="https://user-images.githubusercontent.com/21222704/70766908-28d7bc80-1d14-11ea-91ca-509331f95c80.png">

Thoughts?

**Comment by jeromeleecms** [comment]
Option A seems to express help closest to where it's needed (though I do like the clean look of Option B). 

In regards to wording (happy to also offer this up to other to review) - also, are we using 2nd person in our help text.. feel free to modify or we can talk through during parking lot time.

Objectives and Key Results
Please describe how you will achieve the stated purpose of this activity, as described above, in terms of Objectives and Key Results (OKRs). Describe **what** you are trying to achieve (Objective) and **how** you will show you have achieved the goal (Key Result). Where possible, Key Results should be written as specific, measurable, achievable, relevant, and time-bound (SMART).

Objective
Please describe what you are trying to achieve. 

Key result
Please describe how you will measure progress towards achieving your objective. 

Target
Please provide a numerical measure for your key result.

Baseline
Please provide where you are with this goal now. Use the same units as your target.

**Comment by lauraponce** [comment]
That text seems much clearer, thanks for helping me think through that 😅 

I removed "Please" from the beginning of the hint text since we don't use that anywhere else is the app content and are more direct with the instructions. 

How does this seem with those edits?

![Screen Shot 2019-12-16 at 10 00 41 AM](https://user-images.githubusercontent.com/21222704/70930831-f61b1600-1fea-11ea-8f9c-42ad9785d5e1.png)

**Comment by jeromeleecms** [comment]
Last two things:
1) For the target and baseline help text, let's add "If applicable" or "Where applicable" somewhere - we might not always have a number associated with it (see example below)
2) Let's also update the example as well (let me know if this is too long and I can try to streamline this)...

Objective: "Increase availability of standards compliant Admit, Discharge, and Transfer messages within the 10 counties within the state."
Key Result: "Define priority order of counties within the state."
Key Result: "Expand ADT connections to top 3 counties by end of FFY 2020"
Key Result: "Expand ADT connections to top 8 counties by end of FFY 2021"

Let me know if you want to talk through this.

**Comment by lauraponce** [comment]
1. Added!

2. For the help text, I think it'd be most useful to state users if we spelled out what the example would be for each of the fields. What do you think about condensing it to this?

I also added it in to the section below to see how it'd look for an objective with multiple key results. 

![Screen Shot 2019-12-16 at 11 41 17 AM](https://user-images.githubusercontent.com/21222704/70937373-ffab7a80-1ff8-11ea-8494-e6764c1749e5.png)

**Comment by lauraponce** [comment]
@hbillings here's the final mock up of the OKR section:

![Screen Shot 2019-12-16 at 1 48 17 PM](https://user-images.githubusercontent.com/21222704/70945768-bd8b3480-200a-11ea-91eb-bdb5952e8bbe.png)
