### ISSUE TITLE
Initial pass at field instructions

### ISSUE THREAD

**Issue by nicoleslaw** [18F/cms-hitech-apd#182]
Walk through the prototype and compare the field lengths with actual APD content and the [APD guidelines](https://docs.google.com/document/d/1yhP0rgbV9UUE10FOhN6eft-OpTYaP30GeEgfAhClgx8/edit). Think about ways to better set expectations about what kind of information we need (both in text length and potential guidelines for data entry).

### Related issues
 - #191 Help text in activity, goal, objective section
 - #190 Revise language in activity, goal, objective section

### This task is done when...
 - [x] Ron has documented ways to improve the field length as an affordance to help users know how much to write
 - [x] Ron has documented some initial inline text

**Comment by nicoleslaw** [comment]
cc @brendansudol @mgwalker as FYI

**Comment by quarterback** [comment]
Mocked some screens to expand size of form fields inside APD v1 document.
