### ISSUE TITLE
Explore options for changing the unique ID of the APDs 

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1821]
Right now the unique ID keys off of the creation date rather than the submission date. In our pilot research, it came up that some users weren't sure what the date referred to and federal reviewers preferred to have the submission date because it matches how the SEA tool works.

The goal of this issue is to find a better way to identify the APDs rather than use the creation date.

If the date in the name of the APD is going to be removed, how will they be uniquely identified? What will the dashboard show when a new APD is created?

### This task is done when...
 - [ ] There is agreement on how to handle the APD IDs in a way that works for states and reviewers

![Screen Shot 2019-09-16 at 4.09.00 PM.png](https://images.zenhubusercontent.com/57f4106595e42b6c5ba9e43c/6d6fee96-643a-4982-bdbb-6b14ba5f259f)

![Screen Shot 2019-09-16 at 3.50.19 PM.png](https://images.zenhubusercontent.com/57f4106595e42b6c5ba9e43c/d916599a-7684-463c-bdd2-7a1dd16ee639)

**Comment by lauraponce** [comment]
Cross-posting @jeromeleecms's comment from #1820 :

 This is not prescriptive redesign directive, but if remove the unique identifier and add the dates, we can also think about how this scales for other types of APDs (sample rework of how it might look). In lieu of Implementation, we could simply put Planning or Operation...

![image](https://user-images.githubusercontent.com/21222704/65072398-abcfbd80-d945-11e9-9d26-a5355bf9e238.png)

The State name appears duplicative but makes sense since we need it for exporting the document to PDF.

Also, when we export, can we add the final name to the header where it currently resides? Sounds like a separate issue, but just documenting it here.

**Comment by mgwalker** [comment]
A note for dev: this ID is called `name`, it's set when the APD is created (`/routes/apds/post.js`), and the API endpoints for editing APDs don't allow the name to be modified (since it should be immutable).

In other news, how would we feel about an ID that was something like `adjective-animal`? It seems silly, but it's easy to recognize and talk about. "Oh hey, did you submit `fuzzy-pangolin` yet?"

**Comment by lauraponce** [comment]
Using the criteria for the ID that it should be:

- Unique
- Automatically-generated 
- Decipherable  

Here are a couple of options:

### 1️⃣ 2022 TX HITECH 2
`latest year that the APD covers` | `state` | `type of APD` | `number in sequence for APDs that have the same year, state, AND type`

Pros
- It's easy to see what this APD is about from the title
- The numbers at the end won't get too long because it will start over with each new year, state, and/or type of APD

Cons
- Users might not know intuitively what the year signifies (that it's the final year the APD covers), but it is probably something they could learn quickly
- Will need to ask users upfront what years the APD covers before creating the ID and will require adding in new functionality (and testing it)

### 2️⃣ TX HITECH 8
`state` | `type of APD` | `number in sequence for APDs that have the same state AND type`

Pros
- It's short and gives just enough information to show the state and type with a unique ID
- If working with just one state, you can reference it with just the number

Cons
- Doesn't give much information about what is in this APD (unless you know where you are in the sequence
- The numbers will continue to grow for each state

### 3️⃣ 1007 TX HITECH
`number in sequence across ALL APDs` | `state` | `type of APD` 

Pros
- Can refer to any APD by just the number since it's unique across all states
- All IDs will be of uniform length

Cons
- The ID is arbitrary and doesn't tell you much about the APD itself from the title
- How many digits does it need to be?

@jeromeleecms, what are your thoughts on these?

**Comment by jeromeleecms** [comment]
I think it may be helpful to parse this out during parking lot time, but some thoughts:

1) We should be careful to not mix the unique ID for the database and the unique name that CMS provides back to state users.
2) The unique name that CMS provides upon submission is based on the actual submission date (which we won't know until the state submits it). In the future state of online submissions, we can automatically apply the name. 
3) The unique name for the database - does that have to be static? Can we apply the "CMS Name" to the unique ID after it's submitted? This seems **not** great solution (@mgwalker?) to change the unique ID mid-flight. 
4) To @lauraponce suggestions -- 1) When will display this to the user?, 2) How would the user know that this is the "latest" version if we use sequence? 

If this is unclear, I can also try to work up some flow diagrams that show this more concisely..

**Comment by mgwalker** [comment]
From dev perspective, we don't care. The ID in the database is assigned automatically by the database and can never be changed, and that's fine! That ID is meant to be used by machines, not people.

Whatever we do on this issue will likely impact the APD's `name` field. It's an arbitrary text field and it should be fine to change it at any time – it's meant for humans, not machines.

**Comment by lauraponce** [comment]
@jerome here are the mockups based on our conversation:

State dashboard:
![Screen Shot 2020-01-03 at 4 12 14 PM](https://user-images.githubusercontent.com/21222704/71756286-d9cd0500-2e43-11ea-887a-c0ede7cbcc10.png)

eAPD builder:
![Screen Shot 2020-01-03 at 4 11 54 PM](https://user-images.githubusercontent.com/21222704/71756288-dafe3200-2e43-11ea-9236-dba7e0cbb58c.png)

Thoughts?

**Comment by jeromeleecms** [comment]
Great transformation from discussion -> visualization @lauraponce!

1) Please include in the dashboard and the APD that the document is an "**I**APD"
2) In the second screen shot, let's precede the years with FFY to be explicit about what the years the APD covers (that tickles my mind about some user feedback we received during one of our testing sessions)
3) From a 508 standpoint, how does a "|" get read by a screen reader? I know it's a visual divider, but may not make sense to someone listening to the title...?

**Comment by lauraponce** [comment]
1. done!
2. done!
3. Good question. It looks like some screen readers will say "vertical line" for the pipe character but there is also a way to turn down the sensitivity for punctuation and special characters so some more experienced users might have that turned off where it'd ignore it. Either way, it doesn't seem like a problem to have it read as vertical line or to ignore it completely.

Here are the updated mockups:

![Screen Shot 2020-01-06 at 10 25 09 AM](https://user-images.githubusercontent.com/21222704/71839188-732c2f00-306f-11ea-8932-50bacc13ec08.png)

![Screen Shot 2020-01-06 at 10 26 56 AM](https://user-images.githubusercontent.com/21222704/71839193-76271f80-306f-11ea-9248-56d0f6f99028.png)

Do we want to call out that it's an IAPD in the builder as well or is that only important for the dashboard?

**Comment by jeromeleecms** [comment]
@lauraponce Great! I'm good with this - time to spin up some dev issues?

**Comment by lauraponce** [comment]
Created #1993 for the dev work
