### ISSUE TITLE
Spike: Explore creating a print preview page

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1822]
User research has uncovered a few things related to PDF display that would be helpful to change. Mostly, these involve changing positioning of elements or tweaking layout, such as moving the executive summary from the bottom of the page to the top. Originally, we intended to do away with the notion of PDF exports once the app supported submission; however, user research indicates that it might be a longer-lived feature than we anticipated. If we intend to continue allowing PDF printing, we will need to address some of these display quirks.

Currently, we use print styles to change how the interactive part of the app looks when printed. But tying the print view to the interactive app is fragile and hard to maintain. It's not a method we want to expand upon, especially when it comes to changing significant parts of the layout. 

So! A lightweight solution might be to create a separate "PDF preview" page that the user can view when an APD is finished. This would give us much finer control over how we display the information input in the previous interactive screen. It would also allow the user to see the finished export in a way that is testable cross-browser (testing native print preview across browsers is difficult, and the size of the PDF can cause the preview to crash sometimes).

We should do a small spike to explore this idea and see how heavy of a lift it would be.

### This task is done when...
 - [ ] we have explored what it would take to build a preview page

**Comment by jeromeleecms** [comment]
maybe move the executive summary to the top of the print preview - with the idea that each section within the app is agile in its location.
