### ISSUE TITLE
Fix horizontal spacing in Activity Overview section

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1828]
In the Activity Overview section for the detailed summary and alternative considerations, the instructions don't extend to the full length like the rest of the instructional text in the app.

### This task is done when...
 - [ ] The horizontal spacing for the overview section is fixed and matches that of other sections
 
![Screen Shot 2019-09-19 at 9.45.49 AM.png](https://images.zenhubusercontent.com/57f4106595e42b6c5ba9e43c/18bdad60-6bc4-4143-9cf5-51cddc8d7eda)

**Comment by hbillings** [comment]
I'm wondering if this is a caching issue or something? When I run this locally, the label is full width for me. 🤔 @lauraponce What instance of the app did you see this on? Prod?
<img width="746" alt="Screen Shot 2019-09-24 at 10 30 06 AM" src="https://user-images.githubusercontent.com/509309/65531088-60259280-deb6-11e9-958e-3ad3c6e97f53.png">

**Comment by hbillings** [comment]
This fix just hasn't made it to prod yet.
