### ISSUE TITLE
Refine the design of the activities section

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1852]
### Background 
In multiple rounds of usability testing and interviews, state users have been confused by the current implementation of the activities section. The most recent research is [synthesized in this Mural](https://app.mural.co/t/gsa6/m/gsa6/1565221073087/af7440229ec464a7b6ad3973d2f84ea94aafee3b).

**Some of the biggest opportunities for improving the way the activities section works are**:
- Make it easy and obvious how to edit and delete an activity
- Communicate that the first activity is not removable (or solve for this another way)
- Make it possible to escape/cancel out of adding a new activity if you change your mind
- Allow users to rearrange the order of activities
- Let users easily see the full view of all the activities
- Differentiate the short activity summary from the detailed summary in a clear way

**Considerations**:
- Move the activity start and end date up to the top of the activity section so that it's not confused with the milestones/goals
- Add help text for what date to put in (and what to do if there is no end date)
- Keep in mind that there are more improvements to the activity section happening in #1567 for the Goals and Benchmarks subsection

### Screenshots
The current mechanism for editing and deleting takes place in the top section for adding the activities initially:

![Screen Shot 2019-09-04 at 4 30 56 PM](https://user-images.githubusercontent.com/21222704/64300391-6799f180-cf31-11e9-8896-7bf1805610f6.png)

The activity start and end dates are entered in between benchmarks and milestones:

![Screen Shot 2019-09-04 at 4 32 22 PM](https://user-images.githubusercontent.com/21222704/64300518-ebec7480-cf31-11e9-96ed-d261aead4421.png)

The only ways to close out of an activity are by clicking the Close button at the top or the Done button at the bottom of the section:

![Screen Shot 2019-09-04 at 4 35 18 PM](https://user-images.githubusercontent.com/21222704/64300562-1e966d00-cf32-11e9-886e-099429a35442.png)

![Screen Shot 2019-09-04 at 4 35 33 PM](https://user-images.githubusercontent.com/21222704/64300560-1b02e600-cf32-11e9-919f-ffba83065d90.png)

**Comment by jeromeleecms** [comment]
Closing this out per Team Discussion.
