### ISSUE TITLE
Switch rich text editor to TinyMCE

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1871]
Build a small prototype for TinyMCE (either standalone or within the app, depending on which is easier/faster) so we can see how it performs on copy/paste as well as get a sense of the level of effort to integrate it with the app.

For #1408

### This task is done when...
 - [ ] a prototype exists and is accessible to the team

**Comment by jeromeleecms** [comment]
After implemented #1913, it seems like TinyMCE is the winner. The library is hosted locally (so no data leaves the site), is accessible (per the TinyMCE docs), and solves a major pain point from our user testing (copy and paste things from Word). 

We do need to do some work with a delay in the iframe loading on the page so it is less jarring for the user, but we have a solution and will document shortly.

**Comment by mgwalker** [comment]
Changed the name of this issue since it's no longer just about prototyping!
