### ISSUE TITLE
[Research] Figure out a level of effort for creating a custom Draft.js editor

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1872]
Nothing to build, just need to spend some time researching what all goes into building a Draft.js editor. Does it have plugins we can use for things like the toolbar? What do we have to implement ourselves? Etc.

If it has simple plugins, also research any that implement copy/paste especially for Word.

For #1408

### This task is done when...
- [ ] We have an understanding of the level of effort requires to build a Draft.js editor
- [ ] We know if it has plugins for Word copy/paste

**Comment by mgwalker** [comment]
A couple of days, probably. We would need to install plugins for the toolbar and the buttons and hook those up, but we shouldn't have to create much new except for an upload button (which we would also need for TinyMCE (#1871)).

**Comment by jeromeleecms** [comment]
We are going with TinyMCE. Sorry draft.js.
