### ISSUE TITLE
Draft an Acquisition Plan

### ISSUE THREAD

**Issue by randyhart** [18F/cms-hitech-apd#1873]
In order to issue an RFx, the FAR requires an acquisition plan. This is dependent on having nailed down a procurement strategy (Schedules? 8(a)? task order off an IDIQ?) and will come after market research and scoping and estimating exercises. This is a pretty long document.

### This task is done when...
 - [ ] We have a finished acquisition plan that complies with [FAR 7.105](http://farsite.hill.af.mil/reghtml/regs/far2afmcfars/fardfars/far/07.htm#P70_13160)
 - [ ] The acquisition plan is included with the RFx that is submitted to the CO.

**Comment by jeromeleecms** [comment]
Migrated and Tracked through an alternative system
