### ISSUE TITLE
Develop IGCE

### ISSUE THREAD

**Issue by randyhart** [18F/cms-hitech-apd#1874]
As part of the ACQ Plan, we will need to develop an Independent Government Cost Estimate based on the expected size and skill mix of the future contractor team. This is dependent on the scope of work being pinned down for what the future contractor will be focused on.

### This task is done when...
 - [ ] We have a spreadsheet of potential hours and skill mix/labor rates.

**Comment by jeromeleecms** [comment]
Migrated and Tracked through an alternative system
