### ISSUE TITLE
User Stories for future contractor

### ISSUE THREAD

**Issue by randyhart** [18F/cms-hitech-apd#1875]
As a team we need to set the backlog of work we will ask the contractor to start on. This is meant for context and to help the contractors get a sense of the work to be done. It should help them to determine the skill mix of labor categories to include in their proposal.
 
### This task is done when...
 - [ ] We have the initial set of user stories to include in the RFx
 - [ ] We know where the current 18F development team's efforts end and where the new contractor's team begins.

**Comment by jeromeleecms** [comment]
Migrated and Tracked through an alternative system
