### ISSUE TITLE
Market Research

### ISSUE THREAD

**Issue by randyhart** [18F/cms-hitech-apd#1877]
This task has dependencies and has other tasks dependent on it.

The basic idea here is to identify the types of vendors that are available that could do great work in continuing the agile software development practices with CMS serving as the product owner.

This issue is dependent on the vision and initial user stories #1875 that are being established for the RFx. Completion of this issue will allow the team to establish the acquisition strategy and vehicle and complete the Acquisition Plan #1873. 

More information on Market Research requirements can be found in [FAR Part 10](http://farsite.hill.af.mil/reghtml/regs/far2afmcfars/fardfars/far/10.htm). It's important to note that 

>The extent of market research will vary, depending on such factors as urgency, estimated dollar value, complexity, and past experience. The contracting officer may use market research conducted within 18 months before the award of any task or delivery order if the information is still current, accurate, and relevant. 

### This task is done when...
 - [ ] The team has identified the right pool of vendors and acquisition strategy for what is being procured.
 - [ ] Pulled this information into the Acquisition Plan.

**Comment by jeromeleecms** [comment]
Migrated and Tracked through an alternative system
