### ISSUE TITLE
Create navigational anchor to give users a sense of where they are in the process

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#188]
In usability testing, participants were distracted by not knowing where in the process they were. We should add some structure so that participants are more comfortable and have a sense of where they in the process and how what they're working on fits in with everything else in the submission.

### This task is done when...
 - [x] One or more potential designs have been sketched
 - [x] A provisional design has been chosen
 - [x] Dev has implemented the chosen design, so that it can be tested

**Comment by lauraponce** [comment]
Moving this to in progress and am working on a wireframe for the nav

**Comment by lauraponce** [comment]
Here is the first pass at a wireframe for the nav based on the USWDS. The actual content for the nav items is just placeholder until we work through that a bit more. @quarterback @brendansudol open to your thoughts on this!

<img width="584" alt="screen shot 2018-03-05 at 9 36 39 am" src="https://user-images.githubusercontent.com/21222704/36980595-c9982fd4-2058-11e8-8cac-ac51487e2d94.png">

**Comment by nkkl** [comment]
@NAretakis @jeromeleecms I've seen the future and it's pretty swanky. ;)

**Comment by quarterback** [comment]
@lauraponce I like that, Laura.
