### ISSUE TITLE
Revise activity, goal, and objective structure

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#189]
Participants had mixed reactions to the way that activities, goals, and objectives were structured, and didn't consistently interpret the relationship between all three.

### This task is done when...
 - [x] One or more potential designs have been sketched
 - [ ] A design has been selected for implementation
 - [ ] Dev has implemented the design so that it can be tested

**Comment by nkkl** [comment]
@lauraponce thoughts about having a design studio around this?

**Comment by quarterback** [comment]
i've modeled a potential design direction that incorporates the feedback we've received: https://docs.google.com/document/d/1C0KvJ5zMuTOIRSTqyHpSZU7T3aLbqm7U4EdJwIynpJw/edit#heading=h.966raiilk6w5

**Comment by brendansudol** [comment]
we did this!
