### ISSUE TITLE
Compile a list of states to learn from

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#19]
We want to create a list of diverse states, who have had many different experiences and face many different challenges, to focus our research on.

### Criteria to consider

- Project Complexity (High/Medium/Low)
- Project Funding and Scope HIT/HIE/MMIS
- Importance to the Project (High/Med/Low)

**[Spreadsheet for research contacts](https://docs.google.com/spreadsheets/d/1vKsi_Tib2SaUpSSUYQoAv3h_tXRB9RDfjgh0bPA3Oj4/edit#gid=0)**

**Comment by nkkl** [comment]
@mkhandekar @nicoleslaw where would you like Nick and Jerome to put this list?

**Comment by nicoleslaw** [comment]
I created a [spreadsheet](https://docs.google.com/spreadsheets/d/1vKsi_Tib2SaUpSSUYQoAv3h_tXRB9RDfjgh0bPA3Oj4/edit#gid=0). Can you take a look before we send it to CMS, @mkhandekar? I want to make sure it's useful for you!

**Comment by nkkl** [comment]
[This comment](https://docs.google.com/a/gsa.gov/document/d/16Yw8jnl0wW6wFA_KvfyCSEjhsT8HPKGs6V1iaBHkLeE/edit?disco=AAAABd4Zm8g) on the framing doc makes me think it would be helpful for us to get sample APDs from these states as well. And maybe a little color commentary from Nick and Jerome about what is helpful and unhelpful within those.

**Comment by mkhandekar** [comment]
@nicoleslaw the spreadsheet works for me!

**Comment by nicoleslaw** [comment]
Hi @jeromeleecms @NicolasAretakisCMS! We set up a [spreadsheet for research contacts](https://docs.google.com/spreadsheets/d/1vKsi_Tib2SaUpSSUYQoAv3h_tXRB9RDfjgh0bPA3Oj4/edit#gid=0). Please take a look and add to it! (And let me know if you have any issues editing the doc.)

**Comment by NicolasAretakisCMS** [comment]
I added a bit, and made a comment on Risk column. Not sure what that is asking. Otherwise it is pretty much ready. As far as sample APDs, we can pull a few, but for those we'll need to be a little more mindful of storing/sharing the info contained. I think we can start with the list of states, and then get the associated APDs as research materials.

**Comment by mkhandekar** [comment]
@NicolasAretakisCMS For the risk/need column, it could be either. Level or risk (for either CMS or state). Level of need (for either CMS or state). Does that help?

Also just checking -- I don't see any other updates (besides the comment) to the spreadsheet.  Are you saying you added a few states and contacts to this list?

**Comment by NicolasAretakisCMS** [comment]
Added a column is all, I haven't input any state info yet.

**Comment by mkhandekar** [comment]
Gotcha! Thank you!

**Comment by NicolasAretakisCMS** [comment]
Requested info from CMS APD team members, waiting on responses, by COB 12/21/17.

**Comment by NicolasAretakisCMS** [comment]
Progress! I have 10 states with info, I'll transpose into the google doc/sheet for everyone to have. Happy Holidays!

**Comment by NicolasAretakisCMS** [comment]
States added to Drive along with some sample APDs.
