### ISSUE TITLE
Revise language in activity, goal, objective section

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#190]
Participants didn't interpret the language in the UI in a consistent way, and were confused about the ways that some content was worded.

### This task is done when...
 - [x] Top problem spots have been identified
 - [x] Draft an updated approach to the language
 - [ ] Implement the new language so that it can be tested

Related to #191

**Comment by quarterback** [comment]
Updated text draft: https://docs.google.com/document/d/1C0KvJ5zMuTOIRSTqyHpSZU7T3aLbqm7U4EdJwIynpJw/edit#heading=h.966raiilk6w5

**Comment by NAretakis** [comment]
I think we're working on this with the branch/PR I took a stab at. @quarterback you OK to take that content + your additions, to the finish line?

**Comment by quarterback** [comment]
@NAretakis there's a pull request with the changes waiting to be committed. We can close this issue.
