### ISSUE TITLE
Consideration for supplemental documentation for state and federal users

### ISSUE THREAD

**Issue by CSwartzHMA** [18F/cms-hitech-apd#1905]
This task is done when...
 - [x] A meeting has been held to vet ideas
 - [ ] Team has determined how/when to make materials available to state users
 - [ ] A crosswalk from APD template to eAPD sections has been developed, reviewed and approved
 - [ ] A Guided Tour has been developed, approved and recorded 
 - [ ] A sample completed eAPD has been finalized and exported to PDF (to align with Guided Tour content)

**Comment by CSwartzHMA** [comment]
Based on conversations, efforts should be focused on state users. The following are suggested documents that states may benefit from having to support eAPD orientation:
-"How to's" and FAQs 
-Recorded guided tour that would illustrate what information should be included in each section
-Sample completed eAPD in PDF form

Updated issue based on these items.

**Comment by CSwartzHMA** [comment]
[Crosswalk Draft 122818.xlsx](https://github.com/18F/cms-hitech-apd/files/3877031/Crosswalk.Draft.122818.xlsx)

Previous crosswalk document for reference. Will begin to update this based on changes made to the app since this was originally completed.

**Comment by jeromeleecms** [comment]
Closing this pending revisions around the user testing. Will spin up a new issue when needed.
