### ISSUE TITLE
Describe our current tech stack + decisions we anticipate needing to make about tech

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1911]
We should review and update [the wiki page that describes](https://github.com/18F/cms-hitech-apd/wiki/Dev%3A-Index) what the current major parts of our stack are, as well as places where we see big decisions that might need to be made in the future.

### This task is done when...
 - [ ] We've documented what we're currently using (and why, if there's a why)
 - [ ] We've documented any upcoming decisions we're aware of that are going to require a technology choice, and any opinions we have about them.

**Comment by mgwalker** [comment]
- updated the dev index with current libraries, rationale for them, and some thoughts about what we might need to do in the future
- updated the API configuration page with an updated list of environment variables

It might not be the friendliest version of itself yet, but the documentation is more accurate and complete now, so that's a step forward anyway.

**Comment by mgwalker** [comment]
@jeromeleecms I think this is done, but do you want to look it over before we close it? Or maybe have Heather review it?

**Comment by jeromeleecms** [comment]
@mgwalker Is the database model a separate thing to review? Or is that intact even with the move to our new document model? Are we still using knex?

**Comment by mgwalker** [comment]
The database model is still intact _for now_ - I didn't want to update that documentation until the PR is merged, but I've got it queued up and ready to go! We are still using knex, yes!

**Comment by jeromeleecms** [comment]
@mgwalker Reviewing the board -- is the documentation updated now that the document model PR is merged? (The last update I saw was from 11/7). If you are good, it would be good to have @hbillings also take a look to make sure she has enough to go on as part of the vendor onboarding...

**Comment by mgwalker** [comment]
This is good, IMO. It's all up-to-date in the wiki for now, and we just need to be mindful about keeping it updated as we go along.

**Comment by jeromeleecms** [comment]
Done.
