### ISSUE TITLE
Review and update our descriptions of our processes

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1912]
We should review and update our wiki pages that describe how we work and why we work that way.

### This task is done when...
 - [x] The [Tech 101 page](https://github.com/18F/cms-hitech-apd/wiki/Tech-101) is reviewed and updated.
 - [ ] Our [recommendations around how and when to conduct user testing](https://github.com/18F/cms-hitech-apd/wiki/Onboarding#user-testing) have been reviewed and documented.

**Comment by hbillings** [comment]
Do we explicitly state our open source policy anywhere?

**Comment by mgwalker** [comment]
Tech 101 is done

**Comment by lauraponce** [comment]
Going to close this out and will continue to update the wiki on an ongoing basis for the design pages.
