### ISSUE TITLE
Review and Update Documentation in the Wiki

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1917]
We have to review the material in our Wiki to make sure it's up to date as we prepare for vendor transition. We'll have to break this apart into smaller pieces, but for now this will make sure this doesn't fall off the radar.

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
*Add a LABEL (design, dev, compliance, BUG, etc) before submitting.

*If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for PRODUCT to prioritize.

**Comment by lauraponce** [comment]
Going to continue updating on ongoing basis
