### ISSUE TITLE
Contractor hourly rates are not used in any calculations

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1925]
Users can enter contractor costs at an hourly rate, but currently eAPD doesn't use that data anywhere. Instead, it relies on users entering the annual cost of the contract.

### This task is done when...
 - [ ] entering hourly rates affects total contract cost
 - [ ] hourly rates are included in the budget

**Comment by jeromeleecms** [comment]
The behavior we are expecting here:

1) The total cost of the contract should not be used to calculate the total cost of an activity.
2) The total cost by FFY (hourly or annual) is what we should be calculating into the budget tables.

@mgwalker I don't see how the hourly rates are being used. I'm only observing that the total calculated amount (hourly or yearly) is what is making it into the budget tables (by FFY)

**Comment by mgwalker** [comment]
To make sure I'm 100% clear:

For contracts without hourly rates, we should use the **B** fields to calculate the budget.

![image](https://user-images.githubusercontent.com/1775733/69158460-18814880-0aac-11ea-973f-e57b02c190e9.png)

---

For contracts with hourly rates, we should use the **C** fields to calculate the budget. Should we also calculate the **B** fields from the **C** fields?

![image](https://user-images.githubusercontent.com/1775733/69158592-4e263180-0aac-11ea-8b25-4ebe5cee3f10.png)

---

In both cases, the **A** field is independent of **B** or **C** and is not used in the budget anywhere. My understanding is that **A** is for the case where a contract extends beyond the term of the APD, so its full cost wouldn't be captured by just the annual/hourly costs. Is that basically right?

**Comment by jeromeleecms** [comment]
Yes! Awesome visualization. Confirming that currently:

A: independent of B and C (and not used in the budget calculation)
B: used for hourly and non hourly calculations
C: used to calculated B when the contract is identified as a hourly resource 

It looks like the app is already calculated the B fields from the C fields. In your example 600 x $200 = 120k - which is the correct behavior.

Future validation request: B + C <= A (take that algebra!)
