### ISSUE TITLE
Executive Summary missing the breakdown by FFY

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1927]
The help text in the executive summary notes that the FFY breakdown is presented in the text, but it is not present:

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/1ffef1f1-3495-4b89-ae4f-5873b78a4775)

### This task is done when...
 - [ ] Add the FFY amount in the activity list
 - [ ] Design suggests/approves change
 - [ ] Product approves change
 - [ ] Dev understands what data needs to show up where (e.g. annotated screenshot, a mockup, or a clear written description)

**Comment by lauraponce** [comment]
Switching to a dev issue
