### ISSUE TITLE
Make TinyMCE loading less jarring

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1931]
As described in [a comment in #1913](https://github.com/18F/cms-hitech-apd/pull/1913#issuecomment-551960491), the TinyMCE boxes take a couple of seconds to appear. We may be able to make that less visually jarring with some CSS tricks.

### This task is done when...
 - [x] the rich text boxes have a better user experience when first loading

**Comment by nkkl** [comment]
Can we get a GIF of the experience, maybe?

Once we have that, Design and Product can talk about how important it is to fix this now.

**Comment by jeromeleecms** [comment]
We are planning on talking about this today (12/09), but looking at the site for PR #1913, I don't think I would have even noticed that the text boxes were missing unless I knew exactly where I was going to scroll to and that area had a text box that had not loaded yet...
