### ISSUE TITLE
Add more help text for objectives 

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1933]
In the latest round of usability testing for the activities section, we found that users wanted more information about how to fill in the Objective and Key Results. Jerome (and possibly input from Nick) will need to provide some examples of information that should be included in this help text.

Current copy: 

<img width="554" alt="Screen Shot 2019-11-26 at 8 33 47 PM" src="https://user-images.githubusercontent.com/21222704/69693960-16128600-108c-11ea-90ae-92468d27afcc.png">

### This task is done when...
 - [ ] The instructions and help text for Objectives and Key Results have details about what they should enter in this section
- [ ] It is being tracked for a future research session that this should be tested to see if the help text actually helps

**Comment by nkkl** [comment]
Definition of done needs updating:
- What are the necessary details? Do we know, or do we need to do research?
- What is our bar for "clear"; are we usability testing it?

@lauraponce @jeromeleecms

**Comment by lauraponce** [comment]
Updated description and definition of done.

**Comment by hbillings** [comment]
Closed by #1819

**Comment by jeromeleecms** [comment]
Hmm.. this was supposed to be closed by #1819. Closing again...
