### ISSUE TITLE
Revise Standards and Conditions instructions to include how it's used

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1934]
In the latest round of usability testing for the activities section, users expected that a yes/no checkbox should be enough and didn't know how this information is used by their CMS reviewer. 

The thinking is that if we add context along the lines of "why we're asking for this," state users will be more likely to put effort into a thoughtful response to this question which will be helpful for CMS.

Current copy:

<img width="572" alt="Screen Shot 2019-11-26 at 8 34 53 PM" src="https://user-images.githubusercontent.com/21222704/69694155-bcf72200-108c-11ea-93ec-6fe081bf3e0f.png">

### This task is done when...
 - [ ] Revise the instructions and/or add help text to explain more about the Standards and Conditions

**Comment by nkkl** [comment]
Based on discussion during backlog refinement, we should have a longer conversation about this!

**Comment by nkkl** [comment]
Related to #1947

**Comment by beparticular** [comment]
Notes ok to close via @lauraponce
