### ISSUE TITLE
Update the in-house cost category labels 

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1936]
The terms `in-house`, `personnel`, and `non-personnel` have been confusing users and there is an opportunity to make these less ambiguous.

Current labels:

<img width="724" alt="Screen Shot 2019-11-26 at 8 47 44 PM" src="https://user-images.githubusercontent.com/21222704/69694667-71457800-108e-11ea-82bd-9a9c8a24ad8c.png">

Jerome' idea was to add help text saying in-house = state personnel and non-personnel associated with state.

### This task is done when...
 - [ ] The in-house cost category labels are updated so that they make more sense to users

**Comment by hbillings** [comment]
We should go back through research to see what folks were calling these categories in interviews.

**Comment by lauraponce** [comment]
Reading back through the notes from usability testing, it seems like users use the term staff rather than personnel and state in addition to in-house. How about something like this? @jeromeleecms 

From --> to
`in-house` --> `state`
`personnel` --> `state staff`
`non-personnel` --> `other state expenses`

![Screen Shot 2020-01-17 at 2 42 52 PM](https://user-images.githubusercontent.com/21222704/72651256-af954000-3937-11ea-8327-21317e474554.png)

![Screen Shot 2020-01-17 at 2 43 00 PM](https://user-images.githubusercontent.com/21222704/72651263-b328c700-3937-11ea-8c10-8fdd88b4e885.png)

**Question**: will this phrasing be understood by territories users?

**Comment by jeromeleecms** [comment]
I think this makes the request for understandable. It probably is worth mentioning somewhere in help text that this lines up with in-house costs since the term "in-house" is used in our financial reporting system (https://www.medicaid.gov/medicaid/finance/downloads/cms-6410-admin-category-of-services-definition-2-14.pdf) -- take a look at the language in lines 2A&B (similar language appears in 4, 24, and 28).

@lauraponce Do you want me to take a crack at providing some language? May be we can talk about it during parking lot time?

**Comment by lauraponce** [comment]
This is helpful — yes let's chat more about it in parking lot time 👍

**Comment by lauraponce** [comment]
![Screen Shot 2020-01-22 at 3 37 23 PM](https://user-images.githubusercontent.com/21222704/72944202-1c8c4980-3d2d-11ea-8b8c-b8809358ac37.png)
-----------
![Screen Shot 2020-01-22 at 3 37 11 PM](https://user-images.githubusercontent.com/21222704/72944204-1f873a00-3d2d-11ea-9f45-b11fab598b5b.png)

Updated phrasing to include `in-house` in the hint text. @jeromeleecms let me know if this seems clear.

**Comment by jeromeleecms** [comment]
For state staff, the text looks fine.

For the other state expenses, how about something along the lines of this (feel free to edit):

"Provide a breakout and brief description of each non-personnel cost related to this activity. These costs should only apply to state (in-house) expenses and should not include costs related to private contractors."

**Comment by lauraponce** [comment]
That reads clearly to me! 

Here are the updated (final) mock ups for this with the copied over text:

![Screen Shot 2020-01-23 at 10 41 58 AM](https://user-images.githubusercontent.com/21222704/73013355-033ada00-3dcd-11ea-8b71-7b5bd1ff7bf9.png)

> The cost for state (in-house) staff with benefits is per full time employee (FTE). The number of FTEs represents the combined amount of staff time for the duration of the activity. Combine multiple individuals’ commitments only when their costs and roles are the same. Do not include contract personnel in this section; account for them under Private Contractor Costs.

![Screen Shot 2020-01-23 at 10 41 46 AM](https://user-images.githubusercontent.com/21222704/73013361-059d3400-3dcd-11ea-9e16-8067ca276bdc.png)

>Provide a breakout and brief description of each non-personnel cost related to this activity. These costs should only apply to state (in-house) expenses and should not include costs related to private contractors.

This is ready for dev @hbillings @mgwalker – this is for changing the in-house cost, personnel, and non-personnel terminology in that section.
