### ISSUE TITLE
Design table that rolls up all of the contract costs for all activities

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1938]
We heard from users in the latest round of usability testing (and it's also come up in previous rounds) that it'd be helpful for them to see a roll-up of all the contract costs for all activities. This would also be useful for reviewers to see.

The closest thing we have to this now is for milestones.

### This task is done when...
 - [ ] There is a mock-up of a table that rolls up contract costs for all activities

**Comment by jjames521** [comment]
Looking at these currently as variants for design.


![Screen Shot 2020-03-30 at 2.38.55 PM.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/80ab1430-4764-4ef8-9dfd-44f4bf7877a0)
![Screen Shot 2020-03-30 at 11.56.02 AM.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/42b07941-540f-44d9-9720-25062b0edd29)![Screen Shot 2020-03-30 at 11.56.12 AM.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/7a7e8090-3ee6-4150-ae6f-6926b8dd2dbb)![Screen Shot 2020-03-30 at 11.56.02 AM.png]![Screen Shot 2020-03-30 at 11.56.35 AM.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/b8dc4718-435d-4b92-bc0b-2e7619d98255)

**Comment by jjames521** [comment]
@beparticular 

Mock up denoting changes that we discussed via parking lot time.  Let me know what you think.

![StateCostsSummary1.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/8bca6a8d-9337-4ca1-8276-c7b886cfadd5)

**Comment by jjames521** [comment]
@beparticular @lauraponce 

Based on previous conversations for the State Summary Table (earlier labeled State Costs but merged with Private Contractor Table) Here are some of the changes.

Switched Non Personnel and Private Contractor spots to fit in better with math logic we have in place
Took out duplicate subtotals that didn't make sense based on new structure 
Took out "subtotals" and made them totals with Other Funding subtracting at the end and once during the activity

![StateCostsSummary5.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/856fe461-4174-487a-a7cf-f26c24fd8283)

**Comment by jeromeleecms** [comment]
We would still need to include other funding amounts for state personnel, non-personnel costs, and private contractor costs because those numbers would need to tie back to the tables for the Federal Fiscal Year on the next page:

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/183a08e2-e6ea-4238-a8c5-f910d6186590)

Looking at the combined tables, it would seem to make more sense to have the bottom table just be a Summary of the Medicaid Costs by Activities (remembering that there may be multiple Activities that fall under HIT, HIE, or MMIS). Instead of "Other Funding Amount" at the bottom of this table, that should be Subtotal for Medicaid.

Does that make sense? The screenshot next to your sample table is from what we would expect to see from the proposed budget but the numbers won't line up.

**Comment by jjames521** [comment]
Hmmm, yeah it makes sense but would like to circle back for a quick chat to make sure I'm aligned tomorrow if you're available? @jeromeleecms

**Comment by jeromeleecms** [comment]
@jjames521 Here's the language we can place right before the summary table:

These tables summarize the total **Medicaid Costs** for all activities organized by their funding source (HIT, HIE, and/or MMIS) and their cost category (State Personnel, Non-Personnel, and Private Contractor Costs) by FFY. Other funding amounts described in the cost allocation section of the activities are not included in these tables, but can be reviewed in the individual activity summary tables on this page. 

Feel free to propose edits to the language if/where needed!

**Comment by jjames521** [comment]
Excellent, here is the re-edited version

![StateCostsSummary8](https://user-images.githubusercontent.com/62292793/79484888-5e522680-7fe2-11ea-99c6-b89c6df7253e.png)

**Comment by jeromeleecms** [comment]
This is good to go, ready for @pphillips-fearless to review and to spin up a dev task.

**Comment by jjames521** [comment]
@pphillips-fearless Let me know if you need anything, this is ready

**Comment by pphillips-fearless** [comment]
This is now dev task #2183
