### ISSUE TITLE
Move activity name textbox into the modal, remove second activity list

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1939]
There are a couple of different ways to handle editing the names: within the modal or in the activity list. Based on user feedback, either way, seems like it could work. I'm leaning towards adding the editing interaction in the activity list so that it's in the same place as where they wrote the name in the first place. It could be as simple as adding another button next to 'Add another activity' to 'Edit activity list'

### This task is done when...
- [ ] The activity name/program type edit fields are inside the modal
- [ ] the top activity list opens the modal when users click "edit"
- [ ] the second activity list is gone 🎉

**Comment by nkkl** [comment]
PM question: how many times has this come up so far? /cc @jeromeleecms

**Comment by lauraponce** [comment]
This has come up more than once, but it isn't something that comes up every time without prompting. I believe two of the pilot participants mentioned not knowing how to change the name of an activity. It seems like this would be more of an uncommon/infrequent thing that users would need to do so it doesn't need to be super prominent, but there should be a clear path to make the edit. /cc @jeromeleecms

**Comment by lauraponce** [comment]
Could just move the activity name editing and program type selection to be above the rest of the activity section content (at the top of the modal) which would get rid of one of the lists.

**Comment by lauraponce** [comment]
Reassigned to dev to update the issue details

**Comment by mgwalker** [comment]
Closed by #2053
