### ISSUE TITLE
Update activity list

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1942]
<img width="1397" alt="Screen Shot showing the old layout next to the new one" src="https://user-images.githubusercontent.com/1775733/69752565-1efc6980-1117-11ea-890a-b81078c341d5.png">

### This task is done when...
 - [ ] the activity list is displayed as indicated in the screenshot above

**Comment by jeromeleecms** [comment]
Additional context can be found in #1852.

**Comment by mgwalker** [comment]
This will also include reordering the activities. Because Laura is out, I'll put in something basic and then look into drag-and-drop, and we can look at it together when everyone is back.
