### ISSUE TITLE
Open activities in a modal window

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1943]
### This task is done when...
- [ ] clicking the "Edit" button on the activity list opens an activity in the modal
- [ ] the inline activities section is removed
- [ ] tabbing between elements does not escape the modal

**Comment by nkkl** [comment]
@lauraponce please drop in design perspective on this.

**Comment by nkkl** [comment]
Open interaction question: how should save and close interact with this?
