### ISSUE TITLE
Add a navigation bar to the top of the activity modal

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1944]
### This task is done when...
- [ ] there is a navigation bar at the top of the activity modal
- [ ] the currently-scrolled activity section is highlighed in the bar
- [ ] clicking in the bar scrolls to the selected activity section

**Comment by nkkl** [comment]
@mgwalker add screenshot please :)

**Comment by nkkl** [comment]
Task size depends on the interaction design; we'll revisit this once we've done the design.
