### ISSUE TITLE
Replace Performance Goals and Benchmarks section with Objective and Key Results

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1945]
Mostly, this is just changing text, but we should also decide whether we want to change the names of the data model.

### This task is done when...
 - [ ] The form reflects the new title and text
 - [ ] The data model is updated if necessary

<img width="305" alt="Screen Shot 2019-11-26 at 9 30 58 PM" src="https://user-images.githubusercontent.com/509309/69754098-47359980-1112-11ea-8372-ab11c9cf8926.png">

**Comment by mgwalker** [comment]
Closing in favor of the dev work that will come out of #1819
