### ISSUE TITLE
Replace monolithic Standards and Conditions section with single question

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1947]
Remove the long Standards and Conditions section at the end of the section and add in the new Standards and Conditions question right before the statement of alternative considerations.

### This task is done when...
 - [ ] The standards and conditions have been consolidated to a single question
<img width="569" alt="Screen Shot 2019-11-26 at 9 26 16 PM" src="https://user-images.githubusercontent.com/509309/69754135-5d435a00-1112-11ea-96d3-18093b79485b.png">

**Comment by nkkl** [comment]
Blocked, waiting for leadership decision. @jeromeleecms please add more detail.

**Comment by nkkl** [comment]
@mgwalker mentioned that this has implications for our data model and we'll have to think about migrating existing APDs to the new data model if we do this.

**Comment by jeromeleecms** [comment]
How scalable is our current Standards and Conditions section? In the past there were 7, but in 2016, we added some additional ones. While I can't see the future, how would we handle if that # changes? Can we add/remove/edit the Standards and Conditions at will? 

We have time to talk about it during working time today - but if it requires a huge level of effort, consolidating this into a single box may be provide is the best short term solution.

**Comment by jeromeleecms** [comment]
Per our discussion today, we will keep this is a single text box as proposed here.

**Comment by jeromeleecms** [comment]
As part of the migration to the single form, we will take existing data and merge it into a single field.

**Comment by mgwalker** [comment]
For data migrations, we can concatenate the existing standards and conditions into a single string and use that for the "how you will support" box. We don't have an equivalent for the "explain why not" box, so we can safely ignore that.
