### ISSUE TITLE
Fix issue with sidenav bleeding into footer

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1948]
When we removed stickybits to fix the IE sidebar sizing bug, we introduced a bug that causes the sidebar to overflow into the footer at the bottom of the page:

![image](https://user-images.githubusercontent.com/21222704/69691253-5faaa300-1083-11ea-8743-c1ccfdbb552c.png)

We could either bump the z-index of the footer up so that it's greater than that of the sidebar (meaning the sidebar would scroll underneath the footer), or we could consider rolling back the IE fix now that we've decided it only gets yellow support. 

### This task is done when...
 - [x] We know how we'd like to fix this bug
 - [ ] We have fixed it

**Comment by nkkl** [comment]
@hbillings please update the image XD

**Comment by nkkl** [comment]
Product, dev, and design need to have a conversation about the implications of how different fixes will affect IE support.

**Comment by jeromeleecms** [comment]
Just for documentation - Since IE 11 is a "yellow" support browser, we are looking to remove weird workarounds that were done just for IE 11.
