### ISSUE TITLE
Design interaction model for modal

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#1950]
The activities section modal was well-received by users in the most recent round of usability testing and in order to move forward with implementation, we need to figure out what to include in the final design. 

Considerations for this design:
- Size of the modal
- Navigation pattern
- How to save
- Tabbed/scroll interaction
- Closing the modal

### This task is done when...
 - [ ] There is a prototype of the modal that can be used for discussion and decision-making
 - [ ] The interactions are called out and specified

**Comment by nkkl** [comment]
@lauraponce @hbillings please fill out the issue description! :)

**Comment by lauraponce** [comment]
Updated description ✔️
