### ISSUE TITLE
Wiki typo?

### ISSUE THREAD

**Issue by adunkman** [18F/cms-hitech-apd#1952]
Howdy! Happened upon the repo just now, and noticed this [in the Wiki](https://github.com/18F/cms-hitech-apd/wiki):

> The system will be developed and maintained through continuous integration/continuous delivery methods with a loosely coupled architecture connected by Advance Programming Interfaces (APIs).

APIs typically refer to Application Programming Interfaces — is this intentionally different (trying to reference APDs, Advanced Planning Documents?) or just a typo? 🤔

**Comment by jeromeleecms** [comment]
Thank you! It was a typo and now corrected.
