### ISSUE TITLE
Research Validation Interaction Design with Autosave Functionality

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1979]
Implementing Autosave introduces an interesting issue with client-side validation. How would this work with autosave? Can we use the API's invalid message to tell users where they were unable to save? 

For research and discussion.

### This task is done when...
 - [ ] We know how to handle when front end validation fails with autosave
 - [ ] Users know when validation fails on save (back end or front end)

**Comment by mgwalker** [comment]
Also, should we save the valid parts of the data and only reject the invalid parts? Is it okay to save a document when parts of it are invalid? Will users understand that?

**Comment by lauraponce** [comment]
@mgwalker do you have examples for the things that are considered to be invalid parts of the document that will cause an error for autosaving?

**Comment by mgwalker** [comment]
Activity or milestone dates - months must be between 1 and 12, days must be between 1 and 31, and years must be 4 digits. Anything else is invalid and the save will fail.

**Comment by lauraponce** [comment]
@mgwalker @jeromeleecms here is what I'm picturing for alerting the user about what's happening for autosave. It's a little difficult to explain what's happening in writing, so let me know if you'd like to talk through this instead. Use cases 1 and 3 are how it currently works.

### Use case 1: all data was valid before, new data is valid

Saved button with no alert

<img width="167" alt="Screen Shot 2020-01-13 at 2 35 29 PM" src="https://user-images.githubusercontent.com/21222704/72298012-01755780-3612-11ea-8d4c-26f8eaa7d76e.png">

### Use case 2: new invalid dates were added

Warning alert (doesn't disappear) with save button (new valid data was saved, invalid data not saved)

<img width="645" alt="Screen Shot 2020-01-13 at 2 35 24 PM" src="https://user-images.githubusercontent.com/21222704/72298025-0803cf00-3612-11ea-865f-f1370a881bd3.png">

### Use case 3: fixing invalid dates/error (the first valid save after an error) — this is already how it works.

Saved button with alert (disappears)

<img width="274" alt="Screen Shot 2020-01-13 at 2 35 33 PM" src="https://user-images.githubusercontent.com/21222704/72298055-1d78f900-3612-11ea-9aab-a5213815cc29.png">

### Use case 4: Other unpredictable error that prevents a save from happening.

Is there ever a case where this might happen where there needs to be a catch-all error?

Save button with alert (does not disappear)

<img width="631" alt="Screen Shot 2020-01-13 at 2 38 13 PM" src="https://user-images.githubusercontent.com/21222704/72298387-d8a19200-3612-11ea-8dd8-250bae33c132.png">

**Comment by lauraponce** [comment]
Here is the updated phrasing for the warning alert based on our discussion yesterday:

<img width="630" alt="Screen Shot 2020-01-15 at 11 18 26 AM" src="https://user-images.githubusercontent.com/21222704/72463861-0e688700-3789-11ea-9dd0-da2b79960f92.png">

Making a note of this here for whoever needs to know in the future — in the long term, it would be ideal to be able to click the alert and have it take the user to the place with the error (this goes hand in hand with data validation).

**Comment by lauraponce** [comment]
This is ready for dev!

**Comment by lauraponce** [comment]
![Screen Shot 2020-01-16 at 10 37 46 AM](https://user-images.githubusercontent.com/21222704/72552843-92377780-384c-11ea-9d7e-0b962ce40cda.png)

Updated the phrasing on the warning alert because we won't be able to continue saving anything new if there is an invalid date.
