### ISSUE TITLE
Review the pilot findings and give OK to share more widely

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1987]
Carrying over from #1584 

We'd like to share out the pilot findings report with CMS stakeholders and post it on the Wiki so that it's available for the vendor (and anyone else interested!) to check out.

Before we share it more widely, we wanted to get Nick's eyes on it to get a 👍. 

[Pilot findings document](https://docs.google.com/document/d/1ghx6yHbAJ1gWzMeouOq-MM_ZIrF9dQFsx8FTtOkoB2Y/edit?usp=sharing)

### This task is done when...
 - [x] Nick reviews the pilot findings

**Comment by NAretakis** [comment]
Awesome. Just awesome. Doc reads well, and provides a great capstone to the pilot. Also gives good insight into the future cake layer items that we can focus on. Ready for wider release @jeromeleecms .
