### ISSUE TITLE
Add information to the APDs 101 wiki page

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1988]
There is a new wiki page for documenting high level info about what APDs so that we can use it as a reference for new folks joining this project.

https://github.com/18F/cms-hitech-apd/wiki/APDs-101

### This task is done when...
 - [ ] There is high level information on the APDs 101 wiki page

**Comment by jeromeleecms** [comment]
Tried to keep this super high level, but would appreciate another set of eyes on this. @lauraponce @hbillings @mgwalker if any of you have a time for a quick read through. Feel free to add or edit -- or put some inline comments if you want me to expand on something.

**Comment by lauraponce** [comment]
This is great — informative and seems like the right level of detail

**Comment by mgwalker** [comment]
Nice! I was going to complain about the formality of the first paragraph, but then the next paragraph started with "more simply," and I was good. 😆

**Comment by jeromeleecms** [comment]
Thanks, all! Closing - but we can always revisit for modifications.
