### ISSUE TITLE
Add more information to help text for "other funding description"

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1992]
Created from #1935

In our latest round of user research, we heard from users that it wasn't obvious what "other funding" refers to. This issue is for adding more details to the other funding help text so that it's useful for states in understanding what other funding means.

The current help text says:

>Other funding sources include contributions and donations. 

### This task is done when...
 - [ ] There is help text that describes clearly what other funding means
 - [ ] Dev task is created for work that comes from this issue plus #1935 for the tables

**Comment by jeromeleecms** [comment]
Here's some content to massage @lauraponce:

"Other funding is funding not directly tied to the CMS grant with the matching State funds for this project. This funding may come from another Federal source, another State agency, and/or contributions or donations from a 3rd party and should be deducted from the total cost of the project prior to calculating the Medicaid share."

**Comment by lauraponce** [comment]
Makes sense to me! Slightly tweaked:

> Other funding consists of funds that are not directly tied to the CMS grant with matching state funds for this project. This funding may come from another federal source, another state agency, and/or contributions or donations from a third party. Other funding will be deducted from the total cost of the project prior to calculating the Medicaid share.

Thoughts, @jeromeleecms?

**Comment by jeromeleecms** [comment]
Are we using project and activity interchangeably? Now that I'm thinking about this -- should it be (including a small addition to the text):

> Other funding consists of funds that are not directly tied to the CMS grant _and the_ matching state funds for this activity. This funding may come from another federal source, another state agency, and/or contributions or donations from a third party. Other funding will be deducted from the total cost of the activity prior to calculating the Medicaid share.

**Comment by lauraponce** [comment]
👍 that reads well to me

**Comment by jeromeleecms** [comment]
Spun up #2027 for the dev task. Closing.

**Comment by jeromeleecms** [comment]
Re-opening to allow Dev to write issue according to new process. Will close out 2027!

**Comment by mgwalker** [comment]
Dev tasks:

1. update the "other costs" section to be a table, like so:
   ![screenshot of other funding table](https://user-images.githubusercontent.com/21222704/71045116-a753a600-20e8-11ea-98fc-01c602495256.png)

2. update the federal/state split dropdown to also be a table:
   ![screenshot of FFP split table](https://user-images.githubusercontent.com/21222704/71045116-a753a600-20e8-11ea-98fc-01c602495256.png)

3. above the "other costs" table, add the following instruction:
   - **heading:** Other Funding Amount
   - **detail:** Enter the total amount that will be used from additional funding sources.
   - **helpText:** Other funding consists of funds that are not directly tied to the CMS grant and the matching state funds for this activity. This funding may come from another federal source, another state agency, and/or contributions or donations from a third party. Other funding will be deducted from the total cost of the activity prior to calculating the Medicaid share.
