### ISSUE TITLE
Add new unique IDs to the dashboard and the builder

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1993]
Carrying over from the design issue: #1821

The current format for the unique identifiers that keys off of the created date isn't intuitive for users and is confusing for CMS because they use the submitted date. Here is the updated version for the IDs based on a discussion with Jerome:

**Dashboard**
![Screen Shot 2020-01-06 at 10.25.09 AM.png](https://images.zenhubusercontent.com/57f4106595e42b6c5ba9e43c/43647270-137f-4318-a982-ccf352539b44)

**Builder**
![Screen Shot 2020-01-06 at 10.26.56 AM.png](https://images.zenhubusercontent.com/57f4106595e42b6c5ba9e43c/39e8358f-d302-4e9a-b348-df69ea2326c7)

### This task is done when...
 - [ ] The dashboard and builder are updated with the new formatting for IDs

**Comment by mgwalker** [comment]
@lauraponce In the dashboard, it says "HITECH IAPD", but in the builder, it says "HITECH APD" (instead of IAPD). Should it say IAPD in both places?

**Comment by lauraponce** [comment]
@jeromeleecms do you have thoughts on Greg's question above? I've heard a lot of states use the IAPD term, but we've always dropped the I. Is there a benefit to one or the other?

**Comment by jeromeleecms** [comment]
@lauraponce @mgwalker Yes, let's put IAPD in both places. While the APD is a generic term and be used to describe an IAPD, when we introduce the OAPD and the PAPD into this mix, they carry different expectations with them... it's sort of like all squares are rectangles, but all rectangles are not squares situation (math facts!).
