### ISSUE TITLE
Define research questions for discussion with states

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#20]
What do we want to learn from states?

**Comment by nicoleslaw** [comment]
Right now, we're asking for a mix of information and data throughout the process. How do states think about the order of compiling this info, and how can we better organize the timing of questions so we're not asking for summary data before they've even gotten to that part of the process?

**Comment by nkkl** [comment]
Sounds good. I think documenting our research questions and research protocol is a good thing to have in our repo, so that whoever we hand this to has an easy time picking it up and not duplicating work. :)

**Comment by lauraponce** [comment]
Here is the working draft of the [interview questions for states].(https://docs.google.com/document/d/1vVVN1TwAoJHtMNur3z9qa7tqbRdlgPoibbU1ur_bRQs/edit?usp=sharing)

When this is refined, we'll add these questions to the [research wiki](https://github.com/18F/cms-hitech-apd/wiki).

**Comment by nicoleslaw** [comment]
Looks good to me, @lauraponce! I made a few minor suggestions inline.

**Comment by lauraponce** [comment]
@NicolasAretakisCMS and @jeromeleecms here are the [interview questions](https://docs.google.com/document/d/1vVVN1TwAoJHtMNur3z9qa7tqbRdlgPoibbU1ur_bRQs/edit?usp=sharing) we are planning to ask states in the interviews tomorrow and later this week. 

Please feel free to comment on doc! Let us know if something is missing or captured incorrectly in the framing of the question.
