### ISSUE TITLE
Update the behavior of the save button

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#2011]
From #1979

#### Backend

- [ ] the `PATCH` endpoint returns a list indicating which patches failed, so the frontend knows which ones still need to be kept and re-tried

#### Frontend

- [ ] when autosave completes successfully without a prior error, show the green "saved" button, and the list of pending saves is emptied (this is the current behavior)
  ![screenshot of saved button](https://user-images.githubusercontent.com/21222704/72298012-01755780-3612-11ea-8d4c-26f8eaa7d76e.png)
- [ ] when autosave fails due to a validation error (HTTP status code 400), show the blue "save" button along with a warning dialog that does not go away, and the list of pending saves is updated to reflect what was successfully saved
  ![screenshot of the save button with warning dialog](https://user-images.githubusercontent.com/21222704/72463861-0e688700-3789-11ea-9dd0-da2b79960f92.png)
- [ ] when autosave succeeds after previously having an error, show the green "saved" button along with a success dialog that goes away after a period of time, and the list of pending saves is emptied
  ![screenshot of the saved button with the success dialog](https://user-images.githubusercontent.com/21222704/72298055-1d78f900-3612-11ea-9aab-a5213815cc29.png)
- [ ] when autosave fails for another reason, show the blue "save" button along with an error dialog that does not go away, and the list of pending saves is not changed
  ![screenshot of the save button with the error dialog](https://user-images.githubusercontent.com/21222704/72298387-d8a19200-3612-11ea-8dd8-250bae33c132.png)

**Comment by mgwalker** [comment]
blocked by #1980

**Comment by jeromeleecms** [comment]
close this one because we will be removing the save button.
