### ISSUE TITLE
Prototype opening activities in their own page

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#2032]
Take the stuff that's in the modal, put it in a page. We can use the existing page design, and just make the sidebar links open new content areas with React Router. (Reference design: e-QIP)

### This task is done when...
 - [ ] we've decided if this is a route we want to continue down

**Comment by lauraponce** [comment]
Paginated Activity section concepts based on our sync:

![Paginated view](https://user-images.githubusercontent.com/21222704/74273433-4f3eb780-4cc5-11ea-8562-d6141e90cb14.png)

![Paginated view Copy](https://user-images.githubusercontent.com/21222704/74273428-4e0d8a80-4cc5-11ea-951c-363a88312a08.png)

**Comment by jeromeleecms** [comment]
Closing this -- PR's will still open for reference until the synthesis is done.
