### ISSUE TITLE
Cost allocation narrative instructions are unclear

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#2036]
It looks like there was an intent to replace the cost allocation narrative instructions and instead we wound up mashing some sentences together. Here's what it currently says in the 4th bullet:

>Ensure cost allocations are current. Medicaid funds should be not be sole contributor to Cost allocations should be current and ensure financial participation of all parties so Medicaid funds are neither the sole contributor at the onset, nor primary source of funding. Other payers who may benefit must contribute their share from the outset. The absence of ancillary payers is not sufficient cause for Medicaid to be primary payer.

### This task is done when...
 - [ ] we know what the right content is

**Comment by jeromeleecms** [comment]
> 4. Ensure cost allocations are current. Cost allocations should be current and ensure financial participation of all parties so Medicaid funds are neither the sole contributor at the onset, nor primary source of funding. Other payers who may benefit must contribute their share from the outset. The absence of ancillary payers is not sufficient cause for Medicaid to be the primary payer.

@mgwalker / @hbillings  This should be good to implement, but feel free to do a quick read through for a sanity check.
