### ISSUE TITLE
Determine which fields can be deemed invalid client-side

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#2054]
Currently, dates are invalidated on the back end. There are certain other fields which must be within certain values in order to be properly processed by CMS, but we don't want to block autosave if those values don't fall within that range. 

### This task is done when...
 - [ ] We have a list of inputs that we should flag for users

**Comment by jjames521** [comment]
Was able to take a review look at the mural, this looks good and makes sense.  Do we need to talk further on this?

@jeromeleecms 

https://app.mural.co/t/eapd5455/m/eapd5455/1588781600846/74a95a2db5d0b3e72c73cc7a96e6b501f40dcbd1

**Comment by jeromeleecms** [comment]
Reviewed by @CSwartzHMA and @jjames521 - this will unlock work on @2092.

**Comment by akuas** [comment]
All of eAPD validations patterns can be referenced in the validation library below.
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=473%3A8498
