### ISSUE TITLE
Leave the default program type selection blank for new activities

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#2059]
Currently, we select HIT by default for new activities but this can lead to mistakes if a state user overlooks this and doesn't change it to the correct one if it's HIE or MMIS. We should update this so that no radio button is selected by default.

![Screen Shot 2020-02-12 at 10.52.29 AM.png](https://images.zenhubusercontent.com/57f4106595e42b6c5ba9e43c/2640c91c-496f-456c-b6a5-0a834a04dcf6)

### This task is done when...
 - [ ] In the Activity Overview section, the default selection is blank for program type (HIT, HIE, MMIS)

**Comment by mgwalker** [comment]
Marking this as medium because it may have some impacts on the budget reducer. The reducer (the thing that does all the budget calculations) assumes every activity has a program type, and it'll need to be able to handle activities without one.
