### ISSUE TITLE
Always show full dollar amounts

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#2085]
Should we get rid of the shortened dollar values in the builder? E.g., in a lot of the budget tables, we should the numbers shortened with units, to `$3.72 M`, which isn't as useful as `$3,718,332` would be.

We originally switched to the shortened numbers because they weren't fitting in the tables, so we'll need to check if they do now. The quarterly budget tables are probably the most suspect.

### This task is done when...
 - [ ] we know whether we want to always expand the numbers
 - [ ] have done the thing

**Comment by jeromeleecms** [comment]
We are going to hold on making a decision on this until #2086 is implemented so we can:

1. See the ramifications on all the tables.
2. Explore how it will affect various screen / font sizes. During parking lot time, we changed the font sizes in the browser and the table numbers did not significantly change (though surrounding text did).

**Comment by mgwalker** [comment]
Should we create issues for 1 and 2? A task to push up a prototype with the dollars always being full amounts, and a task to explore how it works changing screen/font sizes and document all that? (I don't know why that didn't occur to me yesterday. Brain was mush.)

**Comment by jeromeleecms** [comment]
Sounds good -- could you please spin up the issues since you know what "done" looks like?

**Comment by jeromeleecms** [comment]
2108 has been spun up let's close this out!
