### ISSUE TITLE
Mock up secondary navigation for back/next buttons 

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#2089]
Since we are implementing the paginated view, we heard from users in round 10 that it'd be useful to have a secondary forward/back navigation at the bottom of the section (in addition to the left nav).

### This task is done when...
 - [x] There is a mock-up of the forward/back buttons
 - [x] Product has reviewed and provided feedback
 - [ ] Dev issue has been added

**Comment by lauraponce** [comment]
Since users aren't necessarily filling out the sections in sequence, `Continue` felt like the right verb to use rather than "Next."  Similarly, `Go back` feels like a fitting label since it's actionable using a verb rather than just labeling it "back".  

## A

In A, I put continuing as the primary button with going back as the secondary action using only one button so that `Continue` stands out the most. This version would nudge users to continue progressing forward while making going back the less noticeable option.

![Buttons](https://user-images.githubusercontent.com/21222704/76259474-e6d6ed80-6212-11ea-8baf-a5126aff94bf.png)
________

## B

In B, I used a smaller button for the secondary action and kept `Continue` as the primary with the larger, blue button. The back button is slightly more noticeable than the link text in option A.

![buttons2](https://user-images.githubusercontent.com/21222704/76259485-ec343800-6212-11ea-8bd3-cce8fd0d71ff.png)
________

## C

In C, `Continue` is still the primary action but having the two controls closer together would make the `Go back` action slightly more prominent than having it left-aligned.

![buttons3](https://user-images.githubusercontent.com/21222704/76259495-f0f8ec00-6212-11ea-808b-401152574ebe.png)
________

## D

In D, both buttons are the same size giving closer to an equal weight of the two navigation options, and the blue `Continue` button is still set apart as the primary action to take. This option would make is the easiest to jump forward and backward between all of the sections. 

![buttons4](https://user-images.githubusercontent.com/21222704/76259506-f5bda000-6212-11ea-8c09-544bb6451f71.png)
________

@jeromeleecms what are your thoughts on this?

**Comment by lauraponce** [comment]
## A

* Added arrow to Continue button
* Changed from "Go back" to `Previous`
* Added hints below the buttons for which section they're going to 

![A](https://user-images.githubusercontent.com/21222704/76363524-6f6f8f80-62e0-11ea-91a7-f3dd29acf663.png)
_____
## B

* Removed buttons and replaced with just the section names

![B](https://user-images.githubusercontent.com/21222704/76363533-739bad00-62e0-11ea-8826-c12cb302417f.png)
____

@jeromeleecms 💭? (We can also chat about it in parking lot time since that seemed to work well for this earlier today!)

**Comment by jeromeleecms** [comment]
I'm liking both -- and def. parking lot time -- gives me time to think and develop "opinions" too! :)

**Comment by lauraponce** [comment]
Decision from our standup: move forward with A and get feedback in next round of research

**Comment by lauraponce** [comment]
@mgwalker Tagging you in for creating the dev issue on this:

![image](https://user-images.githubusercontent.com/21222704/76448202-34746700-6387-11ea-9933-ad8ff633fec9.png)

**Comment by jeromeleecms** [comment]
Just for documentation purposes as well - decision was based on feedback from the team, but also from the results of User research Round 10, where users indicated that they expected to have some sort of button at the bottom of the page to move within the application.

**Comment by jeromeleecms** [comment]
Also for accessibility @mgwalker -- would the screen reader read "Continue to Activity 6: Activity Overview" for the continue button (as an example)...?

**Comment by mgwalker** [comment]
Good question! I reckon we could have it say whatever we wanted but I'm not 100% sure. I'll poke around on the internets and see what our options are, but I bet we can do it.

**Comment by mgwalker** [comment]
We can combined `aria-label` on the button with `aria-hidden` on the visual section name to achieve this result!

**Comment by mgwalker** [comment]
Dev issue is #2103
