### ISSUE TITLE
Implement fixed position header and autosave messaging

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#2090]
The page header should be fixed instead of scrolling, and should include autosave status messaging. See the design synthesis and prototype for more info.

Screenshot of what it should look like (exact autosave messaging TBD in #2094):

![A2](https://user-images.githubusercontent.com/21222704/76261995-7fbc3780-6218-11ea-8dbc-0a407ced7f0e.png)
____

### This task is done when...
 - [ ] the header is fixed
 - [ ] there's a save status message in the header

**Comment by lauraponce** [comment]
Updated the description with a screenshot! It's also probably worth mentioning that the error message (#2095) will take up some space right below the header.
