### ISSUE TITLE
Remove the save button

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#2091]
![boy bye](https://media.giphy.com/media/gtgO8iCfaGTG8/giphy.gif)

### This task is done when...
 - [ ] the floating save button is gone
  - the component is removed
  - any other components that exist solely to support the floating save button are removed
  - decide whether to keep the redux state/selectors that the floating save button uses, or refactor them into their own state (I forgot these existed when I did #2099 and created new ones; I'd probably choose to keep these and update #2099 but I'd like to hear what you think after you've had a chance to look at it)
- [ ] there is much rejoicing

**Comment by pphillips-fearless** [comment]
the pull request has been merged
