### ISSUE TITLE
Update save message

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#2104]
The save message in the header should be updated for each of the scenarios listed below (from [#2094](https://github.com/18F/cms-hitech-apd/issues/2094#issuecomment-598295512))

**Actively saving**: `↻ Saving`

**Less than 1 minute**: `Saved`

**Less than 24 hours, more than 1 minute since last edit**: `Last saved 10:05 a.m. PDT (1 minute ago)`

(one minute later, no new activity): `Last saved 10:05 a.m. PDT (2 minutes ago)`

**More than 24 hours**: `Last saved March 10 (1 day ago)`

**More than 30 days**: `Last saved March 10 (3 months ago)`

**More than a year**: `Last saved March 10, 2019 (1 year ago)`

### This task is done when...
- [x] the save message is updated to cover all of the above cases
- [x] the save message is updated automatically as time passes (so "2 minutes ago" becomes "3 minutes ago" as appropriate) 
- [x] all of the cases above as well as automatic updating are tested

**Comment by jeromeleecms** [comment]
For people watching the board that is not part of our team, this will be assigned to one of our incoming devs.

**Comment by radavis** [comment]
View SaveMessage change in the Header, here: https://ec2-18-206-162-145.compute-1.amazonaws.com/

**Comment by lauraponce** [comment]
@radavis the save messaging seems to be showing up correctly — is there a PR for this that you needed a design reviewer on?
