### ISSUE TITLE
Bug: Independent Scroll Bar Results in the Top of the Scroll Base Disappearing Underneath the Sticky Header

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#2105]
#2099 introduced the sticky header and independent sidebar, but also introduced a bug where the top of the left hand nav's scroll bar disappears when you get to the bottom of the page. If possible, the top of the nav bar should always be accessible. 

**Before:** 

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/bd932728-0c32-41c7-a37e-06b4f7c68e69)

**After:** 

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/a732d123-3d95-4a52-951f-7dabc0a6fbba)

Note: The state name does not need to stick to the top of the left nav bar.

### This task is done when...
 - [ ] The left nav's scroll bar's top and bottom scroll arrows are available when reaching at the bottom of the application.
 - [ ] Product approves the experience
- [ ] Design approves the experience
- [ ] Someone else has looked at the code.

**Comment by jjames521** [comment]
Providing a demo prototype, might help illustrate my thoughts on an animated work around.  This gives the user a chance to see the more complex tasks in a cleaner, more minimal UI.  Program Activities comes to mind here.

![eAPDAnimatedLeftNav](https://user-images.githubusercontent.com/62292793/77366479-7bbb0a00-6d2e-11ea-87d4-a3899743bcbc.gif)

**Comment by jjames521** [comment]
So I was looking around, maybe to get around the situation with things disappearing in MacOS is overflow y?  

`html { overflow-y: scroll }`


or


```
::-webkit-scrollbar {
  -webkit-appearance: none;
  width: 7px;
}
::-webkit-scrollbar-thumb {
  border-radius: 4px;
  background-color: rgba(0, 0, 0, .5);
  -webkit-box-shadow: 0 0 1px rgba(255, 255, 255, .5);
}
```
and a padding increase to justify the bar away from the links a little more?  

Just a thought.

**Comment by jjames521** [comment]
@pphillips-fearless checked it out and it looks like it's currently at Auto. @mgwalker is that even viable?

**Comment by mgwalker** [comment]
Since @jeromeleecms mentioned this one in standup, I am also unclear on the status of this issue. If there's an ask for dev, I'm not sure what it is.

**Comment by jjames521** [comment]
@mgwalker @pphillips-fearless Had mentioned adding in margin/padding to the nav so that there is more space between the navigation links and scroll bar.  I spun up 2155 and added that as a dependency.

**Comment by pphillips-fearless** [comment]
closing issue now that the connected dev issue is created

**Comment by pphillips-fearless** [comment]
the dev issue is #2155
