### ISSUE TITLE
Decide whether to use full dollar amounts

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#2108]
Using the prototype from #2113, explore how the full dollar amounts affect the current site. Experiment with changing font sizes and window sizes to see what the impact is. (From #2085). Relates/impacts #2150 as well

### This task is done when...
 - [ ] we know the impacts of switching to full dollar amounts
 - [ ] we have recommendations for how to proceed

**Comment by lauraponce** [comment]
testing site: https://ec2-18-206-245-77.compute-1.amazonaws.com

![Screen Shot 2020-03-31 at 12 12 10 PM](https://user-images.githubusercontent.com/21222704/78066024-0f9d5f00-7349-11ea-9094-9697bea99096.png)

**Comment by beparticular** [comment]
The full amounts seem fine in the prototype. The table font sizes don't change with the default browser font, so they don't break with the larger amounts. At least that is true in FF - I can't get to the prototype in Chrome. 

Let's ship it and look for any problems while we study tables over the next few weeks? @pphillips-fearless  @jeromeleecms

**Comment by CSwartzHMA** [comment]
In addition to the tables, are there limits on the number of digits in other areas? Example:

![image](https://user-images.githubusercontent.com/45497254/81004171-0016a780-8e1a-11ea-8f67-a577d4eeb43f.png)
