### ISSUE TITLE
Review how Key Personnel are Treated during calculations

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#2111]
In #2081, we discussed how Key Personnel are treat in activity 1.

> In the math, we have always treated the key personnel cost as the total cost attributable to the program, not the key person's total cost to the state. (The yes/no radio buttons kind of imply that's what we're asking for, too.) So if someone enters $50,000 and 50% commitment, we use $50,000 for their cost in all the math. We don't scale it based on their percent commitment.
> 
> So one of two things seems to be true:
> 
> We are doing it right, in which case there is no "unit cost" for APD key personnel in this table, there is only a total cost. (We could compute a unit cost as total / commitment, but I chose not to do that because in the table, it looks like a user input but it's calculated. It's also not a useful number to calculate since it is only for display in this one table.)
> 
> We are doing it wrong and the cost entered in the key personnel section is that person's total cost to the state, not to the program, and we should scale their cost based on their time commitment to the program.
> 
> In either case, we probably ought to update the help text to be clear which we're asking for. (And if we're going to tweak help text, can we also explain what it means for someone to have a commitment greater than 0% but also have no costs attributable to the program?)

We should review how to handle key personnel -- and how they contribute to the administrative costs.

### This task is done when...
 - [ ] A decision has been made about how to handle key personnel costs
 - [ ] A new issue has been spun up to document the implementation (OR we close this issue)

**Comment by jeromeleecms** [comment]
We should calculate key state staff the same as how we treat state staff in activities - per parking lot time 04/15. @mgwalker @pphillips-fearless Can we spin up an issue to adjust the math for this.

**Comment by pphillips-fearless** [comment]
The new dev task is #2174
