### ISSUE TITLE
Where does the link home in the sticky side bar take you in the print preview?

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#2117]
Now that we have the sticky header in place, in the print preview, the link for "< {State} APD Home" takes you back to the dashboard. Is the the right place it should take you or should it take you back to the APD Builder screen? 

This was discussed briefly in #2099 and a little in parking lot time when one of the team indicated that using the browser back button in general is not the best User Experience.

### This task is done when...
 - [ ] Decision made about what to do with the link in the sticky bar is made. 
 - [ ] (If needed) Issue documenting the implementation is created or this one is repurposed.
 
*Add a LABEL (design, dev, compliance, BUG, etc) before submitting.

*If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for PRODUCT to prioritize.

**Comment by beparticular** [comment]
@jeromeleecms what do you think about these changes?

![Screen Shot 2020-04-13 at 1.57.32 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/012ad4ac-2144-471b-9aa6-747cf5b8abde)

1) I moved the export/submit instructions from the bottom of this page to the top of the page, to give the page some context. 
2) I added a < Back to eAPD link at the top so folks can get out of this screen 
3) Jesse recommend increasing the font size on the CTA for submitting while we're working on this page (I agree) 18px is good. 
4) Jesse also suggested adding a button to send an email to the noted email in the text for a clearer way to submit (this would be helpful, I think) 
5) Icon change to an icon in the design system for the export button


Specific Questions -
1) Is that the right CTA to send them "back to your eAPD" or is there a more commonly used term they are familiar with to get back to the submit/export screen?
2) Is this the page that has been referenced as "print preview" and if so, do we want to make it more clear that printing is an option here?

**Comment by beparticular** [comment]
Note to @pphillips-fearless for when this goes to development: we have the print preview hiding the instructions that are being moved to the top. Let's make sure that stays hidden on the print PDF. Thanks!

**Comment by jeromeleecms** [comment]
Will address this first: 

1) Is that the right CTA to send them "back to your eAPD" or is there a more commonly used term they are familiar with to get back to the submit/export screen?

"back to APD" would be more accurate. The eAPD is the name of the app and we wanted to be sure that states did not somehow think that an eAPD is a new kind of APD. 

2) Is this the page that has been referenced as "print preview" and if so, do we want to make it more clear that printing is an option here?

When I've been referring to print preview, it's been in reference to the print preview functionality within the browser. This page is more of a review of the content of the application in a single view (but it's worth making sure we are aligned with how we use that term).

Let me think through the suggested changes a little more.

**Comment by jeromeleecms** [comment]
@beparticular 

Some additional comments/feedback:

1) What do you think about splitting the context setting and the actual actions up? If you are concerned about context setting, then the help text should appear at the top of the page and the shortened version of the instructions and the actual actions would appear at the bottom. My thinking is the user would see the instructions, review the APD, and then when they get to the bottom they would want to be able to do something (in this case, export the PDF and then potentially submit to CMS through email).

2) I do like the idea of having a separate navigation between going to the main dashboard OR back to the APD builder screen. Should it be sticky or something else? Similarly to my comments on 1, as a user scrolls to review the content the APD, the actual actions (whether they are export, email, or navigate) will disappear as you navigate away. If it's persistent, then the user would be able to navigate back to the APD immediately if they found an error while reviewing the overall view.

3) What is the expected behavior for the send to CMS button? We had removed a similar button in the past because we didn't want to convey that the system would actually send the document to CMS / route it through the eAPD. 

4) The specific design (font size, icon change) are fine. I like the fact it says PDF.

Looking forward to hearing some additional thoughts/feedback!

**Comment by beparticular** [comment]
Cool, ok. I'm hearing thoughts here around thinking of use cases for this page. 

1. I think it's ok to have everything at the top for now. If folks only want to export and don't review the entire page, they won't know to scroll to the bottom to see any actions. (We do want to look at this whole flow and eventually test the export/submit flow.)

2. Generally I'd want to avoid two sticky headers in a row. I've seen it done, but it can get weird. What about adding the back link at the top and the bottom of this page? 

3. @jjames521 can you elaborate on this? or we could move this into a new ticket if needed?

4. Yay!

**Comment by jeromeleecms** [comment]
1. How about adding a "Return to Top of Page" type option at the bottom of the page then (flexible with the actual words)? It would allow the user to jump quickly to the export actions if they are done reviewing.
2. I'm fine with this too. Not sure if it get's messy with the added option of return to top of page with it as well. But if I had to choose which one, I would choose "Return to Top of Page" because all the options for exporting and navigating back to the builder page can be found at the top.
3. Pending
4. Check - 🎉 

Also something to keep in mind for the longer goals of the project (so we don't spend TOO much time dwelling on this screen so we can keeping moving to the update experience):

- The submission to CMS will eventually be done through the application. This export screen was initially built as a stop gap because states wanted a way to review the whole APD in a single space without having see all the messy form fields. 

- We did hear during research, that states would still want some export functionality because they need to have an option to share the APD with their internal stakeholders, BUT that need may be diminished if/when we implement multiuser editing. 

- In the future, I can walk you through the current overall process as it stands and when we get to the online submission parts of the app, we can do a little re-imagining of what the online submission process would be. Because of the variance of each state's internal processes the app will not include an internal state workflow.

**Comment by beparticular** [comment]
Excellent, I'll add that back to the top link in the design? 

3. The idea in my head was just to open a mailto: link when the submit button is clicked that has the same behavior as clicking the email link above it. @jjames521 would that work for now so we can update the design and close this ticket for this sprint? 
If so, I'll wrap up our decisions with an updated screenshot in a comment and we can move it forward.

**Comment by jeromeleecms** [comment]
I'm good with that behavior as long as the user doesn't expect something beyond the email option at this point. If you and @jjames521 are good with this, new screenshot will be good and we can get this to dev to spin up an issue.

**Comment by jjames521** [comment]
@beparticular @jeromeleecms That was my thought as well, just a mailto style interaction would work.  That is what I had imagined in my head also.  Just a redundancy really.

**Comment by beparticular** [comment]
![Screen Shot 2020-04-17 at 11.01.09 AM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/003cab23-b7ba-484d-96dd-641094389c7a)

Final list of updates to this page - 

1. Moved the export/submit instructions from the bottom of this page to the top of the page
2) Added a < Back to eAPD link at the top so folks can get out of this screen
3) Added a ^ Return to the top of the page link at the bottom of this screen so folks can jump back to the top when they review the page in full
3) Increase the font size on the text instructions in the blue box to 18px (headers are fine at 21px)
4) Added a submit button
5) Icons changed to icons that are in the design system for the export button and the submit button
https://design.cms.gov/style/icons/

@pphillips-fearless this is ready to move to implementation! @radavis

**Comment by pphillips-fearless** [comment]
This has become development task #2182
