### ISSUE TITLE
Cost Allocation and Budget table is confusing when there's little to no budget data

### ISSUE THREAD

**Issue by radavis** [18F/cms-hitech-apd#2131]
Steps to reproduce:
* Navigate to Program Activities: Activity List
* Click 'Add Another Activity'
* Click 'Edit'
* Click 'FFP and Budget' for that New Activity

Screenshot of resulting view:

<img width="769" alt="Screen Shot 2020-03-23 at 5 24 38 PM" src="https://user-images.githubusercontent.com/1299034/77364935-917b0000-6d2b-11ea-8fc8-0d6c60262207.png">

Personally, I was confused by the line items with zero dollar amounts and no name. I would consider the priority of this to be very low, since the user should complete a number of other steps before they even get to this page.

**Comment by jeromeleecms** [comment]
Add placeholder text to help clarify this

**Comment by radavis** [comment]
This has changed since filing. Following the steps to reproduce, we now get this as a result:

![Screen Shot 2020-05-07 at 11.51.26 AM.png](https://images.zenhubusercontent.com/5e62a052e57324bfda300f92/25524259-f004-47d3-840e-a67f0521a748)

It seems as if the bug has scurried away!

**Comment by radavis** [comment]
Fixed by https://github.com/18F/cms-hitech-apd/pull/2148
