### ISSUE TITLE
Figure out what to do with yellow focus styles

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#2134]
The CMS Design System added a new visible focus style in version [3.6.0](https://github.com/CMSgov/design-system/releases/tag/3.6.0) with good intentions:

> This gives the design system a foundation for consistent focus styles across all elements and components without relying on browser styles alone.

However, this doesn't fit in seamlessly with all of the eAPD app styles, for example:

### 1. Header links

After clicking links in the header:

![Screen Shot 2020-03-25 at 3 30 23 PM](https://user-images.githubusercontent.com/21222704/77592707-02e3bb80-6eb0-11ea-8940-9250e83643d5.png)

### 2. Buttons 

Before clicking the button:

![Screen Shot 2020-03-25 at 3 30 42 PM](https://user-images.githubusercontent.com/21222704/77592803-37f00e00-6eb0-11ea-97db-739d0993f081.png)

After clicking the button, it turns bright yellow and distracts from other actions and changes on the page that we actually want users to pay attention to:

![Screen Shot 2020-03-25 at 3 30 36 PM](https://user-images.githubusercontent.com/21222704/77592820-42120c80-6eb0-11ea-974d-7ff1c62de0b3.png)

### This task is done when...
 - [ ] We have a recommendation for what to do with the focus styles
 - [ ] Dev issue is created

**Comment by jjames521** [comment]
Looking at some of these options, notably the USWDS and how they handle focus styles, with a few caveats

![FocusStyles.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/3821ea39-e859-4145-8439-09c700d7d5a4)

This is a look at the blue under different color blind ranges for WCAG 2.0 compliance
![FocusStyles2.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/62b8b263-a9d5-4481-9b57-4c75a8fc35a3)

**Comment by beparticular** [comment]
This is good, an improvement over surprise-yellow. I like the #0071BC you've used above if we want to go ahead and move forward with that. @jeromeleecms

**Comment by nicholeweems** [comment]
@jeromeleecms, ready for review

**Comment by jeromeleecms** [comment]
This looks fine. From our conversation today, implementing this will not dramatically interfere with our ability to implement the design system as they update it.

@jjames521 Do you have a specific list of changes that @pphillips-fearless could use to translate this to a dev task?

**Comment by jjames521** [comment]
@jeromeleecms @pphillips-fearless

Concept taken from https://designsystem.digital.gov/components/button/
Following changes:

Any buttons on #ffffff background from inspection of the component off USWDS something like this:

```
.usa-focus {
    outline: .25rem solid #0071bc;
    outline-offset: 0;
}
```

Any buttons that fall in the header or #112e51 should display a #ffffff border around them for focus

<img width="991" alt="Screen Shot 2020-04-15 at 5 48 01 PM" src="https://user-images.githubusercontent.com/62292793/79393875-34e2bd80-7f44-11ea-8593-dd0bad7bdc31.png">

```
.usa-focus {
    outline: .25rem solid #ffffff;
    outline-offset: 0;
}
```

Any form text boxes .ds-c-field { would need to be transferred from #FFDE11 borders to (this may need consideration @pphillips-fearless in regards to the blue being harder to see on the black, right now the border is implemented right on top of the forms so it hugs the box pretty tight, with #0071bc blue is hard to see, we need to mimic the way the focus styles are with the buttons, seen on USWDS. I've mocked them up here.

<img width="524" alt="Screen Shot 2020-04-07 at 2 30 37 PM" src="https://user-images.githubusercontent.com/62292793/79394084-aa4e8e00-7f44-11ea-9fdb-d052d0fc9d1b.png">

<img width="1026" alt="Screen Shot 2020-04-15 at 6 32 08 PM" src="https://user-images.githubusercontent.com/62292793/79395368-76289c80-7f47-11ea-9f47-dc731f621901.png">


```

 outline: .25rem solid #0071bc;
    outline-offset: 0;

```




The navigation links focus would basically inverse the blue that is used in the left hand navigation text color when highlighted #0071bc and change it to #ffffff with #0071bc background the only addition would be a border that goes around the #0071bc "box" that is serves as an indicator for navigation (If you need clarity on this @pphillips-fearless I can definitely show you). I've mocked it up here

<img width="456" alt="Screen Shot 2020-04-15 at 6 29 39 PM" src="https://user-images.githubusercontent.com/62292793/79395185-1cc06d80-7f47-11ea-9572-2ed7edb205ad.png">


<img width="386" alt="Screen Shot 2020-04-09 at 1 49 44 PM" src="https://user-images.githubusercontent.com/62292793/79394066-9dca3580-7f44-11ea-924e-aebec93d0a85.png">

**Comment by jeromeleecms** [comment]
Thanks and good to go on my end. I'll defer to @pphillips-fearless to spin up the issue(s) or if he has any additional questions/comments on this.

**Comment by pphillips-fearless** [comment]
this is now dev task #2175
