### ISSUE TITLE
Figure out CORS settings

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#214]
Specifically interested in what the `Access-Control-Allow-Origin` header should be.  Currently it is set to the origin of whatever website initiated the request, meaning browsers will allow all websites to interact with our API.  I think it should be set statically to the hostname of the actual API server, in which case it should probably come from an environment variable so we can vary it based on where it's running it (e.g., in development, it could be `http://localhost:8080` or in staging it could be `https://hitech-apd.app.cloud.gov`).

This may be something that the CMS ISSO can help us figure out.

Initially assigning myself and @NAretakis so it's in both our buckets until we find out if the ISSO can help.

**Comment by NAretakis** [comment]
@mgwalker is this obsolete? or should this be part of infrastructure/login?

**Comment by mgwalker** [comment]
It's probably safe to obsolete it.  The question stands, but it's not articulated well in this issue.  The question is:  should the eAPD API be accessible to anything other than the eAPD web app?  If the answer is yes, we don't need to do anything.  If the answer is no, then we need to implement this ***as well as*** some other stuff.

I'd argue in favor of leaving the API open and not doing anything related to this issue.  It could be helpful if states ever want to integrate their own tools.

**Comment by NAretakis** [comment]
answer is yes!
Closing issue 🎉
