### ISSUE TITLE
Plan, conduct, and synthesize round 11 of usability testing

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#2147]
A few considerations for what we can test are:

* Paginated view, back/next buttons
* Sidebar updates
* Print preview updates
* Autosave implementation
* APD unique IDs
* Goals and objectives
* Updated tables (staffing, contractor)
* Renaming in-house to state costs

Potential testing dates: Week of April 21

This task is done when...

- [x] We have a research plan and protocol
- [x] We have the designs/prototype to be tested
- [x] Participants are recruited and sessions are scheduled
- [x] Sessions have been conducted
- [x] Results have been synthesized/analyzed
- [x] Findings have been shared with the team 
- [x] Findings have been added to the wiki
- [x] Next steps are identified and new issues have been created

**Comment by beparticular** [comment]
Planning document in progress,  including Scope for this round  - 
https://docs.google.com/document/d/1tQPPwv4L1ARHnZ7JBz4TV8tSOPYQY7xPHkfbqxTcN90/edit?pli=1#heading=h.3g0ks6vnl97f

**Comment by CSwartzHMA** [comment]
Draft outreach language has been reviewed and approved by the team. A Google form has been created to capture availability from volunteers. The email distribution list which includes previous testers was updated to include volunteers from the February 2020 sessions. This list was used for this round of outreach, rather than the All-States distribution list. Will watch for responses and schedule sessions.

**Comment by beparticular** [comment]
Protocol in progress: 
https://docs.google.com/document/d/1FgCQYUkrziKnR8XCwkarEhsdh4x39HB6Ap2VgNys6b4/edit#

**Comment by CSwartzHMA** [comment]
Sessions have been scheduled with 4 states.

**Comment by beparticular** [comment]
Synthesis document in progress - this document outlines the goals of each part of the tests, as well as the questions we want to have answered by the research. Once the sessions are complete, we'll work to pull information from each session into this document to answer our questions about what we're studying as a whole. 

https://docs.google.com/document/d/1r2wFXD5x438tXfEx-NU1eZLyPusEv2m1kRxSoyrrF7A/edit#

**Comment by beparticular** [comment]
I'm just testing my filters in Outlook. Don't mind me. 
@beparticular
