### ISSUE TITLE
Content Review for consistent use of terms

### ISSUE THREAD

**Issue by CSwartzHMA** [18F/cms-hitech-apd#2162]
To assist the user in following the flow of data between tables, it is important to make sure terms, column titles, etc. are consistent throughout the app.

### This task is done when...
 - [x] The design team has designated the preferred method for review and flagging of changes needed
 - [x] Tables throughout the app have been reviewed for consistent use of terms, including match up to menus and other content which references or describes tables
 - [x] Suggestions for replacement of inconsistencies and/or outdated terms have been relayed to the design team
 - [x] Inconsistencies of column label order (IE State, Fed, Medicaid total) are noted for implementation in story #2166

**Comment by CSwartzHMA** [comment]
@lauraponce Do you think it is most efficient to add notes within a separate dev tool or just drop screen shots with mark ups here?

**Comment by lauraponce** [comment]
@CSwartzHMA whichever is easiest for you! It seems like maybe the screenshots with markups might be the lightest lift? Either way though!

**Comment by CSwartzHMA** [comment]
Screenshots will be captured and marked up here: https://app.mural.co/t/gsa6/m/gsa6/1586284265514/8a926a6fae91bbb6a83a3b4db938f7dfec7dfe10

**Comment by CSwartzHMA** [comment]
The team has decided to use Mural but screenshots will also be dropped here once marked up.

**Comment by CSwartzHMA** [comment]
[eAPD Outline.docx](https://github.com/18F/cms-hitech-apd/files/4576299/eAPD.Outline.docx)

**Comment by CSwartzHMA** [comment]
Closing as all identified discrepancies have been documented in separate issues.
