### ISSUE TITLE
Rearrange columns and rows in Summary Budget Tables

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#2166]
In a conversation with Jerome and design this week, we talked about a more logical way to organize the information in this table. It would make more sense to move Medicaid total to the far right since it's totaling the federal and state columns. Similarly, it would be a little clearer to swap the order of non-personnel and contracted resources because we group state and non-personnel in the state costs table.

![Screen Shot 2020-04-10 at 8.24.10 AM.png](https://images.zenhubusercontent.com/57f4106595e42b6c5ba9e43c/727b3c2b-e1d2-48ea-bb27-f5bd1e8bd262)

### This task is done when...
 - [ ] The table order is updated

**Comment by beparticular** [comment]
This may be covered in #2298
