### ISSUE TITLE
Build the "Summary Budget by Activity" table

### ISSUE THREAD

**Issue by pphillips-fearless** [18F/cms-hitech-apd#2170]
Build the "State Costs summary" table based on the design in task #1937

### This task is done when...
 - [ ] the "State Costs Summary" table is built

**Comment by pphillips-fearless** [comment]
Reference the mural at https://app.mural.co/t/gsa6/m/gsa6/1585942490744/d53ca4663eff051ca34dada15dc3d0172474eec8 to see where the new page will be located in the navigation (also attached image)

**Comment by beparticular** [comment]
Some changes are coming out of 11.5 round of research for the design of this table. 

- Change Medicaid Share and Total Medicaid Costs on the state costs summary table to "Total computable medicaid cost" for both total lines.
- Agree on a name for the table that fits criteria as well as matches and maintains consistency with rest of app/content (update the name of the table in the related tickets after a decision is made) 

@jjames521 will work with @pphillips-fearless to create the appropriate information or tickets to reflect the full new design and reduce confusion amongst the multi existing tickets.

***In the meantime, @jeromeleecms or @CSwartzHMA do you have thoughts on what the table name should be?

**Comment by jjames521** [comment]
@beparticular @jeromeleecms @CSwartzHMA 

I had a few that I was playing around with for the table name:

- Distribution of Expenditure Summary
- Expenditure Distribution
- Expenditure Breakdown
- Attribution of Cost Summary
- Attribution of Expenditure Summary

**Comment by CSwartzHMA** [comment]
I think I like the first option best, but its a mouthful! Should it say something about Activity Cost? I think we mostly use cost, except for historical expenditures. Maybe Distribution of Activity Cost Summary? (also a mouthful)

**Comment by jeromeleecms** [comment]
Since it's in the "Proposed Budget" section how about something like: "Proposed Budget by Activity" or "Summary Budget by Activity"

The next nav option is "Summary Budget Tables" (though we could probably also call this "Summary Budget" for consistency... though this comment might be creeping into our Navigation label evaluation.

**Comment by jjames521** [comment]
![SummaryBudgetByActivityFinalVar.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/f343310e-ea90-46a0-b8a1-f86d77e946cf)

**Comment by jjames521** [comment]
@pphillips-fearless 

![Frame 110.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/b2cfcfae-6a1f-4864-89a4-965bd6aa6035)

![Frame 109.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/4812fcb7-35a6-44a8-a66f-93e90899bcd6)

![Frame 108.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/f90ad328-6dca-4151-9100-1673a0663b76)

**Comment by jjames521** [comment]
@jeromeleecms want to make sure we are in alignment, this should be the Summary Budget by Activity table?

**Comment by jeromeleecms** [comment]
Yes. The title for this table should be "Summary Budget by Activity"

**Comment by jjames521** [comment]
@pphillips-fearless

Noted in the parking lot, it was agreed that we should signify funding source in new Summary Budget by Activity (HIE, HIT etc,) that mirrors what is displayed in the Activity List.

Example:
![Screen Shot 2020-06-17 at 1.27.30 PM.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/484e8908-7654-452f-8fc3-a0e8c0fa2fef)
would be changed to **Activity 1 Program Administration (HIT)**

via

![Screen Shot 2020-06-17 at 1.24.36 PM.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/f081a94b-19dd-4b23-a2ff-77f39790fc73)
