### ISSUE TITLE
update 'Statement of alternative considerations and supporting justification' help text

### ISSUE THREAD

**Issue by pphillips-fearless** [18F/cms-hitech-apd#2185]
Update the help text with the new content described in #2171 

### This task is done when...
 - [ ] the help text has been updated

**Comment by pphillips-fearless** [comment]
@jeromeleecms the detail and help text are specified (in #2171) but there is no "hint" specified.  As there is an existing hint in the yaml file for that entry, I'm wondering if it should be left there as-is or should it be deleted?

**Comment by jeromeleecms** [comment]
Had to pull the YAML file to remind myself about how it is structured!

Here's a copy and paste from the YAML with the sections revised -- I quoted the new text in place.

Please feel free to format as needed for the YAML file:

activityAlternativesInput:
  label: Statement of alternative considerations and supporting justification
  hint: >-

> Example: Explain and justify the decision to build a custom software solution instead of using a COTS or SaaS option.
> 
> Example: Explain and justify the decision to conduct a contract modification instead of doing a fully competitive procurement.

  helpText: >-

> Provide a brief description of each alternative considered for the implementation of this activity. The description should include considerations for costs/benefits/risks for each option. Indicate which option was finally selected and why the final selection was made. As applicable, include how the selected approach supports the economic and efficient management of the Medicaid program.
> 
> If this is a previously approved activity, only use this section to discuss alternative considerations made for substantive changes / decisions made during the implementation of the project. Do NOT include the alternative analysis conducted when justifying the original activity.
>

**Comment by pphillips-fearless** [comment]
@jeromeleecms I ran into an issue with the YAML changes.  The "hint" (lighter color text) can't have two separate paragraphs.  It runs them together into a single paragraph.  The "detail" (regular text) or "helpText" (in the blue box) can have separate paragraphs.  Do you want to move things around (maybe put the helpText into the detail and the hint into the help text)?  Or should I do a code change to make the hint capable of handling two separate paragraphs?

Let me know if it would be helpful to see it the way it is now and I can make a draft PR

**Comment by jeromeleecms** [comment]
That makes sense -- let's move the helpText -> Detail and the hint -> helpText.

That's what it looks like we did for the OKR section and it looks OK: 

https://github.com/18F/cms-hitech-apd/blob/master/web/src/i18n/locales/en/activities/goals.yaml

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/da394189-444a-4c5b-a886-a946de446de6)

Does that work?
