### ISSUE TITLE
Research ideal autosave animation speed

### ISSUE THREAD

**Issue by jjames521** [18F/cms-hitech-apd#2193]
Autosave animation on top header bar after 11.5 research was seen as too fast.  We need to figure out an animation speed that works as a more noticeable save action.

![Screen Shot 2020-04-27 at 4.04.11 PM.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/1dc243b3-a368-4af7-97e2-bc4a6a669a87)

![Screen Shot 2020-04-27 at 4.04.17 PM.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/49ada1df-388a-42c9-a6c9-6679bdf20750)

### This task is done when...
 - [ ] The length of ideal speed so that save animation is at a more noticeable speed has been identified

**Comment by beparticular** [comment]
Some discussion about potential speeds in this Slack thread - 
https://gsa-tts.slack.com/archives/C8E5EJK9V/p1587578261135500

**Comment by jjames521** [comment]
Current review of documentation supports around 750ms as an appropriate time for the saving animation.  I'm splitting the difference between 500ms and 1000ms and adding the assumption of more time to notice since it isn't the main focus.   @beparticular 

Here is a 500ms vs 1001ms example for reference

![Comp 1_2.gif](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/f4bdbd66-1304-49ba-ac8f-8aa86f06bb76)


![Comp 1_2.gif](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/8bb74129-8050-459e-9878-8007c4a3d2f0)

Largely based on research from the Nielsen Norman Group and the Model Human Processor. The Nielsen Norman Group write that 100ms is perceived as instant, and 1 second is considered the upper limit of a user’s flow of thought. Together these outline a range of 0.1s to 1s for feedback to feel connected to a specific user action or input.

![image.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/a7bdf73b-addf-49f5-b678-6964da53a116)

**Comment by jjames521** [comment]
@pphillips-fearless  :)

**Comment by pphillips-fearless** [comment]
This is dev task #2207
