### ISSUE TITLE
Export view creation training

### ISSUE THREAD

**Issue by CSwartzHMA** [18F/cms-hitech-apd#2194]
The team needs to understand how content/structure changes impact the export view.

### This task is done when...
 - [ ] There has been a review of how the Export view is created.

**Comment by jeromeleecms** [comment]
Discussed during working session. Will still need some research without browser constraints. @CSwartzHMA will spin up a list of things to investigate and create an issue.

**Comment by CSwartzHMA** [comment]
See #2221 for browser constraint research.
