### ISSUE TITLE
Hide Create New APD button for users who don't have create permission

### ISSUE THREAD

**Issue by pphillips-fearless** [18F/cms-hitech-apd#2198]
Hide Create New APD button for users who don't have permission to create a new APD

### This task is done when...
 - [ ] "Create new" button is hidden for users who cannot perform this action

reference design task #2146 for context

**Comment by lauraponce** [comment]
Jenn, Jesse, and I chatted about this earlier and I wanted to share some thoughts that came up here.

Since all of the accounts will be created for the states (either by Jerome or by someone else on the team), would this actually be a use case that anyone would run into where we'd need to hide the button? My understanding is that each state would have one single login until we build in multi-user support which is down the line. @jeromeleecms is that still the case?

Assuming the permissions are set up accurately for each of the state accounts (as they are created) where states are able to create their own APDs, they shouldn't run into permission issues unless they are not logged in. In that case, we'd just prompt them to log in. It seems like this issue could be avoided upstream by just ensuring that we set up the permissions for each state's account correctly and maybe that could be what's captured in an issue to track.

cc @beparticular

**Comment by jeromeleecms** [comment]
That sounds right (one user per state) from our other discussions. The only reason we ran into this issue is because I set up the account with the wrong user role. Maybe the better solution is to temporarily hide the non active user roles so no one can select the wrong option?

**Comment by jeromeleecms** [comment]
@beparticular @lauraponce Just following up on this one ... does my suggestion make more sense for the short term?

**Comment by beparticular** [comment]
@lauraponce leaving this one to you since you know more about what's upstream from the button.

**Comment by lauraponce** [comment]
@jeromeleecms are you saying hide the non-active roles from the admin view when setting up the accounts?

**Comment by jeromeleecms** [comment]
Yes - let's just hide the non active roles from the Admin until we need them -- that way I can't select the wrong option!

**Comment by lauraponce** [comment]
Makes sense to me! 👍

**Comment by pphillips-fearless** [comment]
@jeromeleecms of the current roles, which should be hidden?

Here's the full list:
admin
federal analyst
federal leadership
federal sme
state coordinator
state sme

**Comment by jeromeleecms** [comment]
Let's hide:

- federal leadership
- federal analyst
- federal sme
- state sme

Related, is it easy to restore them? We may need to bring some of these back once we dive deeper in the update experience and bridging the link between the state submission and the federal review.

So what will remain is:

- admin
- state coordinator

These are the only active roles in the system at this moment.

**Comment by pphillips-fearless** [comment]
I've been doing some analysis for this today and realized that the roles are in the database so
to remove a role requires a database migration (and remembering which roles need to be put back).  It's not hard, but after some thought I realized that I prefer to hide the create button for roles that don't have the permission (eventually we will need to do it and I think it will be pretty easy).  To see if there are other authorization issues that will give us trouble, I looked at the activities that get assigned to the roles and thought about what it would take to lock them down on the client-side (they're already locked down in the back end).  Some of them may already be locked down (I didn't do an exhaustive analysis).  Many of them seem to related to future capabilities that we don't have yet.  For what it's worth, I thought I'd document it here:

'view-users'   --             edit-account page, hide save button and change password link if you can't add
'add-users'    --             create-account page
'view-roles'   --             not available (unless you also have view-users)
'create-roles' --             not available
'edit-roles'   --             not available
'submit-federal-response' --  not available
'submit-clearance'   --       not available
'edit-comments'      --       not available
'submit-document'    --       disable our new submit button if you don't have this permission
'submit-state-response' --    not available
'create-draft'       --       only show the create button if you have this permission
'edit-document'      --       disable saveing if you don't have this permission
'edit-response'      --       not available
'delete-users'       --       not available
'view-document'      --       disable apd link if you don't have this permission

**Comment by pphillips-fearless** [comment]
@jeromeleecms I wanted to document the conversation we had yesterday about this.  The decision was to add an "active" column to the role table  and set the ones you listed before as inactive so we won't see them now but we can easily turn them back on later.
