### ISSUE TITLE
Finish filling out the journey map

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#22]
During the design portion of kick-off week, y'all graciously started to map out what CMS and states (and other users) are doing, thinking and feeling as part of the ADP user journey.  To help us more fully understand your perspective, we'd love for you to complete the rest of the journey map in murally.

The areas to be completed are:

+ Doing: for decision and response steps
+ Thinking and Feeling for all steps. Since we didn't spend any time writing and reviewing the thinking and feelings portions of this exercise, do please review all steps for these two rows.

Any and all specific details about the actions and the systems each user group touch/use to do their work will help!

**[Journey Mapping Exercise murally](https://app.mural.ly/t/gsa6/m/gsa6/1513179635965/db6944475bd1ff323947dc9d534e69ac09602360)**

I'm sure we will have questions for y'all after this is complete, so we may set up a follow up call with you!

**Comment by jeromeleecms** [comment]
Took a crack at finishing the journey map. @mkhandekar @nicoleslaw any updates on having the people not involved on the project removed from accessing the MURAL page?

**Comment by mkhandekar** [comment]
@jeromeleecms + @NicolasAretakisCMS thanks for taking the time to wrap up the journey map!

I have asked our contact at murally to make us admins of this room. My estimate for removing folks who are not in this team is early January.

**Comment by NicolasAretakisCMS** [comment]
Added content to journey map. For the last few sections.

**Comment by nkkl** [comment]
Closing, per convo during sprint planning. Jerome and Nick have done their part. :)
