### ISSUE TITLE
Connectivity Test Between GitHub and Integrated Components

### ISSUE THREAD

**Issue by cthulhuplus** [18F/cms-hitech-apd#2200]
Test new CMS eAPD GitHub repository for connectivity between integration points. 

### This task is done when...
Test Results:
GitHub

- [x] Copy code into the CMS eAPD repo in a separate branch
- [x] Push branch to CMS eAPD repo
- [x] No issues or organization data came over

CircleCI

- [x] Upon pushing the branch to the CMS eAPD repo the CMS CircleCI begins automated tests
- [x] Automated tests fail

ZenHub

- [x] Create an issue in the CMS eAPD GitHub repo and it shows in the CMS ZenHub account

- [x] No additional Issues, Tags, etc... are present in CMS ZenHub account

CodeCov

- [x] See CodeCov report in CMS eAPD CodeCov

Slack

- [x] Message successfully sent to CMS Slack #cmcs-dsg-dss-eapd from CircleCI

**Comment by cthulhuplus** [comment]
> CodeCov
> See CodeCov report in CMS eAPD CodeCov

Could not observe any inter-connectivity between CMS eAPD GitHub/CircleCI and CodeCov. The reports that CodeCov displays are generated by tests successfully completing in CircleCI.

**DEPENDENCY: CircleCI tests completing successfully**

**Slack
Message successfully sent to CMS Slack #cmcs-dsg-dss-eapd from CircleCI**

It looks like CircleCI sends messages to Slack, will need to research/coordinate with someone who has workspace owner/admin access to the CMS cmcs-dsg-dss-eapd to integrate notifications.

DEPENDENCY: Slack webhook, human resource w/proper privileges

![image.png](https://images.zenhubusercontent.com/5e9749aa5773ead7746338c1/b640dcdc-00f3-42b3-8945-09166999779f)

**Comment by cthulhuplus** [comment]
CircleCI Environment Variables in 18F CircleCI, will need values for CMS CircleCI:
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KE
CODECOV_TOKEN
GH_BOT_PASSWORD
GH_BOT_USER
GH_REPO_ID
PREVIEW_API_PBKDF2_ITERATIONS
PREVIEW_AWS_AMI
PREVIEW_AWS_REGION
PREVIEW_AWS_SECURITY_GROUP
PREVIEW_AWS_SUBNET
PRODUCTION_API_AWS_ACCESS_KEY_ID
PRODUCTION_API_AWS_AMI
PRODUCTION_API_AWS_REGION
PRODUCTION_API_AWS_SECRET_ACCESS_KEY
PRODUCTION_API_AWS_SECURITY_GROUP
PRODUCTION_API_AWS_SUBNET
PRODUCTION_API_AWS_TARGET_GROUP
PRODUCTION_API_DATABASE_URL
PRODUCTION_API_FILE_S3_BUCKET
PRODUCTION_API_PBKDF2_ITERATIONS
PRODUCTION_API_PORT
PRODUCTION_API_SESSION_SECRET
PRODUCTION_WEB_API_URL
PRODUCTION_WEB_AWS_REGION
PRODUCTION_WEB_AWS_S3_BUCKET
SLACK_WEBHOOK_URL
SNYK_TOKEN
STAGING_API_AWS_ACCESS_KEY_ID
STAGING_API_AWS_AMI
STAGING_API_AWS_REGION
STAGING_API_AWS_SECRET_ACCESS_KEY
STAGING_API_AWS_SECURITY_GROUP
STAGING_API_AWS_SUBNET
STAGING_API_AWS_TARGET_GROUP
STAGING_API_DATABASE_URL
STAGING_API_FILES_S3_BUCKET
STAGING_API_FILE_S3_BUCKET
STAGING_API_PBKDF2_ITERATIONS
STAGING_API_PORT
STAGING_API_SESSION_SECRET
STAGING_WEB_API_URL
STAGING_WEB_AWS_REGION
STAGING_WEB_AWS_S3_BUCKET

**Comment by cthulhuplus** [comment]
I have been able to get CodeCov test results on my test, working on Slack Integration still, but close.

**Comment by cthulhuplus** [comment]
GitHub
Copy code into the CMS eAPD repo in a separate branch
 Push branch to CMS eAPD repo
 No issues or organization data came over
Image showing code in CMS eAPD repo:
![image.png](https://images.zenhubusercontent.com/5e9749aa5773ead7746338c1/faa36545-9ffa-43a3-944a-8156dbbfdb40)

CircleCI
 Upon pushing the branch to the CMS eAPD repo the CMS CircleCI begins automated tests
 Automated tests fail
Image showing CircleCI detected and ran based on code sent to CMS eAPD repo:
![image.png](https://images.zenhubusercontent.com/5e9749aa5773ead7746338c1/a8cf46a2-452d-44e4-b0a7-13455938d7c4)

ZenHub
 Create an issue in the CMS eAPD GitHub repo and it shows in the CMS ZenHub account
 No additional Issues, Tags, etc... are present in CMS ZenHub account
Image showing just the activity on the CMS Zenhub board:
![image.png](https://images.zenhubusercontent.com/5e9749aa5773ead7746338c1/56225e1d-0e78-4e64-bf77-fa6fb8a73a7c)

CodeCov
 See CodeCov report in CMS eAPD CodeCov
Image showing CodeCov is generating reports from eAPD repo
![image.png](https://images.zenhubusercontent.com/5e9749aa5773ead7746338c1/54ebea4b-b459-42bc-b0f6-977aa4065576)

Slack
 Message successfully sent to CMS Slack #cmcs-dsg-dss-eapd from CircleCI
Image showing GitHub sending data to Slack:
![image.png](https://images.zenhubusercontent.com/5e9749aa5773ead7746338c1/fd1bc707-39f7-48cd-a2ac-c787837a6b67)
CircleCI is not currently alerting to Slack, there is a hook in the build scripts that does that messaging. There is also a ticket in the back log into moving away from that script and leveraging the build in CircleCI messaging.

**Comment by jeromeleecms** [comment]
Per discussion with @cthulhuplus, all the criteria have been met and/or verified.
