### ISSUE TITLE
Move the activity schedule information to the top of the Activity Overview section

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#2210]
We intended to make this update a while back based on user feedback, but the ticket disappeared somewhere.

The change is to move the activity schedule to the top of the section right above overview (see pink arrow)

![Screen Shot 2020-05-06 at 10.11.15 AM.png](https://images.zenhubusercontent.com/57f4106595e42b6c5ba9e43c/e8db7cc1-183a-4f12-8d35-504b80fd74e5)

____________________________

Section to move:

![Screen Shot 2020-05-06 at 10.11.24 AM.png](https://images.zenhubusercontent.com/57f4106595e42b6c5ba9e43c/3a730410-aa59-47da-aa19-a5815d4252b5)

### This task is done when...
 - [ ] Activity schedule is moved to the top right above overview in editing view and print preview

**Comment by pphillips-fearless** [comment]
@lauraponce or @beparticular, should this change be made on the print-preview view as well, or just on the interactive view?

**Comment by pphillips-fearless** [comment]
in the review version it looks a little funny with the schedule just before the overview.  What do you think?

![Screen Shot 2020-05-27 at 12.09.55 PM (2).png](https://images.zenhubusercontent.com/5e6a4b048168d5a15258c7d1/5320b853-26e7-4361-af97-af8dd35f67a7)

**Comment by pphillips-fearless** [comment]
created draft PR 2248 so you can take a look

**Comment by jeromeleecms** [comment]
Can we make this section consistent with the way we lay out the executive summary?

Executive Summary in Print Preview:

![image](https://user-images.githubusercontent.com/34279968/83059273-8172eb80-a00e-11ea-894e-82c8f966301c.png)

Proposed View in Print Preview:

![image](https://user-images.githubusercontent.com/34279968/83060193-ef6be280-a00f-11ea-933c-d4f2feb551fb.png)

@beparticular ?

**Comment by jjames521** [comment]
@pphillips-fearless @beparticular @jeromeleecms 

We spoke about this, for decision archive purpose we decided the following:

**- Remove schedule from the field
- Flip Activity Summary and planned start/end date to have Activity Summary above**

This is a mockup of what it might look like, this change of fields would reflect on both the Builder and the Export view.

![exportviewdemo1.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/202abbd0-1e32-458f-b5dd-ada23c9ed4b6)
