### ISSUE TITLE
CMS Slack #cmcs-dsg-dss-eapd Integration

### ISSUE THREAD

**Issue by cthulhuplus** [18F/cms-hitech-apd#2224]
We need the CMS Slack #cmcs-dsg-dss-eapd to be integrated with CircleCI and GitHub so that messages can be sent to the Slack channel to notify of build success/failures and PR requests like we have in the current 18F setup.

### This task is done when...
 - [x] CMS CircleCI can send messages to CMS Slack #cmcs-dsg-dss-eapd
 - [x] CMS GitHub can send messages to CMS Slack #cmcs-dsg-dss-eapd

**Comment by jeromeleecms** [comment]
@NAretakis I'm putting this into this sprint since we started talking about through a separate channel

**Comment by jeromeleecms** [comment]
Still waiting for CircleCI to Slack Integration #2271. Per @cthulhuplus We are currently are using webhooks in the code.
