### ISSUE TITLE
The FTE count accepts negative numbers

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#2229]
In the State Cost Categories subsection, the FTE count allows negative numbers to be entered. Though it's probably an edge case that someone would directly type in a negative number, the up/down arrows on the right side would make it easier to make this mistake if they are clicking down.

![Screen Shot 2020-05-21 at 12.49.33 PM.png](https://images.zenhubusercontent.com/57f4106595e42b6c5ba9e43c/8d53d72f-320a-4341-805b-9771433f58f6)

### This task is done when...
 - [ ] There is no way to add negative FTEs

**Comment by radavis** [comment]
Are there any other form fields within the app that should not allow negative numbers?
