### ISSUE TITLE
Review of navigation labels

### ISSUE THREAD

**Issue by jjames521** [18F/cms-hitech-apd#2231]
After content review w/Jerome, Jenn, and Caryn it was discovered that there were several instances where navigation labels could benefit from being moved around, renamed, and overall structure re-thought.

### This task is done when...
 - [ ] It is agreed on structure of navigation
 - [ ] Labels are considered and ticket is created for change w/dev

**Comment by nicholeweems** [comment]
Closing as it duplicates #2243
