### ISSUE TITLE
Rename State Costs Summary table

### ISSUE THREAD

**Issue by jjames521** [18F/cms-hitech-apd#2233]
Discussion and review of what the best naming schema would work for the new table being deployed.

This was brought up by Jerome, Jenn, and Caryn as reference.

### This task is done when...
 - [ ] Agree on a name that fits criteria as well as matches and maintains consistency with rest of app/content

**Comment by nicholeweems** [comment]
To be revisited along with #2170 & #2234 for potential consolidation and closure

**Comment by beparticular** [comment]
Has been moved into a comment on #2170, will close
