### ISSUE TITLE
"State Costs Summary" Table Change: Medicaid Share and Total Medicaid Costs

### ISSUE THREAD

**Issue by jjames521** [18F/cms-hitech-apd#2234]
Change Medicaid Share and Total Medicaid Costs on the state costs summary table to "Total computable medicaid cost" for both total lines. #2170 to be revisited by design & dev leads

### This task is done when...
 - [ ] Design mockup done with changes
 - [ ] Agree on content change.

**Comment by beparticular** [comment]
Has been moved into a comment on #2170, will close
