### ISSUE TITLE
"State Costs Summary" table change: Move combined activity costs section

### ISSUE THREAD

**Issue by jjames521** [18F/cms-hitech-apd#2235]
Move the combined activity costs above the break down by activity in the state costs summary table. Also take a look at more established sectioning.

### This task is done when...
 - [ ] Design mockup done
 - [ ] Sign off on mockup

**Comment by jjames521** [comment]
@beparticular 

Ready for review on structure, also played around with titles and the changing of the content a little as I was messing around with the structure already.  I wanted to see holistically how it would look.

![ExpenditureSummary.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/47f2d5ac-0b6a-440e-86f4-84bd76014c49)

**Comment by jeromeleecms** [comment]
I thought for these tables we discussed including "other funding" by each line item (state staff, non-personnel costs, and private contractors) so their was a clear connection between this table and the next page of the app which breaks down the Medicaid costs with the appropriate match rate...? Otherwise, it looks like the app did some hand waving and attributed costs in a non-transparent way.

**Comment by jjames521** [comment]
@jeromeleecms this table is already out of date at this point

**Comment by jjames521** [comment]
Other funding to each section is added in, I'll post the new tables shortly

**Comment by jjames521** [comment]
@jeromeleecms

![SummaryBudgetByActivity](https://user-images.githubusercontent.com/62292793/83063065-9448e880-a02d-11ea-8cb7-a223d26475dc.png)

**Comment by jjames521** [comment]
@jeromeleecms preview of changes with related changes from #2217 and #2247

![SummaryBudgetByActivity.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/669cc3d3-659c-4328-8560-d6a6b7237102)

**Comment by CSwartzHMA** [comment]
I love the separators here! They are not seen elsewhere in the app, but is it possible to consider using them elsewhere? 
Also verifying that the ordering of elements that we should be using throughout is: State Staff, Other State Expenses, Private Contractors. Is that correct?

**Comment by beparticular** [comment]
@CSwartzHMA that's the order we're asking people to give us information in, so I believe that is correct

**Comment by beparticular** [comment]
Final design is in #2170, closing this design ticket.
