### ISSUE TITLE
Allow Creation of Deploy Key in CMS GitHub for CircleCI

### ISSUE THREAD

**Issue by cthulhuplus** [18F/cms-hitech-apd#2237]
CMS CircleCI needs to be able to add a deploy key to the CMS GitHub in order to successfully build.

### This task is done when...
 - [x] Deploy key has been added to github

**Comment by cthulhuplus** [comment]
I am not able to do this myself, I will need either @jeromeleecms or @NAretakis to create one:

https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys

**Comment by cthulhuplus** [comment]
Image of deploy key in CMS CircleCI

![image.png](https://images.zenhubusercontent.com/5e9749aa5773ead7746338c1/f8e299e0-f0af-420d-88a5-b65b480853af)

**Comment by jeromeleecms** [comment]
Under @cthulhuplus watchful eye, I set up the SSH key and this is working.
