### ISSUE TITLE
Review Cost Allocation and FFP and Budget pages for flow

### ISSUE THREAD

**Issue by CSwartzHMA** [18F/cms-hitech-apd#2244]
Information should flow in a way that makes documenting related information easy to follow.

### This task is done when...
 - [ ] Review of both pages and content within each page has been documented.
 - [ ] Recommendations and mockups for better flow have been completed and approved for implementation in the app

**Comment by CSwartzHMA** [comment]
relates to #2243

**Comment by nicholeweems** [comment]
Closing as it duplicates #2217
