### ISSUE TITLE
Use "target completion date" for milestones

### ISSUE THREAD

**Issue by CSwartzHMA** [18F/cms-hitech-apd#2246]
When Milestones are referenced, use "Target completion date".

Repurposing this design task as the new dev task.

In the Objectives and key results > Milestones section, change "Planned end date" to "target completion date".

### This task is done when...
 - [x] Identify all sections where milestone dates are referenced
 - [ ] Update content description to "Target completion date"

**Comment by CSwartzHMA** [comment]
Sections to be considered for editing:
1. Objectives and key results; Milestones - Current "Planned end date" should be "target completion date".
2. Activity Schedule Summary; Summary Schedule Table - See related issue around redesign of this section.

**Comment by CSwartzHMA** [comment]
Updated description for the Milestones section in Objectives and key results: 
![image](https://user-images.githubusercontent.com/45497254/83278337-72707280-a1a1-11ea-9d5b-7a84f2492089.png)

**Comment by CSwartzHMA** [comment]
@beparticular This is ready for your review and discussion on next steps.

**Comment by beparticular** [comment]
@pphillips-fearless approved. this is ready for dev.

**Comment by pphillips-fearless** [comment]
I'm just noticing that the changes in #2251 seem to make this change moot.  Should we not do this task?  @beparticular or @jeromeleecms ?
