### ISSUE TITLE
Use "Start Date" and "End Date" throughout app where Activities include dates

### ISSUE THREAD

**Issue by CSwartzHMA** [18F/cms-hitech-apd#2251]
Content review revealed inconsistencies in how these dates are labeled.

Repurposing this task for the dev task

Please make changes to the following pages:

    Activity > Activity Overview > Activity Schedule
    Change current "Planned start date to "Start date" and "Planned End to to "End date"

    Activities > Private contractor costs > Contract term.
    Change current "Start" should be "Start date". Current "End" should be "End date".)

    Executive Summary > Activities Summary
    Change current "Date" should be "Start date - End date"

### This task is done when...
 - [x] List of all areas of the app where this occurs has been provided
 - [ ] The text has been changed

**Comment by CSwartzHMA** [comment]
Goal is to match Activity Schedule Summary. 

Also note where this should be the actual vs. FFY end and consider whether instruction is needed to clarify desired date.

**Comment by CSwartzHMA** [comment]
Applicable sections are:
1. Objectives and key results; Activity Schedule (suggest adding instruction to conform with other sections and enforce transition to next section, then update field titles to "Start date" and "End date" for consistency.)
2. Private contractor costs; Contract term (Current "Start" should be "Start date". Current "End" should be "End date".)
3. Activity Schedule Summary; Summary Schedule Table (See separate issue around redesign of this section) (Should include range description "Start date - End date")
4. Executive Summary; Activities Summary (Current "Date" should be "Start date - End date")

**Comment by CSwartzHMA** [comment]
@beparticular This is ready for your review and thoughts in next steps.

**Comment by beparticular** [comment]
Approved and @pphillips-fearless  ready to move into the dev category

**Comment by radavis** [comment]
Does it make sense to update the activity date property names to 'startDate' and 'endDate', or something similar?

**Comment by pphillips-fearless** [comment]
I like the idea of changing the property names if it makes them match the display -- it should be a quick copy-paste operation.

**Comment by radavis** [comment]
Yeah, I appreciate consistency in a codebase. Gonna go with it.

**Comment by mgwalker** [comment]
One note is that `plannedEndDate` is named that way because in the update experience, we expected users might tell us the `actualEndDate`, which used to also be a property on the activity. I'm fine with changing the property names, but wanted to give y'all the context for why they're named the way they are. 🙂

**Comment by radavis** [comment]
I stopped short of changing property values, since it feels like that would take this 'small' t-shirt sized story into a medium or large. We can revisit this at a later date, possibly after implementing some e2e tests.
