### ISSUE TITLE
Create and Install TLS Certificates for Staging Domains

### ISSUE THREAD

**Issue by cthulhuplus** [18F/cms-hitech-apd#2254]
Create TLS certificates (via Jira ticket) for staging-eapd.cms.gov and staging-eapd-api.cms.gov. 

### This task is done when...
 - [ ] TLS certificates are created and provided in Jira ticket
 - [ ] staging-eapd.cms.gov and staging-eapd-api.cms.gov are reachable without certificate errors

**Comment by cthulhuplus** [comment]
Domains working:

![image.png](https://images.zenhubusercontent.com/5e9749aa5773ead7746338c1/663e3033-7730-4bf5-903a-4832945f690c)

![image.png](https://images.zenhubusercontent.com/5e9749aa5773ead7746338c1/c365cfd7-eb26-4f1e-b545-13444c95501b)

**Comment by pphillips-fearless** [comment]
I confirmed that the two domains are working
