### ISSUE TITLE
Update Activities Summary section in Executive Summary

### ISSUE THREAD

**Issue by CSwartzHMA** [18F/cms-hitech-apd#2255]
Following content review, a few updates to this section are needed to provide consistency.

### This task is done when...
 - [x] Identified changes have been mocked up
 - [x] Team is in agreement on changes to be made

**Comment by CSwartzHMA** [comment]
Changes needed:
Change order of elements on this page to to consistent with other sections. A decisions has been made that all sections should be ordered in the same order information is asked for in the app.
Dates on this section should reflect the date range for each activity as identified in the Activity Schedule.

**Comment by jjames521** [comment]
@CSwartzHMA Let me know how this looks

![ExecSummary Reformat.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/e8449d12-9de5-4943-9602-e80139accfe9)

**Comment by CSwartzHMA** [comment]
Looks much more consistent. I like it. The one question I have is in relation to Medicaid Share. Should this be Total Computable? Or should we leave that to be addressed in the issue pertaining to that change?

**Comment by jjames521** [comment]
Here is the mock with total computable.  What are your thoughts @beparticular @CSwartzHMA ?

![ExecSummary Reformat1.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/d85d6d35-9577-4d2b-a862-e29d39422fd6)

**Comment by beparticular** [comment]
@CSwartzHMA we can go ahead and change total computable here and take it off the list in the other ticket.

**Comment by CSwartzHMA** [comment]
Agreed @beparticular . Looks good!

**Comment by jjames521** [comment]
Linked to #2324 made comment there as well.

**Comment by jjames521** [comment]
@beparticular @CSwartzHMA 

![ExecSummary ReformatEdit1.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/2f68547b-aa5b-41eb-98b2-26469683e359)

**Comment by CSwartzHMA** [comment]
This looks good and not aligns to the order in which information is collected in the app.

**Comment by beparticular** [comment]
@jeromeleecms does this work with these changes?

**Comment by jeromeleecms** [comment]
Asked in the channel, but "Total Computable" should be "Total Medicaid Computable" based on the work from #2324 -- right? Sequence looks good.

**Comment by jjames521** [comment]
That makes sense to me I can quickly mock this up too

**Comment by jeromeleecms** [comment]
This is good to go from my end.

**Comment by jjames521** [comment]
@pphillips-fearless @thetif 

This is ready to move forward, just got the got ahead from Jerome, Jenn, and Caryn.  Let me know if you need any further details in the change log.

**Comment by pphillips-fearless** [comment]
new dev task is #2376
