### ISSUE TITLE
Plan Interviews with States for the update experience research

### ISSUE THREAD

**Issue by beparticular** [18F/cms-hitech-apd#2267]
Speak with states about or observe how they currently update their APDs. 
What works about it and what is frustrating about it in order to understand their experience of updating an APD

Mural for planning
https://app.mural.co/t/eapd5455/m/eapd5455/1589473078197/1c0aba980ae37ce1440b520f53566dd46195d992

### This task is done when...
 - [x] We have a research plan and protocol
 - [ ]  We have the designs/prototype to be tested if needed
 - [x]  Participants are recruited and sessions are scheduled

**Comment by beparticular** [comment]
Protocol in progress
https://docs.google.com/document/d/1zHdfsy4XocQigDCZiVU4Csg75BfS9jRdSc1CQXqQVMo/edit#heading=h.hgcy541w1s18

**Comment by CSwartzHMA** [comment]
Message and google form have been created. Email has been sent for approval and dispatch to the all-states listserv.
