### ISSUE TITLE
Create a UX Strategy Doc 

### ISSUE THREAD

**Issue by beparticular** [18F/cms-hitech-apd#2272]
Create a document in Mural that helps the team focus new ideas and revisions holistically and consistently as we decide what to build for the update experience. 

This will be different from the roadmap or the board as it will be organized by section. Can use this outline in Figma as a basis once we look at #2243. https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-pages-LP-March2020?node-id=456%3A12

If this format works, we can continue this as a general UX Strategy Doc for our product 

### This task is done when...
 - [x] Look to see if there's a visual way to do this in zenhub before creating something new (there is not)
 - [x] A framework for UX Strategy is created in Mural
 - [x] Notes about future states currently being captured in the design sync document need to be moved here

**Comment by beparticular** [comment]
This document has been created and will be an ongoing document that is maintained by design. 

It ended up being less of a strategy document, so I've asked @jeromeleecms to change the title to "UX Consistency and Considerations" and to extend the size of the Mural so that I can clean it up and make it a usable board. It can be for keeping track of ideas, upcoming changes, and considerations for different sections as we begin to work on the update experience. Once the title change has been made, this ticket can be closed.  

Link to document https://app.mural.co/t/cmsmural6360/m/eapd5455/1589473192667/fd6acff3bfacd8e9241c07941d9ac20d544c7fc1

**Comment by nicholeweems** [comment]
Closing, doc linked above
