### ISSUE TITLE
CircleCI - Cleanup Preview Deploys Job fails

### ISSUE THREAD

**Issue by cthulhuplus** [18F/cms-hitech-apd#2279]
Currently the CircleCI Cleanup Preview Deploys job fails when there are no instances to clean up. This is a continuation of a previous that was patched by @mgwalker, but another issue has sprung up. Specifically:

jq: error (at <stdin>:1): Cannot index string with string "number"

https://circleci.com/gh/18F/cms-hitech-apd/59774?utm_campaign=chatroom-integration&utm_medium=referral&utm_source=slack

### This task is done when...
 - [ ] The above error has been resolved
 - [ ] The Cleanup Preview Deploys job either succeeds or ends gracefully when there is nothing to cleanup

**Comment by cthulhuplus** [comment]
I have been unable to manually reproduce this issue by running the cleanup script on the command line nor via rerunning the failed job in CircleCI. I will leave this ticket open a little while long to see if the issue resurfaces.

**Comment by nicholeweems** [comment]
Closing as issue is no longer occurring and not reproducible. Will reopen if deemed necessary.
