### ISSUE TITLE
Define use-case completion state

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#228]
This issue will clarify what counts as completion for use-cases to be used in HiC.

### This task is done when...
 - [x] Use-case template is constructed
 - [x] Use-case for HIT is constructed
 - [x] Use-case for HIT/HIE is constructed
 - [x] Use-case for HIT/MMIS is constructed
 - [x] Use-case for HIT/HIE/MMIS is constructed
 - [x] Use-case cases have been reviewed by CMS APD Team
 - [x] Use-case cases have been reviewed by Design Team

**Comment by NAretakis** [comment]
@quarterback @lauraponce Before I start in on some of the use-case stuff. Do y'all have a template or structure that you might prefer? I am then thinking that we create one for the varying levels of complexity with each submission type.

**Comment by lauraponce** [comment]
I don't have a template, but the structure that I'm most familiar with is listing out:

- The user
- Their goal/motivations
- How they accomplish a particular task (the steps they take)
- How the app should respond

**Comment by NAretakis** [comment]
Cool cool, that should work.

**Comment by NAretakis** [comment]
OK, 4 out of 5 use cases are roughed in. The 5th one might not be necessary, but I want to walk through this with @lauraponce @quarterback and @jeromeleecms, so we can come to a decision. I'll see if we can grab a bit of time to walk through these.

**Comment by NAretakis** [comment]
Use cases have been shared with CMS APD team. Expecting to have consolidated feedback by 3/22/18

**Comment by NAretakis** [comment]
@lauraponce @quarterback [Use-Cases and their basic flows have been updated.](https://docs.google.com/document/d/1Oh8C9YSORO03Mh9kGF-TKgWnmQvamuaTIUjcoK3cc7U/edit) Low priority pass to you to make sure these make sense and will be useful.

**Comment by lauraponce** [comment]
Just read through the use cases and this all looks great. It's so helpful to have this outlined.

**Comment by quarterback** [comment]
@NAretakis This is very helpful!

**Comment by NAretakis** [comment]
Yay! Closing issue.
