### ISSUE TITLE
Write help text that explains Other Funding

### ISSUE THREAD

**Issue by beparticular** [18F/cms-hitech-apd#2281]
As discussed in the design sync, help text that explains Other Funding needs to be created. 
Consideration - Other Funding will be moved to the cost allocation page, so consider that particular context. 

### This task is done when...
 - [ ] The help text draft is written
 - [ ] Product signs off on the draft
 - [ ] Instructions for dev on where the help text needs to go are provided. (Could be a screenshot with an arrow pointing to the right place, for instance.)

**Comment by CSwartzHMA** [comment]
Existing Content for consideration
**Cost Allocation>Other Funding:** Write a high level description of funding used to support this activity. (Review Letter 10‐016 for examples of grants for inclusion.)
Help Text:Ensure new grants are included, and remove expired grants.
**FFP and Budget>Other Funding Amount:** Enter the total amount that will be used from additional funding sources.
Help Text: Other funding consists of funds that are not directly tied to the CMS grant and the matching state funds for this activity. This funding may come from another federal source, another state agency, and/or contributions or donations from a third party. Other funding will be deducted from the total cost of the activity prior to calculating the Medicaid share.

When these fields are reorganized, proposed text for this section is:
Other Funding includes funds that are not directly tied to the CMS grant and the matching state funds for this activity. This funding may come from another federal source, another state agency, and/or contributions or donations from a third party such as payer and provider subscription fees or contributions. Other funding will be deducted from the total cost of the activity prior to calculating the Medicaid share. (Review SMD Letter 10‐016 for examples of grants for inclusion.)

**Comment by jeromeleecms** [comment]
Made some edits to account allow for examples:

**Cost Allocation>Other Funding:** 
Provide a high level description of funds that are not directly tied to the HITECH Medicaid grant. This funding may come from another federal source, another state agency, and/or contributions or donations from a third party such as payer and provider subscription fees or contributions. If this other funding will be used to cover the State share tied to HITECH Medicaid grant, please provide a justification for this here. (Review SMD Letter 10‐016 for examples of grants for inclusion.)

**FFP and Budget>Other Funding Amount** (will be relocated to the cost allocation page). 
Provide the total amount of funds not associated with the HITECH Medicaid grant (i.e. any cost allocated funding from all parties) and the amount from other funding that will will not be used for the state share of the HITECH Medicaid grant. This amount will be deducted from the total cost of the activity to calculate the total computable Medicaid share for this activity.

Example: (in blue box help text)
For a $1,000,000 project that is 80% cost allocated to Medicaid and 20% for all other stakeholders, enter **$200,000** (20% of $1,000,000).

For a $1,000,000 project which receives a $100,000 grant (i.e. other funding) prior to cost allocation and is cost allocated to Medicaid at 80%, enter $280,000 ($100,000 [other funding] + $180,000 [20% of the remaining $900,000]).

Would be helpful to have another set of eyes @beparticular @CSwartzHMA ...

**Comment by CSwartzHMA** [comment]
Minor edits, but I really like the way this is shaping up:

**Cost Allocation>Other Funding:**
Provide a high level description of funds that are not directly tied to the HITECH Medicaid grant. This funding may come from another federal source, another state agency, and/or donations or contributions from a third party such as payer and provider subscription fees. If other funds will be used to cover the State share tied to the HITECH Medicaid grant, please include a justification for this here. (Review SMD Letter 10‐016 for examples of grants for inclusion.)

**FFP and Budget>Other Funding Amount** (will be relocated to the cost allocation page).
Provide the total amount of funds not associated with the HITECH Medicaid grant (i.e. any cost allocated funding from all parties) and the amount from other funding that will will not be used for the State share of the HITECH Medicaid grant. This amount will be deducted from the total cost of the activity to calculate the total computable Medicaid share for this activity.

Example: (in blue box help text)
For a $1,000,000 project that is 80% cost allocated to Medicaid and 20% for all other stakeholders, enter $200,000 (20% of $1,000,000).

For a $1,000,000 project which receives a $100,000 grant (i.e. other funding) prior to cost allocation and is cost allocated to Medicaid at 80%, enter $280,000 ($100,000 [other funding] + $180,000 [20% of the remaining $900,000]).

@jeromeleecms Do we need to include anything that clearly outlines costs for portions of activities that do not support Medicaid recipients or do you feel that is understood based on the reference to payer contributions?

**Comment by jeromeleecms** [comment]
The revised text looks good. For your question, is that addressed at the top of the cost allocation section already? I'm thinking that the portion of activities not supporting Medicaid recipient might be described in the Cost Allocation Methodology box.

Happy to dissect this a bit more to make sure I'm understanding your question...

**Comment by CSwartzHMA** [comment]
@jeromeleecms We talked about changing the second example, but the first is simpler so maybe we expand on that one?

For a $1,000,000 project that is 80% cost allocated to Medicaid (related to 80% Medicaid transaction volume, for example) and 20% for all other stakeholders, enter $200,000 (20% of $1,000,000).

**Comment by jeromeleecms** [comment]
Works for me, @CSwartzHMA. Here's the final text with screenshots as it is meant to appear in the specific sections -- any last changes?

Cost Allocation>Other Funding:
Provide a high level description of funds that are not directly tied to the HITECH Medicaid grant. This funding may come from another federal source, another state agency, and/or donations or contributions from a third party such as payer and provider subscription fees. If other funds will be used to cover the State share tied to the HITECH Medicaid grant, please include a justification for this here. (Review SMD Letter 10‐016 for examples of grants for inclusion.)

![image](https://user-images.githubusercontent.com/34279968/85777164-38c65500-b6d6-11ea-9e32-c27e8c085f80.png)

FFP and Budget>Other Funding Amount (will be relocated to the cost allocation page).
Provide the total amount of funds not associated with the HITECH Medicaid grant (i.e. any cost allocated funding from all parties) and the amount from other funding that will will not be used for the State share of the HITECH Medicaid grant. This amount will be deducted from the total cost of the activity to calculate the total computable Medicaid share for this activity.

Example: 
For a $1,000,000 project that is 80% cost allocated to Medicaid (related to 80% Medicaid transaction volume, for example) and 20% for all other stakeholders, enter $200,000 (20% of $1,000,000).

For a $1,000,000 project which receives a $100,000 grant (i.e. other funding) prior to cost allocation and is cost allocated to Medicaid at 80%, enter $280,000 ($100,000 [other funding] + $180,000 [20% of the remaining $900,000]).

![image](https://user-images.githubusercontent.com/34279968/85778076-0f59f900-b6d7-11ea-9526-f9cb2b628c71.png)

**Comment by CSwartzHMA** [comment]
@jeromeleecms This looks great. Thanks for adding the mockups. I like the flow of information. Much improved.

**Comment by beparticular** [comment]
Added to #2217 for implementation. Closing so #2217 is unblocked.
