### ISSUE TITLE
Write help text for the FFP/Federal-state split selection 

### ISSUE THREAD

**Issue by beparticular** [18F/cms-hitech-apd#2283]
As discussed in the design sync, help text that explains the FFP/Federal-state split needs to be created. 
Consideration - FFP/Federal state split will be after the summary budget on the FFP and budget page. (Currently being discussed in #2217) 

### This task is done when...
 - [x] The help text draft is written
 - [x] Product signs off on the draft
 - [ ] Instructions for dev on where the help text needs to go are provided. (Could be a screenshot with an arrow pointing to the right place, for instance.)

**Comment by CSwartzHMA** [comment]
Draft text for consideration: Please select the funding split applicable to this activity.

**Comment by jeromeleecms** [comment]
Select the match rate for Federal Financial Participation applicable to this activity. Calculations for the Federal and State share will be updated in the table below.

1) Removed the "please" for consistency
2) "match rate" is a term used in regulation (45 CFR 95)
3) Added the second sentence from the observation in user research where the user didn't realize that the table was going to be automatically updated. Open to rewording here.

**Comment by CSwartzHMA** [comment]
@jeromeleecms I like this and was thinking about this second sentence, too. So, I say go with it.

**Comment by jeromeleecms** [comment]
@beparticular Screenshot with updated text:

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/d2136435-697f-450c-9ee9-ff61149a7ae3)

If you are good with this -- we can move to Dev.

**Comment by beparticular** [comment]
@jeromeleecms thumbsup

**Comment by jeromeleecms** [comment]
@pphillips-fearless This is ready for dev. See screenshot above. Export view should not include help text.

**Comment by pphillips-fearless** [comment]
new dev issue is #2311
