### ISSUE TITLE
Write help text for Activities > Activity Overview > Activity Schedule 

### ISSUE THREAD

**Issue by beparticular** [18F/cms-hitech-apd#2284]
As discussed in the design sync, help text that explains Activities > Activity Overview > Activity Schedule needs to be created

### This task is done when...
 - [x] The help text draft is written
 - [x] Product signs off on the draft
 - [ ] Instructions for dev on where the help text needs to go are provided. (Could be a screenshot with an arrow pointing to the right place, for instance.)

**Comment by CSwartzHMA** [comment]
Draft text for consideration: 

Please provide the planned start and end dates for this activity. These dates may extend beyond the FFY included in this APD.

@jeromeleecms @beparticular Please provide feedback.

**Comment by jeromeleecms** [comment]
Provide the planned start and end dates for this activity. These dates may extend outside of the FFY(s) included in this APD.

1. Removed the word "please" for consistency with our other phrasing within the app
2. @CSwartzHMA what do you think about the rewording in the second sentence? I was debating whether or not "beyond the FFY" conveyed a sense of "future" state vs. some start dates may be before the included FFYs...

**Comment by CSwartzHMA** [comment]
I agree. Maybe "Provide the planned start and end dates for this activity. Activities may extend beyond the FFY included in this APD."

**Comment by jeromeleecms** [comment]
@CSwartzHMA Sounds good one small change (adding the optional plural to FFY): "Provide the planned start and end dates for this activity. Activities may extend beyond the FFYs included in this APD."

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/9803ccbb-4bea-450a-8619-391c7864c257)

@beparticular thoughts? Otherwise, I'm good to move to Dev for implementation.

**Comment by beparticular** [comment]
I think this is clear. Thumbs up from me.

**Comment by jeromeleecms** [comment]
@pphillips-fearless This is ready for dev. Screenshot above for builder view. Help text should not display in export view.

**Comment by CSwartzHMA** [comment]
@jeromeleecms @beparticular Just calling out out here that I believe this is the first instance where we have used "FFY(s)". I will add to the Content Guide to be sure we are consistent with FFY(s) vs FFYs in the future.

**Comment by pphillips-fearless** [comment]
new dev task is #2313
