### ISSUE TITLE
Update Summary Budget Table

### ISSUE THREAD

**Issue by pphillips-fearless** [18F/cms-hitech-apd#2290]
update summary budget table as follows (before and after screenshots from design task #2247):

Before:
![before.png](https://images.zenhubusercontent.com/5e6a4b048168d5a15258c7d1/8fffd8a1-31a3-4cbf-9bdf-2b297e1caa9c)

After:
![after.png](https://images.zenhubusercontent.com/5e6a4b048168d5a15258c7d1/76ed432f-1dbd-43f9-8b42-15f003f80421)

### This task is done when...
 - [ ] Change header "totals" to have Medicaid Total Computable the right most table column
 - [ ] Remove the term "Project" from this page".
 - [ ] Replace Contracted Resources with Private Contractor.
 - [ ] Replace Non-Personnel with Other State Expenses.
 - [ ] In the instructions change Medicaid Share = Medicaid Total Computable
 - [ ] In the table change Medicaid Total = Medicaid Total Computable

**Comment by jeromeleecms** [comment]
Just to confirm - ordering for the line items in the "After" view is correct -

1) State Staff and Other State Expenses should be group together in the context of budget because those make up "State Costs"
2) Private Contractor Costs should follow other state expenses
