### ISSUE TITLE
Create List of Hardware/Software for SIA/ATO

### ISSUE THREAD

**Issue by cthulhuplus** [18F/cms-hitech-apd#2302]
Part of the SIA/ATO requires a list of hardware and software that we are using.

### This task is done when...
 - [ ] There is a list of hardware that is used by MACPro eAPD
 - [ ] There is a list of software that is used by MACPro eAPD

**Comment by nicholeweems** [comment]
Reviewed by Paul and his feedback and has been applied to final draft.

**Comment by cthulhuplus** [comment]
I couldn't attach a Word document, so here is the list:

**Hardware**
_AWS Infrastructure_
AMI
EC2 Instances
Lambdas
Load Balancers
RDS
S3 Buckets
Volumes
VPC

**Software**
CircleCI (SaaS)
CodeCov (SaaS)
Docker - Generates Artifacts & Local Dev, not used in Staging or Prod
GitHub (SaaS)
Node.js
NPM
PostgreSQL
_Client Javascript modules_

- axios
- axios-mock-adapter
- babel/cli
- babel/core
- babel/node
- babel/plugin-proposal-class-properties
- babel/plugin-syntax-dynamic-import
- babel/plugin-transform-runtime
- babel/polyfill
- babel/preset-env
- babel/preset-react
- babel-eslint
- babel-jest
- babel-loader
- babel-plugin-transform-require-context
- cmsgov/design-system-core
- cmsgov/design-system-layout
- connected-react-router
- css-loader
- cssnano
- d3-format
- d3-geo
- detect-browser
- env
- enzyme
- enzyme-adapter-react-16
- enzyme-to-json
- eslint
- eslint-config-airbnb
- eslint-config-prettier
- eslint-plugin-import
- eslint-plugin-jsx-a11y
- eslint-plugin-react
- file-loader
- fortawesome/fontawesome-svg-core
- fortawesome/free-regular-svg-icons
- fortawesome/free-solid-svg-icons
- fortawesome/react-fontawesome
- history
- html-webpack-plugin
- i18n-js
- jest
- json-loader
- jsonpatch
- js-yaml
- markdown-it
- mini-css-extract-plugin
- moment
- node-sass
- postcss
- postcss-cli
- postcss-cssnext
- postcss-custom-properties
- postcss-import
- postcss-loader
- postcss-url
- prettier
- prop-types
- react
- react-dom
- react-hot-loader
- react-redux
- react-router
- react-router-dom
- react-test-renderer
- react-waypoint
- redux 
- redux-logger
- redux-mock-store
- redux-thunk
- reselct
- reselect
- resolve-url-loader
- sass
- sass-loader
- sinon
- stage-2
- stickybits
- style-loader
- tinymce/tinymce-react
- tinymce
- topojson
- updeep
- webpack
- webpack-cli
- webpack-dev-server
- yaml-jest
- yaml-loader
- zxcvbn

_API/Backend Javascript modules_

- ajv
- aws-sdk
- axios
- body-parser
- colors
- compression
- cookies
- cors
- dotenv
- eslint
- express
- form-data
- jest
- jsonpatch
- jsonpointer
- jsonwebtoken
- knex
- moment
- multer
- node
- nodemon
- node-tap
- OpenAPI
- passport
- passport-local
- pg
- prettier
- sinon
- stream-mock
- Swagger UI
- tap
- uuid
- winston
- zxcvbn

tota11y
