### ISSUE TITLE
Start/End Dates in Export View should be in MM/DD/YYYY format.

### ISSUE THREAD

**Issue by radavis** [18F/cms-hitech-apd#2314]
APD > Export and Submit > Continue to Review

"Start date - End date:" should display dates in MM-DD-YYYY format

![Screen Shot 2020-06-22 at 2.31.27 PM.png](https://images.zenhubusercontent.com/5e62a052e57324bfda300f92/64cdb517-30c7-4866-9b5c-22fef5d86bf4)

### This task is done when...
 - [ ] displayed date format is correct

**Comment by jeromeleecms** [comment]
@mgwalker Did you create a reusable piece of code that automatically formats this?

**Comment by mgwalker** [comment]
I honestly don't remember, but the project has Moment.js in it, which is really handy for date formatting, so we could use that.

**Comment by mgwalker** [comment]
We do have a utility function for that purpose! It's in `web/src/util/index.js` called `stateDateToDisplay`, for converting dates from the format used by our redux state into the format used for display. Currently that utility will convert dates to `M/D/YYYY` format.

**Comment by jeromeleecms** [comment]
Thanks for confirming! I remember us talking about this since it was such a frequent thing to display. We'll get this into the prioritized backlog for action.
