### ISSUE TITLE
Initial Discussion of Release Strategy

### ISSUE THREAD

**Issue by nicholeweems** [18F/cms-hitech-apd#2326]
As we plan for eAPD's production release to a larger audience within 3-4 months, an initial release strategy discussion is the first step on a path to success. Some discussion topics may include timeline, milestones, scope, audience, communication plan, support, roles, and documentation.

### This task is done when ....
 - [x] release strategy next steps have been identified and assigned
 - [x] an _initial_ Mural board is created as an artifact**
 - [x] a workshop is scheduled including discussions of thoughts, dependencies, etc

**Comment by beparticular** [comment]
Work is being done on a release plan and workshop plan in the Cake Layer Mural for now (since Mural access is hard in the mornings).

**Comment by beparticular** [comment]
The initial discussion has taken place and the team workshop will be held this afternoon. Closing.
