### ISSUE TITLE
OKTA intake form and set up meetings with OKTA team

### ISSUE THREAD

**Issue by pphillips-fearless** [18F/cms-hitech-apd#2344]
Fill out the OKTA intake form to get us started with them, and set up support meeting(s) with the OKTA team

### This task is done when...
 - [x] Fill out the OKTA intake form
 - [x] set up support meeting(s) with the OKTA team

**Comment by jeromeleecms** [comment]
OKTA intake form completed; Pending response from OKTA team about scheduling a regular meeting to ensure we can keep this moving.

**Comment by jeromeleecms** [comment]
We now have a reoccurring meeting setup with the Okta team. Had our first meeting with the team on 07/15/2020.
