### ISSUE TITLE
Finalize logo design

### ISSUE THREAD

**Issue by beparticular** [18F/cms-hitech-apd#2364]
A logo has been in the works, but we need to document approval and where it may live in the app or in communications. 

### This task is done when...
 - [x] The logo works for the application, footers, and communications for the release, etc
 - [x] Variations of the logos are provided for each need/deliverable

**Comment by jjames521** [comment]
Went in another direction and simplified the design a bit for ease of use.

@jeromeleecms 

![eAPDlogoColor.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/0566863e-cd2a-4290-86b5-2e5c922ba406)

![eAPDDarkVar.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/fd539fa6-94e2-452c-9acf-d47050f86e1b)

![eAPDLightVar.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/0ce7ee20-f6c3-4e75-a91f-07642965fd33)

**Comment by NAretakis** [comment]
:pixar-oooooh-ahhhh:

for what it's worth, I like the blue and gold one.

**Comment by jeromeleecms** [comment]
Per @NAretakis - he's good with this version of the logo! We can start using this unless there are additional tweaks or thoughts.

**Comment by jeromeleecms** [comment]
Can we create an icon for our page title as part of this? Talking with Jesse, I like using the "e with the checkmark" - or do you want to create separate issue?

**Comment by jjames521** [comment]
I think the favicon we are talking about can be introduced here too, it's within logo scope and only takes a second

**Comment by jjames521** [comment]
This has a white circle around it too for accessibility in the chrome browser
![apple-touch-icon-57x57](https://user-images.githubusercontent.com/62292793/88334639-112bd200-cd00-11ea-9f98-86a497fcfcd8.png)

Favicon 16x16
![favicon-16x16](https://user-images.githubusercontent.com/62292793/88332198-2d2d7480-ccfc-11ea-8dcd-0f90b7574db2.png)

Favicon 32x32
![favicon-32x32](https://user-images.githubusercontent.com/62292793/88332233-374f7300-ccfc-11ea-9bc8-06698294b8c3.png)

favicon.ico can be provided but wont load here but this is the google doc folder for now

https://drive.google.com/drive/u/0/folders/1WlrSZlMzoEzGIunDwudO8MyoqR4Rodsl
