### ISSUE TITLE
UI to API end-to-end: state profile page 1 

### ISSUE THREAD

**Issue by brendansudol** [18F/cms-hitech-apd#239]

**Comment by mgwalker** [comment]
@brendansudol Should we break this into multiple issues, or create a checklist in this issue?  I lean towards checklist so it's all nicely contained in one place.  It seems like the different pieces should be similar enough that they don't really need their own issues.

**Comment by brendansudol** [comment]
✅list sounds 💯

**Comment by brendansudol** [comment]
actually going to break this into individual issues (since they each might have specific things to comment on)

**Comment by brendansudol** [comment]
state profile page 1 is done end-to-end
