### ISSUE TITLE
Confirm Dev Access to Hosting Environment

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#240]
After selection and approval of Hosting Environment, verify that Devs have correct access and permissions to the hosting environment.

### This task is done when...
 - [x] Hosting Environment is selected
 - [x] Dev's confirm access and permissions
 
 ** don't forget to fill out the LABEL, MILESTONE, and PROJECT sections before submitting (then delete this line) **

**Comment by NAretakis** [comment]
Adding job codes for @mgwalker, then we can test access.

**Comment by NAretakis** [comment]
Hello access for everyone! Closing this out.
