### ISSUE TITLE
Walkthrough of Prototype with Internal Team

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#247]
Mentioned this at stand-up on 02/23. Lots of new screens being added to the prototype - would be good to have an internal walk through before we present to leadership (#181) on 02/28 and HITECH team (#229).

### This task is done when...
 - [x] Walkthrough Scheduled
 - [x] Walkthrough Completed
 
When scheduling, should include Design team.

**Comment by nkkl** [comment]
I put some time on everyone's calendar!

**Comment by jeromeleecms** [comment]
Walkthrough completed. Will look to have a cadence of 2 weeks to look at "what's new" with the team.
