### ISSUE TITLE
Usability testing round 2

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#268]
### This task is done when...
 - [x] Draft email recruiting template
 - [x] Send email to distribution list of potential participants
 - [x] Create usability test protocol
 - [x] Schedule sessions
 - [x] Conduct testing (3/8/18)
 - [x] Synthesis

**Comment by lauraponce** [comment]
@NAretakis @jeromeleecms we would like to schedule two usability testing sessions for this Thursday and were wondering if you could help send the recruiting email to the distribution list that volunteered for testing?

We drafted up an email template here: https://docs.google.com/document/d/1QlHnm_-TtXbr0HsDhLZIEub-8_CbRe8AjMxWRme48RE/edit#heading=h.rgzpry8s4ek1

(cc @quarterback)

**Comment by NAretakis** [comment]
Yes, can send, but I am thinking that @nkkl setup a distribution list as a way to recruit from all states interested. Can we just use your distro list Nikki?

**Comment by nkkl** [comment]
Yeah, I reckon all we need to do is change the greeting and ship it to CMS-testers@gsa.gov

**Comment by NAretakis** [comment]
alright, @lauraponce the template looks good (I made a minor edit). You good to ship it out to the mailbox @nkkl referenced?

**Comment by lauraponce** [comment]
I think it will look most official coming from you @NAretakis or @jeromeleecms since they are familiar with you. Would you mind sending it out to the distro?

**Comment by NAretakis** [comment]
Sure, I can send. Confirming with @nkkl on how exactly to do that. As an aside, this means we need to jam on the protocol ASAP for testing on 3/8, yes?

**Comment by NAretakis** [comment]
email sent. @Nkkl to confirm that it actually went, as I don't think I'm on the list.

**Comment by nkkl** [comment]
I got it!

**Comment by NAretakis** [comment]
me too!

**Comment by lauraponce** [comment]
Going to start updating the test protocol for the second round of testing: https://docs.google.com/document/d/1dVjRjLzEkPwFlDH0CS6Y4QmMybpziZBf9IdSfBQUflo/edit#heading=h.rxsnujmu2ig5

@NAretakis - Nikki mentioned you might be interested in joining @quarterback and I while we update the test plan, is there a time today that works for you for us to spend a few minutes talking through the research questions we want to answer in this round?

**Comment by lauraponce** [comment]
The protocol is updated: https://docs.google.com/document/d/1dVjRjLzEkPwFlDH0CS6Y4QmMybpziZBf9IdSfBQUflo/edit?usp=sharing and the sessions are scheduled:
- 1:00-1:45 pm with Flordia
- 2:00-2:45 pm with Texas
- 3:00-3:45 pm with New York

**Comment by lauraponce** [comment]
Here is the high-level synthesis of the feedback from the three sessions yesterday: https://docs.google.com/document/d/1ouVoorKh3WxRa3VgdFP0NNNNgIssAJY_a_V2MaHXvKA/edit#

The stuff in bold are the recommendations or questions based on the quote from the user. Feel free to add to this if anyone has thoughts!
