### ISSUE TITLE
Estimate travel expenses for State HIT Connect

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#269]
We want to go to the HIT Connect Summit in Baltimore! In order to do that, everyone has to put in their travel expense estimates. The current plan is as follows:

 - Everyone arrive prior to 1:00pm on April 4
 - Spend April 4 on heads down co-working and conference prep
 - April 5–6 attend select conference sessions, meet with states privately, do co-design and usability sessions
 - After day sessions, fly home (either evening of the 6th or the 7th during the day)
 - If people leave on the 7th we can go to the aquarium 😀

### This task is done when...
 - [x] Nikki has put in her travel estimates
 - [x] Brendan has put in his travel estimates
 - [x] Greg has put in his travel estimates
 - [x] Laura has put in her travel estimates
 - [x] Ron has put in his travel estimates
 - [x] Jessie has put in her travel estimates

**Comment by nkkl** [comment]
Note: y'all are free to make preliminary reservations in Concur/FedRooms and all that, but it won't get approved by the Travel Team until we have authorization from CMS.

**Comment by mgwalker** [comment]
We should also register for the conference, right?  http://www.healthcareitconnect.com/2018-state-healthcare-it-connect-summit/

**Comment by jposi** [comment]
yes please. I'm almost done with shipping over the approval.

**Comment by jposi** [comment]
I'd flagged registration a week or so ago  - please sign up for the waitlist now @mgwalker et al

**Comment by nkkl** [comment]
We probably want to flag this upwards, as well. I doubt random @gsa.gov email addresses are going to have sufficient context on their own.

**Comment by jposi** [comment]
For sure, I just want everyone to at least be on the waitlist.

**Comment by lauraponce** [comment]
Registered for the conference, booked my hotel, and booked my flights! I'm staying at the Hyatt Regency which is about .4 miles from the conference (the Hilton didn't have the gov rate). My flight gets in at 12:30 on Wednesday, and I fly out at 4:00 on Friday.

**Comment by nkkl** [comment]
Same!

**Comment by mgwalker** [comment]
Booked hotel and flight.  But I got the Hilton (at the government rate!) because the Hyatt Regency was sold out.  😆

**Comment by jposi** [comment]
y'all - I think we're all done. Dom and Alla have approved the event request, and I've passed it along to Ethan H. LMK if your tickets aren't approved!

**Comment by jposi** [comment]
Not moving this to done until I know your tickets are approved.

**Comment by lauraponce** [comment]
My trip was just approved in Concur!

**Comment by nkkl** [comment]
Mine was as well.

**Comment by NAretakis** [comment]
Closing this to clean up the board.
