### ISSUE TITLE
[OBSOLETE] Put API interactions in place

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#29]

**Comment by brendansudol** [comment]
What do we mean by this? I wonder if this should actually come later once we have a better sense for what endpoints we want and the structure of the data for each of those.

I guess I'm unsure how to work on this card effectively.

cc: @mgwalker @nkkl

**Comment by mgwalker** [comment]
Yeah, I think you're right.  The intent was to figure out how the frontend will talk to the backend (maybe a thin API layer using something like [frisbee](https://www.npmjs.com/package/frisbee)?), but we don't have anything to actually talk to yet.

Maybe after we revisit the content type (like we started to talk about in #63), that will constitute enough of an API that we can actually do something with this.  In the meantime, I think you're right that there's nothing to do here.
