### ISSUE TITLE
Choose technical deep dive activities for kickoff

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#3]
Goals
- [ ] Identify *open questions* regarding infrastructure and tooling
- [ ] Identify CMS-internal escalation paths for infrastructure and tooling
- [ ] Learn about data
- [ ] Understand architectural implications of the proposed process
- [ ] Figure out how to start technical work without painting design into a corner

[CMS APD project kickoff](https://docs.google.com/a/gsa.gov/document/d/1yL59-FqIS3s6Xen2jqrRNEfByCZzFAY_Ato265InHPE/edit?usp=sharing) doc 🔒

**Comment by brendansudol** [comment]
High-level tech topics / questions

* Infrastructure

- hosting needs
- any restrictions on languages and runtimes
- freedom around choosing libraries
- deployment (manual, automated)

* Do we have data that needs to be migrated / transferred to or from new app? Will we be integrating with other / existing systems?

* What languages / frameworks / tools do you like / have experience in?

* What do you see as the meatier technical components / features of this app?

* High-level talk around frontend, backend, database needs / preferences

* Code review process

* Testing philosophy

* (For partners) How involved do you want to be on the code side of things?
