### ISSUE TITLE
Update project description on the wiki

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#303]
Let's make it easier to understand the project by looking at the wiki. At minimum we should probably cover the following things:

- Our vision/goals
- Background on the project (it's fine to link out to other sources) and the scope of what we are and *are not* doing
- Who we're trying to help
- What success looks like to us, written in human-readable terms (ex. instead of saying "achieve Net Promoter Score of 3.5 or better" we might say "create a product that people are excited to share with their friends")
- Guidelines for what kind of content will and will not be on the wiki (ex. no PII or information about specific states)

### This task is done when...
 - [x] The [home page of the wiki has been updated](https://github.com/18F/cms-hitech-apd/wiki/Home/_edit)

**Comment by nkkl** [comment]
@NAretakis @jeromeleecms can one of you two take this one? (self-assign and close when complete please)

**Comment by NAretakis** [comment]
Home page updated. :tada:
