### ISSUE TITLE
Decide how to document lessons learned and major decision points on the wiki

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#305]
We should define a way to capture the major decision points that we hit, including what alternatives we considered and why we went the direction we went.

### This task is done when...
 - [x] We've decided where to document lessons and decisions
 - [x] Past lessons and decisions have been documented per ^

**Comment by nkkl** [comment]
@jeromeleecms @NAretakis this might be a good thing for one of you and one of @lauraponce or @quarterback to collaborate on. I know that the design team was thinking about this early on, so they may have some thoughts already.

**Comment by quarterback** [comment]
Added this to my queue.

**Comment by quarterback** [comment]
I'm documenting these changes on the stakeholder insights page of the wiki: https://github.com/18F/cms-hitech-apd/wiki/Stakeholder-insights/

**Comment by quarterback** [comment]
Updated with design decision and iteration information from four previous rounds, but it's enough to close this five-month old issue.
