### ISSUE TITLE
Document the technology stack we're using in a general audience friendly way

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#306]
In addition to making technologist-friendly documentation in our repository, we should also add a short wiki page that explains to a nontechnical audience what kinds of tech tools we're using. The target audience of this is program folks in government who aren't sure what's possible at their agency. Realistically, we should pull topics from [our existing docs](https://github.com/18F/cms-hitech-apd/blob/master/docs/index.md), make them more entry level, and link out to the full documentation as appropriate.

Key topics to hit:
- What cloud infrastructure we're using
- How we do continuous integration, and what that even means
- The relationship between our front end, back end, and API
- How we make sure our site is secure

### This task is done when...
 - [x] The [Tech 101 wiki page](https://github.com/18F/cms-hitech-apd/wiki/Tech-101) is updated

**Comment by nkkl** [comment]
@jeromeleecms @NAretakis does one of you want to grab this one? I reckon @brendansudol and @mgwalker can translate anything that's confusing, but their existing docs are pretty thorough. I think the work here is more around abstracting the concepts and answering questions like "If it's in the cloud, how do we know it's secure?" and "How do the pieces of the app connect to each other?"

**Comment by NAretakis** [comment]
Page is created. Content exists. Working on refining the page and links

**Comment by NAretakis** [comment]
@mgwalker do you mind taking a quick peek at the [tech 101 page](https://github.com/18F/cms-hitech-apd/wiki/Tech-101) to make sure it makes sense? A few placeholders in there still, but I think it is half way decent. Happy to rework/include more if you think it needs it.

**Comment by NAretakis** [comment]
page is updated.
