### ISSUE TITLE
Planning for Part 2 of HiC

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#310]
Develop needs assessment for HiC with cost estimates for a proposal to leadership to continue project beyond initial term of the current IAA. 

### This task is done when...
 - [x] Needs assessment is complete
 - [x] Cost Estimate is complete
- [x] Proposal Written
- [x] Proposal Submitted to Leadership
 
@NAretakis @jposi @nkkl Not sure what this will look like, but don't want to be waiting till the last minute to get this together.

**Comment by NAretakis** [comment]
@jposi should we (do we?) have a google doc for this? Realistic to possibly get a rough outline strategy document, with placeholders, this week?

**Comment by jposi** [comment]
Doc here:
https://docs.google.com/document/d/1YLTfO2pTvnWNBu9bctIEMNmeKqgExCSuH3SD5Xnkkpk/edit

**Comment by jeromeleecms** [comment]
Adding reference to #480 and #481

**Comment by jeromeleecms** [comment]
Adding reference to potential timeline: https://app.mural.co/t/gsa6/m/gsa6/1524169233914/c7b32f5b51433bc9124a4d9020be85ea87b3bfad

**Comment by NAretakis** [comment]
Sent to Marty, Carrie, and Eugene. Thank all!
