### ISSUE TITLE
Complete XLC Slide Deck (Slides 54-89)

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#312]
Building out the [XLC Slide Deck ](https://docs.google.com/presentation/d/1UNs2rB9-ywxPiqwYDeZJbw1ko1erxDkGBsEe-eYa7O0/edit#slide=id.p95)is a necessary step on our path to ATO. We can focus on slides 54-89, but I'll work on filling out some of the introductory slides as well.

### This task is done when...
 - [ ] Slides 54-89 are completed
 - [x] Introductory slides are completed.

**Comment by nkkl** [comment]
I documented our testing practices (slides 79–81, 83). I'm also going to sit down with Britta this afternoon and look through some of the compliance stuff earlier in the deck. I suspect we'll need a lot of support from our ISSO on this stuff.

**Comment by NAretakis** [comment]
Rough draft of 54-89 slides are in. Continuing work on this.

**Comment by NAretakis** [comment]
Presented at TRB. Closing issue and spawning new issues that originated from the megadeck concerning artifacts needed for TRB.
