### ISSUE TITLE
Build initial authorization model

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#32]

**Comment by brendansudol** [comment]
this is done

**Comment by mgwalker** [comment]
We have authentication but not _authorization_.  😆   Right now the only authorization we have is "are you logged in?"  That's enough to get started, but I want to keep this issue open for a bit because we're going to need to think about how to do real authorization pretty soon.

**Comment by brendansudol** [comment]
is this done now, @mgwalker? 😜
