### ISSUE TITLE
Decide how to let people know what's required in the Activity schedule section

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#320]
Users were confused about what was required and what was optional for this section because they won't know the actual dates until later. Should they leave it blank? Should it be grayed out? Should there be instructions letting them know what to do?
### This task is done when...
 - [ ] Decision has been made about what how to let people know what's required here and what's not
 - [ ] Design has been sketched 
and/or
 - [ ] Content has been written

**Comment by quarterback** [comment]
This issue was solved with the redesign of the form. Obsolete.
