### ISSUE TITLE
Take a second pass at the expenses section

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#322]
Should the Select expenses and the Expense list pages be combined? 
### This task is done when...
 - [ ] One or more designs have been wireframed for the flow and/or screens
 - [ ] Users have a way to add other expenses that are not on the list
 - [ ] Users are informed they will have a chance to enter more expenses later

**Comment by NAretakis** [comment]
Pretty sure this is an old issue that is not longer relevant, because expenses are working at the activity level correctly. Closing.
