### ISSUE TITLE
Refine the summary section

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#323]
Do we need a summary for each activity in addition to the full summary?
### This task is done when...
 - [x] Decide at what level the summaries will be (activity level, full summary, all of the above, etc)
 - [ ] Refine the table layout (Nick has added images of some options here: https://docs.google.com/document/d/1PjbmxnxnCxE7RrQwm0pIWy_xAs7pX2olD03zgp8JAN4/edit?ts=5aa95067#heading=h.wxeywj1czam)
 - [x] Summary sections are linked up to take users back to those respective sections to make edits

**Comment by quarterback** [comment]
The v2 covers this issue.  https://docs.google.com/document/d/1C0KvJ5zMuTOIRSTqyHpSZU7T3aLbqm7U4EdJwIynpJw/edit#heading=h.sx5269izjfbx
