### ISSUE TITLE
Setup authorization on APD routes

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#325]
Currently, the various APD endpoints on the API just require a user to be logged in.  A logged in user can edit any APD that is associated with the same state as them.  We need to add the activities described in the [roles and activities](https://github.com/18F/cms-hitech-apd/blob/master/docs/users-and-roles.md) doc and modify the endpoints to enforce those.

### This task is done when...
- the following routes have been updated
  - [ ] GET `/apds`
  - [x] PUT `/apds/:id`
  - [x] POST `/apds/:id/activities`
  - [x] PUT `/activities/:id`
  - [x] PUT `/activities/:id/goals`
- [ ] endpoint tests for all of ☝️ those are updated to test both unauthenticated ***and*** unauthorized
- [x] OpenAPI documentation for all of ☝️ those reflect that both 401 and 403 responses are possible
  - we kind of accidentally get this one for free

**Comment by mgwalker** [comment]
@NAretakis We don't have an activity that seems to correspond to being able to review an APD: https://github.com/18F/cms-hitech-apd/blob/master/docs/users-and-roles.md - should we add one?

All the others look like they're covered by `edit-document`

**Comment by NAretakis** [comment]
Yes, I think we need "view-document" which is something Federal Leadership needs as well.
