### ISSUE TITLE
start client side validation

### ISSUE THREAD

**Issue by brendansudol** [18F/cms-hitech-apd#330]

**Comment by jeromeleecms** [comment]
@brendansudol Could we add more detail to this issue so we know the scope of this (it's pretty broad now)? 

Would it be helpful for design/product to walk through the app and document what fields need to be validated?

**Comment by jeromeleecms** [comment]
@brendansudol Is this the general heuristics you were looking for?

General Heuristics for Client Side Validation

- Email Addresses: Must be valid email address
- Phone Number: Must be valid 11 digits (though how do we handle extension)
- Zip Code: Valid 5 or 9 digit Zip
-  Program Overview: At least one FFY must be selected
- Dollar Values: cannot be < 0
- Dates: Start Dates cannot be greater than end dates

**Comment by brendansudol** [comment]
done via https://github.com/18F/cms-hitech-apd/pull/832

woo!
