### ISSUE TITLE
Wireframe concepts from design studio

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#346]
### This task is done when...
 - [ ] Sketches from design studio have been mocked up as wireframes

**Comment by lauraponce** [comment]
<img width="651" alt="screen shot 2018-03-22 at 12 46 49 pm" src="https://user-images.githubusercontent.com/21222704/37785182-de00666a-2dcf-11e8-8f57-43e7555e857c.png">

**Comment by lauraponce** [comment]
There could also be a way to collapse the right sidebar in order to make more room for the main content area in the center.

**Comment by jeromeleecms** [comment]
Would it be too much to ask if you could mock-up what an APD with multiple activities would look like? It looks nice and clean in this view, but would it start to get too jumbled if a state has 9-10 proposed activities (not a theoretical situation)? In another APD, I had one that contained 20+ activities (though maybe an outlier).

Still on the fence about the right side bar... but I appreciate the visual!

**Comment by lauraponce** [comment]
Closing this issue because we have the new issue to capture this work: https://github.com/18F/cms-hitech-apd/issues/349
