### ISSUE TITLE
Design v1 of the submission experience

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#349]
Sketch/wireframe a v1 of the submission experience
### This task is done when...
 - [ ] V1 of submission experience is sketched
 - [ ] V1 has been shared with the team (3/29)

**Comment by jeromeleecms** [comment]
In the wireframes, could you also include some placeholders for how someone would navigate the rest of the functionality of the app ? 

- For example, if the user had a dashboard or screens that show the status of their submission, how would they access that? 
- An example for #350, how would the analyst experience tie back to their dashboard or the work tracker? 

It doesn't have to tie to specific screens/functionality, but the navigation will take some screen real estate so it would be good to see where it would fit in/plan for it.

**Comment by lauraponce** [comment]
Definitely, @jeromeleecms — will do! It will actually work out nicely because @quarterback is sketching things for the state dashboard (#359) so hopefully we can see it all start to flow together in our crit tomorrow.

**Comment by lauraponce** [comment]
1. More sections in view, with help
![state experience v1 with help](https://user-images.githubusercontent.com/21222704/38094359-8a9b86c8-333b-11e8-8a7e-11b47b49209f.png)

2. More sections in view, collapsed help
![state experience v1 no help](https://user-images.githubusercontent.com/21222704/38094366-8dde96c2-333b-11e8-8146-4e43ee3f6a85.png)

3. Step by step with help
![step by step with help](https://user-images.githubusercontent.com/21222704/38094378-91a8a5b8-333b-11e8-809c-16131443a2eb.png)

4. Step by step, collapsed help
![step by step no help](https://user-images.githubusercontent.com/21222704/38094383-94187346-333b-11e8-8cae-8bb24a7e8a6e.png)

5. Step by step, in-line help
![step by step in-line help](https://user-images.githubusercontent.com/21222704/38094384-96bf63fc-333b-11e8-82d3-df5c824814bd.png)

**Comment by quarterback** [comment]
@lauraponce This looks good to me. My only critique is minor, changing the headings of the form fields to bold perhaps?

**Comment by NAretakis** [comment]
uhhhh, **_totally awesome_** seems to be the understatement of the year.... I've also run this by the CMS APD team and have positive and good feedback I'll share.

**Comment by jeromeleecms** [comment]
Is it easy to to convert the sketch to a clickable version (or is that already underway)? You know me, I like to press buttons.

**Comment by NAretakis** [comment]
_The designs look extremely user friendly—great job! 

My only question thus far is related to Activities (and if this was covered and I missed it, disregard). Because the HIT and HIE narrative are both included in the same program summary section, I am wondering if states will be prompted to enter activities separated by HIT and HIE, or if the system could ask the user to select HIT or HIE for each activity, and then potentially auto organize the activities by HIT/HIE. Is this part of the current functionality?_

Carenza Love - CMS

**Comment by lauraponce** [comment]
V2 

![state experience v2](https://user-images.githubusercontent.com/21222704/38122437-f8ee851e-33a2-11e8-8990-2dab42211a49.png)

**Comment by lauraponce** [comment]
Changes in V2:
- Addition of Save to PDF button in left nav
- Removed help nav item from top nav
- Added Activity List subsection
- All of Program Activities (would work similarly for all of the main nav items) subsections would show up in this list (long scroll) with breadcrumbs once you reach a new subsection, for example once you scroll down to Activity 1, you'll see the breadcrumbs. This could also snap to the top of the page when you scroll so you always know which subsection you're in.
- Added in-line help text (this text would say something about what this is, what it relates to in the current template and why it's necessary)
- Added placeholder text in input area
- Added a second activity to the page to show how it would look for scrolling through multiple
- Added "Save and continue" text above Next buttons
- Added Review and Submit section in nav
- Renamed "Short Activity Summary" to "Short Summary of Activity"
