### ISSUE TITLE
Add token mechanism

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#35]
Some kind of bearer token, probably.  Maybe JWT?

**Comment by mgwalker** [comment]
This might be fully covered by #47.  Up for discussion.

#47 uses client sessions, where an authenticated user is serialized and then stored in an encrypted cookie.  In this case, the user is serialized as simply their ID.  When the user requests an API resource, the API receives back the encrypted cookie.  If the API can decrypt the cookie, then we assume it has not been tampered with.  Then we deserialize it, reconstructing the user ID back into a full user object.

**Comment by brendansudol** [comment]
Yep, this is all set -- nice work, @mgwalker
