### ISSUE TITLE
Design v1 of the analyst dashboard

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#350]
Sketch/wireframe v1 of the analyst experience
### This task is done when...
 - [ ] Analyst experience is sketched or wireframed
 - [ ] v1 of the analyst experience is shared with the team (3/30_

**Comment by lauraponce** [comment]
V1
![analyst experience v1](https://user-images.githubusercontent.com/21222704/38151834-e563ddec-3432-11e8-85b0-c00cd2ca2934.png)

**Comment by lauraponce** [comment]
V2 
![analyst experience v1](https://user-images.githubusercontent.com/21222704/38179933-7346a486-35f6-11e8-9f06-d064c2d8d306.png)

**Comment by lauraponce** [comment]
Changes in V2:

- Added notifications to left nav
- Added way to view by state/region in left nav
- Removed messages from top nav
- Reworked the work queue
- Added reporting section
- Added filtering to Recent Activities section
- Reworked states at a glance
- Removed messages section

**Comment by jeromeleecms** [comment]
- Ditto! I like the revisions. 

- For a more complete list of statuses, here's the list of statuses that the submission could sit with (left hand side of the diagram): https://drive.google.com/drive/u/0/folders/1kXTK2y9ea9IoP64qEHlIOfmmTJX2bAwJ This was from our proposed workflow document that was based on the original prototype, but I think it still holds true now. The current tracker identifies where the document is physically (i.e. Baltimore, Denver, Chicago), but I propose considering changing that from location -> step in the process. 

- For reporting: do you envision those metrics be specific to the reviewer? I think the capability to have both reviewer specific and a rolled up one is good for people to have insight into their own work.

- For user management: How would the user access their "profile" to update their states (i.e the self assigning functionality we discussed)?

**Comment by lauraponce** [comment]
@jeromeleecms that Google Drive link ^ goes to the main folder for me, which doc has the diagram with the full list of statuses?

**Comment by lauraponce** [comment]
@jeromeleecms to your second point about the reporting, I agree. Maybe we can start with a single reporting view for the MVP and then add functionality from there to allow for showing the metrics specific to the reviewer?

For the user management of self-assigning states, would that make sense from the left nav? As in, they could go to "all states" or a specific state from the drop-down and then assign it to themselves. Thoughts?

**Comment by jeromeleecms** [comment]
@lauraponce Apologies for the generic link!

1. The file name with potential statuses is called "Proposed workflow 1 - APD review.jpg." 
2. Sounds good for the MVP. The SQL query for "by reviewer" shouldn't be too much of a stretch to add down the road. :)
3. How about having a generic icon of a user that when you click on it gives them a dropdown with links to updating profile, name, etc? Feel like that's a pretty standard user interface/experience that I've seen across multiples apps.
