### ISSUE TITLE
Design v1 of the state dashboard

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#359]
Sketch the components of the state dashboard — this can build off the existing prototype that @jeromeleecms built out. 

Some considerations for things to include:
- What do people see when they have APDs in progress
- Notifications
- Ongoing conversations/messages
- What needs their attention (prioritization of tasks)

### This task is done when...
 - [x] Dashboard has been sketched
 - [x] Design has been shared with the team for feedback (3/29)

**Comment by quarterback** [comment]
@lauraponce I'm working on higher fidelity version but I wanted to upload what I had so far. 
![image_67169025](https://user-images.githubusercontent.com/4461062/38106980-a5f95e0e-335e-11e8-85f9-f090ee9f97ed.JPG)

**Comment by quarterback** [comment]
![very_basic_state](https://user-images.githubusercontent.com/4461062/38110022-2529e10e-3368-11e8-85a8-8a66e9729bc5.png)
