### ISSUE TITLE
Review past research into the state experience

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#36]
- [x] talk to Alex Pandel
- [x] review report outs from prior 18F-CMS projects
- [x] review Nick Brethauer's notes from usability tests with state APD preparers

**Comment by nicoleslaw** [comment]
@mkhandekar I set up time for us with Alex but she is booked until after the holidays. Let me know if you want to join, @nkkl!

**Comment by nkkl** [comment]
Happy to join if I'm free. Add me as optional? Alex and I sometimes remind one another of things that we'd forgotten.

**Comment by nkkl** [comment]
Here's some stuff that may be helpful:

- [Synthesis of our first usability session, with MMIS analysts](https://docs.google.com/document/d/1BBJD5R4tmspLOzJ7WZ3USPHqOlo2oFMlJ3Y-tF6RP24/edit#heading=h.vi3tx3id8lhc) (we tested with [this](https://docs.google.com/document/d/1uLRx4IVB_Pn50HDTRkDT-wz1NABkOtCzD_zx6YTVU_g/edit))
- [Synthesis of our second usability session, with state users](https://docs.google.com/spreadsheets/d/12jSwwXhTooHHkjfUj4kUpXHmSzsB71qv-hFLxDYrcos/edit#gid=0)
- [Raw notes from our second usability session, with state users](https://docs.google.com/document/d/1htNZ1ptjabRJoHIGgEoJLTam_8Am9rQ27NGev8enggw/edit#heading=h.pmdhzi7lwaoo) (we tested with [this](https://gsa.invisionapp.com/share/8HCKSKMNK#/screens/243623477))
- [Raw notes from our third usability session, with state users](https://docs.google.com/document/d/1G8bbZwsRA5mQqN3KQAG5_ZJHDPacc9eYwotGkNGsfPA/edit) (we tested with [this](https://gsa.invisionapp.com/share/8HCKSKMNK#/screens/244544431))

**Comment by nicoleslaw** [comment]
This is wonderful @nkkl! Thank you for compiling these links.

**Comment by nicoleslaw** [comment]
Just making a note: I read through the notes and am not sure if I should leave this issue open until after we've met with Alex. Either way, I will leave it open until @mkhandekar has time to read through these docs!

**Comment by mkhandekar** [comment]
Thanks! I am making my way through them.

**Comment by nicoleslaw** [comment]
Added Laura to the invite for our chat with Alex.

**Comment by nicoleslaw** [comment]
Closing this—but I've included the above references in the README for Laura's reference.
