### ISSUE TITLE
Educate the team about different activity types

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#366]
We still don't deeply understand HIT vs HIE vs MMIS vs IE, and it seems really relevant!

### This task is done when...
 - [x] a team session has been scheduled
 - [x] content is prepared
 - [x] the team has been walked through everything

**Comment by NAretakis** [comment]
closing this out because we covered these at a high level. We're now doing individual HIE or MMIS sessions if needed.
