### ISSUE TITLE
v1 of state dashboard (Sketch-level fidelity)

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#383]
Potential features to include:

- APDs in progress
- Notifications
- Ongoing conversations
- Dates

### This task is done when...
 - [ ] v1 has been sketched
 - [ ] v1 has been shared with the team
 
Builds off of #359

**Comment by lauraponce** [comment]
V1
![state dashboard v1](https://user-images.githubusercontent.com/21222704/38225916-142be6d0-36c5-11e8-8d59-146e83f9ca9a.png)

**Comment by lauraponce** [comment]
@NAretakis @jeromeleecms @nkkl @quarterback let me know if you have any feedback and I can update this for tomorrow!

**Comment by jeromeleecms** [comment]
Few quick thoughts -- will think about this more tonight/tomorrow and we can also noodle some of this out in person!

1. In the current statuses card, how would the state see that the item was received back from CMS (i.e. returned with comments)?
2. Also in the current statuses card, is this mean to show only pending submissions or any/all submissions? Maybe this card should be only active submissions and recent approvals can show up in the "Recent Activities" messaging. Hmm.. or alternatively, the Current Statuses card could have the filterable views that show pending, completed, and all?
3. How were you thinking "Current Drafts" would work? Did we land on only having one authorized account for state for the MVP with the potential to add more users down the road (pending administrative support availability)?
4. Upcoming Dates: For the line item with unused funding, I think it's better served as an alert vs. a date. Some feedback we got from the APD team was to make sure that we were able to identify unused funding early (as opposed to when the funding was expiring).

**Comment by lauraponce** [comment]
For the current drafts, I pictured it working as a way to see if they are on track for submitting on time and when they click it, it would take them to where they left off. For the authorized user question, each user would have their own account, but they would be seeing the same APD for their state when they log in. Is that what your assumption was as well @jeromeleecms?

**Comment by lauraponce** [comment]
Here is a v2

![state dashboard v2](https://user-images.githubusercontent.com/21222704/38330339-52f16534-381e-11e8-86e7-ef50a2f18423.png)

**Comment by jeromeleecms** [comment]
Thanks, @lauraponce! For the drafts due date, we'd have to develop metrics for the state to see what was "on-time" for drafts - I don't think this would scope to our MVP. Though from the feedback today, it may be something the state's may find valuable, but I don't think we can include this since each state may have it's own interpretation of what this metric is/represents.

For the user permissions standpoint + hearing feedback from the state today, it sounds like we need to revisit (1) multiple users for the state and (2) role based permissions by state.

Do you want to take some time to talk through this?

**Comment by lauraponce** [comment]
@jeromeleecms we can definitely talk through the permissions stuff in more depth, good idea. @brendansudol and @mgwalker would be good to include in that discussion as well. I'm going to close this issue for the dashboard v1 and we'll talk about permissions on that new thread.
