### ISSUE TITLE
v1 of the review experience

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#398]
What do the analysts see when they are in the process of reviewing?

### This task is done when...
 - [ ] Wireframe concept of v1 for the review experience
 - [ ] Design has been shared with the team for feedback

**Comment by lauraponce** [comment]
v1
![review 1](https://user-images.githubusercontent.com/21222704/38380457-cbfdc90a-38d1-11e8-8322-e374fd7e6e16.png)
![review 2](https://user-images.githubusercontent.com/21222704/38380458-cc11ef0c-38d1-11e8-9c9a-3e0e3ca1999b.png)
![review 3](https://user-images.githubusercontent.com/21222704/38380459-cc1f3630-38d1-11e8-871a-f1b7387c9645.png)
![review 4](https://user-images.githubusercontent.com/21222704/38380460-cc2cfbc6-38d1-11e8-94f1-29b78819aa22.png)

cc @NAretakis @jeromeleecms

**Comment by lauraponce** [comment]
Closing this issue out since it was just the v1, I'll make a new issue for any new iterations

**Comment by jeromeleecms** [comment]
@lauraponce I had this thought this morning -- from the State interviews at the conference, would it make sense to have a "N/A" checkbox in the bar / in the content section so we know that the state considered the section? It may also make the final "completeness check" easier for the dev team. I don't think it would apply to all the sections, but HIE summary, personnel resources, and/or cost allocation or other funding sources would be good candidates.

For example: State personnel -- if there is no staff working specific to the activity, then a N/A button could gray out that area and the final check would know that there is nothing to ask the state to input.

**Comment by NAretakis** [comment]
Perhaps just a sort of automatic checkbox for each section noting that they went through it. This would not only show that each section is completed, but that they didn't skip/omit content.
