### ISSUE TITLE
Choose design deep dive activities for kickoff

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#4]
Goals
- [ ] Understand the major implications of the current and proposed processes
- [ ] Start to identify the major users and stakeholders
- [ ] Identify key research questions
- [ ] Figure out what our path forward is for design work

[CMS APD project kickoff](https://docs.google.com/a/gsa.gov/document/d/1yL59-FqIS3s6Xen2jqrRNEfByCZzFAY_Ato265InHPE/edit?usp=sharing) doc 🔒

**Comment by nicoleslaw** [comment]
Drafting ideas for exercises here — feel free to comment! https://docs.google.com/document/d/1yL59-FqIS3s6Xen2jqrRNEfByCZzFAY_Ato265InHPE/edit#heading=h.n1i6pz9q331

**Comment by nicoleslaw** [comment]
Closing this since we're mostly done planning everything.
