### ISSUE TITLE
Establish consistent microcopy across application

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#402]
Language around microcopy needs to be consistent. What are section headers, calls-to-action & buttons going to be called? 

### This task is done when...
- [x]  Develop first draft of microcopy for sections throughout the application.
- [x] Get feedback from @jeromeleecms & @NAretakis identifying high-level parameters for naming (based on any particular requirements.)

**Comment by NAretakis** [comment]
Added content to IA doc for what CMS wants, as well as Do's and Don'ts. I think we're covered.
