### ISSUE TITLE
Finalize IA content for titles of sections and subsections

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#406]
Let's use this doc: https://docs.google.com/document/d/1fGhLysBin97BZG0ykM8pTD7ug5mEDaAFt3svm8dC-zI/edit?usp=sharing that has just the names of the sections and subsections and finalize the titles so it can be implemented.
### This task is done when...
 - [x] Sections and subsections have been finalized

**Comment by quarterback** [comment]
Updated to match IA post-changes.
