### ISSUE TITLE
Read prior material about the APD process

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#41]
Read all the things in Drive from prior projects.

**Comment by nicoleslaw** [comment]
@nkkl Should we mainly be looking in [this folder](https://drive.google.com/drive/folders/0Bzc-6_yruTAkSS1JTGIyeW9DVkU)?

**Comment by nkkl** [comment]
Broadly, yes, but I can give you more helpful stuff:

- [Final discovery findings](https://drive.google.com/drive/u/0/folders/0B-mH7S3Kbx_xOEtyZnJsb0lsbDA) from team II
- [Recommendations](https://drive.google.com/drive/u/0/folders/0BzZVmD5fX0bwSzFzZWZmTEgyNUk) from team II
- [Raw research materials](https://drive.google.com/drive/u/0/folders/0Bzc-6_yruTAkbFlZTC1aTVZSd00) from team II
- [Early hypotheses](https://docs.google.com/document/d/1gus4pwceGZZ_rt--_wth-VrBwN5add7a1nuLAb6jq88/edit) about where the project should go from team II
- [Observations and recommendations](https://docs.google.com/presentation/d/13_Q0bEhx8p5kgQVDeFb6wqgFjSb9ZB2-dSeSETShYs8/edit#slide=id.g15dffc6d9b_0_396) from team I

I don't see much else from the very first team that is super useful to dive into right now. At that point it's pretty far away from what we're doing and is more interesting history about how we got here (especially since it's heavily focused on MMIS, which is a totally different animal that HITECH).

**Comment by nicoleslaw** [comment]
I have officially read all of the [aforementioned] things. 🎉

**Comment by mkhandekar** [comment]
Yes I am! 🔨
