### ISSUE TITLE
Synthesize and share findings from round 4 usability testing

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#417]
Synthesize the findings from the research, share with the team, and prioritize issues
### This task is done when...
 - [x] Research has been synthesized
 - [x] Findings have been shared with the team
 - [x] Issues have been prioritized and/or added to the backlog

**Comment by lauraponce** [comment]
The research will be tracked in #416

**Comment by lauraponce** [comment]
Raw research notes: https://docs.google.com/document/d/1W7hptuiF6HjwKWCODXGsHYAlay1gu_aHr-GOGRIpbNY/edit?usp=sharing

Synthesis doc: https://docs.google.com/document/d/1cLi9A9Xa0nc8-g_dLgY9bxOfSmOWCeJ-0FKZ9pF3JMw/edit?usp=sharing

**Comment by jeromeleecms** [comment]
@lauraponce Thanks for sharing this. Super disappointed that I couldn't make it, but the comments/notes are great -- though now I wonder if I'm being too casual.

**Comment by lauraponce** [comment]
@jeromeleecms The way it came off in the conversation that isn't fully captured in the notes is that you were teaching him how things the right way through gradual steering in the right direction rather than laying down the law and making it hard on him :)

**Comment by quarterback** [comment]
Updated the synthesis doc (https://docs.google.com/document/d/1cLi9A9Xa0nc8-g_dLgY9bxOfSmOWCeJ-0FKZ9pF3JMw/edit#). Still need to add issues from it.
