### ISSUE TITLE
Revise framing doc

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#42]
- [x] Update vision statement per comments
- [x] Turn 6 month mission into sentences?
- [x] De-dupe/integrate goals
- [x] prioritize goals
- [x] Add measures to each goal

**Comment by nkkl** [comment]
@NicolasAretakisCMS @jeromeleecms I'm passing this to you to fill in some more measures, and then we can circle up, use that to identify our KPIs, and add them to the roadmap. Not super time sensitive.

**Comment by nkkl** [comment]
Nikki to set up time for this!

**Comment by NAretakis** [comment]
This task is ready to be closed, I added measures for each of the phase 1 goals. As well as revised the 6-month mission into three sentences.

Before I closed out, checking with @nkkl if we should create a new task to have Design/Development review to make sure this makes sense?

**Comment by nkkl** [comment]
A 30 minute review with design/dev is not a bad idea.

**Comment by nkkl** [comment]
@jeromeleecms @NAretakis looks good to me! I left a few comments for y'all.

Let's take the following action items on this:
 - [ ] We should walk through the design findings and make sure important findings are incorporated. I'll set up a half hour with the designers, and we can use that time to flag things to update (and then update them offline).
 - [ ] The three of us should meet and identify KPIs – this can probably be done in half an hour.
 - [ ] We should do a review of the updated doc with the team. Probably about an hour.
