### ISSUE TITLE
Write a specification for product MVP to inform gap analysis

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#427]
We want to do a gap analysis of what stands between us and a shippable submission experience. The first step of that is to write down what the baseline requirements are for our MVP.

### This task is done when...
 - [x] An MVP has been identified
 - [x] The MVP behavior has been documented so that we can do a gap analysis

**Comment by jeromeleecms** [comment]
Workflow diagrams completed. Can be viewed on [Drive](https://drive.google.com/open?id=10KU2Fm11WBqvIPucEgW3haQxAHrGYSmt). Planning spike 04/24 to walk through diagrams for gap analysis and spec out MVP.

**Comment by NAretakis** [comment]
I feel like this is done, but I want to wait until #480 and #481 are closed before we close this out. Waiting for those two issues allows us to confirm MVP with design and dev.

**Comment by jeromeleecms** [comment]
@NAretakis We still need to document the specs for the MVP in the framing document. We can either use this issue or create a new one. I'm good either way.

@nkkl Do you have a good example of an MVP spec document that we can reference/model after?

**Comment by nkkl** [comment]
Let's add a section to the framing document – we can do a subheading for each chunk of functionality, and then detail out what we know about it so far.

**Comment by nkkl** [comment]
For a lot of them, I suspect that pulling the Visio diagrams will be 80% of the work.

**Comment by NAretakis** [comment]
We did this!
