### ISSUE TITLE
Figure out how to document design decisions

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#44]
We should make sure that all decisions we make are clearly documented, understandable, and easy for new people to follow.

**Comment by nicoleslaw** [comment]
I set up a [wiki](https://github.com/18F/cms-hitech-apd/wiki), but we should talk about documentation and process after we tackle our P1s!

**Comment by nicoleslaw** [comment]
@mkhandekar and I talked through how we want to use the wiki, and our initial plan for experience design documentation today. 

Wiki: documenting design decisions, key quotes, findings, hypotheses, testing plans.

Deliverables: using USWDS as a base for prototyping, planning to do lower fidelity comps and move into code quickly for usability testing, adding notes from sessions in Mural or GitHub depending on complexity.

cc @brendansudol
