### ISSUE TITLE
[Program Overview] Add help text for narrative sections

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#463]
Write help text narrative that help users better understand what CMS wants from them in each section.

### This task is done when...
 - [x] Ron writes content for each section
 - [x] Team provides feedback
- [x] Text is implemented into the application for testing.
 
 ** don't forget to fill out the LABEL, MILESTONE, and PROJECT sections before submitting (then delete this line) **

**Comment by quarterback** [comment]
@NAretakis We should get some time on the calendar, after I draft something I'll want to talk about it.
