### ISSUE TITLE
(Redundant) [Results of Previous Activities] Design fronted for this section

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#468]
Results of previous activities needs to have a flow that follows [this section of the application flow](app.mural.co/t/gsa6/m/gsa6/1524714012930/d34a6666c3cb4db8dfee9cfadc5e4c13e7a88f72?wid=0-1524752073311).

### This task is done when...
 - [ ] For new APDs a rich text box is displayed.
 - [ ] For new APDs an editable program budget table (sourced from the wireframes from executive summary) is available for states to input dollar amounts into.

**Comment by quarterback** [comment]
Same as #534
