### ISSUE TITLE
[Assurances and Compliance] Design frontend of assurances & compliance checklist

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#470]
Assuances and Compliance section of the APD needs to have a list of regulations/citations that must be checked by the state users during APD creation and updates.

### This task is done when...
 - [ ] Wireframes for Assurances and Compliance are created.
 - [ ] Design hands task off to Development.

**Comment by quarterback** [comment]
I added the text to this section, but it's not clear from the text prototype what should go in this section. Is it just a text box? Or a yes/no, with a text box only necessary if they check "No" and need to explain? It should be easy to model, it's just not clear to me what goes here and the example APDs didn't glean anything because they were structured differently than our application.

**Comment by NAretakis** [comment]
It is as simple as [ ] check boxes with text underneath so they can justify any no responses.

**Comment by NAretakis** [comment]
Specifically, this: 
![image](https://user-images.githubusercontent.com/34281281/40664186-96629710-6317-11e8-9c7c-9e4a8e92cfeb.png)

**Comment by quarterback** [comment]
Dev issues #609

**Comment by mgwalker** [comment]
@quarterback Is there a final design decision on these?

@NAretakis @jeromeleecms Should the CFR and SMM citations link somewhere?  It looks like in Jerome's prototype, they do - would be nice to at least link to something like ecfr, and maybe in some future iteration we could have the regulatory text pop up when you hover or something.  Just thinking it might be useful to be able to see exactly what these apply to, though if I was to guess, folks probably just tick all the boxes without spending a lot of time thinking about it.

**Comment by jeromeleecms** [comment]
@mgwalker That was my intention in the prototype to link to the relevant sources. eCFR maybe easier, but the only copy of the SMM that i can find is here: https://www.cms.gov/Regulations-and-Guidance/guidance/Manuals/Paper-Based-Manuals-Items/CMS021927.html (in zip files). 

For the MVP, I'm OK with no links and having that tracked as a future enhancement.

**Comment by quarterback** [comment]
@mgwalker Yes, the radio boxes the way Jerome has implemented it (with the text box only showing up when the person selects no) is the best way to go for the MVP.

**Comment by quarterback** [comment]
@brendansudol This one. We need check boxes for the assurances section that are yes/no that correspond with the various sections. I just added the text to the yaml file, I thought it had to be done on the front end.
