### ISSUE TITLE
Multi Regional Office in Denver (July 16-18)

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#476]
Identify if 18F should attend the Multiregional Meeting in Denver (July 16-18). If yes, also identify who and how much will it cost for them to attend.

### This task is done when...
 - [x] Determine if 18F should attend the multiregional meeting
 - [x] Identify who should attend
- [x] Calculate how much it will cost to attend

**Comment by nkkl** [comment]
When is the regional meeting?

**Comment by jeromeleecms** [comment]
Updated the body of the original comment to include the dates (July 16-18).

**Comment by nkkl** [comment]
I did out the [cost estimate](https://docs.google.com/spreadsheets/d/1XqdTlJScOn1jGlWTjf6sOZIsmlh5NEF6GGSufAJn6_k/edit#gid=1000729692) and it should be about $9000 to send the whole team to Colorado (because we're west coast heavy at that point).

**Comment by nkkl** [comment]
@NAretakis if we are thinking we want to do this, let's decide what we want to get out of it!

**Comment by nkkl** [comment]
Also if we can get some more info on what will be happening and where, that'd be great.

**Comment by nkkl** [comment]
Travel is booked!
