### ISSUE TITLE
Multiregional Meeting in Boston (June 19-21)

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#477]
Identify if 18F should attend the Multiregional Meeting in Boston (June 19-21). If yes, also identify who and how much will it cost for them to attend.

### This task is done when...
 - [x] Determine if 18F should attend the multiregional meeting
 - [x] Identify who should attend
- [x] Calculate how much it will cost to attend

**Comment by nkkl** [comment]
@jeromeleecms when is the meeting?

**Comment by jeromeleecms** [comment]
Updated the body of the original comment to include the dates (June 19-21). Would it be helpful if you saw the agendas for both meetings?

**Comment by nkkl** [comment]
Maybe. I did a [cost estimate](https://docs.google.com/spreadsheets/d/1Rf48FpXh7ePcg_pg9IzKjSw_vPvz3dQs-rQ4s7OjY6U/edit#gid=1000729692) and it looks like bringing the whole team will cost us close to $15k. I don't think it's worth it to send everyone.

**Comment by nkkl** [comment]
Resolution is that we're not going to send anyone.
