### ISSUE TITLE
Complete work estimates based on Visio gap analysis [Design]

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#480]
### This task is done when...
 - [x] Content hour estimates have been added to the worksheet in drive
 - [x] Visual hour estimates have been added to the worksheet in drive
 - [x] Research hour estimates have been added to the worksheet in drive

**Comment by NAretakis** [comment]
[Here is the link to the worksheet in drive.](https://docs.google.com/spreadsheets/d/1YEORpJxOWEz5fIfxUmn4PQCKWy_-ktlg5PrucGIJCSM/edit?usp=sharing)

[Here is a link to the workflow diagrams that show the high level, as well as breakdown each sub-process.
](https://docs.google.com/spreadsheets/d/1YEORpJxOWEz5fIfxUmn4PQCKWy_-ktlg5PrucGIJCSM/edit?usp=sharing)

**Comment by lauraponce** [comment]
What does "CMS Decision with Letter Issuance" involve on the design side? @jeromeleecms @NAretakis

**Comment by jeromeleecms** [comment]
That part of the workflow is still not clear to me yet. Once the APD is ready to go for clearance, it would be ideal to have the entire process cleared through the system as mocked up in the original prototype (so more design work) or in the least invasive scenario, the system would export an executive summary so the analyst would circulate that + the decision letter for review (less design work) through email.

Added #485 so @NAretakis and I can talk through this more and provide more specifics.

**Comment by jeromeleecms** [comment]
@lauraponce Spoke with @NAretakis this morning. For the MVP, we are thinking that the system will route the submission (APD/contract) up through/including the secondary review. After that point, the CMS analysts would route the appropriate documents through email for the rest of the clearance process (like we do now). Doing the rest of the clearance process/auto-generating executive summaries in the application may be worth considering for future enhancements.

Does that help your time estimates?

**Comment by NAretakis** [comment]
content estimates have been added.
