### ISSUE TITLE
Review CMS clearance workflow and how it aligns with application

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#485]
As a member of the project team, I want to understand how the clearance workflow would work within the application, so I can design/develop a supporting system within the application.

### This task is done when...
 - [ ] First pass of the clearance workflow has been created
 - [ ] Workflow has been shared with team

**Comment by jeromeleecms** [comment]
Sure. We still need to document the workflow in and out of the app so people see how the app fits into the overall process. We already did some work on #570, so that view + this piece will fit into the larger picture - do we need to spin up an issue on the "big picture" flow?

**Comment by NAretakis** [comment]
Right, this stuff: 
![image](https://user-images.githubusercontent.com/34281281/40683552-2ccecbb8-634c-11e8-8256-d15690908129.png)

**Comment by NAretakis** [comment]
OBSOLETE
