### ISSUE TITLE
Add design iterations to the wiki

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#504]
Tell the story of the progression of the APD experience through design iterations.
### This task is done when...
 - [x] Early concepts have been added to the wiki

**Comment by NAretakis** [comment]
@lauraponce this is kind of old, but I still think it is valuable. Don't let this jump the work queue, but I just wanted to drop it on radar (OutOfSyncSprintPlanning) :wink:

**Comment by jeromeleecms** [comment]
@nkkl can we tie this into our Ship mail writing parties?

**Comment by nkkl** [comment]
Sure! As long as it doesn't become a pain in the neck for people. :)

**Comment by jeromeleecms** [comment]
@lauraponce @quarterback Can you take a look at the current state of the app and take some screenshots of the items you think will change as we work on design? Do we want to make this part of the regular cadence for Friday's before the beginning of the next sprint?

**Comment by quarterback** [comment]
I think we can close this issue now. I have at least four different iterations up, and as we continue to do it, I'll add others.
