### ISSUE TITLE
Update framing doc to include MVP specs

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#507]
Use the milestones we've created to identify the MVP specs in the framing document.

### This task is done when...
 - [x] Specs are identified for each MVP milestone
 - [x] @nkkl has reviewed

**Comment by NAretakis** [comment]
First stab at this completed. [There's definitely room for improvement in the framing doc.](https://docs.google.com/document/d/16Yw8jnl0wW6wFA_KvfyCSEjhsT8HPKGs6V1iaBHkLeE/edit?usp=sharing) @jeromeleecms take a peek, and then we can tag Nikki for her input.

**Comment by NAretakis** [comment]
@nkkl can you take a look at the MVP specs in the last section of the framing doc? Edit as necessary please, thanks ;)

**Comment by nkkl** [comment]
Looks great!
