### ISSUE TITLE
Get documentation from compliance about what needs to be logged

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#509]
We have some logging scattered throughout the API right now, but before we spend a lot of time and effort adding more thorough logging, it would be very useful to have documentation from CMS about what ***needs*** to be logged.

It would also be helpful if we could get an indication of suitable log "levels" for the things that need logging.  For example, does a failed login attempt warrant a "warning" level?

**Comment by NAretakis** [comment]
It looks like most of our logging is going to come from our security control requirements. And we can track that via #1271 

The details we do have are below:

Much of the overarching log information and log level related info can be pulled from the security control requirements (NIST 800-53 Rev 4).  More specifically, the team should look closely at the Audit and Accountability Control (AU).  It includes, for example, AU-3 Content of Audit Records which focuses on  “The information system generates audit records containing information that establishes what type of event occurred, when the event occurred, where the event occurred, the source of the event, the outcome of the event, and the identity of any individuals or subjects associated with the event.”  
 
For CMS specific requirements, we’ve been using the MACPro SSP.  You’ll see numerous references to logging and should be able to pull more specific requirements from this document.  For example, AWS generates many of the audit files using Auditd and Acquilent (see AU-03 in MACPro SSP.) Aquilent manages the central logging system, so they are able to handle review, analysis, and reporting of audit events, including monitoring for unusual activity. Our understanding is that Aquilent is setup to meet CMS logging requirements, so we plan to inherit them for SPoTT.
