### ISSUE TITLE
Add dollar sign & percentage sign in budget tables

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#515]
In the application, when you insert dollar amounts and dates in the calendar, the formats are displayed differently depending on what field you're using. This is confusing.

### This task is done when...
 - [x] dates & dollar fields are standardized.

**Comment by quarterback** [comment]
I notice the dates are now fixed, so I removed that from the title.

**Comment by brendansudol** [comment]
this is done!
