### ISSUE TITLE
How to copy and paste material from external sources into the textbox

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#521]
During user testing, users tried to copy and paste text from external sources into the text boxes, but formatting was incorrect. Looking to dev to see how we can copy and paste from:

1) Word
2) Excel
3) PDF

Into the textboxes and preserve formatting.

### This task is done when...
 - [ ] Dev has determined if the current tool can handle copy and paste from external sources
 - [ ] Dev has tested/enabled functionality

**Comment by mgwalker** [comment]
FWIW, when I copy from a some source (Macdown, Google Docs/Chrome, Pages) into our rich text boxes, I get formatting.  It's inconsistent, which isn't surprising, but it does handle some formatting automatically it seems.  I don't have Word on my computer so I can't test that.

The rich text box we're using doesn't support tables at all, so I don't think copy/paste from Excel will ever work unless we switch to another rich text box.

**Comment by jeromeleecms** [comment]
I tested Word when I put in a sample APD into the app this past Friday. Bullets don't work very well with copy and pasting and numbering is not preserved if there are underlying bullets or text that breaks up the bullets. 

As @mgwalker noted, formatting can be pretty rough when coming from an external source.

**Comment by jeromeleecms** [comment]
Per Standup (07/11), @brendansudol will explore other react rich text editors and report back.

**Comment by brendansudol** [comment]
https://react-rte.org/demo

![image](https://user-images.githubusercontent.com/1060893/42763983-7c3a5378-88e2-11e8-9cac-d54a48e77e3c.png)

**Comment by brendansudol** [comment]
done via https://github.com/18F/cms-hitech-apd/pull/806
