### ISSUE TITLE
Crosswalk AI material with Framing Document

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#524]
@NAretakis and Jerome to review and crosswalk the AI APD reimagine material and framing document

### This task is done when...
 - [x] Nick and Jerome have crosswalked the AI Reimagine material with the HiC Framing Document
 - [x] Nick and Jerome have delivered a report to Julie

**Comment by NAretakis** [comment]
Ok, finished swimlane-ish version of a mural, with some first stab sticky notes. @jeromeleecms [you can access the mural here](app.mural.co/t/gsa6/m/gsa6/1528226066202/f85892ea6093c3deb82595820973d005547b17e1?wid=0-1528386238032), and then add in or adjust the stickies that correspond.

**Comment by NAretakis** [comment]
report sent, yay!
