### ISSUE TITLE
Create a sticky header for the activities

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#529]
When users are scrolling through the activities section, they lose the reference point of the specific activity they are entering information for. The name of the activity should stick to the top of the page and stay there when they are seeing the corresponding subsections.

In the screenshot below, the "Program Activities > Activity 1: SLR Administration (HIT)" would be sticky.

### This task is done when...
 - [ ] A sticky header option has been explored
 - [ ] The sticky header has been implemented
 
![screen shot 2018-05-11 at 11 27 19 am](https://user-images.githubusercontent.com/21222704/39932444-2ca8b820-550e-11e8-93b5-eb5411f5b59b.png)

**Comment by brendansudol** [comment]
done!
