### ISSUE TITLE
Build incentive payments table

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#532]
Build out the table that was designed and approved in #503

**Comment by NAretakis** [comment]
Latest version for reference: 
![image](https://user-images.githubusercontent.com/34281281/40800135-be80fd34-64cc-11e8-9611-7eafcf0c775b.png)

**Comment by NAretakis** [comment]
Also, this table is blank, and states simply fill in the cells. This is not driven from any content.
