### ISSUE TITLE
Wireframe Results of Previous Activities section

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#534]
Results of Previous Activities includes **Prior Activities Outline**, **Approved Expenses**, and **Actual Expenses** – each of these subsections needs a wireframe.
### This task is done when...
 - [x] V1 wireframes have been designed
 - [x] Wireframes have been shared with the team for feedback
 - [x] Wireframes have been approved

**Comment by lauraponce** [comment]
@NAretakis Do you have some time today or tomorrow to talk about this section? 

cc @jeromeleecms

**Comment by lauraponce** [comment]
If they have already submitted an APD, this is what they would see: ![screen shot 2018-05-24 at 5 35 29 pm](https://user-images.githubusercontent.com/21222704/40515035-40a065c4-5f79-11e8-88b6-6eed1861b73a.png)

**Comment by lauraponce** [comment]
For the first time users enter info, they won't have an APD to pull from so we can show rich text editor and have them input the information: 
![screen shot 2018-05-24 at 5 35 22 pm](https://user-images.githubusercontent.com/21222704/40515097-7ec7af56-5f79-11e8-8725-7408066b6c93.png)

**Comment by lauraponce** [comment]
@NAretakis for the other two section of the Previous Activities, we talked about putting in the Approved Program Budget Table and the Actual Program Budget Table –– would those end up being the HITECH and MMIS tables from the executive summary? (Sorry I am having a hard time rememebering what I meant in my notes from our earlier conversation about this!)

**Comment by NAretakis** [comment]
Yes, the HITECH and MMIS tables from the executive summary are the same tables that go into the Approved Expenses, and Actual Expenses sections. 
![image](https://user-images.githubusercontent.com/34281281/40515291-779899d0-5f69-11e8-943e-7f2b01dd4c83.png)

**Comment by NAretakis** [comment]
And the table/narrative section you wireframed is what goes into the "Prior Activities Outline" section.

**Comment by NAretakis** [comment]
If you want to get clever, we could collapse approved and actual into a single section/table. This would be the HITECH and MMIS tables from the executive summary, which a spaces to put in Approved $$ and Actual $$.

**Comment by NAretakis** [comment]
These are good to go!

**Comment by NAretakis** [comment]
@lauraponce done?

**Comment by lauraponce** [comment]
I moved it over to declutter the board, but it's just pending the HITECH and MMIS tables. I'm wrapping up the executive summary issue (which uses the same tables as the ones that go with this) so this will be done when #606 is good to go. Does that seem right?

**Comment by NAretakis** [comment]
Perfect, thanks!

**Comment by lauraponce** [comment]
@NAretakis here is a version with approved and actual in a combined table. The actual numbers are in the lighter font to show they are just suggestions based on the approved and and they would be able to click on it to edit. Once they edit it, it will turn to the regular font weight. 

<img width="799" alt="screen shot 2018-06-07 at 12 56 09 pm" src="https://user-images.githubusercontent.com/21222704/41123045-42ff5d96-6a52-11e8-9e90-ec9613cb155c.png">

**Comment by NAretakis** [comment]
Perfect, so this will fit into the results of previous activities section, underneath the narrative box. 
For a new APD being created, this will be blank, and once a user inputs the data it does not need to go anywhere else (it is just stored here for record keeping purposes).

Let's ship it!

**Comment by NAretakis** [comment]
@lauraponce I think this same/similar styling can be used for within the executive summary too, per #639 .

But for exec summary, we don't need all the actual stuff, is just basically the "approved" fields (you can look at issue #639 for reference).

**Comment by lauraponce** [comment]
:high-five:! I just created #652 to capture the development work for this, so that's in the backlog for when it's ready to be prioritized.
