### ISSUE TITLE
Design the Core Activity Section as Activity #1

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#546]
We need to remove the Key Personnel section from the Overview, and adjust our approach to activities fit user testing feedback. As such, the first activity needs to exist as a core activity that applies to all state APDs.

By making activity 1 into _Core Activity_ (official name TBD), we are essentially moving the key personnel section under activity 1. Additionally, we need to make sure there is sufficient help text and any design elements that establish the Core Activity as something different from each subsequent activity that a state might add to the submission. 

For example, a Core Activity should include:

1. Key program administration information
2. Key needs and objectives
3. Key activity schedule
4. Key personnel
5. Key contract resources
6. Key expenses
7. Key cost allocation
8. Key standards and conditions

Additional activity (2, 3, 4, n) examples might be:

1. Provider Onboarding - HIE
2. Environmental Scan - HIT
3. Data analysis - HIT/MMIS
4. HIE Public Health Interface Development - HIE
5. etc.

### This task is done when...
 - [x] Remove Key Personnel section from the Overview
 - [x] Core Activity is designed as the number 1 activity within the activity list
 - [x] Help text is created to define Core Activity as well as subsequent Activities.

**Comment by quarterback** [comment]
In progress.

**Comment by quarterback** [comment]
I'll need to sync with dev about this next week. Right now, I'm not sure exactly where this section fits into the existing application, whether it needs another section entirely. Design wise, it'd take exactly the same form as existing sections, so that's not an issue. It's mostly about structural questions that I don't have answers to.

**Comment by quarterback** [comment]
Replaced Activity One with core activities text.
