### ISSUE TITLE
Complete Walkthrough of v1 of APD Creation Submission Experience

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#577]
Perform a complete walkthrough of v1 of the APD creation/submission experience. [Mural workflows](https://app.mural.co/t/gsa6/m/gsa6/1524714012930/d34a6666c3cb4db8dfee9cfadc5e4c13e7a88f72) will be used as a reference.

### This task is done when...
 - [x] Meeting scheduled to walkthrough the entire creation/submission experience.

 - [x] **Program Overview Section Complete  `[P1.1]`**
- Design = Done
- Dev = #647 (closed) [Includes: #462 (closed), #632(closed), #630 (closed), #631 (closed)], #624/#648 (closed)
- [x] **Program Activities Section Complete `[P1.2]`**
- Design = **#320 (obsolete), #546 (closed)**, #596 (closed), #499 (obsolete); 
- Dev = #583 (closed), #607 (closed) `[P1.2]`
- [x] **Program Activities: HIE Specific Items Section Complete `[P1.2]`** 
- Design = **#497 (closed);** 
- Dev = #659 (closed)
- [x] **Proposed Budget Section Complete `[P1.3]`** 
- Design = Done; 
- Dev = #584 (closed via #584), #532 (closed), #651 (closed), #645 (closed)**, #629 (closed), #685 (closed) 
- [x] **Executive Summary Section Complete `[P1.4]`**
- Design = **#606 (closed), #639 (closed),** 
- Dev = **#626 (closed), #672 (closed)** #612 (closed)
- [x] **State Profile Complete `[P1,5]`**
- Design = #460 (closed); 
- Dev = #613 (closed), #679 (closed)
- [x] **Assurances and Compliance Section Complete `[P1,6]`**
- Design = #470 (closed)
- Dev = #609 (Greg); #709 (Greg)
 - [x] **APD can be certified/submit `[P1,7]`**
- Design = #471 (closed), #611 (closed), #657 (closed) 
- Dev = #655 (Bren), #686 (Greg)
- [x] **Summary Activity Schedule `[P1,8]`**
- Design = #646 (closed)
- Dev = #683 (closed), #684 (closed), #688 (closed)
- [x] **Results from Previous Activities Section Complete  `[P2]`; this will be moved to Milestone 6**
- Design = #534 (closed)
- Dev =#652 (Greg); #627 (closed), #691 (merged)

- [ ] Mural workflows updated
 
cc: @nkkl @NAretakis

**Comment by nkkl** [comment]
Sounds good to me.

**Comment by NAretakis** [comment]
@jeromeleecms How do you feel about me doing a bit of pre-work for this, so that we can prioritize our time during the actual meeting to focus on unclear sections?

The idea would be to have everyone go into the Mural, and use the Design Questions stamp or Dev Questions stamp and drag them onto the various sections where there are questions. Then, we can focus our walkthrough on those sections, and not spend time on the stuff that everyone has a handle on. Let me know and I can spin up the homework assignment :wink:

**Comment by jeromeleecms** [comment]
@NAretakis The intent of this issue was more of a final summary review to sign off that v1 was done vs. doing a working session. We should work through the mural together + the GitHub board so we have a good handle on progress (similar to our discussion yesterday). 

Once that is done, I think our next sprint planning will be more targeted and align with our milestones (it's just this APD Creation/Submission experience is really broad and is the most nebulous). That next round of planning would probably be a good place to do as you are suggesting using Mural.

**Comment by NAretakis** [comment]
Sounds good to me!

Nick Aretakis
•: 303.844.7117| •: Nicolas.Aretakis@cms.hhs.gov<mailto:Nicolas.Aretakis@cms.hhs.gov>

**Comment by NAretakis** [comment]
drops mic. @thewholeteam
