### ISSUE TITLE
Update frontend to read and write APD key personnel data from API

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#579]

**Comment by NAretakis** [comment]
I think the personnel section is working, I can save and open. @mgwalker good to close this?

**Comment by mgwalker** [comment]
The intent of this was that we'd capture "key personnel" separately from standard personnel.  But I think we decided that the "program administration" personnel would be key.  If that's the case, then we can probably close this one as obsolete.

**Comment by NAretakis** [comment]
Closing issue.
