### ISSUE TITLE
Shift key personnel to the first activity listed (Program Administration)

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#583]
From our testing we found that this section was a bit of a struggle for users, so the plan is actually to shift the Key Personnel section into the first activity listed under the activity list. 

The first activity listed is a special activity called "Program Administration". Here is the help text for context: _"Please Note: The first activity in this list is Program Administration. Program Administration is where you should include information that pertains to implementing the EHR Incentive program. Examples of information that belongs within this activity includes: State and Contractor costs associated with operating the EHR incentive program and SLR Enhancements/Upgrades."_

This means that we are can remove the key personnel stuff from the Overview section. And then the first activity in the activity list (Program Administration) is effectively the place for key personnel/key contracting resources.
### This task is done when...
 - [x] Key personnel is removed from the overview section
 - [x] The first activity in the activity list is not delete-able 
 - [x] The first activity in the activity list is named "Program Administration"

**Comment by mgwalker** [comment]
Finished by #585
