### ISSUE TITLE
Implement Program Overview section refinements

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#587]
Per design issue #545 
This is the issue for development to implement the design changes to the program overview section. 

### This task is done when...
 - [ ] Overview section now contains HIT Narrative, HIE Narrative, and MMIS narrative sections within it.
 - [ ] Stand-alone HIT Narrative, HIE Narrative, and MMIS narrative sections are removed.
 
linked image below:
![image](https://user-images.githubusercontent.com/34281281/40387271-77656fca-5dc9-11e8-8213-fc739e734577.png)

**Comment by NAretakis** [comment]
@mgwalker @brendansudol for visibility. Let me know if you'd rather us assign the issue when we create them from Design work. Or if self-assigning is preferred.

**Comment by mgwalker** [comment]
Either way is fine for me.  The advantage of you assigning it is I'll see it sooner - I don't get notifications based on the label (but that should be a feature...  someone should tell Github) so I'll only see them when I check the board again.  I do check the board pretty regularly though, so it's probably also fine to just wait for one of us to pick it up.

@brendansudol interested in your thoughts.

**Comment by brendansudol** [comment]
i check board a lot too, so self assignment may be advantageous when unsure, no direct assignment is also fine by me
