### ISSUE TITLE
[Obsolete] [Executive Summary] Design front-end (wireframes) for executive summary and program budget tables

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#595]
Describe the task here, including any supplemental information.

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
 ** don't forget to fill out the LABEL, MILESTONE, and PROJECT sections before submitting (then delete this line) **

**Comment by quarterback** [comment]
Same as #606
