### ISSUE TITLE
[Cost Allocation] Design front-end (wireframe) for cost allocation section.

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#596]
This is based on the structure for the executive summary table (short activity summary table).

### This task is done when...
 - [ ] Cost allocation table is created
 - [ ] Design has done design work on it.

**Comment by NAretakis** [comment]
Roughed in image for Cost Allocation section:
![image](https://user-images.githubusercontent.com/34281281/40515492-462f214c-5f6a-11e8-8dd3-15495c8c92b4.png)

**Comment by NAretakis** [comment]
@lauraponce if you want to run this through your design magic before Brendan goes to town.
@brendansudol for visibility.

**Comment by jeromeleecms** [comment]
Done - per standup.
