### ISSUE TITLE
Set and enforce size limits on API rich text fields

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#600]
The rich text fields on the APD can include images, which might be quite large.  Currently those images are converted into text and stored directly in the rich text, and stuffed into the database.  The problem is that it results in requests that are too large for the API's default configuration.

We should figure out some estimates about how big we expect images to be and how many per field so we can make sure the API will accept large enough requests.  The total estimate should be something like:

```
maximum image size * number of images per rich text field * number of rich text fields
```

Once we've got that, we can make sure the API will accept requests up to that size.

Longer term, there may be some options to upload the images separately and instead of inserting the image into the rich text, we can insert a link to the image - that will make the text much smaller and help with request sizes.  There are some complexities with that (i.e., we may end up with lots of orphaned images if people add some to their text fields and then remove them - we won't have a way to know that).

Arises from #591

**Comment by mgwalker** [comment]
It's related and not related.  I think we probably need to carve out some time to do some research on what our options are and then present those back to you.  File attachments are easier because the file is not embedded into a text field - it's a standalone thing.  These images are converted into text and added to the rich text boxes.  It's problematic because if they add a bunch of images, each image is below the limit, but because they're represented as one big blob of text, they are cumulatively too big.

@nkkl Do you have thoughts about how we could handle a "research" issue?

**Comment by NAretakis** [comment]
OBSOLETE
