### ISSUE TITLE
[obsolete] helptext/content key personnel checkbox to state staff entries

### ISSUE THREAD

**Issue by brendansudol** [18F/cms-hitech-apd#603]
"Results from key personnel convo with @jeromeleeCMS: We're good to proceed with the approach discussed (removing key personnel from where it is & creating the first activity name "Program Administration). Secondly, to address the issue of capturing state staff who are actually key personnel under Program Administration, versus the rest of the folks. We'd like to go with a checkbox in the State Personnel section that indicates if a person is "Key Personnel" or not. We'll have to figure out how this works with the data model, as we'd like to be able to differentiate between the "state staff" and "state staff flagged as key personnel".

**Comment by brendansudol** [comment]
do we still want this special checkbox in the state personnel activity section for the "Program Admin" to denote "Key Personnel"?

I'm kinda confused because we're now calling this section "Key personnel" for all activities so this additional checkbox seems strange now.

cc: @jeromeleecms @NAretakis

**Comment by brendansudol** [comment]
moving this to backlog until we firm up the direction for this

**Comment by jeromeleecms** [comment]
@brendansudol I thought I saw an issue that stated that "Key" language should only exist in the first activity since it has a special designation, but looking through the issues I can't find it. 

@NAretakis Is this something that you recall giving guidance on? It would be nice to be able to pull out the Key Personnel, but for the MVP, maybe we can limit it to having the help text indicate that "Key Personnel" should be identified by name and title and leave it at that?

**Comment by NAretakis** [comment]
Right, "Key" language is special to the first activity only. And honestly, we can just do that in help text for MVP. It would be nice if the data model tracked the first activity differently (as "key" items), but not necessary for MVP.

So, I guess I am saying we can probably handle all this with helptext, unless it its a small lift to just track Activity 1 slightly differently (as "key" items).

**Comment by NAretakis** [comment]
This has evolved a bit. Our current MVP approach is to handle this via Helptext that is specific for Activity 1

**Comment by quarterback** [comment]
The key text is already outlined in the application, is there anything that's missing or that I need to add besides what we already have in the first section (key activity 1)?
