### ISSUE TITLE
Design executive summary section

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#606]
### This task is done when...
  - [x] V1 wireframes have been designed
  - [x] Wireframes have been shared with the team for feedback
  - [ ] Wireframes have been approved

**Comment by NAretakis** [comment]
Should be a close copy of #534 for reference.

**Comment by NAretakis** [comment]
the wireframes for this are in #626 unless @lauraponce wants to make any adjustments.

**Comment by lauraponce** [comment]
The wireframe refinements for this are in #639

**Comment by lauraponce** [comment]
Closed via #639
