### ISSUE TITLE
Code HIE activities section

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#607]
When an analyst checks the HIE section, a different section appears with content specific to HIE activities. Related to #497 

### This task is done when...
 - [ ] wireframe is coded into the application
 - [ ] design signs off on interaction

**Comment by quarterback** [comment]
via @NAretakis: (via #497) 
so, Jerome and I talked this through and I think we have a good, low LOE, approach for getting this coded. Basically, what we'd like to do is use the "HIE Checkbox" 
![image](https://user-images.githubusercontent.com/34281281/40516906-0d204740-5f70-11e8-974d-5b7a80e3d2ec.png)

to drive a special rich text box that appears within the Activity Description section of the corresponding activity.

How this would work is that when a user checks the "HIE" box, a special chunk of helptext appears for "Detailed Activity Description" section. And this special helptext addresses [these HIE questions (link to MU, Value Proposition, & Sustainability)](https://app.mural.co/t/gsa6/m/gsa6/1524714012930/d34a6666c3cb4db8dfee9cfadc5e4c13e7a88f72?wid=0-1524756276698)

![image](https://user-images.githubusercontent.com/34281281/40516978-5b83111a-5f70-11e8-9ca2-45453e54cfa6.png)

The special helptext only needs to appear when the "HIE" checkbox is used, otherwise, the default description is just fine. Does this make sense?

**Comment by NAretakis** [comment]
This looks done per #669 . We might need to format the helptext a bit, but it now only shows up if the activity is an HIE (checkbox) activity. @quarterback please reopen if you think we need to revisit this.
