### ISSUE TITLE
Implement Assurances and Compliance section

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#609]
This is the assurances and compliance section of the application. 

### This task is done when...
 - [x] A working version of the design in #470 is implemented.

**Comment by mgwalker** [comment]
There's a lot of content in #470.  What represents the final design?

**Comment by jeromeleecms** [comment]
@quarterback Did you update the YAML file for this?

**Comment by quarterback** [comment]
@jeromeleecms Yes, last week before I left. It's already implemented.

**Comment by mgwalker** [comment]
The dev implementation was not finished.
