### ISSUE TITLE
Implement executive summary section

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#612]
Dev implementation of executive summary section.

### This task is done when...
 - [ ] Develop a submission experience
 - [ ] Design reviews upon implementation

**Comment by mgwalker** [comment]
This one is pending #606, right?  Or is that design done?

**Comment by brendansudol** [comment]
can you advise here @quarterback?

**Comment by NAretakis** [comment]
Sorry, we have some overlap. This is a duplicate of #626
