### ISSUE TITLE
v1 of state profile development

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#613]
State profile section is developed

### This task is done when...
 - [ ] Develop a state profile interaction
 - [ ] Design reviews upon implementation

**Comment by mgwalker** [comment]
The old state contacts page was last edited in 862d02a9.  We should be able to pull that as a reference point if we need it.

**Comment by mgwalker** [comment]
Dev implementation started in #679

**Comment by jeromeleecms** [comment]
Closed Via #679.
