### ISSUE TITLE
Construct Executive Summary Section

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#626]
Describe the task here, including any supplemental information.

### This task is done when...
 - [ ] Executive Summary has the table/card structure below (except it should not say previous activities). 
![image](https://user-images.githubusercontent.com/34281281/40799411-c1e55e86-64ca-11e8-8ab9-87d4db857940.png)

 - [ ] Below the content above, we also need to include, Program Budget tables should which shows HITECH and MMIS costs by FFY. These tables should be driven by the content from the Summary Budget.
       These tables should following this structure:
![image](https://user-images.githubusercontent.com/34281281/40799676-80fd91b2-64cb-11e8-9592-51915a9c4d95.png)
![image](https://user-images.githubusercontent.com/34281281/40799768-b319aadc-64cb-11e8-9e7f-dd7b56641c0c.png)

**Comment by lauraponce** [comment]
Linking this to #639 #606

**Comment by NAretakis** [comment]
@brendansudol FYSA, I know this is closed, so I can spin up a bug. But to close out exec summary, I think we just need to incorporate a totals column via the screenshot below. This would just add the FFY's that already exist. 

![image](https://user-images.githubusercontent.com/34281281/41856883-677dc31a-7853-11e8-8dd3-51885a6663e4.png)
