### ISSUE TITLE
Document how to capture Future Enhancements or New Functionality 

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#638]
Develop process to capture and track future enhancements/new functionality

### This task is done when...
 - [x] Process developed
- [x] Process approved by someone else
- [x] Wiki has been updated

 
cc: @NAretakis @nkkl

**Comment by NAretakis** [comment]
Wrote this up following our Bug process with a few tweaks. [Its also on the wiki](https://github.com/18F/cms-hitech-apd/wiki/Workflows-and-processes). We can revise as needed.

### Tracking and Adding a Future Enhancement
Sometimes you come up with a great idea, but it isn't viable in a current milestone, or requires a significant amount of work to address. 

1. Create a new issue for the future enhancement.
2. Describe the enhancement with as much detail as you can.
3. Add a label to mark it as **Future Enhancement**
4. **Don't** add it to project board (don't put it in the backlog); future enhancements will get added to the task board during triage.
