### ISSUE TITLE
Refine Program Budget Tables into Executive Summary & Results of Previous Activities Section

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#639]
Design to look at the program budget tables below and refine them to match the rest of the tables.

### This task is done when...
 - [x] Tables are refined and have a consistent design
 - [ ] Tables with null values are constructed to be used in the Results of Previous Activities sections
 - [ ] Tables with values driven from the Summary Budget are constructed to be used within the Executive Summary Section.

Here are the tables we need to use: 

![image](https://user-images.githubusercontent.com/34281281/40994699-28bfe4a8-68ba-11e8-94e6-c94b41eb06ae.png)
![image](https://user-images.githubusercontent.com/34281281/40994704-2d89cb7a-68ba-11e8-9897-fd40fc41adb0.png)

**Comment by lauraponce** [comment]
Here is the updated version of the table to match the version in previous activities and the budget table styles. The MMIS table would be formatted the same way as this as well:

![screen shot 2018-06-08 at 10 15 41 am](https://user-images.githubusercontent.com/21222704/41171335-0700c8da-6b05-11e8-9ba8-a78f4888939d.png)

**Comment by lauraponce** [comment]
@jeromeleecms @NAretakis is this 👍 ?

**Comment by lauraponce** [comment]
@jeromeleecms how does this seem to have the key under the table? 

![screen shot 2018-06-11 at 11 32 59 am](https://user-images.githubusercontent.com/21222704/41250280-49135964-6d6b-11e8-922d-d39df49d0e59.png)

**Comment by NAretakis** [comment]
Good to go!

**Comment by lauraponce** [comment]
Created #672 to capture the dev work for adding in these tables

**Comment by lauraponce** [comment]
The key will be collapsed by default:
![screen shot 2018-06-12 at 11 06 46 am](https://user-images.githubusercontent.com/21222704/41308473-d4084a6e-6e30-11e8-8679-0ba12ad48b0d.png)


When you click on the text or the arrow, the details will expand:
![screen shot 2018-06-12 at 11 06 29 am](https://user-images.githubusercontent.com/21222704/41308460-c8656cd2-6e30-11e8-82c5-b3e3261f7ead.png)

**Comment by NAretakis** [comment]
Good to go. It’s probably good to figure out how to do the collapsible info because I can see us potentially using it in a variety of places.
