### ISSUE TITLE
Document how we are doing accessibility testing

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#643]
Document how we do accessibility testing and then update the Wiki.

### This task is done when...
 - [ ] Tools for testing have been identified
- [ ] Test scripts for accessibility have been completed (@NAretakis)
- [ ] Document process for testing accessibility 
 - [ ] Wiki has been updated
- [ ] One round of testing has been completed using documented process 
- [ ] @nkkl Has signed off on the procedure

**Comment by NAretakis** [comment]
closing this in favor of #1259 and #1260 . We'll probably have more accessibility testing issues, but these are the ones we're targeting first.
