### ISSUE TITLE
Missing Activity Schedule Summary Section

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#646]
We have activity schedule sections for each individual activity, however there is no place within the app that a user can see the "sum" of all milestones that have been input for each activity.

To fix, we should create a Activity Schedule Summary section that is positioned after Activities and before Proposed budget. This section should take all of the individual milestones input for each activity and present them in a singular "summary" view ordered in ascending order by milestone start date.

**Comment by NAretakis** [comment]
@lauraponce  if you have a bit of time, Jerome and I realized we neglected to include a schedule summary section. This is filed as a bug for now, but probably needs a wireframe for Devs to fix.

Essentially, if you can wireframe up what the Activity Schedule Summary would look like, then the Devs can take the data from each activity's schedule and merge it into a singular view. Does that make sense?

**Comment by lauraponce** [comment]
👍 I'll work on this today

**Comment by lauraponce** [comment]
@NAretakis @jeromeleecms thoughts on something simple like this? 

<img width="753" alt="screen shot 2018-06-13 at 1 10 03 pm" src="https://user-images.githubusercontent.com/21222704/41375490-1d181c0e-6f0b-11e8-950e-871a5081638f.png">

**Comment by lauraponce** [comment]
And it would have the actual titles they gave for the milestones in there, not just the text "milestone 1"

**Comment by jeromeleecms** [comment]
@lauraponce I think this looks fine (as long as it formats on the screen well). Milestone descriptions made need to be longer... but good to go!
