### ISSUE TITLE
Initial content prototype

### ISSUE THREAD

**Issue by nicoleslaw** [18F/cms-hitech-apd#65]
- [x] Map the current APD doc to the guidelines
- [x] Ask questions about the language
- [x] Inventory the elements

**Comment by nicoleslaw** [comment]
Existing language from the form, guidelines, and addendum is here: https://docs.google.com/document/d/1yhP0rgbV9UUE10FOhN6eft-OpTYaP30GeEgfAhClgx8/edit#

**Comment by nkkl** [comment]
Do you have a copy of the regs? Do you have an _understandable_ copy of the regs? That's something that we will need for all of us, but I think you're running into it first.

**Comment by nicoleslaw** [comment]
I'm not there yet, but these are the regs and conditions listed for users to agree to:

### Procurement Standards (Competition / Sole Source)

42 CFR Part 495.348
SMM Section 11267
45 CFR Part 95.615
45 CFR Part 92.36

### Access to Records, Reporting and Agency Attestations'

42 CFR Part 495.350
42 CFR Part 495.352
42 CFR Part 495.346
42 CFR Part 433.112(b)(5) – (9)
45 CFR Part 95.615
SMM Section 11267

### Software & Ownership Rights, Federal Licenses, Information Safeguarding, HIPAA Compliance, and Progress Reports

42 CFR Part 495.360
45 CFR Part 95.617
42 CFR Part 431.300
42 CFR Part 433.112

### Security and Interface Requirements to be Employed for All State HIT Systems

45 CFR 164 Securities and Privacy

**Comment by nicoleslaw** [comment]
Finished the first pass of the inventory today: https://docs.google.com/spreadsheets/d/1rMov0wQdJh9bs2PDV8Lt0OIAadAuAsHk7OrarrfE_zE/edit#gid=0 — I need to meet with Jerome and Nick to talk through Appendix A and D. Scheduled that time for next week. I am going to close this out and open a new task for the new iteration.
