### ISSUE TITLE
Entering a leading 0 into a field that is related to $ prevents additional user input

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#650]
If you enter a leading 0 in a field related to $, the user can not enter additional numbers.

Work around is to just delete it and start typing again. 

![image](https://user-images.githubusercontent.com/34279968/41113298-16c69968-6a36-11e8-83b9-4584c520699d.png)

### This task is done when...
 - [ ] Leading 0 are ignored for fields related to $

**Comment by brendansudol** [comment]
honest question @jeromeleecms - why would one start an amount with a leading zero?

**Comment by brendansudol** [comment]
what are your thoughts on the desired way to handle this?

**Comment by jeromeleecms** [comment]
@brendansudol I did it by accident and than it took me a second to figure out how to fix it. I'm OK if we leave this alone and let you focus on higher priority items.

**Comment by brendansudol** [comment]
with the library we're using to format these inputs, i'm not sure there's much we can do here; i'm going to close this for now
