### ISSUE TITLE
Adjusting the FTE % on the State Personnel Section does not affect the budget table

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#651]
Adjust FTE % does not affect budget table:

![image](https://user-images.githubusercontent.com/34279968/41118012-7f1146a0-6a43-11e8-9289-85eb95bdaad4.png)

![image](https://user-images.githubusercontent.com/34279968/41118023-8d035b68-6a43-11e8-879b-25dc694a92cc.png)

### This task is done when...
 - [ ] FTE % is reflected the summary budget table.
- [ ] Code has reviewed by someone else
- [ ] Product verified experience

**Comment by mgwalker** [comment]
Cost is the position's full annual cost to the state.  Cost * FTE% is the cost to the *activity*.  FTE should not be capped at 100%; eg if a state has 4 auditors at 100%, they can just add one personnel row and put it at 400% FTE
