### ISSUE TITLE
Build out Results of Previous Activities section 

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#652]
Corresponds to #534 

There should be 3 subsections: previous activities summary, HITECH table, and MMIS table. There is no wireframe for the MMIS table, but it should work similar to the HITECH table.

**Comment by NAretakis** [comment]
@mgwalker before we can finish up this section, we need to construct the table below, and put it underneath the previous activities summary. This is just a blank table, to be filled out by a state user.
table for reference
![image](https://user-images.githubusercontent.com/34281281/41314486-1fffd13a-6e4a-11e8-90c8-df90aaa88a57.png)

**Comment by mgwalker** [comment]
What FFYs should be shown here?

**Comment by NAretakis** [comment]
Ah. Kind of a moving target. Ideally it would be the FFY's approved in the previous CMS approval letter. So, if we can't make it variable (add/delete), we could go with current year + two previous FFYs.

**Comment by jeromeleecms** [comment]
The rendering issue we saw in Firefox during user testing appears to have popped up in Chrome now. 

![image](https://user-images.githubusercontent.com/34279968/42108862-a0fdcbcc-7b90-11e8-9a71-bdc7a2001217.png)

No vertical scroll bar, either.

Just something to monitor during the refinement.

**Comment by mgwalker** [comment]
That one is a data bug.  😬   See #731

**Comment by NAretakis** [comment]
This is done for HIT/HIE. We now just need an MMIS table inserted to close this issue.
