### ISSUE TITLE
Saving an APD provides feedback on success/fail of saving

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#655]
Saving an APD by pressing the "Save APD" button does not report whether or not the save was successful or failed. This behavior should be updated to tell the user whether or not the save succeeded or failed.

### This task is done when...
 - [x] Clicking the Save APD notifies user that the APD was "Saved" or "Failed" 
 - [x] If APD failed, app should report a meaningful reason to the user 
- [x] Code has been reviewed by someone else
- [x] Product has approved experience

**Comment by brendansudol** [comment]
maybe having an UI like this? https://material-ui.com/demos/snackbars/

**Comment by mgwalker** [comment]
I think this one was finished by #698?  We do need to make sure we track getting the error messages to make sense, but at least there are success/failure notifications now.

**Comment by NAretakis** [comment]
Yes, I definitely am getting saving and submitting notifications. Closing out.
