### ISSUE TITLE
Add a section for HIE activities

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#659]
Relate to #497 
we need a section for HIE activities. Rather than do a "toggle", the idea is just to add this as another subsection under activity list. 

<img width="951" alt="screenshot 2018-06-08 12 41 21" src="https://user-images.githubusercontent.com/4461062/41170197-47ce490a-6b19-11e8-830e-77d014f543a7.png">

**Comment by mgwalker** [comment]
Closed by #669
