### ISSUE TITLE
Standardize our definition of done

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#66]
What do we need to have in place to merge a PR and close issues?

**Comment by nkkl** [comment]
Talked to @mgwalker and drafted a checklist for closing issues:

Dev ensures that the feature does the following:
 - Tests have been updated
 - Passes applicable tests
 - Has been code reviewed by someone else
 - Passes basic manual a11y test (keyboard nav, screenreader, text scaling)

Once all of that is good, they put it somewhere that everyone can see it and tag product and design:
 - Design has looked at the experience and given it a 👍 
 - Product has looked at the experience and given it a 👍 
 - Product closes the issue IFF design and product have given the thumbs up

We'll want to create a parallel workflow for closing out design tasks; perhaps @lauraponce and @nicoleslaw can weigh in here. This matters most when Design is handing something to Dev (like wireframes), as opposed to a task that they depend on (like conducting primary research).

**Comment by brendansudol** [comment]
a 🖼 is worth a 💯 * 1️⃣0️⃣ words:
<img width="427" alt="done" src="https://user-images.githubusercontent.com/1060893/35158815-4b2cc6c0-fd06-11e7-8a03-d014f04c15f2.png">

**Comment by brendansudol** [comment]
"Once all of that is good, they put it somewhere that everyone can see it and tag product and design"

@nkkl - perhaps this can be another category in between "in progress" and "done" on our project board?

**Comment by brendansudol** [comment]
For small/strictly dev tasks, after the dev checklist above is met, i think issue can be closed (by a dev involved with it)

**Comment by nkkl** [comment]
Makes sense to me! And I'll add a column for things that are in review.

**Comment by nkkl** [comment]
I think we've got general agreement on this process. @mgwalker / @brendansudol – how would you feel about creating a PR template that captures this checklist in some manner?
