### ISSUE TITLE
Implement standards and conditions checkboxes

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#664]
Related to #478. 
Attached is how the section should look. 

Text is included in the latest PR for these sections. 
<img width="440" alt="screenshot 2018-06-08 17 47 17" src="https://user-images.githubusercontent.com/4461062/41182524-0d00ac0c-6b44-11e8-8e0f-2f204207cff0.png">

### This task is done when...
 - [ ] Dev implements the check boxes sections for standards and conditions

**Comment by quarterback** [comment]
Here's what I was thinking about with the standards and conditions checkboxes @mgwalker. I'll add this text to the latest PR I just sent up, but we need the radio buttons.

**Comment by NAretakis** [comment]
This is done. Closing unless @quarterback feels otherwise.
