### ISSUE TITLE
Implement automated a11y testing

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#67]

**Comment by brendansudol** [comment]
so it looks like we get this, at least in part, for free by using airbnb's eslint config, which includes `eslint-plugin-jsx-a11y`; more details [here](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react-a11y.js)

**Comment by brendansudol** [comment]
perhaps that's good enough to start -- what are your thoughts @mgwalker? we could also wire up a script similar to that one i made for 14(c)

**Comment by mgwalker** [comment]
Automated a11y testing is super hard and not super effective, so I'm not sure it's worth putting much time into it.  The best, most effective a11y testing is manual.

I think the eslint plugin/config is a good start, and then manual CodeSniffer or similar testing on individual pages to make sure sizes and colors are okay will get us about as far as automated tools will go.  Beyond that, someone will have to manually test it - the automated tools will green light all kinds of things that simply aren't usable with assistive technologies.

**Comment by brendansudol** [comment]
`eslint-plugin-jsx-a11y` should catch a bunch of stuff, and as an extra level of eyes / tooling, i'm also adding `tota11y` (http://khan.github.io/tota11y/) to all of our pages on the development side (can add to staging too if/when we do that) -- i think it will be super useful

**Comment by brendansudol** [comment]
cc: https://github.com/18F/cms-hitech-apd/pull/75
