### ISSUE TITLE
Make a decision about how to break up the content of the app

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#675]
Based on recommendations from #573, we need to make a decision about whether or not to keep the app as one long flow or to break the components into logical pieces. We will include this as part of our user testing.

### This task is done when...
 - [ ] User testing has been completed 
 - [ ] Decision has been made about keeping the app in one long form or in blocks
- [ ] Issue created (if applicable) for Design and/or Dev to start work
 
cc: @lauraponce @NAretakis

**Comment by lauraponce** [comment]
@NAretakis @jeromeleecms okay to close this one and track the work in #758? My understanding from our discussion for the research share out last week was that we're keeping the long scroll, but we will refine the navigation components, then will retest. Let me know what your thoughts are on this one.

**Comment by NAretakis** [comment]
yes. Good to close this one, thanks.
