### ISSUE TITLE
Design content of opening experience

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#680]
Related to #377 & #460 

Per the conversation about what someone sees the first time they login to the app. Tied to the state profile and dashboard issues. 

### This task is done when...
 - [ ] A design of the state/federal opening experience is mocked up.
 - [ ] The mockup is shared with the team.

**Comment by jeromeleecms** [comment]
Also reference #570

**Comment by lauraponce** [comment]
Closing this one because #813 and #811 are more up-to-date
