### ISSUE TITLE
Change cost allocation section to fix Other Funding and Medicaid match rates

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#685]
Need to change how the cost allocation section works. In order to feed the Program Budget tables correctly, we need to:

1. Move the "Other Funding Amount" field into each of the FFY cards
2. Calculate and display the math associated with "Total Cost" minus "Other Funding Amount" = "Medicaid Share"
3. Remove the adjustable percentage allocation boxes
4. Insert a drop down menu that allows for 90/10, 75/25, and 50/50 allocations. 
5. Calculate and display the math showing the "Medicaid Share" broken into Federal and State shares.

Once this is completed, PR #681 can be resumed and will be able to have data fed from Cost Allocation into the Program Budget Tables.

Example flow is below:

![image](https://user-images.githubusercontent.com/34281281/41421452-1ab7ac28-6fb4-11e8-9979-59e23c6752fc.png)

**Comment by brendansudol** [comment]
done!
