### ISSUE TITLE
Walkthrough of CMS conditions and standards

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#69]
18F folks don't understand these well enough! Let's learn more about it.

**Comment by jeromeleecms** [comment]
May be helpful when we do the walkthrough: added SMD Letter 16-009 to Google Drive in the reference docs section. In addition to the 7 standards and conditions (S&C) outlined in the IAPD template, this letter addresses the changes to the S&C which went into effect last year (Jan 1, 2016). Some of the changes are modifications to the existing S&C, while others are new to the list.

**Comment by jeromeleecms** [comment]
Just checking in on this one -- in some of our discussions there have been some indications that this may not be needed. Should we keep this open?

**Comment by NicolasAretakisCMS** [comment]
@nkkl are you OK if we close? Honestly this is mostly a check box for states to give us assurances. It may not be worth deeply exploring at this point (phase 1).
