### ISSUE TITLE
Document Scenario Testing

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#690]
Scenarios testing via use-cases. We'll use the google form for tracking results, but need to come up with the list of scenarios.

### This task is done when...
 - [x] Scenarios are listed.
 - [ ] Scenario are tested.

**Comment by NAretakis** [comment]
We can use this comment to create a list of scenarios, I'll start:

1. Scenario A
2. Scenario B

**Comment by nkkl** [comment]
I think these are our scenarios:

- [ ] A state user can submit an APD with HIT 
   - [ ] No assistive technology or modifications
   - [ ] CSS disabled
   - [ ] Text zoomed
   - [ ] With only keyboard
   - [ ] With a screen reader
- [ ] A state user can submit an APD with HIT, HIE, and MMIS content
   - [ ] No assistive technology or modifications
   - [ ] CSS disabled
   - [ ] Text zoomed
   - [ ] With only keyboard
   - [ ] With a screen reader

**Comment by jeromeleecms** [comment]
Here's some considerations:
1) HIT Only
2) HIE Only
3) HIT and MMIS

We do have situations where the states are only requesting funding for HIE activities. It would be interested to see how we would handle a situation where there is no HIT admin funding.

**Comment by nkkl** [comment]
Reasonable! You understand the nuances better than I do!

**Comment by NAretakis** [comment]
Testing itself will occur in a different issue/milestone.
