### ISSUE TITLE
v0.5 landing page rethink

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#703]
A quick reimpression mock up of the landing page. The existing landing page needs to be refurbished. Until we know how it'll integrated with other parts of the application in a longer term, it doesn't need a great deal of polish but should at least reflect the existing styles, etc.

### This task is done when...
 - [x] design a landing page 
 - [ ] create an issue for dev to review & implement using existing style (#704)

**Comment by quarterback** [comment]
<img width="391" alt="screenshot 2018-06-22 17 47 46" src="https://user-images.githubusercontent.com/4461062/41800746-e873bb20-7644-11e8-852d-31aa6b53dc76.png">

**Comment by quarterback** [comment]
Essentially taking what we have now and applying the button styles to it. Again, until we're able to nail down what we're doing vis a vis dashboard/styles/single page vs long scroll, I don't think we need to spend a lot of time on this. I just wanted something that didn't look like what we have.

**Comment by lauraponce** [comment]
Quick q, is this meant as a placeholder for the dashboard page until that would be implemented? Or would both of these pages be used for different purposes?
