### ISSUE TITLE
Get CMS AWS Sandbox up and running

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#708]
We're going to be using the MACPro AWS world, but before we can do this, we need to have a technical coordination meeting and CMS AWS sandbox.

### This task is done when...
 - [x] Meeting scheduled with MACPro technical team to assess difference between cloud.gov sandbox and CMS sandbox.
 - [ ] Technical gap analysis is written
 - [ ] CMS AWS and HiC team has clear direction to setup sandbox.

**Comment by cmc333333** [comment]
I'd love to sit in on that meeting and might be able to translate a bit where needed. I'd bet @mgwalker should also attend; are there others?

**Comment by NAretakis** [comment]
@mgwalker is a superuser, and as such has started deploying stuff to our AWS space. I think we can close this for now, and potentially revisit if we hit some infrastructure blockers.
