### ISSUE TITLE
Build out the new state dashboard

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#722]
Use #676 as a reference (the only thing changing in the design since the last version posted is removing the priority column in the tasks section)

**Comment by NAretakis** [comment]
@lauraponce can we spend just a bit of time on this to wireframe the dash based on the latest user feedback, and then Devs and run with it.

**Comment by lauraponce** [comment]
Dashboard tweaks:

- Remove the Due Date column in the Tasks section
- Swap places of My Tasks section and the Statuses section
- Update Statuses states to be: `Drafting` **or** `Submitted`, `Received`, `Under Review` **or** `Pending State Response to CMS Comments`, `In Clearance`, and `Approved` **or** `Disapproved` **or** `Withdrawn` (So there are a total of 5 circles along the status line.)
- Add dates under the status states such as:

<img width="740" alt="screen shot 2018-09-07 at 1 45 37 pm" src="https://user-images.githubusercontent.com/21222704/45242311-51b50a80-b2a4-11e8-8a7b-c7e52e580529.png">

**Comment by lauraponce** [comment]
^ These updates are based on the feedback from the last round of research: https://docs.google.com/document/d/1AqZpgtV_aqstOlKnfZLT_gzQpRI26TBT9KGtPHmCxDA/edit#

@NAretakis @jeromeleecms does this list look right as the next step in making some UI tweaks to the dashboard? [This](https://hitech-apd-pr1008.app.cloud.gov/) is the current state of the dash from @mgwalker's latest [PR](https://github.com/18F/cms-hitech-apd/pull/1008).

**Comment by lauraponce** [comment]
I was thinking that maybe we don't need the `Received` status as a state since it should be a given once it's submitted, but I can see it giving people extra peace of mind seeing a greencheck there showing that their APD is now in the hands of CMS even if the actual review process hasn't begun. Open to other opinions on this though!

**Comment by NAretakis** [comment]
I don't know how we'd calculate `Expected Due Date` unless we just did 60 days from the submission. That said, I am not sure how useful it would be because we definitely want to be under that target. I think I prefer not have expected date there (unless we actually had some metrics/math to make it realistic). And then it gets a date stamp once we mark it as approved. That work for you @lauraponce ?

**Comment by mgwalker** [comment]
`Pending State Response to CMS Comments` is a _really long_ title.  Everything else is 1 or 2 words, and this one is 6 words, half of which are themselves kinda lengthy.  It's going to be hard to make that fit in the same space as the others without it looking really funky.  Is there a shorter title we could use?

**Comment by jeromeleecms** [comment]
How about `Returned with Comments` or `Return with CMS Comments`?

**Comment by NAretakis** [comment]
@jeromeleecms how about "Pending Comments"?

**Comment by NAretakis** [comment]
Per the conversation, while the final status is grey it can "Decision". And then when something actually happens there, it can change to Approved, Disapproved, Withdrawn, on and RAI (Request for Additional Information).

**Comment by NAretakis** [comment]
`RAI` is similar to withdrawn, but it should trigger the APD to be sent back to the state, exactly as the same as `Pending Comments`. The state needs to fix something in the APD that is huge, and then would fix and resubmit.

**Comment by mgwalker** [comment]
For withdrawn-and-closed APDs, would we want to cut out the interim dots?

![screen shot 2018-09-11 at 1 14 25 pm](https://user-images.githubusercontent.com/1775733/45378991-871f6800-b5c4-11e8-8e6f-fe878910eef8.png)

**Comment by NAretakis** [comment]
Really, whatever is easiest for you to work up. It is fine with the interim dots, and it is OK without as well.

**Comment by mgwalker** [comment]
I'm going to close this in favor of #1039 so there's a clearer action of remaining work for dev.
