### ISSUE TITLE
Plan round 6 of research

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#724]
### This task is done when...
 - [x] Create research plan
 - [x] Schedule sessions

**Comment by lauraponce** [comment]
@quarterback we are a *go* for 8/7 from @NAretakis and @jeromeleecms, so we can use this issue to track the mod guide and scheduling logistics

**Comment by quarterback** [comment]
Here's the schedule form: https://docs.google.com/forms/u/1/d/15gDpcwuDFuuLBGHwJfYT9KDy8lC52R3Htb63rcipw6s/edit?usp=forms_home&ths=true

**Comment by lauraponce** [comment]
I just sent out the recruiting email, so we should start to hear back about folks' availability today.

**Comment by lauraponce** [comment]
Using this issue to keep track of the testing docs: https://docs.google.com/document/d/1Lzsq9HAHzuYOSTCbBtgqAh1ZPxX4HDaGzqr69e-kWKY/edit?usp=sharing

**Comment by lauraponce** [comment]
The [protocol draft](https://docs.google.com/document/d/1Lzsq9HAHzuYOSTCbBtgqAh1ZPxX4HDaGzqr69e-kWKY/edit?usp=sharing) is ready for review when you have a minute, @NAretakis and @quarterback . (And we're already getting responses for the sessions next week! 🎉)

**Comment by quarterback** [comment]
I went ahead and plotted a few folks who submitted onto a schedule already, we still have one time left open. @lauraponce @NAretakis

**Comment by NAretakis** [comment]
Protocol looks good. Might be a little long based on past testing. Thoughts on what would be most important to prioritize?

**Comment by lauraponce** [comment]
I just went through and highlighted the sections we should definitely try to get feedback on in blue and the sections to skim through or skip entirely in yellow (depending on time). Does that balance seem right?

**Comment by lauraponce** [comment]
@quarterback can you share the schedule you drafted up so we can start slotting in the times here? https://docs.google.com/spreadsheets/d/1F6X9p-6RBFGadPtrG-7ubxHpO5Bz6acYhyOnmQbGzos/edit#gid=0

**Comment by quarterback** [comment]
@lauraponce already in that same spreadsheet on the 2nd tab (Round 6) with an open spot. If we get someone who has a conflict, I can readjust them. I just went ahead and added the names to the first tab.

**Comment by lauraponce** [comment]
Whoops 🙈I'm the worst at noticing more than one sheet, sorry!! Thanks for taking care of biz, @quarterback, looks good! 👍 I added the other person to the list who responded via email so it looks like we have our four?

**Comment by quarterback** [comment]
I will send out the calendar invites now to the people we've selected and let other folks know we're plotting the office hours and to await more information on that.

**Comment by quarterback** [comment]
I sent out the calendar invites now to the people we've selected and will send a letter to the state testers to look for more info next week about the open office hours. (#866)
