### ISSUE TITLE
Mockup of a card interface for APD status tracking (dashboard)

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#726]
I talked to @lauraponce about an alternate idea kicking in my head about displaying the APD status tracking on the dashboard. This is just an issue for me to design something and show it. Successor to #400 

### This task is done when...
 - [x] Ron designs a prototype of this idea clanging around in his head.
 - [x] Laura sees it.

**Comment by quarterback** [comment]
<img width="1256" alt="screenshot 2018-07-06 15 14 54" src="https://user-images.githubusercontent.com/4461062/42396407-87852e3e-812f-11e8-9b24-2e46f22deb84.png">

**Comment by NAretakis** [comment]
This looks great! We'll just have to figure out how to incorporate a bit of this into the dashboards that are being constructed.
