### ISSUE TITLE
Questions about the APD content and guidelines

### ISSUE THREAD

**Issue by nicoleslaw** [18F/cms-hitech-apd#73]
Hello 👋  Here is the doc where I combined the content from the APD template, guidelines, and addendum. I flagged some questions for you in the margins: https://docs.google.com/document/d/1yhP0rgbV9UUE10FOhN6eft-OpTYaP30GeEgfAhClgx8/edit#

---

I also started breaking this out into chunks of information, feel free to peek but there's no action for you there yet: https://docs.google.com/spreadsheets/d/1rMov0wQdJh9bs2PDV8Lt0OIAadAuAsHk7OrarrfE_zE/edit#gid=0

Relates to #65

**Comment by jeromeleecms** [comment]
@nicoleslaw Provided responses to your questions. Let me know if you need any further clarification.

@NicolasAretakisCMS feel free to round out (or flat out refute!) any of the responses.

**Comment by nicoleslaw** [comment]
Thank you so much @jeromeleecms!
