### ISSUE TITLE
Actual previous expenses table is empty and can't be modified

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#731]
I think this is a bug where the API is sending back blank information by default (because it starts out not having anything to send, which makes sense), but the frontend just accepts that and doesn't replace the nothingness with a default value.  Not sure the best way to deal with this one.

@jeromeleecms @NAretakis: Is it ever valid for the "previous expenses" table to be missing?  If the answer is no, I think we can fix this by adding a default value when the API doesn't send anything.

**Comment by NAretakis** [comment]
On a brand new APD, this section would be simply marked as not applicable. Can we setup a default $0 value so it displays correctly?

FYSA, when a state comes in with an update within the application, we’d want to have the previous activities table populated from the previous Program Budget Table (exec summary).
