### ISSUE TITLE
Content for the Contract Experience

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#734]
This is an issue for the attach contract buttons. Specifically, how to use and when to use it. 

### This task is done when...
 - [x] language around contract uploading is modeled.
 - [x] Product reviews the experience.

**Comment by quarterback** [comment]
I'll need more info on this issue @NAretakis @jeromeleecms.

**Comment by quarterback** [comment]
Updated per the standup convo about this. I should be able to attack this.

**Comment by jeromeleecms** [comment]
@quarterback Put a first cut at the process flow in Mural (it's a picture from Visio). Does this help get you started? https://app.mural.co/t/gsa6/m/gsa6/1524714012930/d34a6666c3cb4db8dfee9cfadc5e4c13e7a88f72

Also, if you need some general guidance on what should be captured in a procurement, there is some content we can adapt from the E&E template (Appendix C): https://www.medicaid.gov/affordable-care-act/provisions/downloads/medicaid-eligibility-and-enrollment-iapd-template.pdf

HITECH regs for this are 42 CFR 495.348

**Comment by quarterback** [comment]
Thanks @jeromeleecms I'll use this to get started.

**Comment by quarterback** [comment]
Replaced "add resource" with "add contractor" because add resource when paired with adding an attachment felt confusing.

**Comment by quarterback** [comment]
<img width="813" alt="screenshot 2018-07-11 13 08 13" src="https://user-images.githubusercontent.com/4461062/42588310-7cfb81d6-850b-11e8-9404-660bda8a4123.png">

Just expanding on #736/#764, some ideas related to the experience worth exploring content wise and interactionwise. Instead of having people choose from a drop-down, giving a small line where they'd name the document would give the analyst a better understand of what it is exactly. Mislabeled documents might not be a huge issue, but at volume they could be. Also, it gives users more accountability for what they're sharing.

Also, actual help text that explains what type of documents can be uploaded can be added (and I'll add it once this experience is modeled in the prototype.)

Just wanted to share for visibility/future discussion not reopen ideas that had already been explored. cc: @jeromeleecms @lauraponce @NAretakis

**Comment by quarterback** [comment]
This issue is closed with PR #793

**Comment by jeromeleecms** [comment]
@quarterback I like the idea of naming (esp if standardized!), but we also have to mechanism for how we can track content for the dashboards/run reports. Always open to future enhancements on how we can make the experience better!
