### ISSUE TITLE
Linking attached contracts to backend (Activity & Contract resource)

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#735]
Need to define and construct how contract attachments will be linked to the database, activity and/or contract resource.

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2

**Comment by mgwalker** [comment]
I'm leaning towards a simple `files` table that isn't *directly* linked to anything.  It would look something like this:

|column|type|
|---|---|
|id|(auto) integer|
|key|string - identifies the file in a way that the storage mechanism understands (e.g., a filename)|
|size|integer - file size in bytes|
|metadata|json - for any additional information we want to store about the file; this could be vary based on what kind of file it is|

Then we'd have several many-to-many mapping tables.  For example: A `contract_files` table that has two columns, `file_id` (foreign key into the `files` table) and `contract_id` (foreign key into the `activities_contractor_resources` table).  A nearly identical table for `activity_files`, maybe even `apd_files`.

Curious for others' thoughts.  @jeromeleecms @brendansudol

**Comment by jeromeleecms** [comment]
So this is structure is essentially a master file listing and it would abstract out file location + meta-data into this table right? Seems that this would enable flexibility in the off case we'd have to have track another set of files. Would you need to have a field that denotes how the file is being stored (blob vs physical location)?

**Comment by mgwalker** [comment]
Yep, that's right.

For your second question, no.  That's a possibility, but in the short term, I think it's smart to just assume all of our files will be stored the same way.  We can modify the database later if that turns out to be incorrect.

**Comment by mgwalker** [comment]
#852 updates the database and data models.  The next step will be adding API endpoints to upload and download files, and then I think this one will be done.

**Comment by mgwalker** [comment]
Closed by #865 and #852
