### ISSUE TITLE
Wireframe contract upload/management experience

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#736]
Design the UI flow for how users will upload/manage contracts with an APD that is currently being prepared. This will cover the following functions:

- Attaching new 
- Viewing existing
- Modifying existing
- Deleting

Uploading/Managing Contracts independent of an APD will be tracked in a separate Milestone/Issue.

**Comment by lauraponce** [comment]
After contract is attached, it shows up next to the line item it's associated with. If you click the blue text link to the name of the file, it downloads so you can view it, and if you click the X, it will delete it and you'll see the yellow Attach contract button there again.

 ![screen shot 2018-07-02 at 12 27 22 pm](https://user-images.githubusercontent.com/21222704/42182548-64013762-7df3-11e8-93e1-ac2f9106b839.png)

**Comment by lauraponce** [comment]
@NAretakis @jeromeleecms is this along the lines of what you were thinking?

**Comment by NAretakis** [comment]
Yes, except I think we need to allow for multiple attachments linked to a single contract resource in the event a state needs to attach an RFP, and a contract. Or at least two documents that are associated with a single contract "line item".

**Comment by lauraponce** [comment]
@NAretakis gotcha –– so the attach contract button should always be present even after they add a file? 

Also, would it make more sense to call it something more generic such as "Attach file" instead of contract?

**Comment by NAretakis** [comment]
Yes for the button. We want to allow multiple attachments. And how about we say “Attach Procurement Document” which should cover contracts, RFPs, SOWs, and everything else. We could always go with “Attach File” and then some helptext. I’ll defer to y’all on what makes the most sense.

**Comment by lauraponce** [comment]
@NAretakis  how does this seem?

![screen shot 2018-07-02 at 2 16 40 pm](https://user-images.githubusercontent.com/21222704/42186717-8817cfda-7e02-11e8-934a-64da7748d322.png)

**Comment by jeromeleecms** [comment]
@lauraponce @NAretakis During the upload process, what do you think about having a form that requests the type of document is being uploaded + approval status + comment? I.e. Contract, Contract Amendment, RFP (we can mirror the current HITECH tracker). Help text would essentially be anything that is not a new contract would fall as a contract amendment (SOW, Task Orders, etc). 

This would make it easier to track + what would appear on the State dashboard for what has been submitted and under review.

**Comment by NAretakis** [comment]
@jeromeleecms lets take the form idea and incorporate it into a later feature request. For MVP, I think just attaching contracts and having them linked to the contractor in the back-end will suffice.

**Comment by NAretakis** [comment]
if @jeromeleecms is good with that, then this is good to ship to the Devs.

**Comment by NAretakis** [comment]
my thinking is that we keep this as simple as possible:

We should be already storing the document in the database, and there's an issue for the Devs to link it to the activity on the back-end. 

1. If an attachment is added during the APD creation, we pull the linked contract attachment data to trigger a Contract Review Pending status event.
2. In this case, an APD would have a status, but so would the contract attachment.
3.  If an attachment is added as a stand-alone, we could reuse the same trigger from the attachment, and kick off a stand-alone Contract Review Pending status event.

To that end, I think it is OK for us to kick this down the road because we're not yet at the Review/Update work yet. When we get to those milestones, we'll have to revisit which I think is OK.

**Comment by jeromeleecms** [comment]
@lauraponce: Nick and I had a "quick" chat on this. For the MVP, we can make this light weight. Basically (in whatever order you think looks good):

1) Dropdown for document type (Options: Request for Procurement, Contract annd Contract Amendment)
2) Attach document

From the OG prototype:

![image](https://user-images.githubusercontent.com/34279968/42232681-0c8e8c8a-7ea4-11e8-845d-9b8dc2a9c1f8.png)

We'll work on some maps to help devs track what happens after the document is upload and the APD is submitted.

**Comment by lauraponce** [comment]
Users would select from the dropdown and then click select file to choose from their file system. If they click 'Select file' before specifying the type, the dropdown would light up with an error to show that it's required.

How does this look?

![screen shot 2018-07-03 at 10 55 06 am](https://user-images.githubusercontent.com/21222704/42236382-970e28ba-7eaf-11e8-82c7-4a8b0d323082.png)

**Comment by NAretakis** [comment]
Love it.

**Comment by lauraponce** [comment]
Created #764 for the dev task
