### ISSUE TITLE
Add "+" content into the summary budget table section

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#738]
The summary budget table has "+" signs for each line item. When clicked, users should see a row for each state, contract, or non-personnel entry that is being summed. 

### This task is done when...
 - [ ] Designs are wireframed to display detailed information when the "+" is clicked.

**Comment by lauraponce** [comment]
@brendansudol do you need a wireframe for this? I'm picturing the text would just show up where you have the "Details will go here" – nothing fancy. Does that work? Let me know if you need something mocked up though and I can do that.

![screen shot 2018-07-09 at 10 42 02 am](https://user-images.githubusercontent.com/21222704/42466781-bc5fccea-8364-11e8-8904-cf9b4ee61c4e.png)

cc @jeromeleecms

**Comment by brendansudol** [comment]
i'm good to iterate on this without a mock -- my one question is around what level of detail we want to show for the individual entries that make up these rolled-up category. i.e., do we need to show all of the numbers that we're showing at the category level? can/should we simplify that and just show entry name and totals? do we even need this detail section at all?

cc: @jeromeleecms @NAretakis

**Comment by jeromeleecms** [comment]
I remember hearing one of the state testers mentioning this functionality, but I thought the initial intention of the + was to show any cost allocation (Reference #404 / #540). 

If we go this route (and not go the route of cost allocation), the "+" sign can show the total cost by Activity (i.e. Activity 1 - FFY 2018: $100,000 / Activity 2 - FFY 2018: $100,000). I do like the idea of clicking "+" under contracts and seeing all the contracts associated with the APD.

Do we want to do a quick discussion on this?

**Comment by brendansudol** [comment]
if we go the cost allocation route @jeromeleecms, would the only entries with the '+' be mmis where there's an option for diff allocations besides the standard 90/10?

re: total cost by activity by year, i'm actually not convinced we need this because it's the exact same info as what's in the exec summary.

my latest thinking is that we should simply remove the '+' and see if it's missed.

**Comment by jeromeleecms** [comment]
1. Cost Allocation: Yes, MMIS would be the major use case for this option. 
2. Total Cost by Activity By Year: The only difference would be that this wouldn't be an entire summary of the activity, but that piece of it. For example: Under personnel costs category, clicking the plus button would show the activity costs for personnel costs only. Under the contract costs, clicking the plus button would show the list of contracts for the activity. 
3. Removing the "+": I don't think the "+" would be missed, but we don't have any view in the app right now that summarizes the activity costs as (1) or (2) would.

Thinking through this a bit more, it would be nice to have a view of this table that would we could toggle between "Cost Allocation" and "Summary by Cost Category." For MVP, (2) seems like the expectation for this table from user testing. Having a toggle between the (1) and (2) could go into a future enhancement.

**Comment by brendansudol** [comment]
sounds good re: MVP, and you're right about diff between this and exec summary! will continue to move forward with 2
