### ISSUE TITLE
Refine the boundary of the individual activity sections

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#754]
It's not immediately obvious what is included with each activity and when you're moved onto the next one. The UI needs a little work in order to make this clear.

**Comment by lauraponce** [comment]
If we introduce some of the colors from our style guide into the activities area, it better defines the space for each activity.

How about something like this?

![screen shot 2018-07-12 at 2 40 59 pm](https://user-images.githubusercontent.com/21222704/42661153-32478644-85e2-11e8-90a5-d6c5931713fb.png)

Versus the current state:
![screen shot 2018-07-12 at 2 43 45 pm](https://user-images.githubusercontent.com/21222704/42661164-3a6e2512-85e2-11e8-9370-bff53657637f.png)

@jeromeleecms @brendansudol @quarterback

**Comment by jeromeleecms** [comment]
Blue = Good :+1: 

It is much easier to see in the app - though as I mentioned, it would be cool if each activity was assigned a subtle, related shade so users could have a visual link between activity they entered and how it propagates through the app/tables. Not for MVP unless it solves a major usability problem.

**Comment by lauraponce** [comment]
@brendansudol the colors used: 

light blue: #DAE9F7
dark blue: #317CB9
