### ISSUE TITLE
Solve for per-hour in Contract Resources 

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#755]
During user testing, one state referenced that some contractor resources (and perhaps some state resources) were hourly resources. We need to come up with how we will handle hourly resources within the app.

This is done when:
- [ ] Agreed upon a process to address this situation
- [ ] Sketched out the user interaction within the app
- [ ] Design has signed off 
- [ ] Product has signed off 
- [ ] New Issue has been created for Dev

**Comment by jeromeleecms** [comment]
@lauraponce Updated + please let me know if you need more details on this.

**Comment by lauraponce** [comment]
Users would see this when they first get to this section:

<img width="618" alt="screen shot 2018-07-09 at 7 33 13 pm" src="https://user-images.githubusercontent.com/21222704/42486020-fdbed89e-83ae-11e8-98b9-1371bda9af4f.png">

If they check the box, this appears below:

<img width="635" alt="screen shot 2018-07-09 at 7 33 25 pm" src="https://user-images.githubusercontent.com/21222704/42486037-0cf53b96-83af-11e8-8952-3cc498940b2c.png">

@jeromeleecms thoughts on this? Does this solve for what is needed here, or am I missing anything?

**Comment by jeromeleecms** [comment]
I think this is a good start -- some additional thoughts:
1) Hourly rate could increase by FFY (so maybe have the ability to say this applies to all years or enter a rate by FFY)
2) Hours per FFY may also vary, so each year would have to individually entered.
3) Can you add the attach contract document to the mock-up to this, please? It will give us a sense of how busy this section might get.

**Comment by lauraponce** [comment]
@jeromeleecms I can't believe I forgot to include the contract stuff in this design :facepalm: it would definitely make the most sense to have that in. I ended up re-working the whole section because it started to get a little cramped for space, what are your thoughts on something like this?

![screen shot 2018-07-11 at 2 58 16 pm](https://user-images.githubusercontent.com/21222704/42601562-e1f1e1f2-851a-11e8-86e6-9bc76bb31058.png)

**Comment by lauraponce** [comment]
Visually it would look a little better if we could add another descriptor word or two associated with "Cost" so that it lines up closer to the row, but it's also not going to be the end of the world if we just leave it as Cost. 🙂  cc @quarterback

**Comment by jeromeleecms** [comment]
Liking the direction of this!

- We would still need the hourly resource checkbox, right? 
- If we have multiple contracts to add, would it be just a continuous scroll to add more or would each contract be in a self contained card that we could collapse as users work on filling this out (is that what the circle at the top right is denoting?) ? Just trying to avoid our "lost in the scroll feeling" since each contract" won't be bookmarked in the left navigation.

**Comment by lauraponce** [comment]
What if instead of having them opt-in for the hourly resource checkbox, they opt out and check a "not applicable" box like this and then that section would gray out?

For adding 2+ contracts, they would click the Add button at the bottom and then the boxes for the next one would show up after the separating line under the first one. Does that work?

The circle with the line in it in the top right is supposed to be the remove icon in case they wanted to delete it. 

![screen shot 2018-07-12 at 2 16 55 pm](https://user-images.githubusercontent.com/21222704/42659935-9c620f94-85de-11e8-8b89-3da4fa4f992a.png)

**Comment by jeromeleecms** [comment]
I would make the N/A button default to "checked" then they can opt-in to the hourly resource -- other than that, I would say let's build it and get people's take on it! :+1:

**Comment by lauraponce** [comment]
In that case, if the hourly stuff won't apply to most resources, how about something like this with that section grayed out when "No" is selected (default) and when they click "Yes" it would un-gray out?

![screen shot 2018-07-12 at 3 08 17 pm](https://user-images.githubusercontent.com/21222704/42662201-8f9b8da6-85e5-11e8-88d3-782a6b60ec71.png)

**Comment by jeromeleecms** [comment]
Looks good! We can probably get a quick take from the State's on this in Denver if @brendansudol or @mgwalker get it done. :) No pressure.

**Comment by mgwalker** [comment]
If they tell us hourly rate and number of hours, should we just calculate the cost for them?

Other than potentially calculating the contractor cost here, does the hourly rate/#hours have any downstream implications for how we calculate other things?

**Comment by lauraponce** [comment]
Created #801 for the dev work.
