### ISSUE TITLE
Add in a way to specify which quarters activity is funded in Cost Allocation

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#756]
Users should be able to specify when/which quarter(s) the activity will be funded while entering the activity details in Cost Allocation

**Comment by lauraponce** [comment]
We'll want to have @quarterback take a peek at the content here once the design is approved, I just put in what I thought might make sense for now. 

@jeromeleecms can you give some feedback on how this is set up? I want to make sure I'm understanding what states would need to specify for the quarters (e.g. is it a percentage? or is it just checking a box for each quarter? etc...)

![screen shot 2018-07-06 at 10 29 10 am](https://user-images.githubusercontent.com/21222704/42393012-b8e31a8e-8109-11e8-85b9-66090e87d1b2.png)

And here's is the more zoomed out view of how it would fit within that section:

![screen shot 2018-07-06 at 10 29 16 am](https://user-images.githubusercontent.com/21222704/42393075-fd641b72-8109-11e8-9747-102944bd793b.png)

**Comment by lauraponce** [comment]
@jeromeleecms how about something like this?

<img width="697" alt="screen shot 2018-07-09 at 7 10 17 pm" src="https://user-images.githubusercontent.com/21222704/42485284-d74f6442-83ab-11e8-91c6-fbc4d0dd5e69.png">

When a cell is in focus being edited:

<img width="699" alt="screen shot 2018-07-09 at 7 10 27 pm" src="https://user-images.githubusercontent.com/21222704/42485304-efe6b474-83ab-11e8-820f-9a5128ab3d11.png">

**Comment by brendansudol** [comment]
i'm worried that allowing them to adjust both the dollar amount and percentage may be confusing / also more difficult in terms of validation. What if those pieces of information are together but you can only edit the percents (and as soon as you do, you see the impact to the dollar amounts)?

**Comment by jeromeleecms** [comment]
@lauraponce This looks good!

@bren for the MVP that's fine (since we've already been using that design pattern and state's have been OK with it). Ideally we should have both -- for state staff, percentages would be OK, but for contracts (like a deliverable based contract) states would more likely have a $ amount by quarter. 

We can just put the dollar amount functionality into a future enhancement. Good?
