### ISSUE TITLE
Refine navigation throughout the app experience

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#758]
It's possible to get "lost in the scroll" so the navigation should be intuitive and obvious to let people know where they are at all times as well as making it easy to go to another section.

**Comment by jeromeleecms** [comment]
With #765 almost being completed, what do you think about using something like "Scroll-Spy" (https://www.npmjs.com/package/react-scrollspy) to track users as they move through the app? We can do that in combination with other UI enhancements that you think would be helpful.

Here's an example (horizontally), but it can probably be made to work vertically (not sure if this is the same library): https://mdbootstrap.com/react/advanced/scrollspy/

**Comment by brendansudol** [comment]
yeah, `scrollspy` is a good pattern to follow -- i can look into this implementation

**Comment by brendansudol** [comment]
looked into some scrollspy libraries (i.e., http://makotot.github.io/react-scrollspy) and none work great given our nested nav structure.

i wonder if there are some other designs / treatments to help with this "getting lost in the scroll" issue.

**Comment by lauraponce** [comment]
Here's a decent resource for long scrolling pages: https://www.smashingmagazine.com/2017/05/long-scrolling/

A couple of the design patterns that are relevant to us and could help solve this "lost in scroll" problem are:

- Scroll-based sticky nav (this could help let people know where they currently are)
- Progress tracker by section (this could help people see what sections they've started and which ones they still need to visit)

**Comment by NAretakis** [comment]
@lauraponce these are some good options, but to close out this issue for now, how about we just reuse the Sticky Header functionality that we have for Activities and apply that throughout all Header Sections of the application?

If you are good with that, can you spin up a Dev issue to implement?

**Comment by lauraponce** [comment]
#826 is the dev issue for building that out
