### ISSUE TITLE
Cross-browser issues for the table and navigation

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#760]
The tables and left nav (not sticking) are not showing up properly in IE and Firefox, and unfortunately, many of the state users from testing are stuck on using IE  😢

**Comment by jeromeleecms** [comment]
Per Stand-up, @mgwalker is deferring to @brendansudol expertise on this one.

**Comment by brendansudol** [comment]
also, we should try to find out exactly what versions of IE and Firefox people are using -- maybe we're already doing this?

**Comment by jeromeleecms** [comment]
This is from IE 11, using the default Edge rendering system. Also had the same issue with using IE 10 rendering.

![image](https://user-images.githubusercontent.com/34279968/42456698-6621d0ae-834a-11e8-8842-cd91a0763350.png)

If you scroll in the main content section, the entire left nav bar also scrolls with it.

**Comment by brendansudol** [comment]
thx, that's helpful! can you provide a similar one for table too?

**Comment by jeromeleecms** [comment]
Also: 
- Anything <= IE 9 or below results in the app erroring out. In IE9, I get kicked out of the app and can't login. With IE 8, I get a JavaScript error. I seem to recall reading that one user was using IE8(?)
- Firefox seems to be OK now - it looks like this rendering issue was resolved once some content was initialized into a new APD (?)

@lauraponce I wasn't able to attend all the user testings, do you remember the browser versions that our testers used? 

Related aside, maybe in the next text protocol, we can explicitly check the browser?

**Comment by jeromeleecms** [comment]
Sorry - click over to the browser and accidentally closed the issue -- reopening...

**Comment by brendansudol** [comment]
we also likely need to set some cutoffs -- as in, if you're using something less than ie9 or 11, the app doesn't load and you get a message to update your browser

**Comment by mgwalker** [comment]
Just some extra info about browser support: React dropped support for IE 8 in 2016, shortly after Microsoft also dropped support for it.  But Microsoft _also_ dropped support for IE 9 and 10 at the same time.  IE 11 is the only supported version left, and it'll likely be supported for a long time to come (fortunately or unfortunately, depending on your perspective).

**Comment by jeromeleecms** [comment]
Good to know! 

If React is the limiting factor here, sounds like we will have to defer to its minimum requirements. I did some searching in the react documentation and found this:

-https://reactjs.org/docs/getting-started.html
-https://reactjs.org/docs/javascript-environment-requirements.html

Will defer to you all about what browsers meet those requirements (unless there is another technology we are using that a needs a even more "up-to-date" browser).

**Comment by mgwalker** [comment]
To be honest, it feels weird to me to create a new thing that has to support a 6-year-old browser (no new features or substantial changes were made after initial introduction) that isn't even supported by its maker anymore.  Edge, Chrome, and Firefox all have the advantage of continuous updates and upgrades to the latest standards.  I'm wondering if this might be an opportunity for CMS to nudge the states to using one of these modern browsers, at least as an alternative (I assume some of them _have_ to use older versions of IE for legacy systems reasons; the same reasons Microsoft has promised to support - but not modernize - IE11 essentially indefinitely).

**Comment by jeromeleecms** [comment]
For the MVP, do you all have a gut feeling on where we can make the cut off? If 80% of users a good benchmark (http://gs.statcounter.com/browser-market-share/desktop/united-states-of-america <- this is the first one that popped up in Google that had some stats to look at)? I also noticed that in user testing, some people had the other browsers, but defaulted to using IE. 

Regarding nudging states to using modern browsers, sounds like this a battle for our colleagues in USDS. If their playbook (1.0, 2.0 or future versions) has minimum browsers standards for Federal government websites, we can also defer to their guidance on how we based our requirements.

**Comment by brendansudol** [comment]
yes, would love to nudge people to use a better browser, and there are many tasteful ways to do this

for example,

![image](https://user-images.githubusercontent.com/1060893/42462639-d8271c78-8371-11e8-8a84-96178d81527c.png)

**Comment by brendansudol** [comment]
![image](https://user-images.githubusercontent.com/1060893/42462722-0c0da2e6-8372-11e8-8a60-919d266b15ec.png)

**Comment by mgwalker** [comment]
The [analytics.usa.gov](https://analytics.usa.gov/health-human-services/) dashboard is also a good source for checking browser use stats, and it shows a breakout by IE version as well - fewer than 2% of all HHS website visitors are on IE versions lower than 11, for example.  So if we target IE 11, Edge, Chrome, Firefox, and Safari (have to support Safari if we're supporting mobile), it looks like that gets us to ~94%.  :)

**Comment by brendansudol** [comment]
i think this issue may not be closable @jeromeleecms and perhaps we should open a new one re: adding a "please upgrade" banner/message as well as documenting exactly which browsers we're supporting?

**Comment by jeromeleecms** [comment]
As far as I can tell, Firefox is rending properly in the current deploy. IE fixes look good.

Will spin up a new issue for the please upgrade banner/message.
