### ISSUE TITLE
Build out the contract attachment section in Contract Resources

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#764]
Refer over to #736 for the designs.

The drop-down options are: 
- Request for Procurement
- Contract
- Contract Amendment

Selecting the doc type is required before selecting the file.

**Comment by lauraponce** [comment]
#801 is a more up to date version of this task. @jeromeleecms should we close this dev task out since 801 covers this work?

**Comment by jeromeleecms** [comment]
I concur. :)
