### ISSUE TITLE
Add in all of the nav items into the left sidebar

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#765]
Navigation items that should go in the left nav:

- **State Profile Contact Information**
- **Program Summary**
-- Program Overview
- **Results of Previous Activities**
-- Prior Activities Outline
-- Actual Expenses
- **Program Activities**
-- Activity List
-- Activity 1
-- Activity 2 etc etc
- **Activity Schedule Table**
-- Summary Schedule Table
- **Proposed Budget**
-- Summary Budget Table
-- Federal Share by FFY Quarter
-- Incentive Payments by FFY Quarter
- **Assurances and Compliance**
-- Federal Citations and Justification
- **Executive Summary**
-- Executive Summary Overview
-- Program Budget Table
- **Certify and Submit**
-- Submit APD

**Comment by brendansudol** [comment]
done via https://github.com/18F/cms-hitech-apd/pull/779
