### ISSUE TITLE
Make the content consistent with second person or third person

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#775]
Throughout the instructions in the app, we use second person (e.g. "you should do this") and third person (e.g. "states should do this"). We should review this and decide on which one we want to go with so it reads easier. 

Third person feels the most formal, and I think we wanted to be a little friendlier than that, so I feel like second person is the probably the way to go? Will leave this up to the experts though: @quarterback @NAretakis @jeromeleecms 

### This task is done when...
 - [x] decision has been made on second vs third
 - [x] content has been updated/revised throughout the app for consistency 
- [x] Wiki has been updated (https://github.com/18F/cms-hitech-apd/wiki/Content-guide)

**Comment by jeromeleecms** [comment]
I like the idea of being tonally consistent with the help text. 

@quarterback Are you thinking something like this (removing the familiar text):

Old:
In this section, provide information about relevant state contacts. You will only need to input this information once. If we have information on record, it will be listed below. Ensure the director's name and office address are listed correctly.

New:
In this section, provide information about relevant state contacts. This information will only need to be entered once. If this information on record, it will be listed below. Ensure the director's name and office address are listed correctly.
