### ISSUE TITLE
Revise Key Cost Allocation instructions

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#776]
The instructions for the Key Cost Allocation subsection are a little intimidating and could be broken down into multiple paragraphs and could use some wordsmithing to make them easier to follow. 

Here's the text:

> As specified in OMB Circular A‐87, a cost allocation plan must be included identifying all participants and their associated cost allocation to depict non‐Medicaid activities and non‐Medicaid FTEs participating in this project, if any. HITECH cost allocation formulas should be based on the direct benefit to the Medicaid EHR Incentive Program, taking into account State projections of eligible Medicaid provider participation in the incentive program (leveraging actual data/experience as deemed appropriate). Cost allocation must account for other available federal funding sources, the division of resources and activities across relevant payers, and the relative benefit to the State Medicaid program, among other factors. Ensure cost allocations involve the timely and insured financial participation of all parties. States should demonstrate that other payers who stand to benefit are contributing their share, ideally from the beginning of the program/activity/service for which funding is being requested.

Screenshot of that section in the app:

![screen shot 2018-07-05 at 5 31 04 pm](https://user-images.githubusercontent.com/21222704/42354075-25d5aca6-8079-11e8-9c6e-db15698471eb.png)

### This task is done when...
 - [ ] Content has been made closer to plain language
 - [ ] @NAretakis and @jeromeleecms have reviewed/approved it

**Comment by quarterback** [comment]
I didn't rewrite this, because I wasn't sure if there were legal reasons this content needed to be this way. @NAretakis @jeromeleecms can confirm whether that's the case or not. If it's okay to revise, then I'll revise entirely. (But then, that'd apply to other standards and conditions content in other parts of the application, too.)  cc: @lauraponce

**Comment by jeromeleecms** [comment]
@quarterback For now, how about doing some reformatting and some general language refinement for tonally consistency? The APD template has it broken out with bullets.

![image](https://user-images.githubusercontent.com/34279968/42392267-1415a014-8107-11e8-8ded-5f996252f5c3.png)
