### ISSUE TITLE
Collapse subsections by default

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#781]
When you first load the app, the subsections should all be collapsed by default. The active section/subsection should be expanded with the yellow bar indicator next to it.

Each section should have the carrot next to it indicating there is more in that section.

e.g. if Activity 1 was open, this is what it would look like:

![screen shot 2018-07-06 at 10 10 33 am](https://user-images.githubusercontent.com/21222704/42391621-d363c32c-8104-11e8-9dc9-f2757941546d.png)

**Comment by jeromeleecms** [comment]
Reference #758

**Comment by mgwalker** [comment]
I misunderstood this one completely.  I thought it was about expanding a page section/subsection when the user clicked on its corresponding sidebar link.  😬

So is the intent that the sidebar should unfurl as the user navigates?  I.e., is this right?

1. the user comes to the APD page
2. the user clicks the "Program Activities" link in the sidebar
3. the "Program Activities" sidebar children expand, and the page scrolls to the "Program Activities" section
4. the user scrolls down to "Activity List" and the sidebar updates to highlight the "Activity List" link
5. the user scrolls down to "Activity 1" and the sidebar updates again, accordingly
6. the user scrolls furiously past the activity to the "Activity Schedule Summary" section; the sidebar collapses the "Program Activities" section, expands the "Activity Schedule Summary" section, and updates the highlight

I know I'm probably overthinking this.  😄  I worry a little bit about overriding user action - like, if they click to expand a sidebar section, should we ever programmatically close it?  If clicking a section link expands, should it also navigate?  (I can imagine a user getting annoyed by that, if they're just trying to see what the subsections are and the page suddenly scrolls away.)

I'm 100% on board with having the sidebar highlighting update dynamically based on where they are on the page, but I'm a little concerned about dynamically expanding/collapsing sections that way.

**Comment by lauraponce** [comment]
@mgwalker I'm glad you're thinking this through because you're bringing up some great points that I didn't consider! 

What if _just_ the arrows (with a comfortable enough click area) next to the main sections in the nav were clickable to expand the subsections below? That way people could click the text to go to the section, and/or they could click on the arrow to take a peek at what all is in that section without getting annoyed by the page jumping around.

Agreed –– I don't think we should ever collapse the sections in the nav for them because if they expanded something, it was probably for a reason.

Does that seem like it would cover all the bases and logically work?

**Comment by mgwalker** [comment]
That makes sense!  Should be able to get that knocked out pretty quickly.  Thank you!  😄

**Comment by mgwalker** [comment]
Should clicking/navigating to a section also expand it?

**Comment by lauraponce** [comment]
Hm, good question. I don't think it should –– it feels right the way you have it built out and working right now.
