### ISSUE TITLE
When calculating budget tables, round values to whole dollars

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#788]
CMS expects dollar values to be in whole dollars, so when we do calculations to fractional values, we need to round them.  Currently we round the dollar amounts when we display them, but they are stored with up to two decimal places.

@jeromeleecms Should we do a standard rounding operation?  Always round up?  Always round down?

### This task is done when...
 - [ ] data model is updated to store whole numbers
 - [ ] if necessary, calculations are updated to round to whole numbers
   - updating the data model may actually be sufficient - let the database do the rounding for us!

**Comment by jeromeleecms** [comment]
We generally start there, but most importantly, the numbers need to add up. We find this is tough when evaluating the 90/10 calculations and then transferring the 90% share and lining that up with the quarterly breakdowns. In many APDs, State's will ignore the standard rounding rules just to get things to line up (normally it's just a few dollars), but it's a pain point to have to check.

Let us know how big of a lift this is and we can evaluate the precision or how much flexibility we need on this.

**Comment by mgwalker** [comment]
Hmm.  Getting the numbers to add up could be quirky.  For example, if you have $25 for the year, that's $6.25 per quarter.  So we'd have to wiggle with it to get $6, $6, $6, and $7, instead.

It's doable, I'm just not certain how to do it in a reusable way off the top of my head.

We'll probably have to ask about edge case rules as we go along, too.  I'm imagining a case where the FFP is 50% and the total cost is $25.  Then the federal and state shares are each $12.50.  Who gets stuck with the extra 50¢?  For quarterly payments, it seems less of an issue - the state would be shorted at most $1 for the quarter, and I find it unlikely that's going to break anyone's budget.  But even so, should we frontload that dollar into the first quarter (i.e., $7, $6, $6, $6 instead)?

Level of effort shouldn't be outrageous, but probably a day, maybe a day and a half, just because of the number of places it happens and all the test code that will need to be updated.

**Comment by jeromeleecms** [comment]
Exactly the pain the author of APDs have to go through! I think your case fits into the discussion about using % vs actual numbers for the quarterly allocations we've had #756.

In your example, I've noticed that state's will give the $1 to the Federal in one line item and then $1 to the State in another line item, so it loosely evens out. Because CMS knows that rounding can be challenging in the APD, we do give the states some leeway in their submission to account for these type of situations.

**Comment by mgwalker** [comment]
Incidentally, here's some prototype code that naively handles rounding across percentages without losing remainders:

```js
const spread = (num, percentsIn) => {
  // convert to 0-1...  probably should just pick one range or the other rather than try to guess
  const percents = percentsIn.map(p => (p > 1 ? p / 100 : p));

  const out = [];
  let remainder = 0;
  percents.forEach(percent => {
    // roll in any previous remainders
    const value = num * percent + remainder;
    remainder = value - Math.floor(value);

    if (remainder > 0.5) {
      // if the cumulative remainder to this point is over half, round up
      out.push(Math.ceil(value));
      // don't throwaway leftover remainders, or we might accidentally
      // roll up a few extra times
      remainder -= 1;
    } else {
      // otherwise round down
      out.push(Math.floor(value));
    }
  });

  return out;
};

// Spread 252,352 across 17%, 9%, 31%, etc.
console.log(spread(252352, [17, 9, 31, 3, 16, 24]));

// Outputs:
//  42900, 22712, 78229, 7570, 40377, 60564 ]
```

|Percent|Actual|Computed|Cumulative remainder after
|---|---|---|---|
17%|42899.84|42900|-0.16
9%|22711.68|22712|-0.48|
31%|78229.12|78229|-0.36|
3%|7570.56|7570|0.2|
16%|40376.32|40377|-0.48|
24%|60564.48|60564|0|
**Total**|252352|252352

**Comment by jeromeleecms** [comment]
@mgwalker I feel like I was set up for this... :1st_place_medal:

**Comment by brendansudol** [comment]
is this done now with the recent budget refactor @mgwalker?

**Comment by mgwalker** [comment]
No, I intentionally left this out of that refactor so the tests wouldn't change.

**Comment by mgwalker** [comment]
Okay, this is actually a lot, lot harder than I thought it would be.  From a purely mathematical perspective, it is impossible to guarantee that we can always round everything to whole numbers such that everything still sums correctly across both rows and columns simultaneously.  That is, if you've got some amount of money and you need to spread it across a table like this:

| |**Q1 13.92%**|**Q2 26.27%**|**Q3 47.3%**|**Q4 12.51%**|**Subtotal**|
|---|---|---|---|---|---|
|**FY1 32.85%**|
|**FY2 15.34%**|
|**FY3 41.62%**|
|**FY4 10.19%**|
|**Subtotal**|

For $100 (or any other exact power of 10, for that matter, and probably lots of other numbers), there is no way to do the whole table - you can either have the rows sum up or the columns sum up, but not both.  There are various techniques and all of them come up 1 or 2 dollars off, and there's no way to redistribute the numbers without breaking another sum somewhere else.

If getting these numbers rounded across the whole table such that they sum up perfectly is critical, then I propose we tweak the total that we're spreading around by $1 over and over until we get a table that works.  E.g., since $100 doesn't work, try $99. Then try $101.  Then $98.  $102.  $97.  $103.  $96.  $96 works, so that'd be what we stick with.  We could constrain it so that it just accepts a wrong table if there's not one that works within some threshold (say, within $10, or maybe within some percent of the original total).

(For a more realistic example, $1,975,352 can't be spread perfectly across that table, but $1,975,347 can.)

Alternatively, we just accept that it can't always be perfect and have a couple of places where it's off by a dollar or two.  (The most it can be off is by one dollar per row *or* column in the table.)

**Comment by jeromeleecms** [comment]
Lets' talk through this - I don't quite get why the Federal Fiscal Years need to broken out by Percentage. Each FFY should be it's only quarterly breakdown first, let the numbers round to that and then do the subtotals based on the calculations by row.

**Comment by mgwalker** [comment]
Ah, right, this whole problem is introduced because of the "other funding" amount.  In the summary budget table, we calculate what percentage of the total activity cost comes from each cost category (personnel, contractors, and non-personnel) so that we can deduct the other funding amount proportionally across the expense categories.  E.g., from the comments in the code:

```js
     *    other funding is $200
     *    the total cost is $1,000
     *    contractor costs are $500
     *    contractor costs is 50% of total costs
     *    so other funding for contractor costs is 50% * $200 = $100
```

As a result, the sums across expense type within a fiscal year _*may not*_ sum up exactly.  That's where this rounding-across-rows-and-columns thing came from - it introduced percentages in a second dimension and got everything honked up.  😄

**Comment by jeromeleecms** [comment]
OK, maybe i'm still missing this.. but what if we remove a level of calculation: 

Instead of trying to calculate the summary budget table with %, can we just add the totals by each activity? So in this example, you would have $400 in remaining contractor costs. At 90/10, that would be 360/40. 

In the summary budget table, you would add the $360 to the federal share/$40 for the state share and add those to get the total (not the other way around -- if I'm understanding how the totals are currently calculated).  Repeat across all activities. 

Getting back to the idea of each activity as a mini-apd, this is actually a more accurate way to calculate totals because the Federal and state totals would be calculated at the activity level. The resulting table would then show a federal and state share that may not be exactly calculated at 90/10 (may have to put this warning text about that), but represents an accurate 90/10 breakdown by activity. 

When we do the quarterly breakdowns, divide that total by 4 and push the dollar around (as you stated). The state can/should have the ability to edit the quarterly breakdowns anyway.

PS. Also let me know if I'm totally missing the boat here.

**Comment by mgwalker** [comment]
I think you're right.  I see what was confusing me.  The federal and state shares do not sum up to the total, because the total does ***not*** subtract out "other funding," but the federal and state shares columns do.

![screen shot 2018-10-12 at 5 16 13 pm](https://user-images.githubusercontent.com/1775733/46896420-95220c00-ce42-11e8-8574-7f517f9b6d42.png)

Should we show the Medicaid total somewhere to make it clear that the state/federal shares do sum up to something?  😛

**Comment by jeromeleecms** [comment]
For the MVP, having it at the activity level is fine. For purposes of review, the most critical part is that each activity has complete funding / properly cost allocated. At the end of the day, we can only approve funding to support Medicaid -- so the summary budget table represents what we can approve (if the APD is approved).

If we want to add other funding in the summary budget table down the road, let's put that in "future enhancements."

**Comment by mgwalker** [comment]
> [...] the summary budget table represents what we can approve [...]

So should the totals columns have the "other funding" already subtracted?  E.g., given this:

|State personnel|$1000|
|---|---|
|Contractors|$1000|
|Non-personnel|$1000|
|Other funding|$1000|

should we produce a table that looks something like this:

|Cost|Total|Federal|State|
|---|---|---|---|
|Project state staff|$667|$600|$67|
|Contracted resources|$667|$600|$67|
|Non-personnel|$666|$600|$66|
|Subtotal|$2000|$1800|$200|

The reason I'm hung up on this is that ***right now*** the table is a little confusing because it shows the totals without subtracting out "other funding," but it shows the state and federal share with "other funding" subtracted.  The result is that if there's "other funding" in the cost allocation, then `federal share + state share` *does not* equal the total shown in the table.

That is, the current table looks like this:

|Cost|Total|Federal|State|
|---|---|---|---|
|Project state staff|$1000|$600|$67|
|Contracted resources|$1000|$600|$67|
|Non-personnel|$1000|$600|$66|
|Subtotal|$3000|$1800|$200|

**Comment by jeromeleecms** [comment]
What if we labeled this section like this: 

![image](https://user-images.githubusercontent.com/34279968/47041262-3360eb00-d13d-11e8-97b8-49b1f4c1b19c.png)

Then the total represents the Medicaid share ONLY and the "other costs" are not included directly in this table (then the totals would add up and make sense!). The help text could reiterate that the costs only represents the Medicaid share. If we need to summarize other costs, we could add another row labeled "Other costs" but that is sounding like a "future enhancement."
