### ISSUE TITLE
Summary budget table: Toggle between Cost Allocation and Activity Summary

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#794]
In user testing, States asked for a "+" button to see a summary of items by activities (#738). In some initial discussion on the summary budget table (#404) we had discussed including a breakout of cost allocation for the summary table. 

This proposed functionality would allow the user to switch between a summary view and a cost allocation view.

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
 ** don't forget to fill out the LABEL, MILESTONE, and PROJECT sections before submitting (then delete this line) **

**Comment by NAretakis** [comment]
Closing this one, as #991 has the sketches for this, I think.
