### ISSUE TITLE
Modeling contracts that span multiple activities

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#796]
Modeling the experience for contracts that span multiple activities, what should this experience look like.

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
 ** don't forget to fill out the LABEL, MILESTONE, and PROJECT sections before submitting (then delete this line) **

**Comment by quarterback** [comment]
#801 already has the design of the contract experience wireframe, this would just be an extension of that.

**Comment by NAretakis** [comment]
Right. This would be a way to potentially link a contract that is already uploaded, to another "contractor resource activity". Not really sure how big of a need this is, but I believe from testing it was a state that asked for the ability to just identify a contract already uploaded if it spans multiple activities.

**Comment by quarterback** [comment]
Here's an idea for this use case? A dropdown could also be possible, where it'd populate with the contractor resource activities you've inputted already. Could potentially be too big a solution for the potential problem, but an idea nonetheless. 
<img width="713" alt="screenshot 2018-07-25 11 32 13" src="https://user-images.githubusercontent.com/4461062/43210897-569aaca8-8ffe-11e8-86da-96530f01a133.png">

**Comment by NAretakis** [comment]
Yes, this works, with the "Other Activities Box" being the names of the activities from the "Activity List" section. However, the more I think about this, the more potentially messy it becomes for a reviewer to try and piece this together. Do you think it is just cleaner to have a contract linked exclusively to an activity? Then, if a contractor is doing multiple things under the contract, all of those "things" should be under the single activity's description.

**Comment by quarterback** [comment]
@NAretakis I do think it'd be cleaner to a contract linked exclusively to an activity. I think the cognitive load it'd create is probably worth more trouble than the potential benefit. Especially for a MVP. If it turned out to be something people were doing down the road, you'd be able to stitch an experience for this together based on feedback.

**Comment by NAretakis** [comment]
I think we can close this, and then potentially revisit it the need arises.
