### ISSUE TITLE
Design Pattern is established for Users Resuming Editing of APDs

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#799]
When a user resumes editing an in progress APD, the system will provide proper guidance to the user about resuming edits.

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
 ** don't forget to fill out the LABEL, MILESTONE, and PROJECT sections before submitting (then delete this line) **

cc: @quarterback

**Comment by jeromeleecms** [comment]
@lauraponce I setup a new milestone and issue for this because the "APD update" milestone talks about updating an existing approved APD. Please take a look and update this with more details.

**Comment by lauraponce** [comment]
@NAretakis @jeromeleecms checking in to see if we still need this issue? I _think_ we talked about this when we mapped out the flow earlier this week and landed on that if they click from the dashboard, it would take them to the specific place. e.g. if they click respond to a comment, it takes them there, if they just click on the APD, it takes them to the top where they can navigate to edit. 

Is there more to this that we need to think through and/or wireframe?

**Comment by jeromeleecms** [comment]
For now, let's push to a future enhancement and close out this milestone so we can focus on the rest of the app. 

The rest of your comment is spot on :1st_place_medal: -- the design pattern and user experience you described is good, but maybe to fancy for MVP. As we discussed on stand up today, let's just put the user at the top of the APD for now.

**Comment by NAretakis** [comment]
closing this in favor of design team coming up with proper design issues for this epic.
