### ISSUE TITLE
Capture screenshots of Jerome's initial prototype

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#8]
Let's get some screenshots of the major flows, for the sake of documentation.

Add them to [Google Drive](https://drive.google.com/drive/u/0/folders/1QN8d4_an8GGfWUvGIKuT0vZGbBYFA7tz).

**Comment by jeromeleecms** [comment]
Is this separate from uploading the prototype files to GitHub after #14 ? Happy to do both if it meets different needs for the team.

**Comment by nkkl** [comment]
I think this can be one and the same – as long as the team can view the screens. So uploading a broken prototype wouldn't be that helpful, but a working prototype would be fine.
