### ISSUE TITLE
Build out additional sections in Contract Resources section

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#801]
This covers design work from #755 (and #736 which is now out of date because of 755).

- Update the Contract Resources section to have the addition of attachments and hourly resources. 

Here's the updated wireframe:

![screen shot 2018-07-12 at 3 10 57 pm](https://user-images.githubusercontent.com/21222704/42663359-0d9c63f2-85ea-11e8-8948-7fe5b1dcb20e.png)

Refer to #755 for the conversations that led up to this design.

**Comment by lauraponce** [comment]
@jeromeleecms I'm not sure if I tagged this with the right milestone, can you check to make sure this is in the right place?

**Comment by jeromeleecms** [comment]
@mgwalker Responding to your comment from #764. If they enter the hourly rate and hours, let's calculate it for them. I think it would be an edge case where they would request money beyond what that calculation would yield.

**Comment by quarterback** [comment]
For #796: thoughts on adding the other activities that the contract covers? Whether that's a list of the other activities with check boxes you select, a drop down or simply for MVP purposes, a text field to list them. Realize(d) the two issues are related.

**Comment by NAretakis** [comment]
no #796 was it.

**Comment by jeromeleecms** [comment]
Cleaning up board and linking issues. Dev has split this into multiple, bite sized components.

Reference: 
#837 (merged)
#839 
#840

**Comment by brendansudol** [comment]
(closing in favor of smaller issues above)
