### ISSUE TITLE
Refine the log in experience

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#811]
The login page should include:

- Content about logging in
- Login button
- Forgot username or password flow
- 'Don't have account' CTA to email Nick or Jerome

**Comment by lauraponce** [comment]
Log in page flow:

<img width="324" alt="screen shot 2018-07-24 at 5 57 58 pm" src="https://user-images.githubusercontent.com/21222704/43173740-4f4cc0aa-8f6b-11e8-9c11-9f347eeea84e.png">

If they click forgot password:

<img width="328" alt="screen shot 2018-07-24 at 5 58 05 pm" src="https://user-images.githubusercontent.com/21222704/43173746-53564590-8f6b-11e8-83cc-6f9e869ab775.png">

<img width="311" alt="screen shot 2018-07-24 at 6 02 56 pm" src="https://user-images.githubusercontent.com/21222704/43173857-d7c76476-8f6b-11e8-9167-bac1a07ecd8e.png">

If they click need an account:

<img width="337" alt="screen shot 2018-07-24 at 5 58 56 pm" src="https://user-images.githubusercontent.com/21222704/43173751-59d9d54e-8f6b-11e8-9ce8-e4fba6539ac2.png">

Clicking the X would just go back to the initial sign in screen.

@NAretakis @jeromeleecms, how does this seem?

**Comment by jeromeleecms** [comment]
I preferentially like a separate screen for password recovery (less options for users, but certainly can be convinced otherwise!): 

![image](https://user-images.githubusercontent.com/34279968/43180636-fd5470ae-8f8d-11e8-8200-4077df9248b5.png)

For new user accounts, I would suggest we simplify the process.. when a user clicks "I don't have an account," can it directly open an email to Nick/I for now? Down the road, it may be less of an issue if/once we incorporate EIDM into the system.

**Comment by lauraponce** [comment]
@brendansudol is it possible to create a link that opens up an email addressed to Nick and Jerome with the email content in there? 

@jeromeleecms suggested that the "I don't have an account" link would just open up an email which seems like a good idea for the MVP, but having some content in there saying something along the lines of, "I don't have an eAPD account and would like to have one set up for me" could help them understand what they should ask for.

**Comment by lauraponce** [comment]
@jeromeleecms here's an option with the password reset on a separate screen, I think either way works. What do you think? 

<img width="345" alt="screen shot 2018-07-25 at 3 06 21 pm" src="https://user-images.githubusercontent.com/21222704/43230226-527b5726-901c-11e8-81cc-11139d515fef.png">

**Comment by jeromeleecms** [comment]
I like the separate screen. 

For the "I don't have an account link" -- would "Request a New Account" or "Email For A New Account" be descriptive enough?

**Comment by jeromeleecms** [comment]
Yes - looks great! If we can, the email should have some generic language in the body about the user’s name and email. 

Maybe @quarterback can provide some language for the email?

**Comment by jeromeleecms** [comment]
Thanks for asking 👍

I’m thinking generic email body text for users who need to have new accounts created for them and what information they need to provide to get the basic account setup. 

Does that clarify?

**Comment by quarterback** [comment]
Yes! I'll take care of this tomorrow morning.

**Comment by lauraponce** [comment]
@quarterback checking in on this one — are we good to close or is this still a to-do that we should bring into the refinements milestone?

**Comment by quarterback** [comment]
@lauraponce we should bring this over into this milestone. A quick sync this week about how we'd want to implement this (are we letting people create accounts already, etc.) but yeah, then I can push a PR and we can close it.

**Comment by quarterback** [comment]
@lauraponce nevermind i re-read this. Let me paste the email copy in this thread and we can close it. i moved it to this milestone.

**Comment by quarterback** [comment]
My sense is no one should be reaching this application that isn't connected to CMS and has some semblance of what this is about. So I'm not writing text that will consider the possibility that the account was created in error (barring having it sent to the wrong email, etc.) 

Alternatively, it could be that account creation isn't automated so we can filter out or confirm submissions ahead of time. Not sure how in-depth this will be. Also, we need to fill in what information we need, I put phone # as a way to verify, but if that's not necessary, then ignore.

**Request A New Account Creation Text**

To request or create a new eAPD user account, provide the following details:
Name:
Phone number:
Email address:
[submit]

You've successfully submitted an eAPD user account request. An email with more details about logging in to the eAPD application will be sent to the email included in your submission.

**New Account Confirmation Email**

An eAPD user account was created for you. 
To login, visit [https://hitech-apd.app.cloud.gov/login]:

User account details
User name: [your email]
Password: [generated password]

If you have questions, contact [catchallemail at cmsteam.moop]

**Comment by mgwalker** [comment]
Not sure if it's related to this issue, but getting ATOed will almost certainly require that we add a government "system use" banner.  My recommendation is to get approval to do something like cloud.gov, where the initial banner text is plain and simple, but with an option to expand to the full text:

https://login.fr.cloud.gov/login

Here's the Github issue where the cloud.gov team worked through getting the system use banner in place and approved:  https://github.com/18F/cg-uaa/issues/15

**Comment by lauraponce** [comment]
Closing this out as obsolete.
