### ISSUE TITLE
Wireframe first time log in experience

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#813]
When a state user logs in for the first time, we need to capture some basic information from them.

This page should include capturing:

- Name
- Phone number
- Email
- Save and next button (drops them into dashboard)

**Comment by quarterback** [comment]
For the MVP could this be integrated with the first page that we have now, so someone saw this screen if they don't have an APD already saved? Or did we want to use a different initial screen? In any case, here's a basic concept using the existing style.  <img width="518" alt="screenshot 2018-07-25 11 13 07" src="https://user-images.githubusercontent.com/4461062/43209867-b7afa262-8ffb-11e8-9ca4-595039e8d776.png">

**Comment by quarterback** [comment]
@lauraponce @jeromeleecms

**Comment by lauraponce** [comment]
Here's what this could look like in the matching log in page style:

<img width="632" alt="screen shot 2018-07-25 at 3 16 59 pm" src="https://user-images.githubusercontent.com/21222704/43230632-dcea9844-901d-11e8-846c-ec76fd32079c.png">

The Save and Continue button would drop them off at their dashboard. We should be able to autofill their email based on what they used to log in, but they would be able to edit that if needed.

Do we need to let them know why we need their phone number or will they know what to expect with that? @NAretakis @jeromeleecms

**Comment by NAretakis** [comment]
This is good. Clean and simplw.

**Comment by lauraponce** [comment]
Created #853 for the development of this
