### ISSUE TITLE
Wireframe the submitted experience

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#814]
After a state user submits their APD, they will see a submission confirmation page.

This page should include:

- Thank you for submitting messaging
- Confirmation that it's been submitted
- What they can expect next
- Link to go to the dashboard

**Comment by lauraponce** [comment]
@jeromeleecms here's a v1 of what this message could be. Let me know what you think:

![screen shot 2018-07-20 at 12 16 19 pm](https://user-images.githubusercontent.com/21222704/43020944-bbf6c528-8c16-11e8-809d-9ce3b6a7b1f9.png)

Will need @quarterback's :eyes: on the content here

**Comment by lauraponce** [comment]
How does this seem for the flow?

When they get to the certify and submit section, they see this. I think we can mitigate the need for the undo button with some stronger messaging _before_ they submit to get them to think about it before they click the button rather than after.

![screen shot 2018-07-20 at 5 43 18 pm](https://user-images.githubusercontent.com/21222704/43030413-7af68954-8c44-11e8-8d19-d82e51c5c9d9.png)

Once they type their name, the button becomes active

![screen shot 2018-07-20 at 5 43 23 pm](https://user-images.githubusercontent.com/21222704/43030415-8153a872-8c44-11e8-848b-00b66858cd57.png)

And once they click Submit APD, they see this confirmation message which would just appear in place (I didn't picture a specific animation for it, but let me know if you have thoughts).

![screen shot 2018-07-20 at 5 39 41 pm](https://user-images.githubusercontent.com/21222704/43030384-2b252eb2-8c44-11e8-85f3-9398ae93b599.png)

**Comment by jeromeleecms** [comment]
I like the flow. The animation piece was just a garnish. For the MVP, let’s just forget it :)

**Comment by lauraponce** [comment]
#833 for the development task
