### ISSUE TITLE
Double-check capitalization throughout the app

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#821]
There are several places with some rogue capitalization so we're probably in a good place to do a full pass through all of the content to ensure we're being consistent with using sentence case. 

- [x] Remove all caps instances. There are a few of them in the help text sections
- [x] Double-check for rogue capitalization
- [ ] Sentence case is being used where possible and title case is used where necessary

**Comment by quarterback** [comment]
rogue capitalization is my new band name, @lauraponce

**Comment by quarterback** [comment]
PR #828

**Comment by quarterback** [comment]
@lauraponce My last PR should have gotten (almost) all of them, but I will take another pass and if you see anything after that, just flag for it for me and I can fix it.
