### ISSUE TITLE
Apply sticky header to all sections

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#826]
Dev implementation issue for #758

**Comment by lauraponce** [comment]
How does this seem for the interaction with the sticky header? @NAretakis @jeromeleecms @brendansudol 


![screen shot 2018-07-24 at 9 53 59 am](https://user-images.githubusercontent.com/21222704/43153967-9861a6f0-8f27-11e8-81e2-930d62d2fd8d.png)

Once you scroll past main section (e.g. Submission):

![screen shot 2018-07-24 at 9 54 15 am](https://user-images.githubusercontent.com/21222704/43153968-99ed21fc-8f27-11e8-80b4-f048c83fb31a.png)

Once you scroll past subnav (e.g. Certify and Submit)
![screen shot 2018-07-24 at 9 54 28 am](https://user-images.githubusercontent.com/21222704/43153970-9b5c4950-8f27-11e8-9932-9d5450930410.png)

**Comment by NAretakis** [comment]
Perfect! Ship it!
