### ISSUE TITLE
Prototype personnel / budget flow

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#83]
- [x] Pick between personnel and budget
- [ ] Work with Nick to scope and understand
- [ ] Push a prototype experience, rough first pass design

**Comment by nicoleslaw** [comment]
We decided to start with `Personnel`. I am going to prototype the larger content flow in the meantime via #91

**Comment by nicoleslaw** [comment]
@brendansudol Would it be helpful for me to prototype the words while you're taking a pass at the interactions for this?

**Comment by nicoleslaw** [comment]
Closing in favor of our bigger tasks/milestones!
