### ISSUE TITLE
Refine the help text styles

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#830]
The current help text treatment doesn't match our current styles and needs some refinement.

<img width="649" alt="screen shot 2018-07-17 at 10 54 22 am" src="https://user-images.githubusercontent.com/21222704/43017400-d53655a0-8c0a-11e8-9816-fc8ceecb046b.png">

**Comment by lauraponce** [comment]
A couple options for the help text building off the style @brendansudol implemented that use our color pallete: ![screen shot 2018-07-30 at 10 27 26 am](https://user-images.githubusercontent.com/21222704/43412894-6127da0e-93e3-11e8-8e2a-246114b1a04d.png)

![screen shot 2018-07-30 at 10 28 27 am](https://user-images.githubusercontent.com/21222704/43412899-63b24264-93e3-11e8-93b8-4790d6d1b8a5.png)

Any preference on yellow vs blue, @NAretakis? I think either one would work well. The yellow seems a bit more attention-grabbing, but it's mute enough that shouldn't compete with the call to action buttons. The blue seems more like "FYI here is some more information," and the yellow is more like "hey read this!"

**Comment by NAretakis** [comment]
I prefer yellow. Likewise, how hard it is it to bold or add a list to this? Some of the helptext is a little long, so it could benefit from a list or header (bolded) format.

**Comment by lauraponce** [comment]
It definitely works with bolding and lists. If any of the help text sections start to get long, we can explore options for opening/closing the help text box. ![screen shot 2018-07-30 at 12 26 38 pm](https://user-images.githubusercontent.com/21222704/43418753-cb52e36e-93f3-11e8-8807-c81e3b61e791.png)
