### ISSUE TITLE
Build out the submitted flow

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#833]
Here is the flow: 

![screen shot 2018-07-20 at 5 43 18 pm](https://user-images.githubusercontent.com/21222704/43091915-4544f066-8e60-11e8-8f85-e013a0199dd1.png)

![screen shot 2018-07-20 at 5 43 23 pm](https://user-images.githubusercontent.com/21222704/43091913-44ebe4b2-8e60-11e8-9082-5330d040cd35.png)

![screen shot 2018-07-20 at 5 39 41 pm](https://user-images.githubusercontent.com/21222704/43091916-455e56be-8e60-11e8-8fb7-f7f6bacb5a76.png)

#814 has more of the design details

**Comment by mgwalker** [comment]
Should the "thanks for your submission" bit be there if they open a submitted APD too?

For @NAretakis @jeromeleecms, do you want to capture their name just as part of the submission?

**Comment by NAretakis** [comment]
Yes, I think the "thanks" should be there every time a submission is sent to CMS (initial submission & open/updated submission).

I don't think we need to capture the name, as we already have it as the Point of Contact field. This was just something to make sure they really meant that they wanted to submit (like a signature field).

**Comment by mgwalker** [comment]
I believe this one was closed by #990 and #994

**Comment by NAretakis** [comment]
Seems good to me. Closing unless @mgwalker thinks there is more to do.
