### ISSUE TITLE
Update Respond buttons to be View buttons 

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#841]
After a conversation with @jeromeleecms and @NAretakis, it makes more sense to have the buttons in the statuses section take people to view their request since the action items are above. We should change the 'Respond' buttons to be 'View' buttons so that it matches this: 

![screen shot 2018-07-24 at 11 09 13 am](https://user-images.githubusercontent.com/21222704/43157486-04156454-8f32-11e8-8026-db743e908fb0.png)

**Comment by jeromeleecms** [comment]
Related to #722
