### ISSUE TITLE
Expand existing content style guide

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#846]
The existing style guidelines in the wiki are a bit thin. We need more granular details, explaining when to use what, and also a better explanation of the various acronyms.

### This task is done when...
 - [x] A style guide is developed & published.
-  [x] Merge tone & voice guidelines (updated) into same document.

**Comment by quarterback** [comment]
Existing style guide in the wiki: https://github.com/18F/cms-hitech-apd/wiki/Content-guide

**Comment by quarterback** [comment]
We finally have a live glossary https://github.com/18F/cms-hitech-apd/wiki/Glossary-of-Acronyms (this is a silly thing to be excited about, but it's been on my mind for a long time.)

**Comment by quarterback** [comment]
This section is updated. It's a living document so changes will be inevitable. Feel free to take a look @NAretakis @jeromeleecms and let me know if you see something I should add.

**Comment by NAretakis** [comment]
Solid work! Is the content page linked anywhere, or do you want to throw it in the sidebar?

Glossary FTW.

**Comment by quarterback** [comment]
It's linked to the sidebar, yes. The glossary is too, even though it's already linked inside of the content guide too.

**Comment by NAretakis** [comment]
Boom.
