### ISSUE TITLE
Build out the withdrawal experience

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#849]
When a user clicks back into a submitted ADP, they will see this in the Submission section:

<img width="426" alt="screen shot 2018-07-25 at 8 44 53 pm" src="https://user-images.githubusercontent.com/21222704/43240547-f174cc52-904b-11e8-83a9-165e8fac2901.png">

<img width="424" alt="screen shot 2018-07-25 at 8 47 07 pm" src="https://user-images.githubusercontent.com/21222704/43240548-f456a9b8-904b-11e8-9214-249da86dee96.png">

#812 has the design details

**Comment by mgwalker** [comment]
Whoa, I didn't even realize that withdrawing a submission was going to be an option.  🤔

From a records perspective, if a state withdraws their submission, should we also discard that "version" of the APD and make it effectively as if they had never submitted it?

**Comment by NAretakis** [comment]
That's correct. Basically, a withdrawal should return the APD to a "Draft", wherein the state can edit and rework until they resubmit. That's really all we need withdrawal to actually do.

**Comment by mgwalker** [comment]
@NAretakis When can states withdraw a submission?  At any time after submission, before it is "complete" (approved/disapproved)?

**Comment by NAretakis** [comment]
Yes. However, in today's world they have to email us directly. I'm a little worried about it happening in the system without some sort of CMS "OK" because we could start a review and then it disappears because the state withdrew it. So, if the LOE for some sort of "CMS is OK with you withdrawing" block is low, then lets put that in. If the LOE is in any way large, then we can just let the states do it, and train them to give us a heads up if this is happening.

**Comment by quarterback** [comment]
Some revisions to the copy on that page for more consistency.

**Submitted**
A [state] 2018 HITECH APD was submitted on [date, time]

**Next steps**
Visit the state dashboard to track APD submissions, start a new APD, or submit questions to CMS.

**Withdraw submission**
Withdrawing an APD submission resets the review process by CMS. APD submissions can be withdrawn to make changes. 

_Note: Withdrawing this submission will reset the APD review process._

**This APD submission is withdrawn.**
The document is now editable. It will need to be resubmitted before it can be reviewed by CMS.

**Comment by quarterback** [comment]
Perhaps instead of letting people withdraw their APD, it's a "withdraw request" and then the CMS analyst has to basically send it back/release it, instead of making it an automated process?

**Comment by NAretakis** [comment]
That works. For MVP the “withdraw request” could even be an email to CMS, and then the actual withdraw button is something that only Federal users have access to. Either way, my vote is whatever is easiest.
