### ISSUE TITLE
Build out the first time log in experience

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#853]
The first time someone logs into their account, we need to capture a few fields:

![screen shot 2018-07-26 at 8 38 01 am](https://user-images.githubusercontent.com/21222704/43272626-4f848acc-90af-11e8-8194-642a715c4a41.png)

Related to #813

**Comment by mgwalker** [comment]
This is blocked pending infrastructure - we'll need a domain so we can setup email in AWS (or we'll need CMS to give us access to a mail server if they'd prefer we use an existing one).

Though I suppose in the interim, we could implement it where initial signup asks for their password as well and use that, then add the email behavior later when the infrastructure is ready.

**Comment by NAretakis** [comment]
OBSOLETE
