### ISSUE TITLE
Dev Refinement Wishlist

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#854]
Describe the task here, including any supplemental information.

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
 ** don't forget to fill out the LABEL, MILESTONE, and PROJECT sections before submitting (then delete this line) **

**Comment by jeromeleecms** [comment]
@brendansudol @mgwalker Is this list rank ordered already? Would be helpful for Nick and I to have a sense of your high ticket items + if this represents more than 2 weeks of work. If we have the opportunity to do another refinement sprint, we can queue those "less priority" items so we don't lose the thread on them.

**Comment by NAretakis** [comment]
This is great! I can make sure there is a corresponding issue for this work. Y'all can close this out when you think its good.

**Comment by NAretakis** [comment]
Created issues for each of these.
