### ISSUE TITLE
Design Refinement Wishlist

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#855]
Current list of Design Issues:

- #861 (refine overall style)
- #860 (scrolling fix)
- #859 (convention for adding/remove items)
- #542 (refine help text content)
- #857 (revisit standard and conditions text)
- #856 (context exegesis)
- #846 (expand content style guide)
- #830 (refine help text styles)
- #869 (update the design wiki)
- #870 (refine non-personnel costs section)

**Comment by NAretakis** [comment]
I saw a bunch of content/UI issues go into the bugfix milestone. I'll put together a little list of what that looks like, so @quarterback and @lauraponce can confirm this wishlist is complete.

**Comment by NAretakis** [comment]
Current list of Design Issues:

- #861 (refine overall style)
- #860 (scrolling fix)
- #859 (convention for adding/remove items)
- #542 (refine help text styles)
- #857 (revisit standard and conditions text)
- #856 (context exegesis)
- #846 (expand content style guide)
- others?
- others?
- others?

**Comment by lauraponce** [comment]
I added a few more to the list so this should be all of it now @NAretakis

**Comment by NAretakis** [comment]
Looks good. I'll close this one and add some prioritization. Let me know if anything looks wonky.
