### ISSUE TITLE
Revisit Standards and Conditions text

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#857]
Describe the task here, including any supplemental information.

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
 ** don't forget to fill out the LABEL, MILESTONE, and PROJECT sections before submitting (then delete this line) **

**Comment by quarterback** [comment]
Question for @jeromeleecms / @NAretakis is how much we want to mess with this standards and conditions text. In a different scenario, we'd probably break that text up and make it more plainlanguage than I've done. I left it alone here because 1) MVP but also because 2) I didn't want to minimize the significance or unintentionally water down any quasi-legal language that's included.

So the question is, how much flexibility do we have to refine that copy?

**Comment by jeromeleecms** [comment]
For MVP, I propose we keep the text as is (though I would be curious to see what your plain language take on one would be). During user testing, one individual remarked they like the level of detail, so if the form of the language helps us get a more accurate response, this is good as is. 

Down the road, if we find that the responses are not hitting the mark, we can revisit.

**Comment by quarterback** [comment]
This was done as part of the #960 update.
