### ISSUE TITLE
Horizontal scroll vs vertical scroll

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#860]
Explore options for when to use horizontal scrolling vs vertical scrolling within sections

**Comment by lauraponce** [comment]
After doing a bit of research on this, I think we should eliminate (or minimize) horizontal scrolling and follow the standard of vertical scrolling for this app.

Some common problems that Nielsen Norman Group points out:

> - On the web, users expect vertical scrolling. As with all standard design elements, it's better to meet user expectations than to deviate.
> 
> - When pages feature both vertical and horizontal scrolling, users have to move their viewport in two dimensions, which makes it hard to cover the entire space. For people with poor spatial visualization skills, it's especially challenging to plan movements along two axes across an invisible plane. (Typically, users score lower than designers on spatial reasoning and visualization tests.) In contrast, one-dimensional scrolling is a simple way to move across content without advance planning: you just keep moving down.

https://www.nngroup.com/articles/scrolling-and-scrollbars/

We are well on our way to getting rid of horizontal scrolling with the refinements in Program Activities (#870 and #863), but the tables will need some more work. So I'll start there!

**Comment by lauraponce** [comment]
Saving this one for when Aviva is able to put in some visual design hours

**Comment by lauraponce** [comment]
The tables have a lot of horizontal scrolling and we found this isn't ideal for usability. Let's see if there are ways to reorganize the information in the tables so that there isn't a lot of horizontal scrolling.

**Comment by NAretakis** [comment]
@lauraponce I kind of lost sight of this one. Do we have any thoughts/designs on this that will turn into Dev issues?

**Comment by AvivaOskow** [comment]
I have a few suggestions for this @lauraponce , but it would probably be best to talk through them with you and a dev?

### First, in the original table design I provided, the columns took up less horizontal space. I'm wondering how much we can fit in if we make the columns tighter? One question with this approach would be knowing what the longest possible number in here would be? Then we could use that width as a starting point.

**Original design (tighter)**
<img width="640" alt="screen shot 2018-09-17 at 11 48 55 am" src="https://user-images.githubusercontent.com/21244661/45634002-4e253e80-ba6f-11e8-8f79-4679a3b67f6b.png">

**Compared to current implementation**
<img width="658" alt="screen shot 2018-09-17 at 11 49 06 am" src="https://user-images.githubusercontent.com/21244661/45634440-6f3a5f00-ba70-11e8-8bd7-3cf718160e93.png">

### Second, if we have to keep them wide horizontal scrolling, there are some other things we could potentially implement to help with the usability (need dev's opinion on this!)
1. Make left column (Activities) sticky, so it's easier to keep track when scrolling)
2. Make columns adjustable for user, so they can start out tight and if they want to expand wider, that's their choice.
3. Add instruction text above or below table that directs user to horizontal scrolling, so they know.

Examples of these options are displayed in this article
https://uxdesign.cc/design-better-data-tables-4ecc99d23356

### Third, make the tables more interactive, so either sortable (only show one year at a time and totals for example) or have them expand to show more details (only show totals, and then expand for breakdowns).

I'm happy to mock up some of these, but would like to have a chat first so I know which directions to pursue. Thanks!

**Comment by NAretakis** [comment]
So, by and large we need 10 characters (plus commas) which will cover 99% of APDs ($123,456,789). However, there is an edge case for a state that needs 11 characters (plus commas) ($1,234,567,899). So, if we design it to be able to accommodate the above size, that would cover all cases.

**Comment by AvivaOskow** [comment]
More options from brainstorming:

- "expand whole table" opens into a shadow box which takes up more of the screen
- tooltips for explaining interactions to users (Aviva trying to find old example of this from another project)

**Comment by hbillings** [comment]
@lauraponce totally! I'll be on Mountain Time Mon - Tues and Central Time Weds - Fri next week. Otherwise my calendar should be up to date!

**Comment by lauraponce** [comment]
Created #1037 for the dev work on these table refinements
