### ISSUE TITLE
Refine overall styles, spacing, font sizing

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#861]
Would be a great task for Aviva when she's able to start putting in hours again

**Comment by AvivaOskow** [comment]
### Refinement 2

Add more **vertical spacing between alert/help text**, suggestion is for 16 pixels above and below

**Current**
<img width="728" alt="screen shot 2018-08-22 at 12 54 27 pm" src="https://user-images.githubusercontent.com/21244661/44478056-7a81a280-a60a-11e8-959b-fc145ab72924.png">

**Updated**
<img width="700" alt="screen shot 2018-08-22 at 12 49 09 pm" src="https://user-images.githubusercontent.com/21244661/44477943-270f5480-a60a-11e8-8874-f711b86e51cc.png">

Also change background of help text to lighter orange FDFAEF

**Comment by AvivaOskow** [comment]
### Refinement 3:

Change **padding on accordion cards**, all content should all have 24 pixel padding on right and left

Example
<img width="701" alt="screen shot 2018-08-22 at 3 18 18 pm" src="https://user-images.githubusercontent.com/21244661/44485408-75c6e980-a61e-11e8-9176-e1fc23507bda.png">

<img width="722" alt="screen shot 2018-08-22 at 3 18 04 pm" src="https://user-images.githubusercontent.com/21244661/44485418-795a7080-a61e-11e8-8b1f-1f17b42b879c.png">

**Comment by AvivaOskow** [comment]
### Refinement 4

Refine drop downs for **table of contents**

- For sections with only one sub section, doesn't need to be a dropdown, can just be the name of the section.
- The caret interaction doesn't work that well - usually those interactions work when you click the words themselves too, but in this case it brings you to the section but doesn't show the drop down in the list unless you hit the caret itself. Solutions?
<img width="176" alt="screen shot 2018-08-22 at 4 57 07 pm" src="https://user-images.githubusercontent.com/21244661/44490476-6fd80500-a62c-11e8-9c5f-d897024ffb9a.png">

**Comment by AvivaOskow** [comment]
### Refinement 5

Some thoughts on the **use of accordions/collapsable sections**:
 
Do we have any room to discuss the use of the accordions? I get that it's more consistent to maybe have each subsection be collapsable, but especially for sections that only have one thing underneath them, it seems like an unnecessary extra action the user needs to take. I worry about the users missing sections as well, with each being collapsed when they arrive on the page. Perhaps if there were all expanded once the user lands on the page, or if we had some sort of "Finished with this section?" checkbox that would then give a checkmark or some other indicator that the section was completed when collapsed...

**Comment by AvivaOskow** [comment]
### Refinement 6

**Radio buttons** and **"remove" buttons**

Change active radio button color to Bright Blue 317CB9 from our palette and change "Remove activity" buttons to size 12 font, regular, and change to an 1 px outline button using Grey E6E6E6 from our palette, with an X icon before words.

<img width="735" alt="screen shot 2018-08-31 at 6 55 27 pm" src="https://user-images.githubusercontent.com/21244661/44938953-d9a08f00-ad4f-11e8-96e4-9559bf0904b0.png">

Currently looks like (too bold and we don't use black buttons anywhere else)
<img width="750" alt="screen shot 2018-08-22 at 5 13 16 pm" src="https://user-images.githubusercontent.com/21244661/44938967-eb823200-ad4f-11e8-828c-df528aefd343.png">
