### ISSUE TITLE
Clean up Personnel section

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#863]
This section could use a closer look to see where we can make it cleaner and match the design patterns from other sections.

**Comment by lauraponce** [comment]
On it!

**Comment by lauraponce** [comment]
Incorporating #851 bug fix and touching on #860 and #859, how does this seem for a cleaner version of the Personnel section?

<img width="488" alt="screen shot 2018-07-26 at 1 14 33 pm" src="https://user-images.githubusercontent.com/21222704/43286111-e4f7ead8-90d5-11e8-8914-408852310ac4.png">

Compared to the current version:

<img width="735" alt="screen shot 2018-07-26 at 1 12 13 pm" src="https://user-images.githubusercontent.com/21222704/43286026-a1b8a60e-90d5-11e8-8a75-41019f06ba4d.png">

Changes this includes:
- Vertical scroll instead of horizontal
- New remove and add styles
- Incorporating #851 update to move Key to a question for each entry

@NAretakis @jeromeleecms?

**Comment by jeromeleecms** [comment]
@lauraponce Help me think through how a user would interact with this in this situation: 

If we had 5, 10 or 20 state staff to add in this section, what would that look like? Would it be a really long scroll? Is there some sort of UI/UX pattern that we could employ to make it easy to view/navigate through multiple employees while keeping the simplicity/look and feel of what you modeled?

For contracts, we wouldn't have as many items by activity, so I don't think the multiple line items by activity would be as dramatic as the scenario above.

**Comment by lauraponce** [comment]
Great point, @jeromeleecms. What about something like this for multiple staff entries where each entry would roll up into a collapsed list. In the collapsed state, users could either remove one of the entries or click it to open it back up and make edits. Clicking the + to add more personnel would collapse the one they just entered and expand out a new edit area where they can add another:

![screen shot 2018-07-27 at 11 48 47 am](https://user-images.githubusercontent.com/21222704/43341123-5e4978ee-9193-11e8-97d1-ffe420db98a6.png)

**Comment by jeromeleecms** [comment]
I like it! Can we put the final FFY costs in the rolled up line items?

![image](https://user-images.githubusercontent.com/34279968/43343121-f2f750b4-9199-11e8-9b63-471149a31c59.png)

We have a similar design pattern in the executive summary: 

![image](https://user-images.githubusercontent.com/34279968/43343172-1baafd76-919a-11e8-8fc3-7a92a4bda3eb.png)

**Comment by lauraponce** [comment]
How does this seem?

![screen shot 2018-07-27 at 12 51 16 pm](https://user-images.githubusercontent.com/21222704/43343631-c82ecf18-919b-11e8-91a3-71d0693a1dbb.png)

**Comment by jeromeleecms** [comment]
Looks good!

**Comment by lauraponce** [comment]
#867 for the dev work
