### ISSUE TITLE
Cleaned up version of journey map

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#87]
Create a cleaned up version of the journey map that shows the phases/steps in the process so that we can use this as a tool in interviews to identify pain points or missing tasks.

**Comment by lauraponce** [comment]
@mkhandekar let me know if there is anything I can do to help with this one! I'm sure you have a ton on your plate these next few days, but I'd love to work through this draft while you're still here so we can take advantage of your knowledge on everything from the last few weeks and other thoughts/ideas you have.

**Comment by lauraponce** [comment]
@mkhandekar and I talked about this today and think that it might be more useful to have a cleaned up version of the journey map with the key steps in each phase identified. We can use it as a tool in the interviews with states to get a better understanding of where it breaks down and where their pain points are.

**Comment by lauraponce** [comment]
Here's the updated version that includes what we heard from states [APD Journey Map.pdf](https://github.com/18F/cms-hitech-apd/files/1731524/APD.Journey.Map.pdf)
