### ISSUE TITLE
Refine non-personnel costs section

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#870]
Refine non-personnel costs section

**Comment by lauraponce** [comment]
To match non-personnel costs to the personnel costs section, how does this seem for the interaction, @NAretakis? Having the section extend vertically instead of horizontally, the dropdown options won't get truncated and there's a little more breathing room for inputting the details.

![screen shot 2018-07-30 at 10 22 58 am](https://user-images.githubusercontent.com/21222704/43412581-8dfcd27e-93e2-11e8-910d-8e06c167899d.png)

![screen shot 2018-07-30 at 10 23 12 am](https://user-images.githubusercontent.com/21222704/43412583-90bb7c18-93e2-11e8-933b-953380ec0e3a.png)

**Comment by NAretakis** [comment]
I think this works, I’ll want to test it a bit to make sure it is still relatively quick. It is definitely more visually pleasing and intuitive, but I want to make sure it isn’t labor intenstive.

**Comment by lauraponce** [comment]
I added this to our list of sections to test (if it's ready in time). I created #872 to capture the dev work for this.
