### ISSUE TITLE
Build out refinements to non-personnel costs section

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#872]
To match the updates to Personnel and Contract Resources, we should also update the Non-Personnel Costs section:

![screen shot 2018-07-30 at 12 30 11 pm](https://user-images.githubusercontent.com/21222704/43418962-6c06857c-93f4-11e8-815d-d598c1886b95.png)

![screen shot 2018-07-30 at 12 30 19 pm](https://user-images.githubusercontent.com/21222704/43418967-6ea38a0a-93f4-11e8-96a4-1603ee997db0.png)

#870 for the design issue

**Comment by brendansudol** [comment]
i say closed, and then we can open up 1 new one for updated button styles and list views across these sections

**Comment by lauraponce** [comment]
@brendansudol do you want me to open up a new issue for refining the style of this to add the blue entries and apply it to non-personnel costs and contract resources with some more details about how the interaction would work?
