### ISSUE TITLE
T-shirt costing of goals in framing doc

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#88]
Use the [t-shirt costing spreadsheet](https://docs.google.com/spreadsheets/d/1lg6-QouBEW-FDrH8MNyQWWqHCFGkLOTbqjsfLkaoo1o/edit#gid=0). Probably best for folks to pair within disciplines.

**Comment by nicoleslaw** [comment]
Can we set up time to do this together? I am wondering if it will be faster if we talk through these as a team (or by discipline?).

**Comment by brendansudol** [comment]
set up a meeting time for this on friday - it's only 30 minutes (due to calendar conflicts) but at least we can do at least a portion together

**Comment by nicoleslaw** [comment]
@lauraponce I added some guesses for the rest of the P2s—feel free to change any of the estimates!

**Comment by lauraponce** [comment]
@nicoleslaw I just had a chance to look over the estimates you added and read the comments. Looks good to me!

**Comment by nkkl** [comment]
Thanks for taking care of this, everyone!
