### ISSUE TITLE
Have Nick or Jerome verify the budget tables manually

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#884]
Devs can self assign whoever wants to tackle this.

Created per #854

**Comment by jeromeleecms** [comment]
Will revisit this when #1051 is closed and the remainder of the app approaches completion.

**Comment by NAretakis** [comment]
Did all kinds of math. Added:

- key personnel, which adds to 90/10 costs to program administration
- HIT costs @ 90/10, 75/25, 50/50, which added correctly in the budget tables, except for the bugs founds in #1217 & #1218 
- HIE costs @ varying FFP rates, which added correctly
- MMIS costs, which added to the appropriate budget tables

So, only two bugs found from this math check.
