### ISSUE TITLE
Create a mini-glossary of relevant CFR title and part numbers

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#9]
I know I heard 42 CFR 433, but what other pieces of regulation are applicable?

**Comment by jeromeleecms** [comment]
The main regs governing HITECH + The Medicaid EHR Incentive Program are 42 CFR 495, Subpart D. There are references within the HIT IAPD Template which are required by States to comply with to receive Federal funding (look on page 8 of the attachment). Nick - am I missing others?

[medicaid_hit_iapd_template.pdf](https://github.com/18F/cms-hitech-apd/files/1549631/medicaid_hit_iapd_template.pdf)

**Comment by NicolasAretakisCMS** [comment]
For what it's worth, here is the direct link to the [42 CFR 495, Subpart D](https://www.ecfr.gov/cgi-bin/text-idx?SID=8dc5fe28536b31740326bf5ab1fe725d&mc=true&node=pt42.5.495&rgn=div5#sp42.5.495.d) Jerome references.

Likewise, [45 CFR 95](https://www.ecfr.gov/cgi-bin/text-idx?SID=8dc5fe28536b31740326bf5ab1fe725d&mc=true&node=pt42.5.495&rgn=div5#sp42.5.495.d) is also referenced in the HITECH world. Although mostly CFR 95 governs E&E and MMIS activities.

**Comment by NicolasAretakisCMS** [comment]
[State Medicaid Manual](https://www.cms.gov/Regulations-and-Guidance/guidance/Manuals/Paper-Based-Manuals-Items/CMS021927.html), part 11 was another reference point.

**Comment by nkkl** [comment]
Updated to reflect that we'd like an easy reference glossary for the team to use. @mgwalker, can you show an example of what this could look like?

**Comment by jeromeleecms** [comment]
Uploaded a few State Medicaid Director Letters to Google Drive which outlines what HITECH funds can support and in what context HITECH funds can be used to support HIT and HIE activities.

**Comment by NicolasAretakisCMS** [comment]
Uploaded acronym listing, and I have engaged one of our supporting contracts to help compile a glossary based on the acronym listing. File is on Drive https://drive.google.com/drive/u/0/folders/1y3GH3pIIC2dQJEWqVRSgnOgDzBew5rDV

**Comment by NicolasAretakisCMS** [comment]
Going to revise files on drive to reflect the new glossary we have. Once I upload, I'll close this out and then can just periodically update the drive as we make revisions.

**Comment by NAretakis** [comment]
Uploaded current version of the HITECH glossary. Closing task, but will keep this updated as our contractor (MeT) provides updates. I also copied in the MAGI addition from @nicoleslaw, and deleted the older version from the drive. 

https://docs.google.com/document/d/1dewMTKRxfZi2P9S90rj78eeaMoLbosDCSu_DXgEESo8/edit
