### ISSUE TITLE
Design for an active state of a section being edited

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#909]
The current active states don't provide enough visual cues to indicate that section is the one that's active:

<img width="668" alt="screen shot 2018-08-02 at 11 44 18 am" src="https://user-images.githubusercontent.com/21222704/43603957-5a78aa22-9649-11e8-8978-15caa50abbf6.png">

<img width="673" alt="screen shot 2018-08-02 at 11 44 23 am" src="https://user-images.githubusercontent.com/21222704/43603967-617a5906-9649-11e8-9fb8-b8dac644e35d.png">

**Comment by lauraponce** [comment]
Currently, the gray outline goes away once the focus moves to another part of the page. 

Maybe the refinement could be something as subtle as using blue (0B4D82) as the outline instead of gray and keeping the outline persistent if that section is expanded to differentiate it from the other sections? 

And then it would move into the sticky nav as in #826 

<img width="742" alt="screen shot 2018-08-02 at 11 50 05 am" src="https://user-images.githubusercontent.com/21222704/43604549-e4fea984-964a-11e8-87e9-1344148d6966.png">

**Comment by brendansudol** [comment]
what if two sections are expanded at the same time -- both blue outlined?

**Comment by brendansudol** [comment]
i like it, nice and simple!
