### ISSUE TITLE
First iteration of overall content flow

### ISSUE THREAD

**Issue by nicoleslaw** [18F/cms-hitech-apd#91]
Remap the content experience for initial prototyping

**Comment by nicoleslaw** [comment]
Working file is here: https://docs.google.com/document/d/1Ln1nqLk-9IEBJPvfMHf01sbS91d4GvJkg5I4O8DOvKw/edit#

**Comment by nicoleslaw** [comment]
@NicolasAretakisCMS @jeromeleecms I took an initial pass at the overall content flow. I would love to hear your thoughts (and I expect this to change as I better understand the appendices etc.): https://docs.google.com/document/d/1Ln1nqLk-9IEBJPvfMHf01sbS91d4GvJkg5I4O8DOvKw/edit#

**Comment by jeromeleecms** [comment]
@nicoleslaw Just to get me in the right frame of mind, when you refer to overall content flow, are you thinking workflow the user would experience -- which I'm thinking: how the system would collect data + how the data would be organized?

**Comment by nicoleslaw** [comment]
Yes for the first two: how the user would experience the order of the content and fields, but not necessarily how the data would be organized on the backend.

@brendansudol can say more about that, but it's possible, for example, we'd have two tables (user data and analyst data). How we organize the data is not my forte, but I will be asking a lot of question about how we name/label the data.

**Comment by nicoleslaw** [comment]
I am going to close this in favor of the milestones we're making!
