### ISSUE TITLE
Refine Federal Citations and Justification section

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#911]
<img width="727" alt="screen shot 2018-08-02 at 6 25 41 pm" src="https://user-images.githubusercontent.com/21222704/43619255-b800bb20-9681-11e8-9a74-7bec3e27e1aa.png">

**Comment by lauraponce** [comment]
@NAretakis can you help me better understand what this section is about? I'm seeing the yes/no buttons next to the link with a space for text, but I am not sure of the question being asked for each of these. I'd like to think through ways to tighten up the spacing and add in some context about what's needed here but want to make sure I'm understanding the ask of states in this section first.

**Comment by NAretakis** [comment]
Basically, states have to indicate that they are complying with these various regulations, as part of an APD request. So, they must check “Yes” for each section. In some rare circumstances, they can indicate “no” which then requires a justification as to why they aren’t going to comply, or why it is not applicable. That’s basically it. Does that make sense?

**Comment by lauraponce** [comment]
How about something like this?

<img width="461" alt="screen shot 2018-08-03 at 2 38 12 pm" src="https://user-images.githubusercontent.com/21222704/43666935-d00636f6-972a-11e8-89dc-69944dcdff52.png">

This adds some context with the instructional text at the top, brings the responses closer to the question by tightening up the space between yes/no and the citation so it's easy to see which response corresponds to which question, and is less cluttered by only showing the justification text box once the person selects "no". Thoughts, @NAretakis?

**Comment by lauraponce** [comment]
:eyes: @NAretakis @jeromeleecms

**Comment by brendansudol** [comment]
one thing i'm worried about in the design above is the length of the justification field. i don't know but i feel like it might be quite long and require more than just a few words.

i updated this UI a week or so ago to account for this, and make it more user-friendly on mobile (https://github.com/18F/cms-hitech-apd/pull/908) -- @lauraponce do u mind taking a look at how it looks now in the app and see if we should refine further? i'm more than happy to change

**Comment by lauraponce** [comment]
Just checked the latest and the size of the justification field looks perfect. I wonder if we can still add in the instructional text telling people what to do in this section at the top?

And if we can't do the fancy yes/no radio buttons, we can keep it like you have it! But if so, can we keep them unselected by default?

**Comment by brendansudol** [comment]
sounds great - will add that text and change the radio buttons to prettier buttons - thanks!
