### ISSUE TITLE
Sticky Navigation Functionality Does not Work in IE 11

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#925]
During user testing on 08/07, we discovered that Sticky Navigation does not work with users with IE 11. 

Related to #826 / #912

### This task is done when...
 - [ ] Sticky Navigation Functions in IE 11 comparable to Chrome/Firefox
 - [ ] Someone else has confirmed bug is resolved.

**Comment by jeromeleecms** [comment]
From our discussion on the CMS design system on #1269, there is a possibility that the sticky nav may/may not make it into the design system implementation. If that is the case, this bug will be obsolete. 

Will continue to monitor.

**Comment by hbillings** [comment]
Flagging @jenniferthibault on this, because I'd love to have a conversation about how/whether to have sticky headers continue to be a thing once we've removed accordions.

**Comment by jenniferthibault** [comment]
👍 @lauraponce & I chatted briefly about this a few weeks back. Here's the gist:

The sticky sections were intended to help orient people to which section they are currently in. But the new vertical nav component from the CMS design system also does that, and doesn't truncate the titles. 

We think we should keep it simple and remove the subsection sticky element for now. If there is a reason to change it later, we could figure out the best way to change it within the new design system then. This would be dependent on the side nav sticking though, so it's always in view.

**Comment by jeromeleecms** [comment]
@jenniferthibault Tangentially/curiosity related - are there any general usability concerns once the accordions are removed? More specifically, with no accordions, the app can become very long to scroll through -- will having the sticky side bar navigation mitigate that? Or are is it generally acceptable practice for users to be OK with scrolling through pages?

**Comment by jeromeleecms** [comment]
Will close out with rationale @jenniferthibault will provide details in the near, not too distant future.

**Comment by jenniferthibault** [comment]
Several things tell me that we're heading in a promising direction for usability by removing accordions. 

> Accordions should be avoided when your audience needs most or all of the content on the page to answer their questions [or in our case, complete their tasks]. Better to show all page content at once when the use case supports it. In such cases, don’t worry too much about page length. Relevance trumps page length. 

> If your pages are extremely long, perhaps the accordion is not the appropriate widget. You many need a different navigational approach, such as presenting the information across several, more digestible pages. 

> Accordions are more suitable when people need only a few key pieces of content on a single page. By hiding most of the content, users can spend their time more efficiently focused on the few topics that matter.

- Source: [Accordions Are Not Always the Answer for Complex Content on Desktops](https://www.nngroup.com/articles/accordions-complex-content/)
by Hoa Loranger on May 18, 2014

Our content is long & complex, and users need it to complete their tasks. I understand that past research told us that users want the reassurance of having all the information on the same page, so with that in mind we're knowingly putting off best practices of splitting the content into separate pages until the experience is more familiar.


> Consider how much information is to be displayed on a single page. Presenting a large amount of information on a single page minimizes the user’s effort, or interaction cost, but only if the user is likely to read the full content, in the exact order in which it is presented. However, if the page contains 4 or 5 related, yet distinct topics, it may be better to separate content into different pages, particularly if any given user is only likely to read a few of the topics.

Our tack instead to use the vertical side nav as the in-page navigation for the pilot comes with some trade-offs too, but at this point we're hypothesizing that it's a reassuring first step for users:

> A table of contents may appear in a column to the left or to the right of the main content. These links, placed beside the main content area, may initially be less noticeable because users are focused on the central content area of the site. If these links stay in place next to the content as the user scrolls, they have the benefit of remaining visible to the user.

This makes figuring out how to get the side nav to stick in #1337 important for this concept.

> When deciding on in-page links or accordions, consider how the page will be used. If people are likely to read all the content sequentially (like they would do with a magazine article or a book chapter), repeatedly opening accordions will lead to a high interaction cost.

> With in-page links, users are able to see the full content of the page if they scroll, and the in-page links act as an enhancement: the user does not have to use them. On the other hand, accordions require user input to reveal content. This means the content behind an accordion is less discoverable and more likely to be ignored— out of sight is out of mind.

- Source for points above: [Anchors OK? Re-Assessing In-Page Links](https://www.nngroup.com/articles/in-page-links/)
by Amy Schade on May 7, 2017

So with all that, we are closing in favor of the side nav approach as a first hypothesis, which will be carried on in #1337
