### ISSUE TITLE
Allow Users to be attached to a State via an API Call

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#926]
Update the API to allow users to be attached to a state through an API call.

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
 ** Don't forget to fill out the LABEL and MILESTONE before submitting. If the issue is for the CURRENT SPRINT, add it to the PROJECT. If the issue is a BUG, FUTURE ENHANCEMENT, or OUTSIDE OF THE CURRENT SPRINT, do not add it to the PROJECT (then delete this line) **

**Comment by mgwalker** [comment]
Rolled up in #1254, implemented by #1302
