### ISSUE TITLE
Calculating Cost Allocation By %

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#929]
Many cost allocations are done by %, not just by a flat dollar amount. The app should allow for multiple % across a project cost.

Less complicated in HITECH, but occurs in E&E and MMIS. 

Example: 
Total Cost: $100
Medicaid Share: 50% ($50)
FNS Share: 30% ($30)
TANF Share: 10% ($10)
LIHEAP Share: 10% ($10)

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
 ** Don't forget to fill out the LABEL and MILESTONE before submitting. If the issue is for the CURRENT SPRINT, add it to the PROJECT. If the issue is a BUG, FUTURE ENHANCEMENT, or OUTSIDE OF THE CURRENT SPRINT, do not add it to the PROJECT (then delete this line) **

**Comment by NAretakis** [comment]
closing until user feedback says otherwise.
