### ISSUE TITLE
Extract personnel sections from activities

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#936]
### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
 ** Don't forget to fill out the LABEL and MILESTONE before submitting. If the issue is for the CURRENT SPRINT, add it to the PROJECT. If the issue is a BUG, FUTURE ENHANCEMENT, or OUTSIDE OF THE CURRENT SPRINT, do not add it to the PROJECT (then delete this line) **

**Comment by NAretakis** [comment]
This is done. We have Key personnel up and running, but kept an activity specific in-house personnel section for each activity. yay!
