### ISSUE TITLE
Clean up the Needs and Objectives section

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#943]
The Needs and Objectives section could use some refinement so that it's easier to how it's organized and see what goes into each of the text boxes.

<img width="671" alt="screen shot 2018-08-15 at 1 34 47 pm" src="https://user-images.githubusercontent.com/21222704/44171765-038b5d80-a090-11e8-9f55-6ba2704b5486.png">

**Comment by lauraponce** [comment]
![screen shot 2018-08-24 at 12 19 56 pm](https://user-images.githubusercontent.com/21222704/44603601-0a088c00-a798-11e8-9357-2c8cb10d516a.png)

@NAretakis @jeromeleecms @quarterback

**Comment by lauraponce** [comment]
@quarterback how does this seem? Not that this has to be the final copy, that can always be updated, but for the layout, does this work?

![screen shot 2018-08-24 at 12 26 19 pm](https://user-images.githubusercontent.com/21222704/44603847-f6115a00-a798-11e8-8d60-1f822839f731.png)

**Comment by quarterback** [comment]
@lauraponce I think that's a good step forward!

**Comment by NAretakis** [comment]
Yes! Ship it.

**Comment by lauraponce** [comment]
Created #988 for the dev work
