### ISSUE TITLE
Pull Key Personnel details outside of the activity section

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#947]
- Should be a standalone section above 
- Explanation as to why this is different from the other personnel

**Comment by NAretakis** [comment]
@lauraponce per meeting with Ron and Jerome. I want to get you a quick sketch of the output of what we talked about. Standby.

**Comment by NAretakis** [comment]
@lauraponce @quarterback @jeromeleecms Per our meeting, here is some copy and sketch of what this could look like if we insert this into the Main Contact (now potentially renamed) section of the APD.

### State Medicaid Director & Medicaid Office Address
-- Existing Content  --

### Key Personnel & Project Management Planning (in place of Main Contact section)
Who are the key state staff that will be involved in the work? Before we approve a state to launch a major IT initiative, CMS wants to ensure that the state team is adequately resourced. States do not need to provide key vendor personnel for this requirement. 

Key personnel are individuals who oversee or are involved in governance, coordination and decision-making that occurs between the key stakeholders, and/or how the single state agency responsible for Medicaid is overseeing and monitoring project performance. 

States must identify key state personnel assigned to the APD by name, role, time commitment, and if applicable, cost.

![image](https://user-images.githubusercontent.com/34281281/44431591-b3af0980-a55b-11e8-9ee6-0aca0e4a5722.png)

**Comment by quarterback** [comment]
@NAretakis This is a good high level view of what you were explaining. I'll add some copy for those sections to this thread.

**Comment by quarterback** [comment]
**Key Personnel**

Key personnel are individuals involved in governance, coordination, stakeholder decision-making, and/or single state agency responsibility for Medicaid oversight and project performance monitoring.

Identify key state staff who will be involved in all activities list in this APD. CMS seeks to ensure state teams are adequately resources, but does not require states to provide key vendor personnel to satisfy this requirement. 

Personnel listed in this section must be assigned to APD by name, role, time commitment, and cost where applicable.

@NAretakis (rewrite)

**Comment by lauraponce** [comment]
@NAretakis how does this seem? 

<img width="392" alt="screen shot 2018-08-23 at 2 00 09 pm" src="https://user-images.githubusercontent.com/21222704/44551742-e5031300-a6dc-11e8-8588-0f92c5c1b9d5.png">

**Comment by lauraponce** [comment]
About how many people will there end up being in this section? (Wondering because we could use the list format like we are using for the other personnel section if there will be a lot of contacts here, but if it will only be a few, that might not be necessary).

**Comment by NAretakis** [comment]
I'd say 2-10 people, possibly more. It really varies depending on what activities each state is doing. List format is probably a very smart move.

**Comment by lauraponce** [comment]
Does name + role make the most sense to have in the quick view list? Or is there another piece of info that could be more useful to have there, @NAretakis 

<img width="394" alt="screen shot 2018-08-23 at 3 00 52 pm" src="https://user-images.githubusercontent.com/21222704/44554329-5e066880-a6e5-11e8-8c3e-cce99788277f.png">

**Comment by NAretakis** [comment]
I think I’d like to have total cost in the quick view list as well. I was on the fence about % commitment but I don’t think that is necessary.

**Comment by lauraponce** [comment]
<img width="390" alt="screen shot 2018-08-23 at 3 50 50 pm" src="https://user-images.githubusercontent.com/21222704/44555946-5bf3d800-a6ec-11e8-9cfc-54f0d42e3378.png">

**Comment by NAretakis** [comment]
Perfect. Let’s roll it out!

**Comment by lauraponce** [comment]
Created #981 for the dev work on this
