### ISSUE TITLE
Combine and refine personnel and non-personnel subsections 

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#948]
- Combine Personnel and Non-Personnel into one subsection called Cost Categories
- Update percentages to # FTE
- Remove descriptions
- Update salary to rate

Whiteboard notes
![img_6735](https://user-images.githubusercontent.com/21222704/44356539-7f0c5680-a464-11e8-8cb0-55300f9fd75f.JPG)

**Comment by NAretakis** [comment]
I'm going to add a sketch to this in the morning. All your points are solid, however the 'Cost Categories' section needs be slightly different for personnel, non-personnel, and/or maybe contracts. I'm pretty confident in combining personnel and non-personnel into a simpler list. But I have to sketch it out for vendors to see how it looks. I'll post to here and then we can maybe chat about it.

**Comment by NAretakis** [comment]
@lauraponce Ok, here is the sketched version. I went back over it with David Koppel this morning and Contract Resources is good as it is. No changes necessary. So, this ask is just to streamline and combine Personnel and Non-Personnel into a single Cost Categories section, that sits within each activity. Note that I've also cut out some of the FTE and Key Personnel help text:

![image](https://user-images.githubusercontent.com/34281281/44412452-34531300-a526-11e8-83ec-9710f802e9a2.png)

**Comment by lauraponce** [comment]
@NAretakis I think it works well to combine the costs like that ^ — here is that version in the current styles:

![screen shot 2018-08-21 at 10 47 01 am](https://user-images.githubusercontent.com/21222704/44419274-9401ec00-a52f-11e8-9ee5-53231ac58f5d.png)

**Comment by NAretakis** [comment]
Looks great! I think we'll need to adjust the helptext because it references that "personnel need only be listed once" when in fact we are doing it a little differently now based on number of FTEs. @quarterback

**Comment by lauraponce** [comment]
Created #970 for the dev work and hoping help text updates can be grouped in #960. Closing this one out!
