### ISSUE TITLE
Content for instructions/help text for standalone key personnel section

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#949]
As per #947 key personnel will be pulled out into its own section above Activities. 

This should include instructions and/or some help text explaining what this means, how its overarching, and why it's separate from the other personnel they will enter per activity.

**Comment by quarterback** [comment]
Key Personnel

Key personnel are individuals involved in governance, coordination, stakeholder decision-making, and/or single state agency responsibility for Medicaid oversight and project performance monitoring.

Identify key state staff who will be involved in all activities list in this APD. CMS seeks to ensure state teams are adequately resources, but does not require states to provide key vendor personnel to satisfy this requirement.

Personnel listed in this section must be assigned to APD by name, role, time commitment, and cost where applicable.

**Comment by quarterback** [comment]
Closed with #947
