### ISSUE TITLE
Process flow for HIE questions

### ISSUE THREAD

**Issue by nicoleslaw** [18F/cms-hitech-apd#95]
Outline the flow of questions and information we need for HIE-related activities

**Comment by jeromeleecms** [comment]
Took a first crack at the [HIE flow](https://docs.google.com/document/d/1bM3Z35QqtwDAwam9dxNkFBiRWq1r3PhE3eRn73Ar0GA/edit?usp=sharing). Tried to mirror the current APD exploration document and adding the HIE components in. @NicolasAretakisCMS could use your eyes on this.

**Comment by NicolasAretakisCMS** [comment]
Added comments to flow.

**Comment by jeromeleecms** [comment]
Thanks @NicolasAretakisCMS. Moved some things around and responded to some of your comments. I think this is good enough for @nicoleslaw and/or @lauraponce to take a look at when they are ready.
