### ISSUE TITLE
Evaluate Scalability for the dashboard/app 

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#950]
Nick and Jerome to talk through some of this.

Include some discussion about the context of documents (APD, SMHP), due dates (maybe submission dates) and categories by program area

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
 ** Don't forget to fill out the LABEL and MILESTONE before submitting. If the issue is for the CURRENT SPRINT, add it to the PROJECT. If the issue is a BUG, FUTURE ENHANCEMENT, or OUTSIDE OF THE CURRENT SPRINT, do not add it to the PROJECT (then delete this line) **

**Comment by NAretakis** [comment]
OBSOLETE
