### ISSUE TITLE
How to evaluate YAML to support design language for help text within the app

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#951]
@bren @mgwalker Feel free to fill this in

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
 ** Don't forget to fill out the LABEL and MILESTONE before submitting. If the issue is for the CURRENT SPRINT, add it to the PROJECT. If the issue is a BUG, FUTURE ENHANCEMENT, or OUTSIDE OF THE CURRENT SPRINT, do not add it to the PROJECT (then delete this line) **

**Comment by mgwalker** [comment]
Not sure what this one is 😬

**Comment by NAretakis** [comment]
OBSOLETE!
