### ISSUE TITLE
Additional help guidance for program activities (attachments)

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#953]
Details for attachment experience and the other sections in the program activities section (what is the workaround for the attachments.)

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
 ** Don't forget to fill out the LABEL and MILESTONE before submitting. If the issue is for the CURRENT SPRINT, add it to the PROJECT. If the issue is a BUG, FUTURE ENHANCEMENT, or OUTSIDE OF THE CURRENT SPRINT, do not add it to the PROJECT (then delete this line) **

**Comment by jameshupp** [comment]
I can make these the actual completion criteria if this all sounds good, but I wanted to get it out here for thoughts. Based on discussion during sprint planning, the approach to program activities content is:

- [ ] Inventory the section (in progress)
- [ ] Review my inventory with SMEs (Nick or Jerome)
- [ ] Edit the yaml and work through via PR until consensus. Seem about right?

@jeromeleecms I think this squares with what we discussed in planning. This issue pre-dates that meeting, but I think it covers the same ground and we can update it to reflect that if this feels like the right place to do this work.

**Comment by jeromeleecms** [comment]
closing this in favor of #1027
