### ISSUE TITLE
One APD won't open.

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#954]
One of my APD links is broken.

![image](https://user-images.githubusercontent.com/766654/44369173-51d29f00-a48a-11e8-95a2-0e9613b5bd33.png)

Repro:
1. Click top APD (draft for 2018, 2019). APD opens as expected.
2. Click bottom APD (draft for 2018, 2019).

Expected behavior:
APD opens.

Actual behavior:
APD does not open. Screen goes blank and must be refreshed.

![image](https://user-images.githubusercontent.com/766654/44369226-89d9e200-a48a-11e8-9b0f-e43ba22e8bb0.png)

Additional info:
Problem persists if I add a new APD (then the APD in the middle is blank, all others work as expected).

**Comment by brendansudol** [comment]
this should now be fixed (via https://github.com/18F/cms-hitech-apd/pull/961) -- @nkkl can you confirm?

**Comment by nkkl** [comment]
😬 

![image](https://user-images.githubusercontent.com/766654/44535409-cdad3100-a6ae-11e8-99bc-7dcc042849e2.png)

**Comment by brendansudol** [comment]
oh i think it's because that apd is saved with bad data, that error shouldn't be possible anymore, but hmm, not sure how to fix your case...

**Comment by nkkl** [comment]
I mean, I'm fine just nuking the bad APD. It's not like it's got any useful information in it...
