### ISSUE TITLE
Define common activity categories

### ISSUE THREAD

**Issue by nicoleslaw** [18F/cms-hitech-apd#96]
Formalize the top ~10 types of activities, such as:

- Administration
- Strategic planning
- Auditing
- Technical assistance
- Outreach

Note: We have the assumption we'll make it possible for states to add their own.

**Comment by nicoleslaw** [comment]
@NicolasAretakisCMS @jeromeleecms Would you feel comfortable taking the lead on compiling the top 10-20 activities, and then I can take an editing pass?

**Comment by jeromeleecms** [comment]
@nicoleslaw How much granularity are we looking at? Public Health Infrastructure and Health Information Exchange are broad topics, but each of those can be broken down to multiple project types. 

Also, helping me think through this task, are you thinking that users would be able to select multiple items (i.e. the users would select "Strategic Planning" and "Health Information Exchange") or would be a singular selection (i.e. "Strategic Planning" and the description would add details)?

**Comment by nicoleslaw** [comment]
I think two levels of granularity would be helpful. For example, for Administration (one of the common activities Nick called out), what kinds of things fit into that category?

My assumption would be the user would choose or enter a custom activity name (e.g., Outreach, Technical Assistance) and then describe the needs of that activity and the funding streams involved (e.g., HITECH, MMIS, HIE). Does that answer your question? Happy to talk through it more!

**Comment by jeromeleecms** [comment]
Took a first crack at this, @NicolasAretakisCMS. Posted to [Drive](https://docs.google.com/document/d/16PmhnjWtS_bU4lcJ-4QUcB-1_X07tNKjEmOtlcCKEUI/edit#). Could you take a look? Also included the financial categories in the same document (tied to #135).

**Comment by NAretakis** [comment]
Added my comments to the doc. Good to move forward. I'm still on the fence about categories and subcategories. I like the granularity, and states have commented that they want CMS to explain what we want in the budgets, and this does that. The drawback seems to be that it adds a layer of complexity that may or may not add value. This might just be a case for testing, and see if having the category, subcategory, +description really adds value? Or if just the top level category, +description would be enough for us to move on a request.

**Comment by nicoleslaw** [comment]
Taking another look at these today.

**Comment by nicoleslaw** [comment]
Passing this to you @quarterback!

**Comment by NAretakis** [comment]
added a few minor comments and suggestions [to the doc](https://docs.google.com/document/d/16PmhnjWtS_bU4lcJ-4QUcB-1_X07tNKjEmOtlcCKEUI/edit#)

otherwise, I think it has a pretty go capture of everything.

**Comment by NAretakis** [comment]
Of note, there is a problem to wrestle, which is lining up all of the categories with any associated contracts. Basically, anything in these categories can be state or contractor costs. So, we'll need a way to identify and link a contractor to each identified category. Might need to talk through this a bit.

**Comment by nicoleslaw** [comment]
Closing this, but I expect @quarterback to bring this back up after usability sessions.
