### ISSUE TITLE
Deleting all state personnel crashes the app

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#964]
Previously, we disallowed deleting the last state personnel.  I think it should be valid for an activity not to list any state personnel - let's investigate our data dependencies to figure out how we can support that.

Alternatively, if the user deletes the last state personnel in an activity, we can automatically insert a new, empty one.

### This task is done when...
 - [x] deleting all state personnel in an activity does not crash the app

**Comment by NAretakis** [comment]
this is now fixed!
