### ISSUE TITLE
Create a Slack gif emoji to represent Zoom kicking everyone out of a meeting

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#965]
Could be a person working and then they get hit in the face with a clock.
Could be a person talking and then curtains close and the Zoom logo appears.
Could be something else amazing, go for it.

**Comment by quarterback** [comment]
LOL

**Comment by NAretakis** [comment]
gif made. Working on uploading. Closing this issue because this really shouldn't be a P1 issue for us to worry about :wink:
