### ISSUE TITLE
What should an exported eAPD look like?

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#975]
All of the state populated sections of the eAPD need to be part of the export. However, how much of the header, sections, helptext should come across in the export?

Essentially, we want to come away with a paper version of the eAPD (with every section expanded). This issue is for us to document what sections of the application need to be brought over for an export.

**Comment by quarterback** [comment]
https://docs.google.com/document/d/1vguSTn02ot8XzdUKQxzin78oFxIDHU_RzitprnqiCQ0/edit?usp=sharing

**Comment by NAretakis** [comment]
Made a few minor adds, but this is the right framework for the export output.

**Comment by quarterback** [comment]
Okay perfect.

**Comment by quarterback** [comment]
cc: @lauraponce for general awareness

**Comment by quarterback** [comment]
Closing this issue since @brendansudol pushed that initial export demo before he left (#993)
