### ISSUE TITLE
Commenting Functionality

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#977]
Should we have comment boxes for each section? Commentary hovering right sidebar?

This Epic is is for the federal reviewer commenting functionality. I think we have some really old design session sketches somewhere that are worth inserting into this issue.

**Comment by lauraponce** [comment]
Posting this as a starting point.

From the reviewer perspective, this would be the hover state for any of the text sections:
<img width="506" alt="screen shot 2018-08-31 at 1 29 51 pm" src="https://user-images.githubusercontent.com/21222704/44934526-0178fe00-ad22-11e8-972c-612b2bbc01da.png">

Once you click the comment circle:
<img width="595" alt="screen shot 2018-08-31 at 1 30 08 pm" src="https://user-images.githubusercontent.com/21222704/44934527-0178fe00-ad22-11e8-8e0d-cb1ec4a39110.png">

When a state user replies, you see the comment thread and can reply back:
<img width="597" alt="screen shot 2018-08-31 at 1 30 30 pm" src="https://user-images.githubusercontent.com/21222704/44934528-0178fe00-ad22-11e8-95ee-a5d03d7f8c2d.png">

**Comment by lauraponce** [comment]
Let me know if this is heading in the right direction @NAretakis @jeromeleecms 

Still to do:
- Comment menu
- Editing/deleting a comment
- Notifications
- Indicating which sections have comments
- Feed

**Comment by lauraponce** [comment]
The way I'm picturing this working is that if your screen isn't wide enough to view the APD content and the comment box, you would just scroll to the right to see it. Maybe down the line, we can look at options for shrinking the APD content down a little bit so there is more room for seeing both on the screen at the same time.

**Comment by NAretakis** [comment]
This is really really good. We'll have to do some testing, but this is very much how I envisioned it looking. Let's go with it.

**Comment by lauraponce** [comment]
For indicating which sections have unread/new comments it would show up as dark blue filled in and for read comments in each section, it would be the blue outline: 

<img width="571" alt="screen shot 2018-09-04 at 9 42 49 pm" src="https://user-images.githubusercontent.com/21222704/45071495-65395900-b08b-11e8-91b6-f81594ca972b.png">

And when you click into the section, the comment thread appears on the right side.

**Comment by lauraponce** [comment]
For the MVP I am thinking that we might be okay to start with the essential features as part of the commenting functionality (view, reply, and be notified) and add to it from there as needed. This would mean leaving out editing and deleting previous comments, but we can definitely ask about that in testing. Any objections to taking that approach?

**Comment by NAretakis** [comment]
No objection. Love the designs.

**Comment by mgwalker** [comment]
It's going to be a lot of work on the dev side, but no red flags or anything else that I see.  This looks really cool.  I'll go ahead and spin up a dev issue and add some more thoughts there.

**Comment by jeromeleecms** [comment]
Closing this out per Team Discussion. Will revisit this functionality when it comes up in the roadmap.
