### ISSUE TITLE
Compile list of important cloud.gov pages

### ISSUE THREAD

**Issue by brendansudol** [18F/cms-hitech-apd#98]
cloud.gov site is great and has everything; what are the pages/things that are must reads at this stage?

**Comment by brendansudol** [comment]
update: put this request in cloud.gov team and they're working on it (gathering links).

they also said that they would be happy to do a call with CMS too.

cc: @NicolasAretakisCMS @nkkl

**Comment by nkkl** [comment]
Waiting for more info from cloud.gov team.

**Comment by pburkholder** [comment]
Hi - Thanks for pinging us on this. 

I think the best place to start is with our overview pages: https://cloud.gov/overview/overview/what-is-cloudgov/ and the sidebar linked pages under 'cloud.gov overview':

* https://cloud.gov/overview/overview/what-is-cloudgov/
* https://cloud.gov/overview/overview/cloudgov-benefits/
* https://cloud.gov/overview/security/fedramp-tracker/
* https://cloud.gov/overview/overview/who-can-use-cloudgov/
* https://cloud.gov/overview/overview/using-cloudgov-paas/
* https://cloud.gov/overview/overview/cloudgov-team/

And also our customer stories, attached, and more indepth for FEC at https://cloud.gov/overview/customer-stories/fec/
[cloudgov-customers.pdf](https://github.com/18F/cms-hitech-apd/files/1668959/cloudgov-customers.pdf)

This are pretty high-level/overview stuff, but should be more than enough to generate enough questions for a follow-up call. We're eager to talk whenever you are.

Cheers, Peter

**Comment by nkkl** [comment]
@mgwalker please review and close if complete :)
