### ISSUE TITLE
Build out separate key personnel section

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#981]
In the first section (State Profile Contact Information), there is a subsection called Main Contact — this will replace that subsection. The design task was #947

![image](https://user-images.githubusercontent.com/21222704/44599161-49c87700-a78a-11e8-9b9e-b144ef3fb8a3.png)

**Comment by mgwalker** [comment]
Well, now another question: if a key person has costs attributable to the APD, do the values in the textboxes here need to be incorporated into the budget tables?  Or are users expected to input their costs again in an activity?

**Comment by lauraponce** [comment]
I feel like just one person should be selected as the primary, and if they select it for someone else, then that unselects it for the original one (in the background). @NAretakis @jeromeleecms thoughts on these questions?

**Comment by NAretakis** [comment]
Yes.
